using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Services.LotR.Templates
{
    public class FrenchTemplateRepository : TemplateRepository
    {
        protected override void Initialize()
        {
            AddHtml("Aragorn-Core", "<p class='main-text'>{keyword:Sentinelle.}</p><p class='main-text'><b>Réponse:</b> quand {self} s'engage dans une quête, dépensez I ressource de sa réserve pour le redresser.</p><p class='flavor-text'>&laquo;Je suis Aragorn, fils d'Ararthorn, et si, par la vie ou par la mort, je puis vous sauver, je le ferai.&raquo;<br>&ndash;La Communaute de l'Anneau</p>");
            AddHtml("Beorn-Core", "<p class='main-text'><b>Action:</b> {self} gagne +5 {Attack} jusqu'a la fin de la phase. A la fin de la phase ou vous avez declenche cet effet, melangez {self} dans votre deck. (Limite: une fois par tour).</p><p class='flavor-text'>&laquo; Je n'ai pas besoin de vos services, merci... mais sans doute avez-vous besoin des miens. &raquo;<br>&ndash; Le Hobbit</p>");
            AddHtml("Guard-of-the-Citadel-Core", "<p class='flavor-text'>&laquo;Mais les Seigneurs de Minas Tirith continuent de se battre, defiant nos ennemis, gardant le passage de la riviere, d'Argonath a la mer.&laquo;<br>&ndash;Elrond, La Communaute de l'Anneau</p>");

            //Children of Eorl
            AddHtml("Ingold-CoE", "<p class='main-text'><b>Réponse</b> : quand un allié <b><i>Gondor</i></b> ou <b><i>Guerrier</i></b> entre en jeu sous votre contrôle, piochez une carte. Ensuite, vous devez dépenser une ressource de la réserve d’Ingold ou augmenter de 1 votre niveau de menace. (Limite : une fois par phase.)</p><p class='flavor-text'>“Nous ne désirons aucun étranger dans le pays en ce moment, sauf de vigoureux hommes d’armes, en la loyauté et l’aide desquels nous puissions avoir confiance.” — Le Retour du Roi</p>");
            AddHtml("Celador-CoE", "<p class='main-text'>À distance.</p><p class='main-text'>Diminuez de 1 le total de {Threat} dans la zone de cheminement pour chaque carte <b><i>Piège</i></b> que vous contrôlez qui n’est pas attachée.</p><p class='main-text'><b>Réponse</b> : quand une carte <b><i>Piège</i></b> que vous contrôlez est attachée à un ennemi, choisissez entre : redresser Celador ou diminuer de 1 votre niveau de menace.</p><p class='flavor-text'>“Un sage ne se fie pas à une rencontre par hasard dans ce pays” — Faramir, Les Deux Tours</p>");
            AddHtml("Thengel-CoE", "<p class='main-text'><b>Réponse</b> : quand un allié en jeu est défaussé, le contrôleur de cette carte cherche parmi les 5 premières cartes de son deck un allié partageant au moins 1 <b><i>Trait</i></b> avec l’allié défaussé, le met en jeu incliné, et mélange son deck. (Limite : une fois par tour.)</p><p class='flavor-text'>“Mon ami, dit Gandalf, vous aviez des chevaux, des faits d’armes et des champs libres” — Le Retour du Roi</p>");
            AddHtml("Herubrand-CoE", "<p class='main-text'>Herubrand gagne +1 {Willpower} pour chaque héros que vous contrôlez ayant au moins 1 attachement Restreint.</p><p class='main-text'><b>Réponse</b> : quand un ennemi est détruit dans la zone de cheminement, piochez une carte.</p><p class='flavor-text'>“Quel fardeau portez-vous, Hommes de Rohan ?” — Imrahil, Le Retour du Roi</p>");
            AddHtml("Deeping-Bowman-CoE", "<p class='main-text'>Dévoué. À distance.</p><p class='main-text'><b>Action</b> : défaussez l’Archer du Gouffre pour choisir un ennemi. Jusqu’à la fin de la phase, cet ennemi ne compte pas sa {Defense} quand vous déterminez les dégâts de combat.</p><p class='flavor-text'>“Nous avons lâché jusqu’à notre dernière flèche, et rempli le Fossé d’Orques” — Les Deux Tours</p>");
            AddHtml("Open-the-Gates-CoE", "<p class='main-text'><b>Action</b> : cherchez parmi les 5 premières cartes de votre deck un allié partageant au moins 1 <b><i>Trait</i></b> avec chacun de vos héros et mettez-le en jeu. Mélangez votre deck. À la fin de la phase, si cet allié est encore en jeu, ajoutez-le à votre main.</p><p class='flavor-text'>“Il semblait que la nouvelle de leur venue les avait devancés, et ils furent admis aussitôt, en silence et sans questions.” — Le Retour du Roi</p>");
            AddHtml("Wealth-of-Adventure-CoE", "<p class='main-text'><b>Action</b> : cherchez dans votre deck 1 carte <b><i>Compétence</i></b> et ajoutez-la à votre main. Mélangez votre deck.</p><p class='flavor-text'>“C’est une affaire dangereuse de passer ta porte, Frodon, me disait-il. Tu vas sur la route et, si tu ne retiens pas tes pieds, Dieu sait jusqu’où tu pourrais être emporté”<br/>— Frodon, La Communauté de l’Anneau</p>");
            AddHtml("Feast-of-Plenty-CoE", "<p class='main-text'>Le coût en ressources de Festin d’Abondance doit être payé avec la réserve d’un seul héros.</p><p class='main-text'><b>Action</b> : redressez jusqu’à 3 héros et ajoutez 1 ressource à la réserve de chacun de ces héros. Seul 1 exemplaire de Festin d’Abondance peut être joué par les joueurs à chaque tour.</p><p class='flavor-text'>“Le festin était joyeux et la chère répondait à tout ce que sa faim pouvait désirer” — La Communauté de l’Anneau</p>");
            AddHtml("Deeping-Defender-CoE", "<p class='main-text'>Dévoué.</p><p class='main-text'><b>Réponse</b> : après que le Défenseur du Gouffre a défendu contre une attaque, renvoyez l’ennemi attaquant dans la zone de cheminement et infligez-lui 1 point de dégâts.</p><p class='flavor-text'>“Le soleil couchant dorait leurs lances et leurs casques, et étincelait dans leurs cheveux pâles et flottants.”<br/>— Les Deux Tours</p>");
            AddHtml("Morwen-Steelsheen-CoE", "<p class='main-text'><b>Action</b> : mettez Morwen Lustre d’Acier en jeu depuis votre main. Ensuite, défaussez un allié <b><i>Rohan</i></b> ou <b><i>Gondor</i></b> que vous contrôlez.</p><p class='main-text'><b>Réponse</b> : quand un allié <b><i>Rohan</i></b> ou <b><i>Gondor</i></b> quitte le jeu, inclinez Morwen Lustre d’Acier pour choisir entre : soigner 2 points de dégâts sur un personnage ou diminuer de 1 votre niveau de menace.</p>");
            AddHtml("It-Should-Be-Spared-CoE", "<p class='main-text'><b>Réponse</b> : quand une carte <b><i>Piège</i></b> que vous contrôlez est attachée à un ennemi, ramenez-la dans votre main. Ensuite, jouez-la de votre main gratuitement.</p><p class='flavor-text'>“Mais je n’abats ni homme ni bête sans nécessité, et je ne le fais pas de gaieté de cœur quand je le dois.” — Faramir, Les Deux Tours</p>");
            AddHtml("Spring-the-Trap-CoE", "<p class='main-text'><b>Réponse</b> : quand une carte <b><i>Piège</i></b> que vous contrôlez est attachée à un ennemi, mettez en jeu un allié <b><i>Rôdeur</i></b> depuis votre main.</p><p class='flavor-text'>“La route passe peut-être, mais eux ne passeront pas ! Pas tant que Faramir sera Capitaine.”<br/>— Mablung, Les Deux Tours</p>");
            AddHtml("Squire-of-the-Mark-CoE", "<p class='main-text'><b>Réponse</b> : quand un allié <b><i>Rohan</i></b> que vous contrôlez est défaussé, ajoutez l’Écuyer de la Marche à la pile de victoire pour mettre en jeu cet allié incliné.</p><p class='flavor-text'>“Je ne puis rendre que peu de services à votre seigneur, mais ce que je peux faire, je le ferai”<br/>— Pippin, Le Retour du Roi</p>");
            AddHtml("Rammas-Lookout-CoE", "<p class='main-text'>Dévoué.</p><p class='main-text'>Tant que chaque héros que vous contrôlez a au moins 1 ressource dans sa réserve, le Guetteur du Rammas gagne +1 {Willpower} et n’est pas incliné pour s’engager dans une quête.</p><p class='flavor-text'>“Quoi qu’il advienne, vous êtes parvenus à la fin du Gondor que vous avez connu. Laissez-moi passer !”<br/>— Gandalf, Le Retour du Roi</p>");
            AddHtml("Theodwyn-CoE", "<p class='main-text'><b>Réponse</b> : quand Théodwyn entre en jeu, choisissez entre : piocher 1 carte ou ajouter une ressource à la réserve d’un héros <b><i>Noble</i></b>.</p><p class='flavor-text'>“Elle est intrépide et a le cœur haut placé. Elle est aimée de tous. Qu’elle soit le seigneur des Eorlingas, pendant notre absence.” — Háma, Les Deux Tours</p>");
            AddHtml("Light-footed-Steed-CoE", "<p class='main-text'>Attachez cette carte à un héros <b><i>Rohan</i></b>. Restreint.</p><p class='main-text'><b>Réponse</b> : quand un personnage que vous contrôlez quitte le jeu, inclinez le Coursier au Pied Léger pour redresser le héros attaché. Ensuite, si le personnage ayant quitté le jeu était unique, ce héros gagne +1 {Attack} jusqu’à la fin du tour.</p><p class='flavor-text'>“… et n’oublie pas leurs chevaux ! Ils peuvent voir le vent nocturne, ou en tout cas on le dit.”<br/>— Uglúk, Les Deux Tours</p>");
            AddHtml("Rammas-Sentry-CoE", "<p class='main-text'>Dévoué.</p><p class='main-text'>Tant que chaque héros que vous contrôlez a au moins 1 ressource dans sa réserve, la Sentinelle du Rammas gagne : “<b>Réponse</b> : annulez 1 point de dégâts tout juste infligé à un personnage <b><i>Gondor</i></b>. (Limite : une fois par phase.)”</p><p class='flavor-text'>“Car si nous tombons, qui tiendra ?”<br/>— Beregond, Le Retour du Roi</p>");
            AddHtml("Live-Bait-CoE", "<p class='main-text'>Vous ne pouvez jouer cette carte que si vous contrôlez une carte <b><i>Piège</i></b> qui n’est pas attachée.</p><p class='main-text'><b>Action</b> : choisissez un ennemi non-unique en jeu. Jusqu’à la fin du tour, cet ennemi perd le texte imprimé dans sa boîte de texte (à l’exception des <b><i>Traits</i></b>). Ensuite, attachez à cet ennemi une carte <b><i>Piège</i></b> que vous contrôlez qui n’est pas attachée.</p>");
            AddHtml("Worthy-of-Remembrance-CoE", "<p class='main-text'><b>[Combat] Action</b> : défaussez un allié <b><i>Rohan</i></b> que vous contrôlez pour choisir un ennemi. Infligez 2 points de dégâts à cet ennemi (4 points de dégâts si l’allié défaussé était unique).</p><p class='flavor-text'>“Alors, le cœur d’Eowyn changea [...] Et soudain son hiver passa et le Soleil brilla sur elle.”<br/>— Le Retour du Roi</p>");
            AddHtml("Need-Brooks-No-Delay-CoE", "<p class='main-text'>Le coût pour jouer cette carte est réduit de 1 pour chaque héros <b><i>Rohan</i></b> que vous contrôlez.</p><p class='main-text'><b>[Organisation] Action</b> : cherchez parmi les 10 premières cartes de votre deck une carte ayant un coût imprimé de 2 ou moins (3 ou moins si elle est unique) et mettez-la de côté. Mélangez votre deck. Ensuite, jouez la carte mise de côté gratuitement comme si elle était dans votre main.</p>");
            AddHtml("Wild-Country-CoE", "<p class='main-text'>Maudit 1. Vaste.</p><p class='main-text'><b>Forcé</b> : à la fin de la phase de voyage, si le lieu actif n’est pas vaste, chaque joueur inflige 1 point de dégâts à un personnage qu’il contrôle.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, infligez 1 point de dégâts au personnage défenseur.</p>");
            AddHtml("Endless-Grasslands-CoE", "<p class='main-text'>Vaste.</p><p class='main-text'><b>Forcé</b> : à la fin de la phase de voyage, si le lieu actif n’est pas vaste, chaque joueur incline un allié qu’il contrôle.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, l’ennemi attaquant effectue une attaque supplémentaire après celle-ci.</p>");
            AddHtml("Windworn-Villages-CoE", "<p class='main-text'>Vaste.</p><p class='main-text'><b>Forcé</b> : à la fin de la phase de voyage, si le lieu actif n’est pas vaste, chaque joueur défausse 1 carte de sa main.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, défaussez un attachement du personnage défenseur.</p>");
            AddHtml("Humpbacked-Downs-CoE", "<p class='main-text'>Vaste.</p><p class='main-text'><b>Forcé</b> : à la fin de la phase de voyage, si le lieu actif n’est pas vaste, chaque joueur augmente de 1 son niveau de menace.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, augmentez de 2 votre niveau de menace.</p>");
            AddHtml("Ride-Through-the-Night-CoE", "<p class='main-text'><b>Une fois révélée</b> : inclinez chaque attachement Restreint que les joueurs contrôlent. Si aucun attachement n’est incliné par cet effet, Chevauchée Nocturne gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, le personnage défenseur ne peut pas se redresser jusqu’à la fin du tour.</p>");
            AddHtml("The-Green-Sea-CoE", "<p class='flavor-text'>L’arrière-pays est vaste et sans fin, épuisant même les chevaux les plus robustes de l’Ouestfolde.</p><p class='main-text'>Les lieux vastes gagnent +3 points de quête et sont immunisés aux effets de carte des joueurs.</p><p class='main-text'><b>Forcé</b> : au début de la phase de voyage, s’il n’y a pas de lieu vaste dans la zone de cheminement, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un lieu vaste soit défaussé et placez-le dans la zone de cheminement.</p>{victory:10}");
            AddHtml("Cold-from-the-Mountains-CoE", "<p class='main-text'><b>Une fois révélée</b> : chaque joueur qui contrôle plus de 2 alliés doit défausser un allié qu’il contrôle (2 alliés à la place, s’il en contrôle plus de 5).</p>{shadow}<p class='shadow-text'><b>Ombre</b> : inclinez un personnage que vous contrôlez.</p><p class='flavor-text'>“Que ceux qui le veulent appellent cela le vent.”<br/>—Boromir, La Communauté de l’Anneau</p>");
            AddHtml("Exhausting-Winds-CoE", "<p class='main-text'><b>Une fois révélée</b> : infligez 1 point de dégâts à chaque personnage à qui il reste plus de 1 point de vie. Inclinez chaque personnage qui n’a pas reçu de dégâts par cet effet.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : après cette attaque, infligez X points de dégâts au personnage défenseur. X est égal au nombre de points de vie restant au personnage défenseur moins 1.</p>");
            AddHtml("Tired-and-Hungry-CoE", "<p class='main-text'>Tant qu’elle est attachée à un héros, compte comme un attachement <b><i><b><i>Condition</i></b></i></b> avec le texte : “<b>Forcé</b> : quand un lieu est exploré, inclinez le héros attaché.”.</p><p class='main-text'><b>Une fois révélée</b> : attachez cette carte à un héros redressé n’ayant pas déjà une carte “Fatigué et Affamé” attachée. Si Fatigué et Affamé n’est pas attachée, elle gagne Renfort.</p><p class='flavor-text'>“Ennemis devant, derrière la peur, sous les cieux sera notre lit.” — La Communauté de l’Anneau</p>");
            AddHtml("Exposed-to-the-Elements-CoE", "<p class='flavor-text'>Votre groupe se trouve à la merci de la pluie, de la grêle et de la faim. Vous devez trouver un abri afin d’obtenir un soupçon de répit.</p><p class='main-text'><b>Forcé</b> : à la fin de l’étape de renforcement, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’une traîtrise soit défaussée. Révélez cette carte.</p>{victory:10}");
            AddHtml("Old-Farmhouse-CoE", "<p class='main-text'><b>Forcé</b> : lorsque la Vieille Grange est explorée, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un lieu soit défaussé. Ajoutez ce lieu à la zone de cheminement.</p><p class='flavor-text'>À environ un furlong de la route principale, ils se trouvèrent devant une forte barricade faite de vieilles charrettes renversées. Cela les arrêta.<br/>—Le Retour du Roi</p>");
            AddHtml("Abandoned-Mill-CoE", "<p class='main-text'>Maudit 1. Immunisé aux effets de carte des joueurs.</p><p class='main-text'><b>Forcé</b> : lorsque le Moulin Abandonné est exploré, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un ennemi soit défaussé. Ajoutez cet ennemi à la zone de cheminement.</p><p class='flavor-text'>Il faut avoir du blé pour moudre, et il n’y en avait pas.<br/>— Le Retour du Roi</p>");
            AddHtml("Dunland-Chieftain-CoE", "<p class='main-text'><b>Forcé</b> : lorsque le Chef de Clan de Dun vous engage au combat, défaussez une carte au hasard de votre main. Ensuite, défaussez chaque autre copie de cette carte qui est dans votre main ou en jeu sous votre contrôle.</p><p class='flavor-text'>“Ils nous haïssent, et ils sont contents.”<br/>— Gamelin, Les Deux Tours</p>{victory:1}");
            AddHtml("Wild-Ravager-CoE", "<p class='main-text'><b>Forcé</b> : au début de la phase de rencontre, sélectionnez un joueur au hasard. Le Ravageur Sauvage engage ce joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : l’ennemi attaquant ne peut pas subir de dégâts jusqu’à la fin du tour.</p>");
            AddHtml("Dunlending-Berserker-CoE", "<p class='main-text'><b>Forcé</b> : lorsque le Berserker Dunlending vous engage au combat, infligez 1 point de dégâts à un héros que vous contrôlez et 1 point de dégâts à un ennemi non-unique engagé au combat avec vous.</p><p class='flavor-text'>“Ils ne fléchiront pas maintenant, que ce soit le crépuscule ou l’aube.” — Gamelin, Les Deux Tours</p>");
            AddHtml("Hillman-Scout-CoE", "<p class='main-text'>Archerie 2.</p><p class='main-text'><b>Forcé</b> : lorsque l’Éclaireur des Collines vous engage au combat, inclinez l’allié que vous contrôlez ayant le coût imprimé le plus élevé.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : inclinez un personnage que vous contrôlez ayant 3 {Attack} ou plus.</p>");
            AddHtml("Surprise-Attack-CoE", "<p class='main-text'>Renfort.</p><p class='main-text'><b>Une fois révélée</b> : le prochain ennemi engagé au combat durant ce tour ne peut pas subir de dégâts jusqu’à la fin du tour. Renvoyez-le dans la zone de cheminement après la résolution de son attaque.</p><p class='flavor-text'>Il semblait n’avoir aucune chance d’atteindre le Gué avant que le chemin ne soit coupé par ceux qui étaient restés embusqués. Il les voyait clairement à présent.<br/>— La Communauté de l’Anneau</p>");
            AddHtml("A-History-of-Strife-CoE", "<p class='flavor-text'>Les Dunlendings nourrissent une vieille rancune envers les étrangers. Ils cherchent à vous surprendre, pillant vos provisions avant de vous laisser pour mort.</p><p class='main-text'>Renfort.</p><p class='main-text'>Chaque ennemi <b><i>Pays de Dun</i></b> gagne “<b>Forcé</b> : après avoir engagé au combat cet ennemi, défaussez une ressource de la réserve d’un de vos héros.”</p>{victory:10}");
            AddHtml("Recreant-Rider-CoE", "<p class='main-text'><b>Forcé</b> : lorsque le Cavalier Renégat entre dans la zone de cheminement, il effectue immédiatement une attaque contre le premier joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : renvoyez l’ennemi attaquant dans la zone de cheminement après la résolution de son attaque.</p>");
            AddHtml("Deadly-Defector-CoE", "<p class='main-text'><b>Forcé</b> : à la fin de la phase de combat, si le Meurtrier Transfuge est dans la zone de cheminement, il effectue immédiatement une attaque contre le dernier joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si l’ennemi attaquant est dans la zone de cheminement, il effectue une attaque supplémentaire après celle-ci.</p>");
            AddHtml("Orc-Battalion-CoE", "<p class='main-text'>Le Bataillon Orque ne peut subir de dégâts de combat tant qu’il est attaqué par moins de 3 personnages.</p><p class='main-text'><b>Forcé</b> : après avoir déclaré un personnage comme attaquant contre le Bataillon Orque, infligez 1 point de dégâts à ce personnage.</p>");
            AddHtml("Servant-of-the-Eye-CoE", "<p class='main-text'>Maudit 1.</p><p class='main-text'><b>Forcé</b> : quand le Serviteur de l’Œil vous attaque, augmentez de 1 votre niveau de menace.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : augmentez de 2 votre niveau de menace.</p>");
            AddHtml("Black-Land-Scouts-CoE", "<p class='main-text'><b>Forcé</b> : au début de la phase de combat, soit vous augmentez de 1 le niveau de menace de chaque joueur, soit vous répartissez 4 points de dégâts parmi les personnages en jeu.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : répartissez 2 points de dégâts parmi les personnages que vous contrôlez.</p>");
            AddHtml("Orcish-Horse-butcher-CoE", "<p class='main-text'><b>Forcé</b> : quand le Boucher Chevalin Orque inflige des dégâts à un personnage, choisissez entre : défausser un attachement de ce personnage ou le joueur engagé au combat avec le Boucher Chevalin Orque augmente de 1 son niveau de menace.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit vous défaussez un attachement que vous contrôlez, soit vous augmentez de 3 votre niveau de menace.</p>");
            AddHtml("Crimson-Banner-CoE", "<p class='main-text'>Renfort.</p><p class='main-text'>Tant qu’elle est attachée à un ennemi, compte comme un attachement <b><i><b><i>Condition</i></b></i></b> avec le texte “<b>Forcé</b> : à la fin du tour, augmentez de 1 le niveau de menace de chaque joueur pour chaque ennemi <b><i>Orque</i></b> en jeu.”</p><p class='main-text'><b>Une fois révélée</b> : attachez cette carte à l’ennemi <b><i>Orque</i></b> non-unique ayant le coût d’engagement au combat le plus élevé.</p>");
            AddHtml("White-Mountain-Reinforcements-CoE", "<p class='flavor-text'>D’autres orques descendent de leurs cavernes dans les montagnes, renforçant les assauts de vos adversaires. Si vous ne parvenez pas à les stopper, ils pourraient bien vous submerger.</p><p class='main-text'><b>Une fois révélée</b> : chaque joueur qui n’est pas engagé au combat avec un ennemi doit chercher dans le deck de rencontre ou dans la pile de défausse de rencontre un ennemi et le mettre en jeu, engagé au combat avec lui. Mélangez le deck de rencontre.</p><p class='main-text'>Chaque carte ombre sans effet ombre gagne : “<b>Ombre</b> : augmentez de 1 votre niveau de menace.”</p>{victory:10}");
            AddHtml("Brigand-Ringleader-CoE", "<p class='main-text'>Maraude 3. Immunisé aux effets de carte des joueurs. Ne peut pas recevoir plus de 5 marqueurs de dégâts par tour.</p><p class='main-text'><b>Forcé</b> : à la fin du tour, le joueur engagé au combat avec le Meneur Brigand ajoute la première carte de son deck à sa pile de butin, puis soigne 1 point de dégâts sur le Meneur Brigand pour chaque coût de carte différent dans sa pile de butin.</p>{victory:10}");
            AddHtml("Plundered-Goods-CoE", "<p class='main-text'>Ajoutez 1 au total de {Threat} de la zone de cheminement pour chaque carte dans la pile de butin des Biens Pillés.</p><p class='main-text'><b>Forcé</b> : quand un ennemi quitte le jeu, ajoutez une carte de sa pile de butin à la pile de butin des Biens Pillés, ensuite ajoutez une autre carte de sa pile de butin à la main de son propriétaire. Défaussez le reste.</p><p class='flavor-text'>Les brigands ont dévalisé le stock de lances et de boucliers du village et ont retourné les armes contre les villageois.</p>");
            AddHtml("Pillaging-Swordsman-CoE", "<p class='main-text'>Maraude 1.</p><p class='main-text'>Le Pillard Bretteur gagne +X {Attack}, où X est le coût imprimé le plus élevé parmi les cartes de sa pile de butin.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : ajoutez les deux premières cartes de votre deck à la pile de butin de l’ennemi attaquant.</p>");
            AddHtml("Grasping-Slaver-CoE", "<p class='main-text'>Maraude 2.</p><p class='main-text'><b>Forcé</b> : quand un allié subit des dégâts ou est détruit par l’attaque du Chasseur d’Esclaves, ajoutez cet allié à sa pile de butin.</p><p class='main-text'><b>Forcé</b> : quand le Chasseur d’Esclaves attaque, infligez X points de dégâts parmi les personnages que vous contrôlez. X est le nombre d’alliés dans sa pile de butin.</p>");
            AddHtml("Vengeful-Bowman-CoE", "<p class='main-text'>Maraude 2. Archerie X.</p><p class='main-text'>X est le nombre de types de carte différents dans la pile de butin de l’Archer Vengeur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si cette attaque inflige des dégâts, ajoutez la première carte de votre deck à la pile de butin de l’ennemi attaquant.</p>");
            AddHtml("Sneaky-Thief-CoE", "<p class='main-text'>Maraude 0. Renfort.</p><p class='main-text'><b>Forcé</b> : quand le Voleur Sournois devrait subir des dégâts, s’il possède des cartes dans sa pile de butin, défaussez chacune de ces cartes à la place.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si cette attaque détruit un personnage, l’ennemi attaquant effectue une attaque supplémentaire après celle-ci.</p>");
            AddHtml("Erelas-Gates-CoE", "<p class='main-text'><b>Trajet</b> : chaque joueur doit choisir un ennemi et ajouter la première carte de son deck à sa pile de butin.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : augmentez de 1 votre niveau de menace pour chaque carte dans la pile de butin de l’ennemi attaquant.</p><p class='flavor-text'>Des colonnes tordues et penchées dressaient leurs fûts ébréchés.<br/>— Les Deux Tours</p>");
            AddHtml("Crossroads-CoE", "<p class='main-text'><b>Trajet</b> : mélangez la pile de défausse de rencontre dans le deck de rencontre et défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un ennemi soit défaussé. Mettez en jeu cet ennemi, engagé au combat avec le premier joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : l’ennemi attaquant gagne +X {Attack}, où X est le nombre de sphères différentes parmi les cartes de sa pile de butin.</p>");
            AddHtml("Erelas-Stables-CoE", "<p class='main-text'><b>Trajet</b> : renvoyez dans la zone de cheminement un ennemi engagé au combat avec un joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si l’ennemi attaquant est non-unique, renvoyez-le dans la zone de cheminement après la résolution de son attaque.</p>");
            AddHtml("Chaos-in-the-Hills-CoE", "<p class='main-text'><b>Une fois révélée</b> : renvoyez dans la zone de cheminement l’ennemi engagé au combat ayant le coût d’engagement au combat le plus élevé. Si aucun ennemi n’est renvoyé dans la zone de cheminement par cet effet, Chaos dans les Collines gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : après cette attaque, l’ennemi attaquant engage au combat le joueur suivant et effectue immédiatement une attaque.</p>");
            AddHtml("Looted-Weapons-CoE", "<p class='main-text'>Tant qu’elles sont attachées à un ennemi, les Armes Dérobées comptent comme un attachement <b><i><b><i>Condition</i></b></i></b> avec le texte : “L’ennemi attaché gagne +1 {Threat} et +1 {Attack} pour chaque attachement dans sa pile de butin.”</p><p class='main-text'><b>Une fois révélée</b> : attachez cette carte à l’ennemi en jeu ayant le coût d’engagement au combat le plus élevé. Ensuite, chaque joueur ajoute un attachement <b><i>Objet</i></b> qu’il contrôle à la pile de butin de cet ennemi, si possible. S’il n’y pas d’ennemi en jeu, Armes Dérobées gagne Renfort.</p>");
            AddHtml("Stockpile-Barricade-CoE", "<p class='flavor-text'>Des chariots et des carrioles renversés formaient une barricade solide en travers de la route.</p><p class='main-text'>Renfort.</p><p class='main-text'>Chaque ennemi gagne +1 {Defense} pour chaque attachement dans sa pile de butin.</p><p class='main-text'><b>Forcé </b>: après avoir résolu le mot-clé Maraude d’un ennemi, s’il n’y a pas d’attachement dans sa pile de butin, il effectue immédiatement une attaque contre le joueur engagé au combat avec lui.</p>{victory:10}");
            AddHtml("Erelas-Beacon-CoE", "<p class='main-text'><b>Forcé</b> : à la fin de la phase de combat, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas pour chaque ennemi dans la zone de cheminement.</p><p class='main-text'><b>Le Feu d’Alarme de l’Erelas a X Points de Vie, où X est égal à 2, plus 3{PerPlayer}. Si le Feu d’Alarme de l’Erelas n’a plus de Points de Vie, les joueurs ont perdu la partie.</b></p><p class='flavor-text'>Toutes les terres étaient grises et silencieuses, l’ombre s’épaississait toujours devant eux, et l’espoir s’affaiblissait dans tous les cœurs.<br/>— Le Retour du Roi</p>");
            AddHtml("Host-of-Rohan-CoE", "<p class='main-text'>Sentinelle.</p><p class='main-text'><b>Action</b> : les joueurs en tant que groupe peuvent dépenser 2 ressources pour redresser l’Ost du Rohan. (Limite : une fois par phase.)</p><p class='flavor-text'>“La guerre est ouverte, et les Rohirrim, seigneurs des chevaux, ne dorment pas.”<br/>— Gandalf, Les Deux Tours</p>");
            AddHtml("Enraged-Dunlending-CoE", "<p class='main-text'><b>Forcé</b> : quand le Dunlending Enragé vous engage au combat, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : les points de dégâts infligés au personnage défenseur par cette attaque doivent être assignés au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Bald-Hill-CoE", "<p class='main-text'>Tant que les joueurs contrôlent le feu d’alarme, la Colline Pelée gagne +3 {Threat}.</p><p class='main-text'><b>Trajet</b> : si les joueurs contrôlent le feu d’alarme, infligez 2 points de dégâts au Feu d’Alarme de l’Erelas.</p><p class='flavor-text'>Ils finirent par atteindre ainsi le sommet de la colline grise, et une brise soudaine souffla dans leurs cheveux et agita leurs capes : le vent froid de l’aube. — Les Deux Tours</p>");
            AddHtml("Wooden-Barricade-CoE", "<p class='main-text'>Tant que la Barricade en Bois est dans la zone de cheminement, elle gagne: “<b>Forcé</b> : à la fin de la phase de combat, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas et placez un marqueur de progression sur la Barricade en Bois.”</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit vous défaussez 2 attachements que vous contrôlez, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Rocky-Slope-CoE", "<p class='main-text'>Quand les effets d’une carte de rencontre sont annulés, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p><p class='main-text'><b>Trajet</b> : le premier joueur doit défausser chaque événement de sa main.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit vous défaussez chaque ressource de la réserve de chacun de vos héros, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Surrounding-Grassland-CoE", "<p class='main-text'>Archerie 1.</p><p class='main-text'><b>Forcé</b> : quand les Prairies Environnantes quittent le jeu en tant que lieu exploré, s’il n’y a pas de copie de Prairies Environnantes dans la zone de cheminement, renvoyez ce lieu dans la zone de cheminement.</p><p class='flavor-text'>Ils voyaient par-delà la rivière les prairies vertes de Rohan se perdre dans le gris lointain. — Les Deux Tours</p>");
            AddHtml("Narrow-Stair-CoE", "<p class='main-text'>Chaque joueur ne peut déclarer qu’une seule attaque et qu’un seul attaquant par phase.</p><p class='main-text'>Tant que l’Escalier Étroit est le lieu actif, chaque joueur ne peut défendre qu’une seule attaque par phase (les autres attaques sont considérées sans défense).</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit l’ennemi attaquant gagne +3 {Attack}, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("From-All-Sides-CoE", "<p class='main-text'><b>Une fois révélée</b> : chaque joueur doit choisir entre : soit infliger 1 point de dégâts à 4 personnages différents qu’il contrôle, soit infliger 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : après cette attaque, soit vous défaussez le personnage défenseur, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Another-Wave-CoE", "<p class='main-text'>Maudit 1. Renfort.</p><p class='main-text'><b>Une fois révélée</b> : si les joueurs contrôlent le feu d’alarme, choisissez entre : infliger 2 points de dégâts au Feu d’Alarme de l’Erelas ou révéler une carte du deck de rencontre.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit l’ennemi attaquant effectue une attaque supplémentaire après celle-ci, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Assault-Upon-Erelas-CoE", "<p class='main-text'><b>Une fois révélée</b> : le premier joueur choisit un ennemi engagé au combat avec un joueur et le renvoie dans la zone de cheminement. Si aucun ennemi n’est renvoyé dans la zone de cheminement par cet effet, choisissez entre : infliger 1 point de dégâts au Feu d’Alarme de l’Erelas ou Assaut sur l’Erelas gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit vous augmentez de 4 votre niveau de menace, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Reclaim-the-Beacon-CoE", "<p class='flavor-text'>Reprenez le feu d’alarme, avant que les Dunlendings ne l’endommagent, ou pire.</p><p class='main-text'>Les Dunlendings contrôlent le feu d’alarme. Les ennemis dans la zone de cheminement ne peuvent pas être engagés intentionnellement au combat ou subir de dégâts.</p><p class='main-text'>Il ne peut pas y avoir plus de X marqueurs de progression sur cette étape, où X est égal à 2, plus 1{PerPlayer}. Quand il y a X marqueurs de progression sur cette étape, retournez-la (conservez les marqueurs de progression).</p>");
            AddHtml("Stolen-Steeds-CoE", "<p class='main-text'>Les objectifs <b><i>Monture</i></b> ne peuvent pas être défaussés ou quitter le jeu. Si un objectif <b><i>Monture</i></b> n’est pas attaché, un joueur doit le prendre et l’attacher à un héros qu’il contrôle.</p><p class='main-text'><b>Forcé</b> : à la fin du tour, ajoutez 1 marqueur de progression sur la quête principale pour chaque objectif <b><i>Monture</i></b> que les joueurs contrôlent. Ensuite, augmentez de 1 le niveau de menace de chaque joueur pour pour chaque objectif <b><i>Monture</i></b> en jeu que les joueurs ne contrôlent pas.</p>");
            AddHtml("Flinthoof-CoE", "<p class='main-text'>Protégé (ennemi). Restreint.</p><p class='main-text'>L’ennemi protégeant Sabotdur gagne +1 {Attack}.</p><p class='main-text'>Le héros attaché gagne +1 {Attack}.</p><p class='main-text'><b>[Combat] Action</b> : inclinez Sabotdur pour infliger 1 point de dégâts à un ennemi en jeu.</p><p class='flavor-text'>Leur longue queue flottait au vent, leur crinière était nattée sur leur fière encolure. —Les Deux Tours</p>");
            AddHtml("Brightmane-CoE", "<p class='main-text'>Protégé (lieu). Restreint.</p><p class='main-text'>Le lieu ou l’ennemi protégeant Claircrin gagne +1 {Threat}.</p><p class='main-text'>Le héros attaché gagne +1 {Willpower}.</p><p class='main-text'><b>[Quête] Action</b> : inclinez Claircrin pour regarder la première carte du deck de rencontre. Si cette carte est un lieu, vous pouvez la défausser.</p>");
            AddHtml("Felarof-CoE", "<p class='main-text'>Protégé (ennemi). Restreint.</p><p class='main-text'><b>Forcé</b> : quand l’ennemi protégeant Felaróf attaque, attribuez-lui 2 cartes ombre supplémentaires.</p><p class='main-text'><b>[Combat] Action</b> : inclinez Felaróf pour défausser une carte ombre face cachée en jeu.</p><p class='flavor-text'>“Mais un autre avance devant : un très Grand Cheval. Je n’ai jamais vu son pareil.” — Legolas, Les Deux Tours</p>");
            AddHtml("Thruk-CoE", "<p class='main-text'>Immunisé aux effets de carte des joueurs. Thruk engage au combat le premier joueur.</p><p class='main-text'><b>Forcé</b> : au début de la phase de combat, si Thruk ne protège pas un objectif, il effectue immédiatement une attaque contre le joueur engagé au combat avec lui.</p>{victory:10}");
            AddHtml("Saddle-slasher-CoE", "<p class='main-text'>Archerie X. X est égal à 2, plus 1 pour chaque objectif <b><i>Monture</i></b> que les joueurs contrôlent.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si vous contrôlez un objectif <b><i>Monture</i></b>, choisissez entre : attacher cet objectif à l’ennemi attaquant en tant qu’objectif protégé ou défausser le personnage défenseur après la résolution de cette attaque.</p>");
            AddHtml("Rein-ripper-CoE", "<p class='main-text'><b>Forcé</b> : quand le Rompeur-de-Rêne attaque, attribuez-lui 2 cartes ombre supplémentaires. Vous pouvez attacher un objectif <b><i>Monture</i></b> que vous contrôlez au Rompeur-de-Rêne en tant qu’objectif protégé pour annuler cet effet.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : l’ennemi attaquant gagne +1 {Attack} pour chaque objectif <b><i>Monture</i></b> que les joueurs contrôlent.</p>");
            AddHtml("Bridle-biter-CoE", "<p class='main-text'>Renfort.</p><p class='main-text'><b>Une fois révélée</b> : le Broyeur-de-Bride engage le joueur qui contrôle le plus d’objectifs <b><i>Monture</i></b>.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : mettez en jeu le Broyeur-de-Bride engagé au combat avec vous et attribuez-lui une carte ombre.</p>");
            AddHtml("Pommel-pouncer-CoE", "<p class='main-text'>Tant que l’Arracheur-d’Arçon est dans la zone de cheminement et ne protège pas d’attachement <b><i>Monture</i></b>, il gagne : “<b>Forcé</b> : quand un joueur devrait prendre le contrôle d’un objectif <b><i>Monture</i></b>, attachez cet objectif <b><i>Monture</i></b> à l’Arracheur-d’Arçon en tant qu’objectif protégé à la place.”</p>");
            AddHtml("Spoiled-Pasture-CoE", "<p class='main-text'>X est égal à 2, plus 2 pour chaque objectif <b><i>Monture</i></b> que les joueurs contrôlent.</p><p class='main-text'><b>Forcé</b> : quand un joueur perd le contrôle d’un objectif <b><i>Monture</i></b>, augmentez de 1 son niveau de menace.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : augmentez de 1 votre niveau de menace pour chaque objectif <b><i>Monture</i></b> que vous contrôlez.</p>");
            AddHtml("Horse-Thieves'-Hovel-CoE", "<p class='main-text'>Quand les joueurs ont la possibilité de voyager, ils doivent voyager vers un lieu non-vaste.</p><p class='main-text'><b>Forcé</b> : quand la Masure des Voleurs de Chevaux quitte le jeu en tant que lieu exploré, s’il y a moins de 1{PerPlayer} ennemi en jeu, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un ennemi soit défaussé et placez-le dans la zone de cheminement.</p>{victory:2}");
            AddHtml("Horse-Lord's-Lodge-CoE", "<p class='main-text'>Quand les joueurs ont la possibilité de voyager, ils doivent voyager vers un lieu non-vaste.</p><p class='main-text'><b>Forcé</b> : quand le Logis des Seigneurs des Chevaux quitte le jeu en tant que lieu exploré, s’il y a moins de 1{PerPlayer} lieu en jeu, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un lieu soit défaussé. Placez ce lieu dans la zone de cheminement.</p>{victory:2}");
            AddHtml("Thirst-for-Horse-Blood-CoE", "<p class='main-text'><b>Une fois révélée</b> : chaque joueur qui contrôle un objectif <b><i>Monture</i></b> doit choisir entre : soit révéler une carte de rencontre, soit attacher à l’ennemi sans attachement ayant le coût d’engagement au combat le plus élevé un objectif <b><i>Monture</i></b> qu’il contrôle en tant qu’objectif protégé. Si aucun joueur ne contrôle d’objectif <b><i>Monture</i></b>, Soif de Sang Équin gagne Renfort.</p><p class='flavor-text'>“Nous festoierons encore de chair de cheval ou de quelque chose de mieux.” — Uglúk, Les Deux Tours</p>");
            AddHtml("Overburdened-CoE", "<p class='main-text'><b>Une fois révélée</b> : chaque joueur qui contrôle plus de 2 attachements doit défausser 1 attachement qu’il contrôle, si possible (à la place, si un joueur contrôle plus de 5 attachements, il doit en défausser 2, si possible). Si aucun attachement n’est défaussé par cette effet, Surchargé gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : défaussez 1 carte prise au hasard dans votre main.</p>");
            AddHtml("The-Last-Alliance-CoE", "<p class='main-text'><b></b> Choisissez deux traits, <b><i>A</i></b> et <b><i>B</i></b>. Chacun de vos héros de départ et chaque allié de votre deck doit avoir le trait imprimé <b><i>A</i></b> ou le trait imprimé <b><i>B</i></b>, mais ne peut pas avoir les deux traits. Vous devez avoir au moins 1 héros de départ et 10 alliés avec le trait <b><i>A</i></b> dans votre deck. De même pour le trait <b><i>B</i></b>.</p><p class='main-text'><b>Mise en place</b> : retournez cette carte.</p><p class='flavor-text'>“La force des Elfes pour lui résister était plus grande, il y a longtemps ; et tous les Hommes ne leur étaient pas aliénés.” — Gandalf, La Communauté de l’Anneau</p>");
            AddHtml2("The-Last-Alliance-CoE", "<p class='main-text'></b> Tant que vous contrôlez plus de personnages <b><i>A</i></b> que de personnages <b><i>B</i></b>, réduisez de 1 le coût du premier allié <b><i>B</i></b> que vous jouez à chaque tour, et vice versa.</p><p class='main-text'><b>Action</b> : inclinez La Dernière Alliance pour choisir une carte de votre main ou en jeu sous votre contrôle. Remplacez chaque instance de “<b><i>A</i></b>” ou “<b><i>B</i></b>” sur la capacité de cette carte par “<b><i>A</i></b> ou <b><i>B</i></b>” jusqu’à la fin du tour.</p>");
            AddHtml("Drive-them-Away-CoE", "<p class='flavor-text'>Le long de la Grande Route de l’Ouest, vous arrivez près d’un camp de Rohirrim dans l’ombre de la colline nue du feu d’alarme de l’Erelas. Mais le calme de votre voyage est interrompu par une attaque soudaine ! Le choc de l’acier et les cris des hommes atteignent bientôt vos oreilles. Vous devez les chasser et protéger le camp de nouvelles destructions !</p><p class='main-text'><b></b> <b>Mise en place</b> : mettez de côté le Meneur Brigand, hors jeu. Placez les Biens Pillés dans la zone de cheminement. Chaque joueur cherche un ennemi différent dans le deck de rencontre et le place dans la zone de cheminement. Mélangez le deck de rencontre.</p>");
            AddHtml2("Drive-them-Away-CoE", "<p class='main-text'></b> <b>Forcé</b> : quand un ennemi est détruit, placez 1 marqueur de ressource sur cette carte.</p><p class='main-text'><b>[Rencontre] Action</b> : retirez 5 marqueurs de progression de cette étape pour choisir une carte dans une pile de butin et la défausser. Limite : une fois par tour et par joueur.</p><p class='main-text'><b>S’il y a au moins X marqueurs de ressource sur Repoussez-les, passez à l’étape suivante. X est égal à 1, plus 2{PerPlayer} (2 par joueur).</b></p>");
            AddHtml("Ambush-CoE", "<p class='flavor-text'>Vous vous êtes battu au cœur du campement, mais les brigands se rassemblent autour de leur chef et lancent une violente attaque.</p><p class='main-text'><b></b> <b>Une fois révélée</b> : mettez fin à la phase en cours. Placez le Meneur Brigand dans la zone de cheminement. Chaque joueur qui n’est pas engagé au combat avec un ennemi cherche dans le deck de rencontre ou dans la pile de défausse de rencontre un ennemi et le met en jeu, engagé au combat avec lui. Mélangez le deck de rencontre.</p>");
            AddHtml2("Ambush-CoE", "<p class='main-text'></b> <b>Forcé</b> : quand un ennemi entre en jeu, chaque joueur fait un test d’engagement au combat contre lui.</p><p class='main-text'><b>[Organisation] Action</b>: retirez 5 marqueurs de progression de cette étape pour choisir une carte dans une pile de butin. Le propriétaire de cette carte peut la défausser ou la jouer gratuitement. Limite : quatre fois par tour pour le groupe.</p><p class='main-text'><b>Quand le Meneur Brigand est éliminé, les joueurs ont gagné la partie.</b></p>");
            AddHtml("Battle-for-the-Hill-CoE", "<p class='flavor-text'>Des Dunlendings et des Rohirrim renégats se sont emparés du feu d’alarme de l’Erelas. Reprenez la colline à tout prix !</p><p class='main-text'><b></b> <b>Mise en place</b> : mettez de côté l’Ost du Rohan, hors jeu. Placez le Feu d’Alarme de l’Erelas et 1{PerPlayer} Dunlending Enragé dans la zone de cheminement. Placez la quête annexe double-face dans la zone de cheminement, du côté Reprendre le Feu d’Alarme. Cherchez un exemplaire de Prairies Environnantes dans le deck de rencontre et faites-en le lieu actif. Mélangez le deck de rencontre.</p>");
            AddHtml2("Battle-for-the-Hill-CoE", "<p class='main-text'></b> <b>Forcé</b> : après avoir placé n’importe quel nombre de marqueurs de progression sur cette étape, chaque joueur doit choisir entre : soit incliner un personnage qu’il contrôle, soit infliger 1 point de dégâts au Feu d’Alarme de l’Erelas.</p><p class='main-text'><b>Cette étape ne peut être passée tant que les Dunlendings contrôlent le feu d’alarme.</b></p>");
            AddHtml("Hold-the-Hilltop-CoE", "<p class='flavor-text'>Alors que vos ennemis se rassemblent pour un nouvel assaut sur le feu d’alarme, vous pouvez apercevoir les torches des troupes de Gálmód se massant en contrebas.</p><p class='main-text'><b></b> <b>Une fois révélée</b> : placez des marqueurs de progression sur Défendre le Feu d’Alarme (en ignorant tout lieu actif) jusqu’à ce qu’il y ait X marqueurs de progression dessus, où X est égal à 2, plus 1{PerPlayer}. Mélangez la pile de défausse de rencontre dans le deck de rencontre. Chaque joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi et le place dans la zone de cheminement.</p>");
            AddHtml2("Hold-the-Hilltop-CoE", "<p class='main-text'></b> Temps 3.</p><p class='main-text'><b>Forcé</b> : à la fin du tour, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas (2 points de dégâts s’il y a au moins 3 joueurs dans la partie). Ensuite, s’il n’y a plus de compteur de temps sur cette étape, passez immédiatement à l’étape 3.</p><p class='main-text'><b>Forcé</b> : quand Défendre le Feu d’Alarme devient la quête en cours, révélez une carte de rencontre.</p><p class='main-text'><b>Si les Dunlendings contrôlent le feu d’alarme, les joueurs ont perdu la partie.</b></p>");
            AddHtml("The-Last-Push-CoE", "<p class='flavor-text'>Alors que les forces de Gálmód chevauchent pour encercler l’ennemi, vous devez vous armer pour une ultime offensive.</p><p class='main-text'><b></b> <b>Une fois révélée</b> : retirez tous les marqueurs de progression sur Défendre le Feu d’Alarme et retournez-la. Mettez l’Ost du Rohan en jeu sous le contrôle du premier joueur. Mélangez la pile de défausse de rencontre dans le deck de rencontre. Chaque joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi et le place dans la zone de cheminement.</p>");
            AddHtml2("The-Last-Push-CoE", "<p class='main-text'></b> Ajoutez 2 au total de {Threat} dans la zone de cheminement pour chaque dégât sur le Feu d’Alarme de l’Erelas.</p><p class='main-text'><b>Forcé</b> : au début de la phase de combat, chaque ennemi engagé au combat effectue immédiatement une attaque.</p><p class='main-text'><b>Forcé</b> : quand un personnage quitte le jeu, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p><p class='main-text'><b>À la fin du tour, si les Dunlendings contrôlent le feu d’alarme, les joueurs ont perdu la partie, et si les joueurs contrôlent le feu d’alarme, ils ont gagné la partie.</b></p>");
            AddHtml("Thieves-and-Coursers-CoE", "<p class='flavor-text'>Side A: Des orques ont envahi l’Estfolde, ravageant le pays et capturant les chevaux de guerre préférés du roi Thengel. Side B: Si vous récupérez Sabotdur et Claircrin, vous pourrez peut-être arrêter l’ost des orques avant qu’il n’atteigne Aldburg.</p><p class='main-text'><b></b> <b>Mise en place</b> : placez Coursiers Volés dans la zone de cheminement. Mettez Thruk, les objectifs <b><i>Monture</i></b>, et les 8 ennemis du set de rencontre Ost des Orques de côté, hors jeu. Mélangez le deck de rencontre. Le premier joueur révèle Sabotdur et Claircrin et les place dans la zone de cheminement. Chaque autre joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi ou un lieu et le place dans la zone de cheminement.</p>");
            AddHtml2("Thieves-and-Coursers-CoE", "<p class='main-text'></b> <b>Cette étape ne peut être passée tant que les joueurs ne contrôlent pas au moins 2 objectifs <b><i>Monture</i></b>.</b></p>");
            AddHtml("The-King's-Stallion-CoE", "<p class='flavor-text'>Le chef de guerre Thruk est arrivé dans la bataille, chevauchant le puissant Felaróf et hurlant des ordres à sa troupe. “Rassemblement ! Ce soir, nous festoierons de chair de cheval !”</p><p class='main-text'><b></b> <b>Une fois révélée</b> : s’il s’agit de la phase de combat, mettez fin à la phase. Mélangez la pile de défausse de rencontre dans le deck de rencontre. Le premier joueur place Thruk dans la zone de cheminement et lui attache Felaróf en tant qu’objectif protégé. Chaque autre joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi et le met en jeu, engagé au combat avec lui.</p>");
            AddHtml2("The-King's-Stallion-CoE", "<p class='main-text'></b> Thruk ne peut pas subir de dégâts, sauf s’il y a au moins 4 marqueurs de progression sur cette étape.</p><p class='main-text'><b>Cette étape ne peut être passée tant que les joueurs ne contrôlent pas 3 objectifs <b><i>Monture</i></b>.</b></p>");
            AddHtml("The-Sweeping-Tide-CoE", "<p class='flavor-text'>L’ost des orques tout entier a répondu au cri de ralliement de Thruk. Vous devez vous unir pour une charge finale afin de les disperser dans les collines.</p><p class='main-text'><b></b> <b>Une fois révélée</b> : s’il s’agit de la phase de combat, mettez fin à la phase. Mélangez la pile de défausse de rencontre dans le deck de rencontre. Cherchez Thruk dans la pile de victoire et placez le dans la zone de cheminement. Chaque joueur choisit 2 ennemis du set de rencontre mis de côté Ost des Orques et les met en jeu, engagés au combat avec lui. Un des ennemis mis en jeu de cette façon doit être le Bataillon Orque.</p>");
            AddHtml2("The-Sweeping-Tide-CoE", "<p class='main-text'></b> Sautez l’étape de renforcement de la phase de Quête. À tout moment, si le deck de rencontre est vide, mélangez la pile de défausse dans le deck de rencontre.</p><p class='main-text'><b>Forcé</b> : quand un ennemi effectue une attaque, attribuez-lui 1 carte ombre supplémentaire.</p><p class='main-text'><b>Si un objectif <b><i>Monture</i></b> est attaché à un ennemi, les joueurs ont perdu la partie. S’il n’y a plus d’ennemis en jeu, les joueurs ont gagné la partie.</b></p>");
            //AddHtml("Reclaim-the-Beacon-CoE", "<p class='main-text'>Les joueurs contrôlent le feu d’alarme. Les cartes ombre sont immunisées aux effets de carte des joueurs.</p><p class='main-text'>Il ne peut pas y avoir plus de X marqueurs de progression sur cette étape, où X est égal à 2, plus 1{PerPlayer}.</p><p class='main-text'><b>Réponse</b> : retirez n’importe quel nombre de marqueurs de progression sur Défendre le Feu d’Alarme pour annuler autant de dégâts tout juste infligés au Feu d’Alarme de l’Erelas. Ensuite, si cette étape a 0 marqueur de progression, retournez-la.</p>");

        }
    }
}