using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Services.LotR.Templates
{
    public class FrenchTemplateRepository : TemplateRepository
    {
        protected override void Initialize()
        {
            CoreSet();

            ChildrenOfEorl();
            TheAldburgPlot();
        }

        private void CoreSet()
        {
            AddHtml("Aragorn-Core", "<p class='main-text'>{keyword:Sentinelle.}</p><p class='main-text'><b>Réponse:</b> quand {self} s'engage dans une quête, dépensez I ressource de sa réserve pour le redresser.</p><p class='flavor-text'>&laquo;Je suis Aragorn, fils d'Ararthorn, et si, par la vie ou par la mort, je puis vous sauver, je le ferai.&raquo;<br>&ndash;La Communaute de l'Anneau</p>");
            AddHtml("Beorn-Core", "<p class='main-text'><b>Action:</b> {self} gagne +5 {Attack} jusqu'a la fin de la phase. A la fin de la phase ou vous avez declenche cet effet, melangez {self} dans votre deck. (Limite: une fois par tour).</p><p class='flavor-text'>&laquo; Je n'ai pas besoin de vos services, merci... mais sans doute avez-vous besoin des miens. &raquo;<br>&ndash; Le Hobbit</p>");
            AddHtml("Guard-of-the-Citadel-Core", "<p class='flavor-text'>&laquo;Mais les Seigneurs de Minas Tirith continuent de se battre, defiant nos ennemis, gardant le passage de la riviere, d'Argonath a la mer.&laquo;<br>&ndash;Elrond, La Communaute de l'Anneau</p>");
        }

        private void ChildrenOfEorl()
        {
            //Children of Eorl
            AddHtml("Ingold-CoE", "<p class='main-text'><b>Réponse:</b> quand un allié <b><i>Gondor</i></b> ou <b><i>Guerrier</i></b> entre en jeu sous votre contrôle, piochez une carte. Ensuite, vous devez dépenser une ressource de la réserve d’Ingold ou augmenter de 1 votre niveau de menace. (Limite : une fois par phase.)</p><p class='flavor-text'>“Nous ne désirons aucun étranger dans le pays en ce moment, sauf de vigoureux hommes d’armes, en la loyauté et l’aide desquels nous puissions avoir confiance.” — Le Retour du Roi</p>");
            AddHtml("Celador-CoE", "<p class='main-text'>À distance.</p><p class='main-text'>Diminuez de 1 le total de {Threat} dans la zone de cheminement pour chaque carte <b><i>Piège</i></b> que vous contrôlez qui n’est pas attachée.</p><p class='main-text'><b>Réponse</b> : quand une carte <b><i>Piège</i></b> que vous contrôlez est attachée à un ennemi, choisissez entre : redresser Celador ou diminuer de 1 votre niveau de menace.</p><p class='flavor-text'>“Un sage ne se fie pas à une rencontre par hasard dans ce pays” — Faramir, Les Deux Tours</p>");
            AddHtml("Thengel-CoE", "<p class='main-text'><b>Réponse</b> : quand un allié en jeu est défaussé, le contrôleur de cette carte cherche parmi les 5 premières cartes de son deck un allié partageant au moins 1 <b><i>Trait</i></b> avec l’allié défaussé, le met en jeu incliné, et mélange son deck. (Limite : une fois par tour.)</p><p class='flavor-text'>“Mon ami, dit Gandalf, vous aviez des chevaux, des faits d’armes et des champs libres” — Le Retour du Roi</p>");
            AddHtml("Herubrand-CoE", "<p class='main-text'>Herubrand gagne +1 {Willpower} pour chaque héros que vous contrôlez ayant au moins 1 attachement Restreint.</p><p class='main-text'><b>Réponse</b> : quand un ennemi est détruit dans la zone de cheminement, piochez une carte.</p><p class='flavor-text'>“Quel fardeau portez-vous, Hommes de Rohan ?” — Imrahil, Le Retour du Roi</p>");
            AddHtml("Deeping-Bowman-CoE", "<p class='main-text'>Dévoué. À distance.</p><p class='main-text'><b>Action</b> : défaussez l’Archer du Gouffre pour choisir un ennemi. Jusqu’à la fin de la phase, cet ennemi ne compte pas sa {Defense} quand vous déterminez les dégâts de combat.</p><p class='flavor-text'>“Nous avons lâché jusqu’à notre dernière flèche, et rempli le Fossé d’Orques” — Les Deux Tours</p>");
            AddHtml("Open-the-Gates-CoE", "<p class='main-text'><b>Action</b> : cherchez parmi les 5 premières cartes de votre deck un allié partageant au moins 1 <b><i>Trait</i></b> avec chacun de vos héros et mettez-le en jeu. Mélangez votre deck. À la fin de la phase, si cet allié est encore en jeu, ajoutez-le à votre main.</p><p class='flavor-text'>“Il semblait que la nouvelle de leur venue les avait devancés, et ils furent admis aussitôt, en silence et sans questions.” — Le Retour du Roi</p>");
            AddHtml("Wealth-of-Adventure-CoE", "<p class='main-text'><b>Action</b> : cherchez dans votre deck 1 carte <b><i>Compétence</i></b> et ajoutez-la à votre main. Mélangez votre deck.</p><p class='flavor-text'>“C’est une affaire dangereuse de passer ta porte, Frodon, me disait-il. Tu vas sur la route et, si tu ne retiens pas tes pieds, Dieu sait jusqu’où tu pourrais être emporté”<br/>— Frodon, La Communauté de l’Anneau</p>");
            AddHtml("Feast-of-Plenty-CoE", "<p class='main-text'>Le coût en ressources de Festin d’Abondance doit être payé avec la réserve d’un seul héros.</p><p class='main-text'><b>Action</b> : redressez jusqu’à 3 héros et ajoutez 1 ressource à la réserve de chacun de ces héros. Seul 1 exemplaire de Festin d’Abondance peut être joué par les joueurs à chaque tour.</p><p class='flavor-text'>“Le festin était joyeux et la chère répondait à tout ce que sa faim pouvait désirer” — La Communauté de l’Anneau</p>");
            AddHtml("Deeping-Defender-CoE", "<p class='main-text'>Dévoué.</p><p class='main-text'><b>Réponse</b> : après que le Défenseur du Gouffre a défendu contre une attaque, renvoyez l’ennemi attaquant dans la zone de cheminement et infligez-lui 1 point de dégâts.</p><p class='flavor-text'>“Le soleil couchant dorait leurs lances et leurs casques, et étincelait dans leurs cheveux pâles et flottants.”<br/>— Les Deux Tours</p>");
            AddHtml("Morwen-Steelsheen-CoE", "<p class='main-text'><b>Action</b> : mettez Morwen Lustre d’Acier en jeu depuis votre main. Ensuite, défaussez un allié <b><i>Rohan</i></b> ou <b><i>Gondor</i></b> que vous contrôlez.</p><p class='main-text'><b>Réponse</b> : quand un allié <b><i>Rohan</i></b> ou <b><i>Gondor</i></b> quitte le jeu, inclinez Morwen Lustre d’Acier pour choisir entre : soigner 2 points de dégâts sur un personnage ou diminuer de 1 votre niveau de menace.</p>");
            AddHtml("It-Should-Be-Spared-CoE", "<p class='main-text'><b>Réponse</b> : quand une carte <b><i>Piège</i></b> que vous contrôlez est attachée à un ennemi, ramenez-la dans votre main. Ensuite, jouez-la de votre main gratuitement.</p><p class='flavor-text'>“Mais je n’abats ni homme ni bête sans nécessité, et je ne le fais pas de gaieté de cœur quand je le dois.” — Faramir, Les Deux Tours</p>");
            AddHtml("Spring-the-Trap-CoE", "<p class='main-text'><b>Réponse</b> : quand une carte <b><i>Piège</i></b> que vous contrôlez est attachée à un ennemi, mettez en jeu un allié <b><i>Rôdeur</i></b> depuis votre main.</p><p class='flavor-text'>“La route passe peut-être, mais eux ne passeront pas ! Pas tant que Faramir sera Capitaine.”<br/>— Mablung, Les Deux Tours</p>");
            AddHtml("Squire-of-the-Mark-CoE", "<p class='main-text'><b>Réponse</b> : quand un allié <b><i>Rohan</i></b> que vous contrôlez est défaussé, ajoutez l’Écuyer de la Marche à la pile de victoire pour mettre en jeu cet allié incliné.</p><p class='flavor-text'>“Je ne puis rendre que peu de services à votre seigneur, mais ce que je peux faire, je le ferai”<br/>— Pippin, Le Retour du Roi</p>");
            AddHtml("Rammas-Lookout-CoE", "<p class='main-text'>Dévoué.</p><p class='main-text'>Tant que chaque héros que vous contrôlez a au moins 1 ressource dans sa réserve, le Guetteur du Rammas gagne +1 {Willpower} et n’est pas incliné pour s’engager dans une quête.</p><p class='flavor-text'>“Quoi qu’il advienne, vous êtes parvenus à la fin du Gondor que vous avez connu. Laissez-moi passer !”<br/>— Gandalf, Le Retour du Roi</p>");
            AddHtml("Theodwyn-CoE", "<p class='main-text'><b>Réponse</b> : quand Théodwyn entre en jeu, choisissez entre : piocher 1 carte ou ajouter une ressource à la réserve d’un héros <b><i>Noble</i></b>.</p><p class='flavor-text'>“Elle est intrépide et a le cœur haut placé. Elle est aimée de tous. Qu’elle soit le seigneur des Eorlingas, pendant notre absence.” — Háma, Les Deux Tours</p>");
            AddHtml("Light-footed-Steed-CoE", "<p class='main-text'>Attachez cette carte à un héros <b><i>Rohan</i></b>. Restreint.</p><p class='main-text'><b>Réponse</b> : quand un personnage que vous contrôlez quitte le jeu, inclinez le Coursier au Pied Léger pour redresser le héros attaché. Ensuite, si le personnage ayant quitté le jeu était unique, ce héros gagne +1 {Attack} jusqu’à la fin du tour.</p><p class='flavor-text'>“… et n’oublie pas leurs chevaux ! Ils peuvent voir le vent nocturne, ou en tout cas on le dit.”<br/>— Uglúk, Les Deux Tours</p>");
            AddHtml("Rammas-Sentry-CoE", "<p class='main-text'>Dévoué.</p><p class='main-text'>Tant que chaque héros que vous contrôlez a au moins 1 ressource dans sa réserve, la Sentinelle du Rammas gagne : “<b>Réponse</b> : annulez 1 point de dégâts tout juste infligé à un personnage <b><i>Gondor</i></b>. (Limite : une fois par phase.)”</p><p class='flavor-text'>“Car si nous tombons, qui tiendra ?”<br/>— Beregond, Le Retour du Roi</p>");
            AddHtml("Live-Bait-CoE", "<p class='main-text'>Vous ne pouvez jouer cette carte que si vous contrôlez une carte <b><i>Piège</i></b> qui n’est pas attachée.</p><p class='main-text'><b>Action</b> : choisissez un ennemi non-unique en jeu. Jusqu’à la fin du tour, cet ennemi perd le texte imprimé dans sa boîte de texte (à l’exception des <b><i>Traits</i></b>). Ensuite, attachez à cet ennemi une carte <b><i>Piège</i></b> que vous contrôlez qui n’est pas attachée.</p>");
            AddHtml("Worthy-of-Remembrance-CoE", "<p class='main-text'><b>[Combat] Action</b> : défaussez un allié <b><i>Rohan</i></b> que vous contrôlez pour choisir un ennemi. Infligez 2 points de dégâts à cet ennemi (4 points de dégâts si l’allié défaussé était unique).</p><p class='flavor-text'>“Alors, le cœur d’Eowyn changea [...] Et soudain son hiver passa et le Soleil brilla sur elle.”<br/>— Le Retour du Roi</p>");
            AddHtml("Need-Brooks-No-Delay-CoE", "<p class='main-text'>Le coût pour jouer cette carte est réduit de 1 pour chaque héros <b><i>Rohan</i></b> que vous contrôlez.</p><p class='main-text'><b>[Organisation] Action</b> : cherchez parmi les 10 premières cartes de votre deck une carte ayant un coût imprimé de 2 ou moins (3 ou moins si elle est unique) et mettez-la de côté. Mélangez votre deck. Ensuite, jouez la carte mise de côté gratuitement comme si elle était dans votre main.</p>");
            AddHtml("Wild-Country-CoE", "<p class='main-text'>Maudit 1. Vaste.</p><p class='main-text'><b>Forcé</b> : à la fin de la phase de voyage, si le lieu actif n’est pas vaste, chaque joueur inflige 1 point de dégâts à un personnage qu’il contrôle.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, infligez 1 point de dégâts au personnage défenseur.</p>");
            AddHtml("Endless-Grasslands-CoE", "<p class='main-text'>Vaste.</p><p class='main-text'><b>Forcé</b> : à la fin de la phase de voyage, si le lieu actif n’est pas vaste, chaque joueur incline un allié qu’il contrôle.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, l’ennemi attaquant effectue une attaque supplémentaire après celle-ci.</p>");
            AddHtml("Windworn-Villages-CoE", "<p class='main-text'>Vaste.</p><p class='main-text'><b>Forcé</b> : à la fin de la phase de voyage, si le lieu actif n’est pas vaste, chaque joueur défausse 1 carte de sa main.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, défaussez un attachement du personnage défenseur.</p>");
            AddHtml("Humpbacked-Downs-CoE", "<p class='main-text'>Vaste.</p><p class='main-text'><b>Forcé</b> : à la fin de la phase de voyage, si le lieu actif n’est pas vaste, chaque joueur augmente de 1 son niveau de menace.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, augmentez de 2 votre niveau de menace.</p>");
            AddHtml("Ride-Through-the-Night-CoE", "<p class='main-text'><b>Une fois révélée</b> : inclinez chaque attachement Restreint que les joueurs contrôlent. Si aucun attachement n’est incliné par cet effet, Chevauchée Nocturne gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si le lieu actif est vaste, le personnage défenseur ne peut pas se redresser jusqu’à la fin du tour.</p>");
            AddHtml("The-Green-Sea-CoE", "<p class='flavor-text'>L’arrière-pays est vaste et sans fin, épuisant même les chevaux les plus robustes de l’Ouestfolde.</p><p class='main-text'>Les lieux vastes gagnent +3 points de quête et sont immunisés aux effets de carte des joueurs.</p><p class='main-text'><b>Forcé</b> : au début de la phase de voyage, s’il n’y a pas de lieu vaste dans la zone de cheminement, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un lieu vaste soit défaussé et placez-le dans la zone de cheminement.</p>{victory:10}");
            AddHtml("Cold-from-the-Mountains-CoE", "<p class='main-text'><b>Une fois révélée</b> : chaque joueur qui contrôle plus de 2 alliés doit défausser un allié qu’il contrôle (2 alliés à la place, s’il en contrôle plus de 5).</p>{shadow}<p class='shadow-text'><b>Ombre</b> : inclinez un personnage que vous contrôlez.</p><p class='flavor-text'>“Que ceux qui le veulent appellent cela le vent.”<br/>—Boromir, La Communauté de l’Anneau</p>");
            AddHtml("Exhausting-Winds-CoE", "<p class='main-text'><b>Une fois révélée</b> : infligez 1 point de dégâts à chaque personnage à qui il reste plus de 1 point de vie. Inclinez chaque personnage qui n’a pas reçu de dégâts par cet effet.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : après cette attaque, infligez X points de dégâts au personnage défenseur. X est égal au nombre de points de vie restant au personnage défenseur moins 1.</p>");
            AddHtml("Tired-and-Hungry-CoE", "<p class='main-text'>Tant qu’elle est attachée à un héros, compte comme un attachement <b><i><b><i>Condition</i></b></i></b> avec le texte : “<b>Forcé</b> : quand un lieu est exploré, inclinez le héros attaché.”.</p><p class='main-text'><b>Une fois révélée</b> : attachez cette carte à un héros redressé n’ayant pas déjà une carte “Fatigué et Affamé” attachée. Si Fatigué et Affamé n’est pas attachée, elle gagne Renfort.</p><p class='flavor-text'>“Ennemis devant, derrière la peur, sous les cieux sera notre lit.” — La Communauté de l’Anneau</p>");
            AddHtml("Exposed-to-the-Elements-CoE", "<p class='flavor-text'>Votre groupe se trouve à la merci de la pluie, de la grêle et de la faim. Vous devez trouver un abri afin d’obtenir un soupçon de répit.</p><p class='main-text'><b>Forcé</b> : à la fin de l’étape de renforcement, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’une traîtrise soit défaussée. Révélez cette carte.</p>{victory:10}");
            AddHtml("Old-Farmhouse-CoE", "<p class='main-text'><b>Forcé</b> : lorsque la Vieille Grange est explorée, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un lieu soit défaussé. Ajoutez ce lieu à la zone de cheminement.</p><p class='flavor-text'>À environ un furlong de la route principale, ils se trouvèrent devant une forte barricade faite de vieilles charrettes renversées. Cela les arrêta.<br/>—Le Retour du Roi</p>");
            AddHtml("Abandoned-Mill-CoE", "<p class='main-text'>Maudit 1. Immunisé aux effets de carte des joueurs.</p><p class='main-text'><b>Forcé</b> : lorsque le Moulin Abandonné est exploré, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un ennemi soit défaussé. Ajoutez cet ennemi à la zone de cheminement.</p><p class='flavor-text'>Il faut avoir du blé pour moudre, et il n’y en avait pas.<br/>— Le Retour du Roi</p>");
            AddHtml("Dunland-Chieftain-CoE", "<p class='main-text'><b>Forcé:</b> lorsque le Chef de Clan de Dun vous engage au combat, défaussez une carte au hasard de votre main. Ensuite, défaussez chaque autre copie de cette carte qui est dans votre main ou en jeu sous votre contrôle.</p><p class='flavor-text'>“Ils nous haïssent, et ils sont contents.”<br/>— Gamelin, Les Deux Tours</p>{victory:1}");
            AddHtml("Wild-Ravager-CoE", "<p class='main-text'><b>Forcé:</b> au début de la phase de rencontre, sélectionnez un joueur au hasard. Le Ravageur Sauvage engage ce joueur.</p>{shadow}<p class='shadow-text'><b>Ombre:</b> l’ennemi attaquant ne peut pas subir de dégâts jusqu’à la fin du tour.</p>");
            AddHtml("Dunlending-Berserker-CoE", "<p class='main-text'><b>Forcé</b> : lorsque le Berserker Dunlending vous engage au combat, infligez 1 point de dégâts à un héros que vous contrôlez et 1 point de dégâts à un ennemi non-unique engagé au combat avec vous.</p><p class='flavor-text'>“Ils ne fléchiront pas maintenant, que ce soit le crépuscule ou l’aube.” — Gamelin, Les Deux Tours</p>");
            AddHtml("Hillman-Scout-CoE", "<p class='main-text'>Archerie 2.</p><p class='main-text'><b>Forcé</b> : lorsque l’Éclaireur des Collines vous engage au combat, inclinez l’allié que vous contrôlez ayant le coût imprimé le plus élevé.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : inclinez un personnage que vous contrôlez ayant 3 {Attack} ou plus.</p>");
            AddHtml("Surprise-Attack-CoE", "<p class='main-text'>Renfort.</p><p class='main-text'><b>Une fois révélée</b> : le prochain ennemi engagé au combat durant ce tour ne peut pas subir de dégâts jusqu’à la fin du tour. Renvoyez-le dans la zone de cheminement après la résolution de son attaque.</p><p class='flavor-text'>Il semblait n’avoir aucune chance d’atteindre le Gué avant que le chemin ne soit coupé par ceux qui étaient restés embusqués. Il les voyait clairement à présent.<br/>— La Communauté de l’Anneau</p>");
            AddHtml("A-History-of-Strife-CoE", "<p class='flavor-text'>Les Dunlendings nourrissent une vieille rancune envers les étrangers. Ils cherchent à vous surprendre, pillant vos provisions avant de vous laisser pour mort.</p><p class='main-text'>Renfort.</p><p class='main-text'>Chaque ennemi <b><i>Pays de Dun</i></b> gagne “<b>Forcé</b> : après avoir engagé au combat cet ennemi, défaussez une ressource de la réserve d’un de vos héros.”</p>{victory:10}");
            AddHtml("Recreant-Rider-CoE", "<p class='main-text'><b>Forcé</b> : lorsque le Cavalier Renégat entre dans la zone de cheminement, il effectue immédiatement une attaque contre le premier joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : renvoyez l’ennemi attaquant dans la zone de cheminement après la résolution de son attaque.</p>");
            AddHtml("Deadly-Defector-CoE", "<p class='main-text'><b>Forcé</b> : à la fin de la phase de combat, si le Meurtrier Transfuge est dans la zone de cheminement, il effectue immédiatement une attaque contre le dernier joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si l’ennemi attaquant est dans la zone de cheminement, il effectue une attaque supplémentaire après celle-ci.</p>");
            AddHtml("Orc-Battalion-CoE", "<p class='main-text'>Le Bataillon Orque ne peut subir de dégâts de combat tant qu’il est attaqué par moins de 3 personnages.</p><p class='main-text'><b>Forcé</b> : après avoir déclaré un personnage comme attaquant contre le Bataillon Orque, infligez 1 point de dégâts à ce personnage.</p>");
            AddHtml("Servant-of-the-Eye-CoE", "<p class='main-text'>Maudit 1.</p><p class='main-text'><b>Forcé</b> : quand le Serviteur de l’Œil vous attaque, augmentez de 1 votre niveau de menace.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : augmentez de 2 votre niveau de menace.</p>");
            AddHtml("Black-Land-Scouts-CoE", "<p class='main-text'><b>Forcé</b> : au début de la phase de combat, soit vous augmentez de 1 le niveau de menace de chaque joueur, soit vous répartissez 4 points de dégâts parmi les personnages en jeu.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : répartissez 2 points de dégâts parmi les personnages que vous contrôlez.</p>");
            AddHtml("Orcish-Horse-butcher-CoE", "<p class='main-text'><b>Forcé</b> : quand le Boucher Chevalin Orque inflige des dégâts à un personnage, choisissez entre : défausser un attachement de ce personnage ou le joueur engagé au combat avec le Boucher Chevalin Orque augmente de 1 son niveau de menace.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit vous défaussez un attachement que vous contrôlez, soit vous augmentez de 3 votre niveau de menace.</p>");
            AddHtml("Crimson-Banner-CoE", "<p class='main-text'>Renfort.</p><p class='main-text'>Tant qu’elle est attachée à un ennemi, compte comme un attachement <b><i><b><i>Condition</i></b></i></b> avec le texte “<b>Forcé</b> : à la fin du tour, augmentez de 1 le niveau de menace de chaque joueur pour chaque ennemi <b><i>Orque</i></b> en jeu.”</p><p class='main-text'><b>Une fois révélée</b> : attachez cette carte à l’ennemi <b><i>Orque</i></b> non-unique ayant le coût d’engagement au combat le plus élevé.</p>");
            AddHtml("White-Mountain-Reinforcements-CoE", "<p class='flavor-text'>D’autres orques descendent de leurs cavernes dans les montagnes, renforçant les assauts de vos adversaires. Si vous ne parvenez pas à les stopper, ils pourraient bien vous submerger.</p><p class='main-text'><b>Une fois révélée</b> : chaque joueur qui n’est pas engagé au combat avec un ennemi doit chercher dans le deck de rencontre ou dans la pile de défausse de rencontre un ennemi et le mettre en jeu, engagé au combat avec lui. Mélangez le deck de rencontre.</p><p class='main-text'>Chaque carte ombre sans effet ombre gagne : “<b>Ombre</b> : augmentez de 1 votre niveau de menace.”</p>{victory:10}");
            AddHtml("Brigand-Ringleader-CoE", "<p class='main-text'>Maraude 3. Immunisé aux effets de carte des joueurs. Ne peut pas recevoir plus de 5 marqueurs de dégâts par tour.</p><p class='main-text'><b>Forcé</b> : à la fin du tour, le joueur engagé au combat avec le Meneur Brigand ajoute la première carte de son deck à sa pile de butin, puis soigne 1 point de dégâts sur le Meneur Brigand pour chaque coût de carte différent dans sa pile de butin.</p>{victory:10}");
            AddHtml("Plundered-Goods-CoE", "<p class='main-text'>Ajoutez 1 au total de {Threat} de la zone de cheminement pour chaque carte dans la pile de butin des Biens Pillés.</p><p class='main-text'><b>Forcé</b> : quand un ennemi quitte le jeu, ajoutez une carte de sa pile de butin à la pile de butin des Biens Pillés, ensuite ajoutez une autre carte de sa pile de butin à la main de son propriétaire. Défaussez le reste.</p><p class='flavor-text'>Les brigands ont dévalisé le stock de lances et de boucliers du village et ont retourné les armes contre les villageois.</p>");
            AddHtml("Pillaging-Swordsman-CoE", "<p class='main-text'>Maraude 1.</p><p class='main-text'>Le Pillard Bretteur gagne +X {Attack}, où X est le coût imprimé le plus élevé parmi les cartes de sa pile de butin.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : ajoutez les deux premières cartes de votre deck à la pile de butin de l’ennemi attaquant.</p>");
            AddHtml("Grasping-Slaver-CoE", "<p class='main-text'>Maraude 2.</p><p class='main-text'><b>Forcé</b> : quand un allié subit des dégâts ou est détruit par l’attaque du Chasseur d’Esclaves, ajoutez cet allié à sa pile de butin.</p><p class='main-text'><b>Forcé</b> : quand le Chasseur d’Esclaves attaque, infligez X points de dégâts parmi les personnages que vous contrôlez. X est le nombre d’alliés dans sa pile de butin.</p>");
            AddHtml("Vengeful-Bowman-CoE", "<p class='main-text'>Maraude 2. Archerie X.</p><p class='main-text'>X est le nombre de types de carte différents dans la pile de butin de l’Archer Vengeur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si cette attaque inflige des dégâts, ajoutez la première carte de votre deck à la pile de butin de l’ennemi attaquant.</p>");
            AddHtml("Sneaky-Thief-CoE", "<p class='main-text'>Maraude 0. Renfort.</p><p class='main-text'><b>Forcé</b> : quand le Voleur Sournois devrait subir des dégâts, s’il possède des cartes dans sa pile de butin, défaussez chacune de ces cartes à la place.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si cette attaque détruit un personnage, l’ennemi attaquant effectue une attaque supplémentaire après celle-ci.</p>");
            AddHtml("Erelas-Gates-CoE", "<p class='main-text'><b>Trajet</b> : chaque joueur doit choisir un ennemi et ajouter la première carte de son deck à sa pile de butin.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : augmentez de 1 votre niveau de menace pour chaque carte dans la pile de butin de l’ennemi attaquant.</p><p class='flavor-text'>Des colonnes tordues et penchées dressaient leurs fûts ébréchés.<br/>— Les Deux Tours</p>");
            AddHtml("Crossroads-CoE", "<p class='main-text'><b>Trajet</b> : mélangez la pile de défausse de rencontre dans le deck de rencontre et défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un ennemi soit défaussé. Mettez en jeu cet ennemi, engagé au combat avec le premier joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : l’ennemi attaquant gagne +X {Attack}, où X est le nombre de sphères différentes parmi les cartes de sa pile de butin.</p>");
            AddHtml("Erelas-Stables-CoE", "<p class='main-text'><b>Trajet</b> : renvoyez dans la zone de cheminement un ennemi engagé au combat avec un joueur.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si l’ennemi attaquant est non-unique, renvoyez-le dans la zone de cheminement après la résolution de son attaque.</p>");
            AddHtml("Chaos-in-the-Hills-CoE", "<p class='main-text'><b>Une fois révélée</b> : renvoyez dans la zone de cheminement l’ennemi engagé au combat ayant le coût d’engagement au combat le plus élevé. Si aucun ennemi n’est renvoyé dans la zone de cheminement par cet effet, Chaos dans les Collines gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : après cette attaque, l’ennemi attaquant engage au combat le joueur suivant et effectue immédiatement une attaque.</p>");
            AddHtml("Looted-Weapons-CoE", "<p class='main-text'>Tant qu’elles sont attachées à un ennemi, les Armes Dérobées comptent comme un attachement <b><i><b><i>Condition</i></b></i></b> avec le texte : “L’ennemi attaché gagne +1 {Threat} et +1 {Attack} pour chaque attachement dans sa pile de butin.”</p><p class='main-text'><b>Une fois révélée</b> : attachez cette carte à l’ennemi en jeu ayant le coût d’engagement au combat le plus élevé. Ensuite, chaque joueur ajoute un attachement <b><i>Objet</i></b> qu’il contrôle à la pile de butin de cet ennemi, si possible. S’il n’y pas d’ennemi en jeu, Armes Dérobées gagne Renfort.</p>");
            AddHtml("Stockpile-Barricade-CoE", "<p class='flavor-text'>Des chariots et des carrioles renversés formaient une barricade solide en travers de la route.</p><p class='main-text'>Renfort.</p><p class='main-text'>Chaque ennemi gagne +1 {Defense} pour chaque attachement dans sa pile de butin.</p><p class='main-text'><b>Forcé </b>: après avoir résolu le mot-clé Maraude d’un ennemi, s’il n’y a pas d’attachement dans sa pile de butin, il effectue immédiatement une attaque contre le joueur engagé au combat avec lui.</p>{victory:10}");
            AddHtml("Erelas-Beacon-CoE", "<p class='main-text'><b>Forcé</b> : à la fin de la phase de combat, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas pour chaque ennemi dans la zone de cheminement.</p><p class='main-text'><b>Le Feu d’Alarme de l’Erelas a X Points de Vie, où X est égal à 2, plus 3{PerPlayer}. Si le Feu d’Alarme de l’Erelas n’a plus de Points de Vie, les joueurs ont perdu la partie.</b></p><p class='flavor-text'>Toutes les terres étaient grises et silencieuses, l’ombre s’épaississait toujours devant eux, et l’espoir s’affaiblissait dans tous les cœurs.<br/>— Le Retour du Roi</p>");
            AddHtml("Host-of-Rohan-CoE", "<p class='main-text'>Sentinelle.</p><p class='main-text'><b>Action</b> : les joueurs en tant que groupe peuvent dépenser 2 ressources pour redresser l’Ost du Rohan. (Limite : une fois par phase.)</p><p class='flavor-text'>“La guerre est ouverte, et les Rohirrim, seigneurs des chevaux, ne dorment pas.”<br/>— Gandalf, Les Deux Tours</p>");
            AddHtml("Enraged-Dunlending-CoE", "<p class='main-text'><b>Forcé</b> : quand le Dunlending Enragé vous engage au combat, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : les points de dégâts infligés au personnage défenseur par cette attaque doivent être assignés au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Bald-Hill-CoE", "<p class='main-text'>Tant que les joueurs contrôlent le feu d’alarme, la Colline Pelée gagne +3 {Threat}.</p><p class='main-text'><b>Trajet</b> : si les joueurs contrôlent le feu d’alarme, infligez 2 points de dégâts au Feu d’Alarme de l’Erelas.</p><p class='flavor-text'>Ils finirent par atteindre ainsi le sommet de la colline grise, et une brise soudaine souffla dans leurs cheveux et agita leurs capes : le vent froid de l’aube. — Les Deux Tours</p>");
            AddHtml("Wooden-Barricade-CoE", "<p class='main-text'>Tant que la Barricade en Bois est dans la zone de cheminement, elle gagne: “<b>Forcé</b> : à la fin de la phase de combat, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas et placez un marqueur de progression sur la Barricade en Bois.”</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit vous défaussez 2 attachements que vous contrôlez, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Rocky-Slope-CoE", "<p class='main-text'>Quand les effets d’une carte de rencontre sont annulés, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p><p class='main-text'><b>Trajet</b> : le premier joueur doit défausser chaque événement de sa main.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit vous défaussez chaque ressource de la réserve de chacun de vos héros, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Surrounding-Grassland-CoE", "<p class='main-text'>Archerie 1.</p><p class='main-text'><b>Forcé</b> : quand les Prairies Environnantes quittent le jeu en tant que lieu exploré, s’il n’y a pas de copie de Prairies Environnantes dans la zone de cheminement, renvoyez ce lieu dans la zone de cheminement.</p><p class='flavor-text'>Ils voyaient par-delà la rivière les prairies vertes de Rohan se perdre dans le gris lointain. — Les Deux Tours</p>");
            AddHtml("Narrow-Stair-CoE", "<p class='main-text'>Chaque joueur ne peut déclarer qu’une seule attaque et qu’un seul attaquant par phase.</p><p class='main-text'>Tant que l’Escalier Étroit est le lieu actif, chaque joueur ne peut défendre qu’une seule attaque par phase (les autres attaques sont considérées sans défense).</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit l’ennemi attaquant gagne +3 {Attack}, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("From-All-Sides-CoE", "<p class='main-text'><b>Une fois révélée</b> : chaque joueur doit choisir entre : soit infliger 1 point de dégâts à 4 personnages différents qu’il contrôle, soit infliger 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : après cette attaque, soit vous défaussez le personnage défenseur, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Another-Wave-CoE", "<p class='main-text'>Maudit 1. Renfort.</p><p class='main-text'><b>Une fois révélée</b> : si les joueurs contrôlent le feu d’alarme, choisissez entre : infliger 2 points de dégâts au Feu d’Alarme de l’Erelas ou révéler une carte du deck de rencontre.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit l’ennemi attaquant effectue une attaque supplémentaire après celle-ci, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Assault-Upon-Erelas-CoE", "<p class='main-text'><b>Une fois révélée</b> : le premier joueur choisit un ennemi engagé au combat avec un joueur et le renvoie dans la zone de cheminement. Si aucun ennemi n’est renvoyé dans la zone de cheminement par cet effet, choisissez entre : infliger 1 point de dégâts au Feu d’Alarme de l’Erelas ou Assaut sur l’Erelas gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : soit vous augmentez de 4 votre niveau de menace, soit vous infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p>");
            AddHtml("Reclaim-the-Beacon-CoE", "<p class='flavor-text'>Reprenez le feu d’alarme, avant que les Dunlendings ne l’endommagent, ou pire.</p><p class='main-text'>Les Dunlendings contrôlent le feu d’alarme. Les ennemis dans la zone de cheminement ne peuvent pas être engagés intentionnellement au combat ou subir de dégâts.</p><p class='main-text'>Il ne peut pas y avoir plus de X marqueurs de progression sur cette étape, où X est égal à 2, plus 1{PerPlayer}. Quand il y a X marqueurs de progression sur cette étape, retournez-la (conservez les marqueurs de progression).</p>");
            AddHtml("Stolen-Steeds-CoE", "<p class='main-text'>Les objectifs <b><i>Monture</i></b> ne peuvent pas être défaussés ou quitter le jeu. Si un objectif <b><i>Monture</i></b> n’est pas attaché, un joueur doit le prendre et l’attacher à un héros qu’il contrôle.</p><p class='main-text'><b>Forcé</b> : à la fin du tour, ajoutez 1 marqueur de progression sur la quête principale pour chaque objectif <b><i>Monture</i></b> que les joueurs contrôlent. Ensuite, augmentez de 1 le niveau de menace de chaque joueur pour pour chaque objectif <b><i>Monture</i></b> en jeu que les joueurs ne contrôlent pas.</p>");
            AddHtml("Flinthoof-CoE", "<p class='main-text'>Protégé (ennemi). Restreint.</p><p class='main-text'>L’ennemi protégeant Sabotdur gagne +1 {Attack}.</p><p class='main-text'>Le héros attaché gagne +1 {Attack}.</p><p class='main-text'><b>[Combat] Action</b> : inclinez Sabotdur pour infliger 1 point de dégâts à un ennemi en jeu.</p><p class='flavor-text'>Leur longue queue flottait au vent, leur crinière était nattée sur leur fière encolure. —Les Deux Tours</p>");
            AddHtml("Brightmane-CoE", "<p class='main-text'>Protégé (lieu). Restreint.</p><p class='main-text'>Le lieu ou l’ennemi protégeant Claircrin gagne +1 {Threat}.</p><p class='main-text'>Le héros attaché gagne +1 {Willpower}.</p><p class='main-text'><b>[Quête] Action</b> : inclinez Claircrin pour regarder la première carte du deck de rencontre. Si cette carte est un lieu, vous pouvez la défausser.</p>");
            AddHtml("Felarof-CoE", "<p class='main-text'>Protégé (ennemi). Restreint.</p><p class='main-text'><b>Forcé</b> : quand l’ennemi protégeant Felaróf attaque, attribuez-lui 2 cartes ombre supplémentaires.</p><p class='main-text'><b>[Combat] Action</b> : inclinez Felaróf pour défausser une carte ombre face cachée en jeu.</p><p class='flavor-text'>“Mais un autre avance devant : un très Grand Cheval. Je n’ai jamais vu son pareil.” — Legolas, Les Deux Tours</p>");
            AddHtml("Thruk-CoE", "<p class='main-text'>Immunisé aux effets de carte des joueurs. Thruk engage au combat le premier joueur.</p><p class='main-text'><b>Forcé</b> : au début de la phase de combat, si Thruk ne protège pas un objectif, il effectue immédiatement une attaque contre le joueur engagé au combat avec lui.</p>{victory:10}");
            AddHtml("Saddle-slasher-CoE", "<p class='main-text'>Archerie X. X est égal à 2, plus 1 pour chaque objectif <b><i>Monture</i></b> que les joueurs contrôlent.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : si vous contrôlez un objectif <b><i>Monture</i></b>, choisissez entre : attacher cet objectif à l’ennemi attaquant en tant qu’objectif protégé ou défausser le personnage défenseur après la résolution de cette attaque.</p>");
            AddHtml("Rein-ripper-CoE", "<p class='main-text'><b>Forcé</b> : quand le Rompeur-de-Rêne attaque, attribuez-lui 2 cartes ombre supplémentaires. Vous pouvez attacher un objectif <b><i>Monture</i></b> que vous contrôlez au Rompeur-de-Rêne en tant qu’objectif protégé pour annuler cet effet.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : l’ennemi attaquant gagne +1 {Attack} pour chaque objectif <b><i>Monture</i></b> que les joueurs contrôlent.</p>");
            AddHtml("Bridle-biter-CoE", "<p class='main-text'>Renfort.</p><p class='main-text'><b>Une fois révélée</b> : le Broyeur-de-Bride engage le joueur qui contrôle le plus d’objectifs <b><i>Monture</i></b>.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : mettez en jeu le Broyeur-de-Bride engagé au combat avec vous et attribuez-lui une carte ombre.</p>");
            AddHtml("Pommel-pouncer-CoE", "<p class='main-text'>Tant que l’Arracheur-d’Arçon est dans la zone de cheminement et ne protège pas d’attachement <b><i>Monture</i></b>, il gagne : “<b>Forcé</b> : quand un joueur devrait prendre le contrôle d’un objectif <b><i>Monture</i></b>, attachez cet objectif <b><i>Monture</i></b> à l’Arracheur-d’Arçon en tant qu’objectif protégé à la place.”</p>");
            AddHtml("Spoiled-Pasture-CoE", "<p class='main-text'>X est égal à 2, plus 2 pour chaque objectif <b><i>Monture</i></b> que les joueurs contrôlent.</p><p class='main-text'><b>Forcé</b> : quand un joueur perd le contrôle d’un objectif <b><i>Monture</i></b>, augmentez de 1 son niveau de menace.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : augmentez de 1 votre niveau de menace pour chaque objectif <b><i>Monture</i></b> que vous contrôlez.</p>");
            AddHtml("Horse-Thieves'-Hovel-CoE", "<p class='main-text'>Quand les joueurs ont la possibilité de voyager, ils doivent voyager vers un lieu non-vaste.</p><p class='main-text'><b>Forcé</b> : quand la Masure des Voleurs de Chevaux quitte le jeu en tant que lieu exploré, s’il y a moins de 1{PerPlayer} ennemi en jeu, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un ennemi soit défaussé et placez-le dans la zone de cheminement.</p>{victory:2}");
            AddHtml("Horse-Lord's-Lodge-CoE", "<p class='main-text'>Quand les joueurs ont la possibilité de voyager, ils doivent voyager vers un lieu non-vaste.</p><p class='main-text'><b>Forcé</b> : quand le Logis des Seigneurs des Chevaux quitte le jeu en tant que lieu exploré, s’il y a moins de 1{PerPlayer} lieu en jeu, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un lieu soit défaussé. Placez ce lieu dans la zone de cheminement.</p>{victory:2}");
            AddHtml("Thirst-for-Horse-Blood-CoE", "<p class='main-text'><b>Une fois révélée</b> : chaque joueur qui contrôle un objectif <b><i>Monture</i></b> doit choisir entre : soit révéler une carte de rencontre, soit attacher à l’ennemi sans attachement ayant le coût d’engagement au combat le plus élevé un objectif <b><i>Monture</i></b> qu’il contrôle en tant qu’objectif protégé. Si aucun joueur ne contrôle d’objectif <b><i>Monture</i></b>, Soif de Sang Équin gagne Renfort.</p><p class='flavor-text'>“Nous festoierons encore de chair de cheval ou de quelque chose de mieux.” — Uglúk, Les Deux Tours</p>");
            AddHtml("Overburdened-CoE", "<p class='main-text'><b>Une fois révélée</b> : chaque joueur qui contrôle plus de 2 attachements doit défausser 1 attachement qu’il contrôle, si possible (à la place, si un joueur contrôle plus de 5 attachements, il doit en défausser 2, si possible). Si aucun attachement n’est défaussé par cette effet, Surchargé gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre</b> : défaussez 1 carte prise au hasard dans votre main.</p>");
            AddHtml("The-Last-Alliance-CoE", "<p class='main-text'>Choisissez deux traits, <b><i>A</i></b> et <b><i>B</i></b>. Chacun de vos héros de départ et chaque allié de votre deck doit avoir le trait imprimé <b><i>A</i></b> ou le trait imprimé <b><i>B</i></b>, mais ne peut pas avoir les deux traits. Vous devez avoir au moins 1 héros de départ et 10 alliés avec le trait <b><i>A</i></b> dans votre deck. De même pour le trait <b><i>B</i></b>.</p><p class='main-text'><b>Mise en place:</b> retournez cette carte.</p><p class='flavor-text'>“La force des Elfes pour lui résister était plus grande, il y a longtemps ; et tous les Hommes ne leur étaient pas aliénés.” — Gandalf, La Communauté de l’Anneau</p>");
            AddHtml2("The-Last-Alliance-CoE", "<p class='main-text'>Tant que vous contrôlez plus de personnages <b><i>A</i></b> que de personnages <b><i>B</i></b>, réduisez de 1 le coût du premier allié <b><i>B</i></b> que vous jouez à chaque tour, et vice versa.</p><p class='main-text'><b>Action</b> : inclinez La Dernière Alliance pour choisir une carte de votre main ou en jeu sous votre contrôle. Remplacez chaque instance de “<b><i>A</i></b>” ou “<b><i>B</i></b>” sur la capacité de cette carte par “<b><i>A</i></b> ou <b><i>B</i></b>” jusqu’à la fin du tour.</p>");
            AddHtml("Drive-them-Away-CoE", "<p class='flavor-text'>Le long de la Grande Route de l’Ouest, vous arrivez près d’un camp de Rohirrim dans l’ombre de la colline nue du feu d’alarme de l’Erelas. Mais le calme de votre voyage est interrompu par une attaque soudaine ! Le choc de l’acier et les cris des hommes atteignent bientôt vos oreilles. Vous devez les chasser et protéger le camp de nouvelles destructions !</p><p class='main-text'><b></b> <b>Mise en place</b> : mettez de côté le Meneur Brigand, hors jeu. Placez les Biens Pillés dans la zone de cheminement. Chaque joueur cherche un ennemi différent dans le deck de rencontre et le place dans la zone de cheminement. Mélangez le deck de rencontre.</p>");
            AddHtml2("Drive-them-Away-CoE", "<p class='main-text'></b> <b>Forcé</b> : quand un ennemi est détruit, placez 1 marqueur de ressource sur cette carte.</p><p class='main-text'><b>[Rencontre] Action</b> : retirez 5 marqueurs de progression de cette étape pour choisir une carte dans une pile de butin et la défausser. Limite : une fois par tour et par joueur.</p><p class='main-text'><b>S’il y a au moins X marqueurs de ressource sur Repoussez-les, passez à l’étape suivante. X est égal à 1, plus 2{PerPlayer} (2 par joueur).</b></p>");
            AddHtml("Ambush-CoE", "<p class='flavor-text'>Vous vous êtes battu au cœur du campement, mais les brigands se rassemblent autour de leur chef et lancent une violente attaque.</p><p class='main-text'><b></b> <b>Une fois révélée</b> : mettez fin à la phase en cours. Placez le Meneur Brigand dans la zone de cheminement. Chaque joueur qui n’est pas engagé au combat avec un ennemi cherche dans le deck de rencontre ou dans la pile de défausse de rencontre un ennemi et le met en jeu, engagé au combat avec lui. Mélangez le deck de rencontre.</p>");
            AddHtml2("Ambush-CoE", "<p class='main-text'></b> <b>Forcé</b> : quand un ennemi entre en jeu, chaque joueur fait un test d’engagement au combat contre lui.</p><p class='main-text'><b>[Organisation] Action</b>: retirez 5 marqueurs de progression de cette étape pour choisir une carte dans une pile de butin. Le propriétaire de cette carte peut la défausser ou la jouer gratuitement. Limite : quatre fois par tour pour le groupe.</p><p class='main-text'><b>Quand le Meneur Brigand est éliminé, les joueurs ont gagné la partie.</b></p>");
            AddHtml("Battle-for-the-Hill-CoE", "<p class='flavor-text'>Des Dunlendings et des Rohirrim renégats se sont emparés du feu d’alarme de l’Erelas. Reprenez la colline à tout prix !</p><p class='main-text'><b></b> <b>Mise en place</b> : mettez de côté l’Ost du Rohan, hors jeu. Placez le Feu d’Alarme de l’Erelas et 1{PerPlayer} Dunlending Enragé dans la zone de cheminement. Placez la quête annexe double-face dans la zone de cheminement, du côté Reprendre le Feu d’Alarme. Cherchez un exemplaire de Prairies Environnantes dans le deck de rencontre et faites-en le lieu actif. Mélangez le deck de rencontre.</p>");
            AddHtml2("Battle-for-the-Hill-CoE", "<p class='main-text'></b> <b>Forcé</b> : après avoir placé n’importe quel nombre de marqueurs de progression sur cette étape, chaque joueur doit choisir entre : soit incliner un personnage qu’il contrôle, soit infliger 1 point de dégâts au Feu d’Alarme de l’Erelas.</p><p class='main-text'><b>Cette étape ne peut être passée tant que les Dunlendings contrôlent le feu d’alarme.</b></p>");
            AddHtml("Hold-the-Hilltop-CoE", "<p class='flavor-text'>Alors que vos ennemis se rassemblent pour un nouvel assaut sur le feu d’alarme, vous pouvez apercevoir les torches des troupes de Gálmód se massant en contrebas.</p><p class='main-text'><b></b> <b>Une fois révélée</b> : placez des marqueurs de progression sur Défendre le Feu d’Alarme (en ignorant tout lieu actif) jusqu’à ce qu’il y ait X marqueurs de progression dessus, où X est égal à 2, plus 1{PerPlayer}. Mélangez la pile de défausse de rencontre dans le deck de rencontre. Chaque joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi et le place dans la zone de cheminement.</p>");
            AddHtml2("Hold-the-Hilltop-CoE", "<p class='main-text'></b> Temps 3.</p><p class='main-text'><b>Forcé</b> : à la fin du tour, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas (2 points de dégâts s’il y a au moins 3 joueurs dans la partie). Ensuite, s’il n’y a plus de compteur de temps sur cette étape, passez immédiatement à l’étape 3.</p><p class='main-text'><b>Forcé</b> : quand Défendre le Feu d’Alarme devient la quête en cours, révélez une carte de rencontre.</p><p class='main-text'><b>Si les Dunlendings contrôlent le feu d’alarme, les joueurs ont perdu la partie.</b></p>");
            AddHtml("The-Last-Push-CoE", "<p class='flavor-text'>Alors que les forces de Gálmód chevauchent pour encercler l’ennemi, vous devez vous armer pour une ultime offensive.</p><p class='main-text'><b></b> <b>Une fois révélée</b> : retirez tous les marqueurs de progression sur Défendre le Feu d’Alarme et retournez-la. Mettez l’Ost du Rohan en jeu sous le contrôle du premier joueur. Mélangez la pile de défausse de rencontre dans le deck de rencontre. Chaque joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi et le place dans la zone de cheminement.</p>");
            AddHtml2("The-Last-Push-CoE", "<p class='main-text'></b> Ajoutez 2 au total de {Threat} dans la zone de cheminement pour chaque dégât sur le Feu d’Alarme de l’Erelas.</p><p class='main-text'><b>Forcé</b> : au début de la phase de combat, chaque ennemi engagé au combat effectue immédiatement une attaque.</p><p class='main-text'><b>Forcé</b> : quand un personnage quitte le jeu, infligez 1 point de dégâts au Feu d’Alarme de l’Erelas.</p><p class='main-text'><b>À la fin du tour, si les Dunlendings contrôlent le feu d’alarme, les joueurs ont perdu la partie, et si les joueurs contrôlent le feu d’alarme, ils ont gagné la partie.</b></p>");
            AddHtml("Thieves-and-Coursers-CoE", "<p class='flavor-text'>Side A: Des orques ont envahi l’Estfolde, ravageant le pays et capturant les chevaux de guerre préférés du roi Thengel. Side B: Si vous récupérez Sabotdur et Claircrin, vous pourrez peut-être arrêter l’ost des orques avant qu’il n’atteigne Aldburg.</p><p class='main-text'><b></b> <b>Mise en place</b> : placez Coursiers Volés dans la zone de cheminement. Mettez Thruk, les objectifs <b><i>Monture</i></b>, et les 8 ennemis du set de rencontre Ost des Orques de côté, hors jeu. Mélangez le deck de rencontre. Le premier joueur révèle Sabotdur et Claircrin et les place dans la zone de cheminement. Chaque autre joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi ou un lieu et le place dans la zone de cheminement.</p>");
            AddHtml2("Thieves-and-Coursers-CoE", "<p class='main-text'></b> <b>Cette étape ne peut être passée tant que les joueurs ne contrôlent pas au moins 2 objectifs <b><i>Monture</i></b>.</b></p>");
            AddHtml("The-King's-Stallion-CoE", "<p class='flavor-text'>Le chef de guerre Thruk est arrivé dans la bataille, chevauchant le puissant Felaróf et hurlant des ordres à sa troupe. “Rassemblement ! Ce soir, nous festoierons de chair de cheval !”</p><p class='main-text'><b></b> <b>Une fois révélée</b> : s’il s’agit de la phase de combat, mettez fin à la phase. Mélangez la pile de défausse de rencontre dans le deck de rencontre. Le premier joueur place Thruk dans la zone de cheminement et lui attache Felaróf en tant qu’objectif protégé. Chaque autre joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi et le met en jeu, engagé au combat avec lui.</p>");
            AddHtml2("The-King's-Stallion-CoE", "<p class='main-text'></b> Thruk ne peut pas subir de dégâts, sauf s’il y a au moins 4 marqueurs de progression sur cette étape.</p><p class='main-text'><b>Cette étape ne peut être passée tant que les joueurs ne contrôlent pas 3 objectifs <b><i>Monture</i></b>.</b></p>");
            AddHtml("The-Sweeping-Tide-CoE", "<p class='flavor-text'>L’ost des orques tout entier a répondu au cri de ralliement de Thruk. Vous devez vous unir pour une charge finale afin de les disperser dans les collines.</p><p class='main-text'><b></b> <b>Une fois révélée</b> : s’il s’agit de la phase de combat, mettez fin à la phase. Mélangez la pile de défausse de rencontre dans le deck de rencontre. Cherchez Thruk dans la pile de victoire et placez le dans la zone de cheminement. Chaque joueur choisit 2 ennemis du set de rencontre mis de côté Ost des Orques et les met en jeu, engagés au combat avec lui. Un des ennemis mis en jeu de cette façon doit être le Bataillon Orque.</p>");
            AddHtml2("The-Sweeping-Tide-CoE", "<p class='main-text'></b> Sautez l’étape de renforcement de la phase de Quête. À tout moment, si le deck de rencontre est vide, mélangez la pile de défausse dans le deck de rencontre.</p><p class='main-text'><b>Forcé</b> : quand un ennemi effectue une attaque, attribuez-lui 1 carte ombre supplémentaire.</p><p class='main-text'><b>Si un objectif <b><i>Monture</i></b> est attaché à un ennemi, les joueurs ont perdu la partie. S’il n’y a plus d’ennemis en jeu, les joueurs ont gagné la partie.</b></p>");
            //AddHtml("Reclaim-the-Beacon-CoE", "<p class='main-text'>Les joueurs contrôlent le feu d’alarme. Les cartes ombre sont immunisées aux effets de carte des joueurs.</p><p class='main-text'>Il ne peut pas y avoir plus de X marqueurs de progression sur cette étape, où X est égal à 2, plus 1{PerPlayer}.</p><p class='main-text'><b>Réponse</b> : retirez n’importe quel nombre de marqueurs de progression sur Défendre le Feu d’Alarme pour annuler autant de dégâts tout juste infligés au Feu d’Alarme de l’Erelas. Ensuite, si cette étape a 0 marqueur de progression, retournez-la.</p>");

        }

        private void TheAldburgPlot()
        {
            AddHtml("Dunlending-Agents-TAP", "<p class='main-text'>Si les joueurs contrôlent au moins 2 objectifs <b><i>Indice</i></b>, les Agents Dunlending gagnent +2 {Attack}.</p><p class='main-text'><b>Forcé:</b> quand les Agents Dunlending attaquent et détruisent un personnage que vous contrôlez, infligez 1 point de dégâts à chaque héros que vous contrôlez ayant un objectif <b><i>Indice</i></b> attaché.</p><p class='flavor-text'>Ceux du Pays de Dun et de nombreux hommes de la garnison du Fort étaient au travail. — Le Retour du Roi</p>");
            AddHtml("Aldburg-Malcontent-TAP", "<p class='main-text'><b>Une fois révélée:</b> si les joueurs contrôlent au moins 3 objectifs <b><i>Indice</i></b>, l’Aldburgeois Mécontent gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre:</b> si les joueurs contrôlent au moins 2 objectifs <b><i>Indice</i></b>, renvoyez l’ennemi attaquant dans la zone de cheminement après la résolution de son attaque.</p>");
            AddHtml("Spreading-Inferno-TAP", "<p class='main-text'>Protégé (lieu).</p><p class='main-text'><b>Forcé:</b> au début de la phase de voyage, défaussez le lieu attaché, augmentez de 1 le niveau de menace de chaque joueur, et chaque joueur défausse l’allié qu’il contrôle ayant le coût imprimé le plus faible. Ensuite, révélez le Brasier Dévorant.</p><p class='main-text'><b>Forcé:</b> quand le lieu attaché est exploré, retournez cette carte et révélez-la.</p>");
            AddHtml("Ruby-Cloak-pin-TAP", "<p class='main-text'>Si cette carte n’est pas attachée, attachez-la au héros ayant le moins d’objectifs <b><i>Indice</i></b> attachés.</p><p class='main-text'><b>Forcé:</b> quand le héros attaché se redresse, défaussez les 4 premières cartes du dessus de votre deck.</p><p class='flavor-text'>Parmi les cendres, vous trouvez une broche que vous reconnaissez immédiatement. Elle appartient au roquet Gálmód, le conseiller de confiance de la reine Morwen.</p>");
            AddHtml("Garrison-Barracks-TAP", "<p class='main-text'>Immunisé aux effets de cartes des joueurs. X est le double du nombre d’objectifs <b><i>Indice</i></b> que les joueurs contrôlent.</p><p class='main-text'>Trajet : mélangez dans le deck de rencontre tous les ennemis <b><i>Pays de Dun</i></b> mis de côté.</p><p class='main-text'><b>Forcé:</b> quand la Caserne est explorée, retournez cette carte et révélez-la.</p><p class='flavor-text'>La garde de la ville a des yeux et des oreilles sur tout à Aldburg. Mais qui les surveille ?</p>");
            AddHtml("Raven-Signet-Ring-TAP", "<p class='main-text'><b>Une fois révélée:</b> placez L’Homme à la Lèvre Tordue dans la zone de cheminement.</p><p class='main-text'>Si cette carte n’est pas attachée, attachez-la au héros ayant le moins d’objectifs <b><i>Indice</i></b> attachés.</p><p class='main-text'><b>Forcé:</b> quand le héros attaché se redresse, défaussez toutes les ressources de sa réserve.</p><p class='flavor-text'>Le prisonnier a parlé aux gardiens d’un agent appelé le Maître-Espion. La seule piste actuellement est cette bague, censée lui appartenir.</p>");
            AddHtml("Whisperer-in-the-Darkness-TAP", "<p class='flavor-text'>La taverne était en proie à des rumeurs au sujet d’un assassin appelé “La Chuchoteuse”. Si vous voulez percer ce mystère, vous devrez la trouver et l’arrêter avant qu’elle ne frappe.</p><p class='main-text'><b>Forcé:</b> quand un lieu est exploré, chaque joueur augmente de 1 son niveau de menace.</p><p class='main-text'><b>Forcé:</b> quand cette étape est passée, placez la Chuchoteuse dans la zone de cheminement.</p>{victory:10}");
            AddHtml("Prison-Key-TAP", "<p class='main-text'><b>Une fois révélée:</b> placez Un Début d’Incendie et Le Prisonnier en Blanc dans la zone de cheminement.</p><p class='main-text'>Si cette carte n’est pas attachée, attachez-la au héros ayant le moins d’objectifs <b><i>Indice</i></b> attachés.</p><p class='main-text'><b>Forcé:</b> quand le héros attaché se redresse, défaussez un attachement non-<b><i>Indice</i></b> qu’il possède.</p><p class='flavor-text'>Blessé et cherchant à fuir, le Maître-Espion laisse échapper un détail clé : un de ses agents est déjà en mouvement et se dirige vers la prison de la ville.</p>");
            AddHtml("Traitor's-Confession-TAP", "<p class='main-text'>Si cette carte n’est pas attachée, attachez-la au héros ayant le moins d’objectifs <b><i>Indice</i></b> attachés.</p><p class='main-text'><b>Forcé:</b> quand le héros attaché se redresse, défaussez une carte au hasard de votre main.</p><p class='flavor-text'>Dans son dernier souffle, le traître Ossian révèle que Gálmód lui a ordonné de tuer l’un des membres de sa propre éored : un témoin d’une terrible trahison.</p>");
            AddHtml("Silver-Dagger-TAP", "<p class='main-text'><b>Une fois révélée:</b> placez Une Affaire d’Identité et Moisson Rouge dans la zone de cheminement.</p><p class='main-text'>Si cette carte n’est pas attachée, attachez-la au héros ayant le moins d’objectifs <b><i>Indice</i></b> attachés.</p><p class='main-text'><b>Forcé:</b> quand le héros attaché se redresse, infligez-lui 1 point de dégâts.</p><p class='flavor-text'>La Chuchoteuse s’est échappée dans les rues d’Aldburg, mais elle a laissé derrière elle une arme distinctive et coûteuse.</p>");
            AddHtml("Fear-Fire-Foes-TAP", "<p class='main-text'>Secret 1. Vous ne pouvez pas jouer cette carte si vous contrôlez un héros <b><i>Guerrier</i></b>.</p><p class='main-text'><b>Action:</b> choisissez un ennemi non-unique et un attribut ({Threat}, {Attack}, ou {Defense}). Jusqu’à la fin de la phase, réduisez l’attribut choisi de cet ennemi à 0.</p><p class='flavor-text'>Au loin, on entendit répondre d’autres cors. L’alerte se répandait. — La Communauté de l’Anneau</p>");
            AddHtml("Sudden-Ambush-TAP", "<p class='main-text'><b>Une fois révélée:</b> le premier joueur doit choisir entre : augmenter de 4 son niveau de menace, ou mettre en jeu, engagé au combat avec lui, l’ennemi le plus proche du sommet de la pile de défausse de rencontre. Cet ennemi effectue immédiatement une attaque. Le premier joueur doit déclarer comme défenseur le personnage redressé qu’il contrôle ayant la {Willpower} la plus élevée, si possible.</p>{shadow}<p class='shadow-text'><b>Ombre:</b> résolvez l’effet “Une fois révélée” de cette carte.</p>");
            AddHtml("Taken-by-the-Night-TAP", "<p class='main-text'><b>Une fois révélée:</b> chaque joueur doit défausser l’allié qu’il contrôle ayant le coût imprimé le plus faible. Si aucun allié ayant un coût imprimé de 2 ou plus n’est défaussé par cet effet, Emporté dans la Nuit gagne Renfort.</p>{shadow}<p class='shadow-text'><b>Ombre:</b> l’ennemi attaquant gagne +1 {Attack} (+2 {Attack} s’il attaque depuis la zone de cheminement).</p>");
            AddHtml("False-Lead-TAP", "<p class='main-text'>Maudit 1.</p><p class='main-text'><b>Une fois révélée:</b> chaque joueur retire de la quête un héros qu’il contrôle ayant un objectif <b><i>Indice</i></b> attaché, si possible. Ensuite, chaque joueur choisit un héros qu’il contrôle qui n’est pas engagé dans la quête et l’incline.</p><p class='flavor-text'>“…essayez-vous maintenant de m’attraper grâce à un mensonge ?” — Frodon Sacquet, Les Deux Tours</p>");
            AddHtml("Red-Fletched-Arrow-TAP", "<p class='main-text'>Si cette carte n’est pas attachée, attachez-la au héros ayant le moins d’objectifs <b><i>Indice</i></b> attachés.</p><p class='main-text'><b>Forcé:</b> quand le héros attaché se redresse, augmentez de 1 votre niveau de menace.</p><p class='flavor-text'>Le quartier-maître de l’armurerie vous informe qu’il a personnellement forgé la dague, ainsi que cette flèche inhabituelle, pour Lord Gálmód.</p>");
            AddHtml("Town-Guard-TAP", "<p class='main-text'>Si les joueurs contrôlent au moins 2 objectifs <b><i>Indice</i></b>, la Garde de la Ville gagne +2 {Threat}.</p><p class='main-text'><b>Forcé:</b> quand la Garde de la Ville attaque et détruit un personnage que vous contrôlez, défaussez 1 ressource de la réserve de chaque héros que vous contrôlez ayant un objectif <b><i>Indice</i></b> attaché.</p><p class='flavor-text'>“Espéré-je en vain que vous m’avez été envoyé en aide dans le doute et le besoin ?” — Éomer, Les Deux Tours</p>");
            AddHtml("Gavin-TAP", "<p class='main-text'>Ne peut pas avoir d’attachements.</p><p class='main-text'><b>Réponse:</b> quand une carte de rencontre n’ayant pas le mot-clé Renfort est révélée, inclinez Gavin pour donner à cette carte le mot-clé Renfort et ajouter 1 ressource à la réserve d’un héros <b><i>Éclaireur</i></b> que vous contrôlez. Si la prochaine carte de rencontre révélée n’est pas un lieu, défaussez-la sans résoudre ses effets.</p>");
            AddHtml("Great-Mead-Hall-TAP", "<p class='main-text'>Immunisé aux effets de cartes des joueurs.</p><p class='main-text'>Trajet : chaque joueur doit augmenter de X son niveau de menace, X étant le nombre d’ennemis dans la zone de cheminement.</p><p class='main-text'><b>Forcé:</b> quand le Grand Hall à Hydromel est exploré, retournez cette carte et révélez-la.</p><p class='flavor-text'>Vous avez traqué les agents de la Chuchoteuse jusque dans les couloirs mêmes du Maréchal Eomund. Quelles peuvent être les limites de ce complot ?</p>");
            AddHtml("Fatty-Bolger-TAP", "<p class='main-text'><b>Mise en place:</b> diminuez de 2 votre niveau de menace.</p><p class='main-text'><b>Réponse:</b> augmentez de 4 votre niveau de menace et inclinez Gros Bolger pour annuler une carte Ennemi non-unique tout juste révélée du deck de rencontre et l’ajouter à la pile de victoire. (Limite : une fois par partie pour le groupe.)</p><p class='flavor-text'>Gros Bolger n’était pas resté inactif. Dès qu’il eut vu les formes noires ramper du jardin, il avait su qu’il devait se sauver au plus vite ou mourir. — La Communauté de l’Anneau</p>");
            AddHtml("Well-lit-Hall-TAP", "<p class='main-text'>Tant que le Hall Lumineux est dans la zone de cheminement, pas plus de 3 marqueurs de progression ne peuvent être placés sur une carte quête suite à un succès de quête.</p>{shadow}<p class='shadow-text'><b>Ombre:</b> l’ennemi attaquant gagne +1 {Attack} (+2 {Attack} si le personnage défenseur a un attachement <b><i>Indice</i></b>).</p>");
            AddHtml("The-Armoury-TAP", "<p class='main-text'>Immunisé aux effets de cartes des joueurs.</p><p class='main-text'>Trajet : chaque joueur doit incliner le personnage redressé qu’il contrôle ayant la {Defense} la plus élevée.</p><p class='main-text'><b>Forcé:</b> quand l’Armurerie est explorée, retournez cette carte et révélez-la.</p><p class='flavor-text'>La Chuchoteuse brandissait un poignard d’apparence familière. Peut-être que le quartier-maître de l’armurerie pourra vous en dire plus.</p>");
            AddHtml("The-Man-with-the-Twisted-Lip-TAP", "<p class='flavor-text'>Vous avez commencé à traquer le Maître-Espion d’Aldburg, bien qu’il soit difficile de dire lequel de vous est le chat et lequel est la souris.</p><p class='main-text'><b>Forcé:</b> à la fin du tour, chaque joueur augmente de 1 son niveau de menace.</p><p class='main-text'><b>Forcé:</b> quand cette étape est passée, placez le Maître-Espion dans la zone de cheminement.</p>{victory:10}");
            AddHtml("The-Whisperer-TAP", "<p class='main-text'><b>Forcé:</b> à la fin du tour, renvoyez la Chuchoteuse dans la zone de cheminement, si possible. Elle effectue immédiatement une attaque contre le premier joueur. Les dégâts infligés par cette attaque sont annulés ; à la place, le joueur en défense augmente d’autant son niveau de menace.</p><p class='main-text'><b>Forcé:</b> quand la Chuchoteuse est éliminée, retournez cette carte et révélez-la.</p>");
            AddHtml("The-Horse's-Tail-TAP", "<p class='main-text'>Immunisé aux effets de cartes des joueurs. X est le double du nombre d’objectifs <b><i>Indice</i></b> que les joueurs contrôlent.</p><p class='main-text'>Trajet : mélangez dans le deck de rencontre tous les ennemis <b><i>Garnison</i></b> mis de côté.</p><p class='main-text'><b>Forcé:</b> quand Le Crin de Cheval est exploré, retournez cette carte et révélez-la.</p><p class='flavor-text'>Cela attirera peut-être les soupçons de la garde de la ville, mais ce mystère ne pourra pas être résolu par les moyens habituels.</p>");
            AddHtml("The-Spy-Master-TAP", "<p class='main-text'><b>Forcé:</b> si la carte ombre attribuée au Maître-Espion n’a aucun effet ombre, infligez 1 point de dégâts au personnage défenseur et attribuez une nouvelle carte ombre au Maître-Espion (Limite 2 fois par attaque).</p><p class='main-text'><b>Forcé:</b> quand le Maître-Espion est éliminé, retournez cette carte et révélez-la.</p>");
            AddHtml("Evil-Under-the-Moon-TAP", "<p class='flavor-text'>Sachant qu’une faction de rebelles a élu domicile à Aldburg, Ealdwulf vous supplie de les dénicher. </p><p class='main-text'> <b>Mise en place:</b> mettez de côté chaque quête annexe de rencontre, chaque exemplaire de Garde de la Ville, et chaque exemplaire de Agents Dunlending, hors jeu. Mettez de côté chaque quête annexe de rencontre double-face, hors jeu, côté <b><i>Indice</i></b> face cachée. Placez la Caserne et Le Crin de Cheval dans la zone de cheminement. Cherchez un ennemi dans le deck de rencontre et placez-le dans la zone de cheminement (2 ennemis différents s’il y a 3 joueurs ou plus dans la partie). Mélangez le deck de rencontre.</p>");
            AddHtml2("Evil-Under-the-Moon-TAP", "<p class='flavor-text'>Où commencer la chasse ? Allez-vous chercher de l’aide auprès des gardes de la ville ou enquêter sur les criminels des bas-fonds dans une taverne sordide ?</p><p class='main-text'> Les ennemis ne peuvent pas être intentionnellement engagés au combat.</p><p class='main-text'><b>Forcé:</b> à la fin du tour, augmentez de 1 le niveau de menace de chaque joueur.</p><p class='main-text'>Cette étape ne peut pas être passée tant que les joueurs ne contrôlent pas au moins un objectif <b><i>Indice</i></b>.</p>");
            AddHtml("The-Prisoner-in-White-TAP", "<p class='flavor-text'>Afin de tenter de dissimuler ses traces, l’agent du Maître-Espion s’est infiltré dans la prison.</p><p class='main-text'>Les joueurs ne peuvent pas voyager ou rendre un lieu actif par un effet de carte de joueur.</p><p class='main-text'><b>Forcé:</b> quand cette étape est passée, placez Ossian dans la zone de cheminement.</p>{victory:10}");
            AddHtml("Letter-from-Dunland-TAP", "<p class='main-text'>Si cette carte n’est pas attachée, attachez-la au héros ayant le moins d’objectifs <b><i>Indice</i></b> attachés.</p><p class='main-text'><b>Forcé:</b> quand le héros attaché se redresse, retirez 2 marqueurs de progression de chaque carte lieu et quête en jeu.</p><p class='flavor-text'>Dans une cachette, vous trouvez une lettre scellée écrite dans un rohirrique douteux, signée “Grimrede”. Elle est adressée à un homme que vous pensiez être votre ami – Gálmód.</p>");
            AddHtml("Lily-Cotton-TAP", "<p class='main-text'><b>Action:</b> inclinez Lily Chaumine pour redresser un autre allié <b><i>Hobbit</i></b> et ajouter respectivement le total de {Willpower}, d’{Attack} et de {Defense} de Lily Chaumine à la {Willpower}, l’{Attack} et la {Defense} de ce personnage jusqu’à la fin de la phase. À la fin de la phase, si cet allié est toujours en jeu, ramenez-le dans la main de son propriétaire. (Limite une fois par phase.)</p><p class='flavor-text'>“Il n’y a guère de magie chez eux que celle, toute ordinaire et courante, qui leur permet de disparaître sans bruit et rapidement…” — Le Hobbit</p>");
            AddHtml("Red-Harvest-TAP", "<p class='flavor-text'>Brusquement, les hommes de la Chuchoteuse vous tombent dessus. Vous devrez vous battre bec et ongles pour vous rendre à l’armurerie.</p><p class='main-text'><b>Forcé:</b> quand un ennemi engage au combat un joueur, ce joueur doit infliger 2 points de dégâts à un personnage qu’il contrôle.</p><p class='main-text'><b>Forcé:</b> quand cette étape est passée, mélangez la pile de défausse de rencontre dans le deck de rencontre. Chaque joueur défausse des cartes du sommet du deck de rencontre jusqu’à ce qu’il défausse un ennemi et le place dans la zone de cheminement. Placez l’Armurerie dans la zone de cheminement.</p>{victory:10}");
            AddHtml("Ossian-TAP", "<p class='main-text'>Immunisé aux effets de cartes des joueurs. Ossian ne peut pas subir plus de X points de dégât par tour, X étant le nombre d’objectifs <b><i>Indice</i></b> que les joueurs contrôlent.</p><p class='main-text'><b>Forcé:</b> quand Ossian est éliminé, retournez cette carte et révélez-la.</p><p class='flavor-text'>Vous trouvez Ossian penché sur un cadavre vêtu de blanc. Entendant votre approche, il se retourne.</p>");
            AddHtml("Rohirric-Coins-TAP", "<p class='main-text'><b>Une fois révélée:</b> placez Chuchotement dans les Ténèbres dans la zone de cheminement.</p><p class='main-text'>Si cette carte n’est pas attachée, attachez-la au héros ayant le moins d’objectifs <b><i>Indice</i></b> attachés.</p><p class='main-text'><b>Forcé:</b> quand le héros attaché se redresse, inclinez un autre personnage que vous contrôlez.</p><p class='flavor-text'>Un inconnu heurte votre table. Il s’excuse abondamment puis s’évanouit dans la nuit. Au moment où vous remarquez la bourse remplies de pièces qu’il a laissé, il est déjà loin.</p>");
            AddHtml("Gathering-Clues-TAP", "<p class='flavor-text'>Il semble que la ville d’Aldburg regorge de mystères. À chaque coin de rue se cache une nouvelle énigme, et derrière chaque énigme se trouve une lame aiguisée et désespérée. Avant que le soleil ne se lève, vous devrez aller plus loin pour découvrir la vérité. </p>");
            AddHtml2("Gathering-Clues-TAP", "<p class='flavor-text'>Il semblerait qu’Aldburg soit l’hôte d’un mystère à deux têtes. Si seulement vous pouvez en saisir un fil, peut-être pourrez-vous démêler cette toile corrompue et amère. Il est minuit passé. Le temps presse.</p><p class='main-text'> <b>Réponse:</b> à la fin du tour, si les joueurs contrôlent au moins 4 objectifs <b><i>Indice</i></b>, ils peuvent passer à l’étape 3A.</p>");
            AddHtml("Weep-No-More-TAP", "<p class='main-text'>Limite : 3 exemplaires de Renonçons aux Larmes ! dans la pile de victoire.</p><p class='main-text'><b>Réponse:</b> après avoir résolu l’effet “une fois révélée” ou l’effet ombre d’une carte Traîtrise, ajoutez Renonçons aux Larmes ! à la pile de victoire pour ajouter cette carte Traîtrise à la pile de victoire.</p><p class='flavor-text'>“Au moins pourrons-nous encore être vengés. Ceignons nos reins et renonçons aux larmes !”<br/>— Aragorn, La Communauté de l’Anneau</p>");
            AddHtml("Misty-Street-TAP", "<p class='main-text'><b>Une fois révélée:</b> défaussez tous les attachements et marqueurs de l’allié contrôlé par le premier joueur ayant le coût le plus élevé. Retournez-le et attachez-le face cachée sous la Ruelle Embrumée.</p><p class='main-text'><b>Forcé:</b> quand la Ruelle Embrumée quitte le jeu, retournez l’allié attaché et renvoyez-le sous le contrôle de son propriétaire, redressé.</p>{shadow}<p class='shadow-text'><b>Ombre:</b> défaussez un attachement non-<b><i>Indice</i></b> que vous contrôlez.</p>");
            AddHtml("Buckland-Shirriff-TAP", "<p class='main-text'>Dévoué. À distance.</p><p class='main-text'><b>Réponse:</b> quand un ennemi qui partage un <b><i>Trait</i></b> avec un ennemi dans la pile de victoire est placé dans la zone de cheminement, dépensez 1 ressource {sphere:Lore} pour mettre le Shirriff du Pays de Bouc en jeu depuis votre main, sous votre contrôle.</p>");
            AddHtml("Horn-call-of-Buckland-TAP", "<p class='main-text'>Attachez cette carte à un héros {sphere:Lore} ou <b><i>Hobbit</i></b>.</p><p class='main-text'><b>Réponse:</b> quand vous engagez au combat un ennemi qui partage un <b><i>Trait</i></b> avec un ennemi dans la pile de victoire, inclinez la Sonnerie de Cor du Pays de Bouc pour redresser le héros attaché. Ensuite, cet ennemi gagne –1 {Attack} et –1 {Defense} jusqu’à la fin du tour.</p><p class='flavor-text'>À ce moment, parmi les arbres proches, un cor sonna. Il déchira la nuit comme un feu au sommet d’une colline.<br/>— La Communauté de l’Anneau</p>");
            AddHtml("Decrepit-Hovel-TAP", "<p class='main-text'>Le coût en ressources des alliés doit être payé avec la réserve d’un seul héros.</p>{shadow}<p class='shadow-text'><b>Ombre:</b> défaussez 1 ressource de la réserve d’un héros que vous contrôlez.</p><p class='flavor-text'>“ Ils en partent pour vagabonder alentour, à voler ou à “ ramasser ” comme ils appellent ça. ”<br/>— Tom Chaumine, Le Retour du Roi</p>");
            AddHtml("Young-Tom-TAP", "<p class='main-text'>Durant le tour où Tom le Jeune entre en jeu, le coût d’engagement au combat de chaque ennemi est augmenté de 5.</p><p class='flavor-text'>“Tout n’y est pas parfait, dit Frodon, mais on y honore certainement les jardiniers.” — Les Deux Tours</p>");
            AddHtml("There-and-Back-Again-TAP", "<p class='main-text'>Secret 1.</p><p class='main-text'><b>Réponse:</b> quand un allié <b><i>Hobbit</i></b> quitte le jeu, cherchez dans votre main ou pile de défausse une copie de cet allié, et mettez-le en jeu sous le contrôle de n’importe quel joueur.</p><p class='flavor-text'>Les ennuis juridiques durèrent des années. Il fallut longtemps pour faire admettre en fait que M. Sacquet était de nouveau vivant. — Le Hobbit</p>");
            AddHtml("A-Fire-Rises-TAP", "<p class='flavor-text'>Quelque chose de terrible se trame à Aldbourg. Alors que vous commencez à assembler les pièces du puzzle, vous voyez de la fumée et des flammes s’élever d’un bâtiment voisin.</p><p class='main-text'>Le coût pour jouer chaque évènement est augmenté de 1.</p><p class='main-text'><b>Forcé:</b> quand cette étape est passée, révélez le Brasier Dévorant.</p>{victory:10}");
            AddHtml("A-Case-of-Identity-TAP", "<p class='flavor-text'>Le mystère de la véritable identité de la Chuchoteuse demeure. Vous devez être sur la bonne piste, à en juger par ses égorgeurs qui rôdent dans les ruelles.</p><p class='main-text'><b>Forcé:</b> à la fin de l’étape de renforcement, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un ennemi soit défaussé. Révélez cet ennemi.</p><p class='main-text'><b>Forcé:</b> quand cette étape est passée, placez le Grand Hall à Hydromel dans la zone de cheminement.</p>{victory:10}");
            AddHtml("The-Uncertain-Dawn-TAP", "<p class='flavor-text'>Alors que le soleil se lève sur les rues d’Aldburg, vos ennemis acculés se révèlent. Vous avez rassemblé vos indices. Maintenant, faites-les porter pendant que vous vous battez pour votre vie — et pour l’âme du Rohan.</p><p class='main-text'> <b>Une fois révélée:</b> retirez de la partie toutes les quêtes annexes de rencontre et toutes les cartes <b><i>Suspect</i></b>. Placez chaque ennemi <b><i>Pays de Dun</i></b> et <b><i>Garnison</i></b> mis de côté dans la zone de cheminement, si possible.</p>");
            AddHtml2("The-Uncertain-Dawn-TAP", "<p class='main-text'> Une Aube Incertaine gagne –5 points de quête pour chaque objectif <b><i>Indice</i></b> que les joueurs contrôlent.</p><p class='main-text'><b>Forcé:</b> au début de la phase de quête, défaussez des cartes du sommet du deck de rencontre jusqu’à ce qu’un ennnemi soit défaussé. Revélez cet ennemi et placez-le dans la zone de cheminement.</p><p class='main-text'><b>Vous ne pouvez pas passer cette étape sauf si c’est la fin du tour. Si les joueurs passent cette étape, ils ont gagné la partie.</b></p>");
            AddHtml("A-Lesson-in-Caution-TAP", "<p class='main-text'>Secret 1.</p><p class='main-text'><b>Action:</b> piochez 1 carte. Ensuite, choisissez entre : réduire de 2 votre niveau de menace ou la prochaine carte que vous jouerez durant cette phase gagne Secret 1.</p><p class='flavor-text'>Les Hobbits ont le pas léger et leurs empreintes ne sont pas faciles à interpréter, même pour un Rôdeur… — Les Deux Tours</p>");
            AddHtml("Widfast-TAP", "<p class='main-text'><b>Mise en place:</b> cherchez un allié <b><i>Créature</i></b> dans votre collection et ajoutez-le à votre main. Durant le premier tour, son coût est réduit de 2.</p><p class='main-text'>[Voyage] <b>Action:</b> s’il y a un lieu actif, dépensez 1 ressource de la réserve de Widfast pour voyager vers un autre lieu en résolvant son effet Trajet. (Il y a maintenant deux lieux actifs.)</p>");
        }
    }
}