using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Services.LotR.Templates
{
    public class GermanTemplateRepository : TemplateRepository
    {
        protected override void Initialize()
        {
            CoreSet();
            HandsUponTheBow();
            ChildrenOfEorl();
            TheAldburgPlot();
        }

        private void CoreSet()
        {
            AddHtml("Aragorn-Core", "<p class='main-text'>{keyword:Schildwache.}</p><p class='main-text'><b><b>Reaktion:</b></b> Nachdem {self} sich einem Abenteuer gestellt hat, kannst du 1 Ressource aus seinem Ressourcenvorrat ausgeben, um ihn wieder spielbereit zu machen.</p><p class='flavor-text'>&bdquo;Ich bin Aragorn, der Sohn Arathorns; und wenn ich dich durch Leben oder Tod retten kann, werde ich es tun.&rdquo;&ndash;Die Gemeinschaft des Ringes</p>");
            AddHtml("Beorn-Core", "<p class='main-text'><b><b>Aktion:</b></b> {self} erhalt +5 {Attack} bis zum Ende der Phase. Am Ende der Phase, in der dieser Effekt ausgelost wurde, wird {self} wieder in dein Deck gemischt. (Nur einmal pro Runde.)</p><p class='flavor-text'>&bdquo;Ich brauche deinen Service nicht, danke ... aber ich erwarte, dass du meinen brauchst.&rdquo;<br>&ndash;Der Hobbit</p>");
            AddHtml("Guard-of-the-Citadel-Core", "<p class='flavor-text'>&bdquo;Aber die Herren von Minas Tirith kämpfen weiter, verteidigen unsere Feinde und halten den Fluss von Argonath zum Meer.&rdquo;&ndash;Elrond, Die Gefährtenschaft des Ringes</p>");
        }

        private void HandsUponTheBow()
        {
            AddHtml("Hands-Upon-the-Bow-SaF", "<p class='main-text'><b><b>Aktion:</b></b> Erschöpfe einen von dir kontrollierten Charakter mit Fernkampf, um ihn sofort zum Angreifer gegen einen Gegner in der Aufmarschzone zu erklären (und seinen Angriff abzuhandeln). Er erhält +1 {Attack} für diesen Angriff.</p>");
        }

        private void ChildrenOfEorl()
        {
            AddHtml("Defend-the-Beacon-CoE", "<p class='main-text'>Die Spieler kontrollieren das Leuchtfeuer. Schattenkarten sind immun gegen Spielerkarteneffekte.</p><p class='main-text'>Verteidigt das Leuchtfeuer kann nicht als X Fortschrittsmarker erhalten, wobei X gleich 2 play 1{PerPlayer} ist.</p><p class='main-text'><b>Reaktion:</b> Entfernt eine beliebigen Anzahl Fortschrittsmarker von Verteidigt das Leuchtfeuer, um eine gleiche Anzahl Schaden, der dem Leuchtfeuer von Erelas zugefügt wird, zu verhindern. Falls sich danach 0 Forschrittsmarker auf Verteidigt das Leuchtfeuer befinden, drehe diese Karte um.</p>");
            AddHtml("Ingold-CoE", "<p class='main-text'><b>Reaktion:</b> Nachdem ein <b><i>Gondor</i></b>- oder <b><i>Krieger</i></b>-Verbündeter unter deiner Kontrolle ins Spiel gekommen ist, ziehe 1 Karte. Gib danach entweder 1 Ressource aus Ingolds Ressourcenvorrat aus oder erhöhe deine Bedrohung um 1. (Nur einmal pro Phase.)</p><p class='flavor-text'>“Zu dieser Zeit wollen wir keine Fremden im Land haben, es seien denn mächtige Krieger, auf deren Treue und Hilfe wir uns verlassen können.” —Die Rückkehr des Königs</p>");
            AddHtml("Celador-CoE", "<p class='main-text'>Fernkampf.</p><p class='main-text'>Senke den Gesamt-{Threat} in der Aufmarschzone um 1 für jede nicht angehängte <b><i>Falle</i></b>, die du kontrollierst.</p><p class='main-text'><b>Reaktion:</b> Nachdem eine <b><i>Falle</i></b>-Karte, die du kontrollierst, an einen Gegner angehängt worden ist, mache entweder Celador spielbereit oder reduziere deine Bedrohung um 1.</p><p class='flavor-text'>“Der kluge Mann vertraut keinen Zufallsbegegnungen auf der Straße in diesem Land.” —Faramir, Die Zwei Türme</p>");
            AddHtml("Thengel-CoE", "<p class='main-text'><b>Reaktion:</b> Nachdem ein Verbündeter aus dem Spiel abgelegt worden ist, durchsucht dessen Besitzer die 5 obersten Karten seines Decks nach einem Verbündeten, der ein <b><i>Merkmal</i></b> mit dem abgelegten Verbündeten gemeinsam hat, bringt ihn erschöpft ins Spiel und mischt sein Deck. (Nur einmal pro Runde.)</p><p class='flavor-text'>“Mein Freund”, sagte Gandalf, “Ihr hattet Pferde und Waffentaten und die freien Felder.” —Die Rückkehr des Königs</p>");
            AddHtml("Herubrand-CoE", "<p class='main-text'>Herubrand erhält +1 {Willpower} für jeden Helden, den du kontrollierst, mit mindestens 1 eingeschränkten Verstärkung.</p><p class='main-text'><b>Reaktion:</b> Nachdem ein Gegner in der Aufmarschzone getötet worden ist, ziehe 1 Karte.</p><p class='flavor-text'>“Welche Last tragt ihr, Männer von Rohan?”<br/>—Imrahil, Die Rückkehr des Königs</p>");
            AddHtml("Deeping-Bowman-CoE", "<p class='main-text'>Treu. Fernkampf.</p><p class='main-text'><b>Aktion:</b> Lege Bogenschütze der Klamm ab, um einen Gegner zu wählen. Bis zum Ende der Phase kann dieser Gegner seine {Defense} nicht abziehen, wenn Kampfschaden ermittelt wird.</p><p class='flavor-text'>“Wir haben alle Pfeile verschossen, die wir hatten, und der Deich wimmelt von Orks.” —Die Zwei Türme</p>");
            AddHtml("Open-the-Gates-CoE", "<p class='main-text'><b>Aktion:</b> Durchsuche die obersten 5 Karten deines Decks nach einem Verbündeten, der ein <b><i>Merkmal</i></b> mit jedem deiner Helden gemeinsam hat, und bringe ihn ins Spiel. Mische dein Deck. Am Ende der Phase, wenn dieser Verbündete das Spiel nicht verlassen hat, füge ihn deiner Hand hinzu.</p><p class='flavor-text'>Es schien, als sei die Nachricht von ihrem Kommen schon vor ihnen eingetroffen; denn sie wurden sofort eingelassen, stumm und ohne Fragen. —Die Rückkehr des Königs</p>");
            AddHtml("Wealth-of-Adventure-CoE", "<p class='main-text'><b>Aktion:</b> Durchsuche dein Deck nach einer <b><i>Fertigkeit</i></b>-Karte und füge sie deiner Hand hinzu. Mische dein Deck.</p><p class='flavor-text'>“Es ist eine gefährliche Sache, Frodo, aus deiner Tür hinauszugehen”, pflegte er zu sagen. “Du betrittst die Straße, und wenn du nicht auf deine Füße aufpasst, kann man nicht wissen, wohin sie dich tragen.”<br/> —Frodo, Die Gefährten</p>");
            AddHtml("Feast-of-Plenty-CoE", "<p class='main-text'>Die Ressourcenkosten von Fest der Fülle müssen aus dem Ressourcenvorrat eines einzelnen Helden bezahlt werden.</p><p class='main-text'><b>Aktion:</b> Mache bis zu 3 Helden spielbereit und füge je 1 Ressource dem Ressourcenvorrat dieser Helden hinzu. In jeder Runde kann nur 1 Kopie von Fest der Fülle von den Spielern gespielt werden.</p><p class='flavor-text'>Das Festmahl war fröhlich und das Essen so, wie es sich sein Hunger nur wünschen konnte. —Die Gefährten</p>");
            AddHtml("Deeping-Defender-CoE", "<p class='main-text'>Treu.</p><p class='main-text'><b>Reaktion:</b> Nachdem Verteidiger der Klamm einen Angriff verteidigt hat, lege den angreifenden Gegner zurück in die Aufmarschzone und füge diesem 1 Schaden zu.</p><p class='flavor-text'>Der Sonnenuntergang vergoldete ihre Speere und Helme und schimmerte auf ihrem hellen, flatternden Haar.<br/> —Die Zwei Türme</p>");
            AddHtml("Morwen-Steelsheen-CoE", "<p class='main-text'><b>Aktion:</b> Bringe Morwen Stahlglanz von deiner Hand ins Spiel. Lege danach einen <b><i>Rohan</i></b>- oder <b><i>Gondor</i></b>-Verbündeten, den du kontrollierst, ab.</p><p class='main-text'><b>Reaktion:</b> Nachdem ein <b><i>Rohan</i></b>- oder <b><i>Gondor</i></b>-Verbündeter das Spiel verlassen hat, erschöpfe Morwen Stahlglanz, um entweder 2 Schaden von einem Charakter zu heilen oder deine Bedrohung um 1 zu senken.</p>");
            AddHtml("It-Should-Be-Spared-CoE", "<p class='main-text'><b>Reaktion:</b> Nachdem eine <b><i>Falle</i></b>, die du kontrollierst, an einen Gegner angehängt worden ist, nimm sie zurück auf die Hand. Spiele sie danach kostenlos von der Hand.</p><p class='flavor-text'>“Aber ich erschlage Mensch oder Tier nicht ohne Not, und auch nicht gern, wenn es nötig ist.”<br/> —Faramir, Die Zwei Türme</p>");
            AddHtml("Spring-the-Trap-CoE", "<p class='main-text'><b>Reaktion:</b> Nachdem eine <b><i>Falle</i></b>, die du kontrollierst, an einen Gegner angehängt worden ist, bringe einen <b><i>Waldläufer</i></b>-Verbündeten von deiner Hand ins Spiel.</p><p class='flavor-text'>“Die Straße mag durchlaufen, aber die Südländer nicht! Nicht, solange Faramir Heermeister ist.”<br/> —Mablung, Die Zwei Türme</p>");
            AddHtml("Squire-of-the-Mark-CoE", "<p class='main-text'><b>Reaktion:</b> Nachdem ein <b><i>Rohan</i></b>-Verbündeter, den du kontrollierst, aus dem Spiel abgelegt worden ist, füge Knappe der Mark zum Stapel beanspruchter Siegpunkte hinzu, um diesen Verbündeten erschöpft ins Spiel zu bringen.</p><p class='flavor-text'>“Nur geringe Dienste kann ich Eurem Herrn anbieten, doch was ich tun kann, würde ich tun.”<br/> —Pippin, Die Rückkehr des Königs</p>");
            AddHtml("Rammas-Lookout-CoE", "<p class='main-text'>Treu.</p><p class='main-text'>Solange jeder Held, den du kontrollierst, mindestens 1 Ressource in seinem Vorrat hat, erhält Wachposten der Rammas +1 {Willpower} und wird nicht erschöpft, um sich dem Abenteuer zu stellen.</p><p class='flavor-text'>“Was immer geschehen mag, ihr erlebt das Ende von Gondor, so wie ihr es gekannt habt. Lasst mich durch!”<br/> —Gandalf, Die Rückkehr des Königs</p>");
            AddHtml("Theodwyn-CoE", "<p class='main-text'><b>Reaktion:</b> Wenn Théodwyn ins Spiel kommt, ziehe entweder 1 Karte oder füge 1 Ressource zum Ressourcenvorrat eines <b><i>Adlig</i></b>-Helden hinzu.</p><p class='flavor-text'>“Sie ist furchtlos und kühn. Alle lieben sie. Lasst sie Herrscherin der Eorlingas sein, während wir fort sind.” —Háma, Die Zwei Türme</p>");
            AddHtml("Light-footed-Steed-CoE", "<p class='main-text'>Hänge diese Karten an einen <b><i>Rohan</i></b>-Helden an. Eingeschränkt.</p><p class='main-text'><b>Reaktion:</b> Nachdem ein Charakter, den du kontrollierst, das Spiel verlassen hat, erschöpfe Leichtfüßiges Streitross, um den Helden mit dieser Verstärkung spielbereit zu machen. Wenn der Charakter, der das Spiel verlassen hat, einzigartig war, dann erhält der Held mit dieser Verstärkung +1 {Attack} bis zum Ende der Runde.</p><p class='flavor-text'>“… und vergesst ihre Pferde nicht! Sie können den Nachtwind sehen, heißt es.” —Uglúk, Die Zwei Türme</p>");
            AddHtml("Rammas-Sentry-CoE", "<p class='main-text'>Treu.</p><p class='main-text'>Solange jeder Held, den du kontrollierst, mindestens 1 Ressource in seinem Vorrat hat, erhält Wächter der Rammas: “<b>Reaktion:</b> Verhindere 1 Schadenspunkt, der gerade einem <b><i>Gondor</i></b>-Charakter zugefügt worden ist. (Nur einmal pro Runde.)”</p><p class='flavor-text'>“Denn wenn wir fallen, wer soll dann standhalten?”<br/> —Beregond, Die Rückkehr des Königs</p>");
            AddHtml("Live-Bait-CoE", "<p class='main-text'>Kann nur gespielt werden, wenn du eine nicht angehängte <b><i>Falle</i></b>-Verstärkung kontrollierst.</p><p class='main-text'><b>Aktion:</b> Wähle einen nicht-einzigartigen Gegner im Spiel. Behandle das aufgedruckte Texfeld dieses Gegners bis zum Ende der Runde, als wäre es leer (mit Ausnahme von <b><i>Merkmalen</i></b>). Hänge danach eine nicht angehängte <b><i>Falle</i></b>-Verstärkung, die du kontrollierst, an diesen Gegner an.</p>");
            AddHtml("Worthy-of-Remembrance-CoE", "<p class='main-text'><b>Kampf Aktion:</b> Lege einen <b><i>Rohan</i></b>-Verbündeten ab, den du kontrollierst, um einen Gegner zu wählen. Füge diesem Gegner 2 Schaden zu (4 Schaden stattdessen, wenn der abgelegte Verbündete einzigartig war).</p><p class='flavor-text'>Da wandelte sich Éowyns Herz … Und plötzlich verging ihr Winter, und die Sonne beschien sie.<br/> —Die Rückkehr des Königs</p>");
            AddHtml("Need-Brooks-No-Delay-CoE", "<p class='main-text'>Senke die Ausspielkosten für Not duldet keinen Aufschub um 1 für jeden <b><i>Rohan</i></b>-Helden, den du kontrollierst.</p><p class='main-text'><b>Planungs Aktion:</b> Durchsuche die 10 obersten Karten deines Decks nach einer Karte mit aufgedruckten Kosten von 2 oder weniger (3 oder weniger, wenn sie einzigartig ist) und lege sie beseite. Mische dein Deck. Spiele danach die beiseite gelegte Karte kostenlos, als ob sie in deiner Hand wäre.</p>");
            AddHtml("Wild-Country-CoE", "<p class='main-text'>Verflucht 1. Weitläufig.</p><p class='main-text'><b>Erzwungen:</b> Am Ende der Reisephase fügt jeder Spieler einem Charakter, den er kontrolliert, 1 Schaden zu, falls der aktive Ort nicht weitläufig ist.</p>{shadow}<p class='shadow-text'>Schatten: Falls der aktive Ort weitläufig ist, füge dem verteidigenden Charakter 1 Schaden zu.</p>");
            AddHtml("Endless-Grasslands-CoE", "<p class='main-text'>Weitläufig.</p><p class='main-text'><b>Erzwungen:</b> Am Ende der Reisephase erschöpft jeder Spieler einen Verbündeten, den er kon-trolliert, falls der aktive Ort nicht weitläufig ist.</p>{shadow}<p class='shadow-text'>Schatten: Falls der aktive Ort weitläufig ist, führt der angreifende Gegner sofort einen weiteren Angriff nach diesem aus.</p>");
            AddHtml("Windworn-Villages-CoE", "<p class='main-text'>Weitläufig.</p><p class='main-text'><b>Erzwungen:</b> Am Ende der Reisephase wählt jeder Spieler 1 Karte aus seiner Hand aus und legt diese ab, falls der aktive Ort nicht weitläufig ist.</p>{shadow}<p class='shadow-text'>Schatten: Falls der aktive Ort weitläufig ist, lege 1 Verstärkung des verteidigenden Charakters ab.</p>");
            AddHtml("Humpbacked-Downs-CoE", "<p class='main-text'>Weitläufig.</p><p class='main-text'><b>Erzwungen:</b> Am Ende der Reisephase erhöht jeder Spieler seinen Bedrohungsgrad um 1, falls der aktive Ort nicht weitläufig ist.</p>{shadow}<p class='shadow-text'>Schatten: Falls der aktive Ort weitläufig ist, erhöhe deine Bedrohung um 2.</p>");
            AddHtml("Ride-Through-the-Night-CoE", "<p class='main-text'><b>Wenn aufgedeckt:</b> Erschöpft alle eingeschränkten Verstärkungen, die die Spieler kontrollieren. Falls keine eingeschränkten Verstärkungen auf diese Weise erschöpft worden sind, erhält Reitet durch die Nacht Nachrüsten.</p>{shadow}<p class='shadow-text'>Schatten: Falls der aktive Ort weitläufig ist, kann der verteidigende Charakter bis zum Ende der Runde nicht spielbereit gemacht werden.</p>");
            AddHtml("The-Green-Sea-CoE", "<p class='flavor-text'>Das Hinterland ist weit und endlos. Selbst die robustesten Pferde der Westfold treibt es an den Rand der Erschöpfung.</p><p class='main-text'>Weitläufige Orte erhalten +3 Abenteuerpunkte und sind immun gegen Spielerkarten-Effekte.</p><p class='main-text'><b>Erzwungen:</b> Falls sich zu Beginn der Reisephase keine weitläufigen Orte in der Auf-marschzone befinden, legt Karten oben vom Begegnungsdeck, ab bis ein weitläufiger Ort abgelegt wurde. Fügt diesen Ort der Aufmarschzone hinzu.</p>{victory:10}");
            AddHtml("Cold-from-the-Mountains-CoE", "<p class='main-text'><b>Wenn aufgedeckt:</b> Jeder Spieler, der mehr als 2 Verbündete kontrolliert, muss 1 Verbündeten, den er kontrolliert, ablegen (legt stattdessen 2 Verbündete ab, wenn der Spieler mehr als 5 Verbündete kontrolliert).</p>{shadow}<p class='shadow-text'>Schatten: Erschöpfe einen Charakter, den du kontrolliert.</p><p class='flavor-text'>“Soll das Wind nennen, wer will.” —Boromir, Die Gefährten</p>");
            AddHtml("Exhausting-Winds-CoE", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt jedem Charakter mit mehr als 1 verbleibenden Trefferpunkt 1 Schaden zu. Erschöpft jeden Charakter, dem auf diese Weise kein Schaden zugefügt wurde.</p>{shadow}<p class='shadow-text'>Schatten: Füge dem verteidigenden Charakter nach diesem Angriff X Schaden zu, wobei X der Anzahl der verbleibenden Trefferpunkte des Charakters minus 1 entspricht.</p>");
            AddHtml("Tired-and-Hungry-CoE", "<p class='main-text'>Solange diese Karte an einen Helden angehängt ist, gilt sie als <b><i>Zustand</i></b>-Verstärkung mit dem Text: “<b>Erzwungen:</b> Nachdem ein Ort erkundet worden ist, erschöpfe den Helden mit dieser Verstärkung.”</p><p class='main-text'><b>Wenn aufgedeckt:</b> Hängt Müde und Hungrig an einen spielbereiten Helden an, an den noch keine Kopie von Müde und Hungrig angehängt ist. Andernfalls erhält Müde und Hungrig Nachrüsten.</p><p class='flavor-text'>Das Lager unterm Himmelszelt Von Feinden und Gefahr umstellt.<br/>—Die Gefährten</p>");
            AddHtml("Exposed-to-the-Elements-CoE", "<p class='flavor-text'>Eure Gruppe ist Regen, Schnee und Hunger ausgeliefert. Ihr müsst Schutz suchen, um zumindest ein wenig Kraft zu sammeln.</p><p class='main-text'><b>Erzwungen:</b> Legt am Ende des Aufmarschschritts Karten oben vom Begeg-nungsdeck ab, bis eine Verratskarte abgelegt wurde. Deckt diese Karte auf.</p>{victory:10}");
            AddHtml("Old-Farmhouse-CoE", "<p class='main-text'><b>Erzwungen:</b> Nachdem Altes Bauernhaus das Spiel als erkundeter Ort verlassen hat, legt Karten oben vom Begegnungsdeck ab, bis ein Ort abgelegt wurde. Fügt diesen Ort der Aufmarschzone hinzu.</p><p class='flavor-text'>Nach einer Biegung, etwa eine Achtelmeile von der Hauptstraße entfernt, stießen sie auf eine mächtige Straßensperre aus umgekippten Bauernkarren. Das brachte sie zum Stehen.<br/>—Die Rückkehr des Königs</p>");
            AddHtml("Abandoned-Mill-CoE", "<p class='main-text'>Verflucht 1. Immun gegen Spielerkarteneffekte.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Verlassene Mühle das Spiel als erkundeter Ort verlassen hat, legt Karten oben vom Begegnungsdeck ab, bis ein Gegner abgelegt wurde. Fügt diesen Gegner der Aufmarschzone hinzu.</p><p class='flavor-text'>Aber man muss Mahlgut haben, ehe man mahlen kann; und für die neue Mühle war nicht mehr da als für die alte.<br/> —Die Rückkehr des Königs</p>");
            AddHtml("Dunland-Chieftain-CoE", "<p class='main-text'><b>Erzwungen:</b> Nachdem Häutpling aus Dunland dich in einen Kampf verwickelt hat, lege 1 zufällige Karte von deiner Hand ab. Danach lege jede andere Kopie dieser Karte, die sich in deiner Hand oder unter deiner Kontrolle befindet, ab.</p><p class='flavor-text'>“Sie hassen uns und freuen sich.”<br/>—Gamling, Die Zwei Türme</p>{victory:1}");
            AddHtml("Wild-Ravager-CoE", "<p class='main-text'><b>Erzwungen:</b> Zu Beginn der Begegnungsphase wähle einen zufälligen Spieler. Wilder Verwüster verwickelt diesen Spieler in einen Kampf.</p>{shadow}<p class='shadow-text'>Schatten: Der angreifende Gegner kann bis zum Ende der Runde keinen Schaden erleiden.</p>");
            AddHtml("Dunlending-Berserker-CoE", "<p class='main-text'><b>Erzwungen:</b> Nachdem Dunländer-Berserker dich in einem Kampf verwickelt hat, füge einem Helden, den du kontrollierst, und einem nicht-einzigartigen Gegner, der mit dir in einem Kampf verwickelt ist, jeweils 1 Schaden zu.</p><p class='flavor-text'>“Sie werden nicht zurückweichen, ob nun die Abend- oder Morgendämmerung kommt.” —Gamling, Die Zwei Türme</p>");
            AddHtml("Hillman-Scout-CoE", "<p class='main-text'>Bogenschießen 2.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Späher der Hügelmenschen dich in einen Kampf verwickelt hat, erschöpfe 1 spielbereiten Verbündeten, den du kontrollierst, mit den höchsten aufgedruckten Kosten.</p>{shadow}<p class='shadow-text'>Schatten: Erschöpfe einen Charakter mit 3 oder mehr {Attack}, den du kontrollierst.</p>");
            AddHtml("Surprise-Attack-CoE", "<p class='main-text'>Nachrüsten.</p><p class='main-text'><b>Wenn aufgedeckt:</b> Der nächste Gegner, der diese Runde einen Spieler in einen Kampf verwickelt, kann bis zum Ende der Runde keinen Schaden erleiden und wird in die Aufmarschzone zurückgelegt, nachdem er diese Runde angegriffen hat.</p><p class='flavor-text'>Es schien keine Aussicht zu bestehen, die Furt zu erreichen, ehe er von jenen abgeschnitten wurde, die im Hinterhalt gelegen hatten. Er konnte sie jetzt deutlich sehen.<br/>—Die Gefährten</p>");
            AddHtml("A-History-of-Strife-CoE", "<p class='flavor-text'>Die Dunländer hegen einen uralten Groll gegen alle Fremden. Sie versuchen, euch zu überrumpeln und eure Vorräte zu stehlen, um euch dann tot zurückzulassen.</p><p class='main-text'>Nachrüsten.</p><p class='main-text'>Jeder <b><i>Dunland</i></b>-Gegner erhält: “<b>Erzwungen:</b> Nachdem dieser Gegner einen Spieler in den Kampf verwickelt hat, legt dieser Spieler eine Ressource von einem Helden, den er kontrolliert, ab.”</p>{victory:10}");
            AddHtml("Recreant-Rider-CoE", "<p class='main-text'><b>Erzwungen:</b> Sobald Feiger Reiter die Aufmarschzone betritt, führt er sofort einen Angriff gegen den Startspieler durch.</p>{shadow}<p class='shadow-text'>Schatten: Lege den angreifenden Gegner nach dem Angriff in die Aufmarschzone.</p>");
            AddHtml("Deadly-Defector-CoE", "<p class='main-text'><b>Erzwungen:</b> Falls sich Tödlicher Überläufer am Ende der Kampfphase in der Aufmarschzone befindet, führt er sofort einen Angriff gegen den Schlussspieler aus.</p>{shadow}<p class='shadow-text'>Schatten: Falls sich der angreifende Gegner in der Aufmarschzone befindet, führt er einen weiteren Angriff nach diesem aus.</p>");
            AddHtml("Orc-Battalion-CoE", "<p class='main-text'>Ork-Bataillon kann keinen Schaden erleiden, solange es von weniger als 3 Charakteren angegriffen wird.</p><p class='main-text'><b>Erzwungen:</b> Nachdem ein Charakter zum Angreifer gegen Ork-Bataillon erklärt worden ist, füge diesem Charakter 1 Schaden zu.</p>");
            AddHtml("Servant-of-the-Eye-CoE", "<p class='main-text'>Verflucht 1.</p><p class='main-text'><b>Erzwungen:</b> Sobald Diener des Auges einen Spieler angreift, erhöht dieser Spieler seinen Bedrohungsgrad um 1.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler erhöht seinen Bedrohungsgrad um 2.</p>");
            AddHtml("Black-Land-Scouts-CoE", "<p class='main-text'><b>Erzwungen:</b> Erhöht zu Beginn der Kampfphase entweder den Bedrohungsgrad jedes Spielers um 1 oder fügt 4 Schaden beliebig verteilt auf Charaktere im Spiel zu.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler fügt 2 Schaden beliebig verteilt auf Charaktere, die er kontrolliert, zu.</p>");
            AddHtml("Orcish-Horse-butcher-CoE", "<p class='main-text'><b>Erzwungen:</b> Sobald Orkischer Pferdeschlächter einem Charakter Schaden zufügt, legt der kontrollierende Spieler eine Verstärkung von diesem Charakter ab oder erhöht seinen Bedrohungsgrad um 1.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler legt entweder eine Verstärkung, die er kontrolliert, ab oder erhöht seinen Bedrohungsgrad um 3.</p>");
            AddHtml("Crimson-Banner-CoE", "<p class='main-text'>Nachrüsten.</p><p class='main-text'>Während Purpurrotes Banner an einen Gegner angehängt ist, zählt diese Karte als <b><i>Zustand</i></b>-Verstärkung mit dem Text: “<b>Erzwungen:</b> Am Ende der Runde erhöht jeder Spieler seinen Bedrohungsgrad um 1 für jeden <b><i>Ork</i></b>-Gegner im Spiel.</p><p class='main-text'><b>Wenn aufgedeckt:</b> Hänge Purpurrotes Banner an den nicht-einzigartigen <b><i>Ork</i></b>-Gegner mit der höchsten Kampfbereitschaft an.”</p>");
            AddHtml("White-Mountain-Reinforcements-CoE", "<p class='flavor-text'>Orks strömen aus ihren Berghöhlen und stärken die Streitmacht eurer Feinde. Wenn ihr sie nicht abfangt, werden sie euch sicher bald überwältigen.</p><p class='main-text'><b>Wenn aufgedeckt:</b> Jeder Spieler, der nicht mit einem Gegner in einen Kampf verwickelt ist, durchsucht das Begegnungsdeck und den Ablagestapel nach einem Gegner und bringt diesen Gegner mit sich in den Kampf verwickelt ins Spiel. Mischt das Begegnungsdeck.</p><p class='main-text'>Jede Schattenkarte ohne Schatteneffekt erhält: “Schatten: Erhöhe deinen Bedrohungs-grad um 1.”</p>{victory:10}");
            AddHtml("Brigand-Ringleader-CoE", "<p class='main-text'>Erbeuten 3. Immun gegen Spielerkarteneffekte. Kann nicht mehr als 5 Schaden pro Runde nehmen.</p><p class='main-text'><b>Erzwungen:</b> Am Ende der Runde fügt der Spieler, mit Rädelsführer der Gesetzlosen in einen Kampf verwickelt ist, die oberste Karte seines Decks dem Beutestapel von Rädelsführer der Gesetzlosen hinzu und heilt einen Schaden von Rädelsführer der Gesetzlosen für jeden unterschiedlichen Kostenwert, der auf Karten in dessen Beutestapel aufgedruckt ist.</p>{victory:10}");
            AddHtml("Plundered-Goods-CoE", "<p class='main-text'>Fügt 1 zum Gesamt-{Threat} in der Aufmarschzone für jede Karte im Beutestapel von Geplünderte Waren hinzu.</p><p class='main-text'><b>Erzwungen:</b> Sobald ein Gegner das Spiel verlässt, fügt 1 Karte von seinem Beutestapel zum Beutestapel von Geplünderte Waren hinzu. Danach gebt eine weitere Karte aus dem Beutestapel dieses Gegners auf die Hand ihres Besitzers zurück. Legt die restlichen Karten des Beutestapels ab.</p><p class='flavor-text'>Die Gesetzlosen haben die Speer- und Schildvorräte des Dorfes geplündert. Nun richten sie diese Waffen auf die Dorfbewohner.</p>");
            AddHtml("Pillaging-Swordsman-CoE", "<p class='main-text'>Erbeuten 1.</p><p class='main-text'>Plündernder Schwertkämpfer erhalt +X {Attack}, wobei X dem höchsten aufgedruckten Kostenwert auf Karten in seinem Beutestapel entspricht.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler fügt die obersten 2 Karten seines Decks dem Beutestapel des angreifenden Gegners zu.</p>");
            AddHtml("Grasping-Slaver-CoE", "<p class='main-text'>Erbeuten 2.</p><p class='main-text'><b>Erzwungen:</b> Nachdem ein Verbündeter durch den Angriff von Habgieriger Sklavenhändler Schaden genommen hat oder getötet worden ist, füge diesen Verbündeten dem Beutestapel von Habgieriger Sklavenhändler hinzu.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Habgieriger Sklavenhändler angegriffen hat, füge Charakteren, die du kontrollierst, insgesamt X Schaden zu. X ist die Anzahl der Verbündetenkarten im Beutestapel von Habgieriger Sklavenhändler.</p>");
            AddHtml("Vengeful-Bowman-CoE", "<p class='main-text'>Erbeuten 2. Bogenschießen X.</p><p class='main-text'>X entspricht der Anzahl unterschiedlicher Spielerkartentypen im Beutestapel von Rachsüchtiger Bogenschütze.</p>{shadow}<p class='shadow-text'>Schatten: Falls dieser Angriff Schaden zufügt, fügt der verteidigende Spieler die oberste Karte seines Decks dem Beutestapel des angreifenden Gegners hinzu.</p>");
            AddHtml("Sneaky-Thief-CoE", "<p class='main-text'>Erbeuten 0. Nachrüsten.</p><p class='main-text'><b>Erzwungen:</b> Sobald Hinterhältiger Dieb Schaden erleiden würde, legt stattdessen eine Karte aus seinem Beutestapel ab, solange sich eine oder mehr Karten darin befinden.</p>{shadow}<p class='shadow-text'>Schatten: Falls dieser Angriff einen Charakter tötet, führt der angreifende Gegner einen weiteren Angriff durch.</p>");
            AddHtml("Erelas-Gates-CoE", "<p class='main-text'>Reise: Jeder Spieler wählt einen Gegner aus und fügt die oberste Karte seines Decks zu dessen Beutestapel hinzu.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler erhöht seinen Bedrohungsgrad um 1 für jede Karte im Beutestapel des angreifenden Gegners.</p><p class='flavor-text'>Verbogene und schräg stehende Säulen ragten mit ihren geborstenen Schäften über die Flut hinaus, aber alle Straßen waren überschwemmt.<br/>—Die Zwei Türme</p>");
            AddHtml("Crossroads-CoE", "<p class='main-text'>Reise: Mischt den Begegnungs-Ablagestapel in das Begegnungsdeck und legt Karten oben vom Begegnungsdeck ab, bis ein Gegner abgelegt wird. Bringt diesen Gegner mit dem Startspieler in einen Kampf verwickelt ins Spiel.</p>{shadow}<p class='shadow-text'>Schatten: Der angreifende Gegner erhält +X {Attack}, wobei X der Anzahl unterschiedlicher Einflusssphären auf Karten in dessen Beutestapel entspricht.</p>");
            AddHtml("Erelas-Stables-CoE", "<p class='main-text'>Reise: Legt einen Gegner, der mit einem Spieler in den Kampf verwickelt ist, in die Aufmarschzone.</p>{shadow}<p class='shadow-text'>Schatten: Falls der angreifende Gegner nicht-einzigartig ist, legt den Gegner nach diesem Angriff in die Aufmarschzone.</p>");
            AddHtml("Chaos-in-the-Hills-CoE", "<p class='main-text'><b>Wenn aufgedeckt:</b> Legt den Gegner mit der höchsten Kampfbereitschaft unter den mit den Spielern in einen Kampf verwickelten Gegnern in die Aufmarschzone. Wenn auf diese Weise kein Gegner in die Aufmarschzone gelegt wurde, erhält Chaos in den Hügeln Nachrüsten.</p>{shadow}<p class='shadow-text'>Schatten: Nach diesem Angriff verwickelt der angreifende Gegner den Folgespieler in einen Kampf und führt sofort einen weiteren Angriff durch.</p>");
            AddHtml("Looted-Weapons-CoE", "<p class='main-text'>Während Geplünderte Waffen an einen Gegner angehängt ist, zählt diese Karte als <b><i>Zustand</i></b>-Verstärkung mit dem Text: “Dieser Gegner erhält +1 {Threat} und +1 {Attack} für jede Verstärkung in dessen Beutestapel.”</p><p class='main-text'><b>Wenn aufgedeckt:</b> Hängt Geplünderte Waffen an den Gegner mit der höchsten Kampfbereitschaft im Spiel an. Jeder Spieler fügt dem Beutestapel dieses Gegners eine <b><i>Gegenstand</i></b>-Verstärkung, die er kontrolliert, hinzu. Solange sich keine Gegner im Spiel befinden, erhält Geplünderte Waffen Nachrüsten.</p>");
            AddHtml("Stockpile-Barricade-CoE", "<p class='flavor-text'>Umgestürzte Karren und Wagen bilden ein unüberwindbares Hindernis entlang der Straße.</p><p class='main-text'>Nachrüsten.</p><p class='main-text'>Jeder Gegner erhält +1 {Defense} für jede Verstärkung in seinem Beutestapel.</p><p class='main-text'><b>Erzwungen:</b> Nachdem das Schlüsselwort Erbeuten auf einem Gegner abgehandelt worden ist und sich keine Verstärkungen im Beutestapel dieses Gegners befinden, führt dieser Gegner sofort einen Angriff gegen den Spieler, mit dem er in einen Kampf verwickelt ist, durch.</p>{victory:10}");
            AddHtml("Erelas-Beacon-CoE", "<p class='main-text'><b>Erzwungen:</b> Fügt am Ende der Kampfphase Leuchtfeuer von Erelas 1 Schaden für jeden Gegner in der Aufmarschzone zu.</p><p class='main-text'><b>Leuchtfeuer von Erelas verfügt über X Trefferpunkte, wobei X gleich 3{PerPlayer} + 2 ist. Sobald Leuchtfeuer von Erelas keine verbleibenden Trefferpunkte hat, verlieren die Spieler das Spiel.</b></p><p class='flavor-text'>All die Lande waren grau und still; und immer dunkler wurde der Schatten vor ihnen, und die Hoffnung schwand in jedem Herz.<br/>—Die Rückkehr des Königs</p>");
            AddHtml("Host-of-Rohan-CoE", "<p class='main-text'>Schildwache.</p><p class='main-text'><b>Aktion:</b> Die Spieler können als Gruppe 2 Ressourcen ausgeben, um Heer aus Rohan spielbereit zu machen. (Nur einmal pro Phase.)</p><p class='flavor-text'>“Denn Krieg ist ausgebrochen, und die Rohirrim, die Herren der Rösser, schlafen nicht.”<br/>—Gandalf, Die Zwei Türme</p>");
            AddHtml("Enraged-Dunlending-CoE", "<p class='main-text'><b>Erzwungen:</b> Nachdem Wütender Dunländer einen Spieler in einen Kampf verwickelt hat, fügt Leuchtfeuer von Erelas 1 Schaden zu.</p>{shadow}<p class='shadow-text'>Schatten: Jeder Schaden, den der verteidigende Charakter durch diesen Angriff erleiden würde, wird stattdessen dem Leuchtfeuer von Erelas zugefügt.</p>");
            AddHtml("Bald-Hill-CoE", "<p class='main-text'>Solange die Spieler das Leuchtfeuer kontrollieren, erhält Kahler Hügel +3 {Threat}.</p><p class='main-text'>Reise: Falls die Spieler das Leuchtfeuer kontrollieren, fügt Leuchtfeuer von Erelas 2 Schaden zu.</p><p class='flavor-text'>Schließlich erreichten sie die Kuppe des grauen Bergs, und eine plötzliche Brise ließ ihr Haar wehen und erfasste ihre Mäntel: der kalte Wind der Morgendämmerung.<br/> —Die Zwei Türme</p>");
            AddHtml("Wooden-Barricade-CoE", "<p class='main-text'>Solange sich Hölzerne Barrikade in der Aufmarschzone befindet, erhält diese Karte: “<b>Erzwungen:</b> Fügt am Ende der Kampfphase Leuchtfeuer von Erelas 1 Schaden zu und legt 1 Fortschrittsmarker auf Hölzerne Barrikade.”</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler legt entweder 2 Verstärkungen, die er kontrolliert, ab oder fügt dem Leuchtfeuer von Erelas 1 Schaden zu.</p>");
            AddHtml("Rocky-Slope-CoE", "<p class='main-text'>Nachdem ein Begegnungskarteneffekt verhindert worden ist, fügt Leuchtfeuer von Erelas 1 Schaden zu.</p><p class='main-text'>Reise: Der Startspieler legt alle Ereigniskarten von seiner Hand ab.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler legt entweder alle Ressourcen von jedem Helden, den er kontrolliert, ab oder fügt dem Leuchtfeuer von Erelas 1 Schaden zu.</p>");
            AddHtml("Surrounding-Grassland-CoE", "<p class='main-text'>Bogenschießen 1.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Umliegendes Grasland das Spiel als erkundeter Ort verlassen hat, legt Umliegendes Grasland zurück in die Aufmarschzone, falls sich keine anderen Kopien von Umliegendes Grasland in der Aufmarschzone befinden.</p><p class='flavor-text'>Von dem hohen Söller auf dem hohen Bergsattel sahen sie jenseits des Stroms die grünen Weiden von Rohan in der grauen Ebene verblassen. —Die Zwei Türme</p>");
            AddHtml("Narrow-Stair-CoE", "<p class='main-text'>Jeder Spieler kann pro Phase nicht mehr als 1 Angriff ausführen und nicht mehr als 1 Angreifer erklären.</p><p class='main-text'>Solange Schmale Treppe der aktive Ort ist, kann jeder Spieler nicht mehr als 1 Angriff pro Phase verteidigen. (Die restlichen Angriffe gelten als unverteidigt.)</p>{shadow}<p class='shadow-text'>Schatten: Entweder erhält der angreifende Gegner +3 {Attack} oder fügt dem Leuchtfeuer von Erelas 1 Schaden zu.</p>");
            AddHtml("From-All-Sides-CoE", "<p class='main-text'><b>Wenn aufgedeckt:</b> Jeder Spieler wählt: Entweder er fügt 4 verschiedenen Charakteren, die er kontrolliert, jeweils 1 Schaden zu, oder er fügt Leuchtfeuer von Erelas 1 Schaden zu.</p>{shadow}<p class='shadow-text'>Schatten: Nach diesem Angriff legt der verteidigende Spieler entweder den verteidigenden Charakter ab oder fügt dem Leuchtfeuer von Erelas 1 Schaden zu.</p>");
            AddHtml("Another-Wave-CoE", "<p class='main-text'>Nachrüsten. Verflucht 1.</p><p class='main-text'><b>Wenn aufgedeckt:</b> Falls die Spieler das Leuchtfeuer kontrollieren, fügt entweder Leuchtfeuer von Erelas 2 Schaden zu oder deckt eine Begegnungskarte auf.</p>{shadow}<p class='shadow-text'>Schatten: Entweder führt der angreifende Gegner einen weiteren Angriff nach diesem aus oder fügt dem Leuchtfeuer von Erelas 1 Schaden zu.</p>");
            AddHtml("Assault-Upon-Erelas-CoE", "<p class='main-text'><b>Wenn aufgedeckt:</b> Der Startspieler wählt einen Gegner, der mit einem Spieler in einen Kampf verwickelt ist, und legt ihn in die Aufmarschzone. Falls auf diese Weise kein Gegner in die Aufmarschzone gelegt wurde, fügt entweder Leuchtfeuer von Erelas 1 Schaden zu oder Angriff auf Erelas erhält Nachrüsten.</p>{shadow}<p class='shadow-text'>Schatten: Entweder erhöht der verteidigende Spieler seinen Bedrohungsgrad um 4 oder fügt dem Leuchtfeuer von Erelas 1 Schaden zu.</p>");
            AddHtml("Reclaim-the-Beacon-CoE", "<p class='flavor-text'>Erobert das Leuchtfeuer, bevor die Dunländer es schänden oder Schlimmeres damit anstellen.</p><p class='main-text'>Die Dunländer kontrollieren das Leuchtfeuer.</p><p class='main-text'>Das Leuchtfeuer zurückgewinnen kann nicht mehr als X Fortschrittsmarker erhalten, wobei X gleich 2 plus 1{PerPlayer} ist. Sobald Das Leuchtfeuer Zurückgewinnen X Fortschrittsmarker auf sich liegen hat, dreht es um. (Diese Karte behält alle Fortschrittsmarker.)</p>");
            AddHtml("Stolen-Steeds-CoE", "<p class='main-text'><b><i>Reittier</i></b>-Zielkarten können nicht abgelegt werden oder das Spiel verlassen. Falls eine <b><i>Reittier</i></b>-Zielkarte nicht angehängt ist, muss ein Spieler sie beanspruchen und an einen Helden anhängen, den er kontrolliert.</p><p class='main-text'><b>Erzwungen:</b> Fügt dem Abenteuer am Ende der Runde 1 Fortschrittsmarker für jede <b><i>Reittier</i></b>-Zielkarte, die die Spieler kontrollieren, hinzu. Erhöht den Bedrohungsgrad jedes Spielers um 1 für jede <b><i>Reittier</i></b>-Zielkarte, die die Spieler nicht kontrollieren.</p>");
            AddHtml("Flinthoof-CoE", "<p class='main-text'>Bewacht (Gegner). Eingeschränkt.</p><p class='main-text'>Der Gegner, der Feuersteinhuf bewacht, erhält +1 {Attack}.</p><p class='main-text'>Der Held, an den Feuersteinhuf angehängt ist, erhält +1 {Attack}.</p><p class='main-text'><b>Kampf Aktion:</b> Erschöpfe Feuersteinhuf, um einem Gegner im Spiel 1 Schaden zuzufügen.</p><p class='flavor-text'>Das graue Fell glänzte, die langen Schweife flatterten im Wind, die Mähnen auf den stolzen Hälsen waren geflochten.<br/>—Die Zwei Türme</p>");
            AddHtml("Brightmane-CoE", "<p class='main-text'>Bewacht (Ort). Eingeschränkt.</p><p class='main-text'>Der Gegner, der Leuchtmähne bewacht, erhält +1 {Threat}.</p><p class='main-text'>Der Held, an den Leuchtmähne angehängt ist, erhält +1 {Willpower}.</p><p class='main-text'><b>Kampf Aktion:</b> Erschöpfe Leuchtmähne, um dir die oberste Karte des Begegnungsdecks anzusehen. Falls es ein Ort ist, darfst du ihn ablegen.</p>");
            AddHtml("Felarof-CoE", "<p class='main-text'>Bewacht (Gegner). Eingeschränkt.</p><p class='main-text'><b>Erzwungen:</b> Sobald der Gegner, der Felaróf bewacht, angreift, teilt ihm 2 zusätzliche Schattenkarten zu.</p><p class='main-text'><b>Kampf Aktion:</b> Erschöpfe Felaróf, um eine verdeckte Schattenkarte aus dem Spiel abzulegen.</p><p class='flavor-text'>“Aber da ist noch ein drittes, das vorausgaloppiert: ein sehr großes Pferd. Seinesgleichen habe ich noch nie gesehen.”<br/>—Legolas, Die zwei Türme</p>");
            AddHtml("Thruk-CoE", "<p class='main-text'>Immun gegen Spielerkarteneffekte. Thruk verwickelt den Startspieler in einen Kampf.</p><p class='main-text'><b>Erzwungen:</b> Falls Thruk keine Zielkarte bewacht, führt er zu Beginn der Kampfphase sofort einen Angriff gegen den mit ihm in einen Kampf verwickelten Spieler aus.</p>{victory:10}");
            AddHtml("Saddle-slasher-CoE", "<p class='main-text'>Bogenschießen X. X entspricht 2 plus 1 für jede <b><i>Reittier</i></b>-Zielkarten unter der Kontrolle der Spieler.</p>{shadow}<p class='shadow-text'>Schatten: Falls der verteidigende Spieler eine <b><i>Reittier</i></b>-Zielkarte kontrolliert, hängt er diese entweder an den angreifenden Gegner als eine bewachte Zielkarte an, oder der Spieler legt nach dem Angriff den verteidigenden Charakter ab.</p>");
            AddHtml("Rein-ripper-CoE", "<p class='main-text'><b>Erzwungen:</b> Sobald Zügelreißer angreift, teilt ihm 2 zusätzliche Schattenkarten zu. Der verteidigende Spieler darf eine <b><i>Reittier</i></b>-Zielkarte, die er kontrolliert, an Zügelreißer als bewachte Zielkarte anlegen, um diesen Effekt zu verhindern.</p>{shadow}<p class='shadow-text'>Schatten: Der angreifende Gegner erhält +1 {Attack} für jede <b><i>Reittier</i></b>-Zielkarte unter der Kontrolle der Spieler.</p>");
            AddHtml("Bridle-biter-CoE", "<p class='main-text'>Nachrüsten.</p><p class='main-text'><b>Wenn aufgedeckt:</b> Zaumbeißer verwickelt den Spieler, der die meisten <b><i>Reittier</i></b>-Zielkarten kontrolliert, in einen Kampf.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler bringt Zaumbeißer mit sich in den Kampf verwickelt ins Spiel und teilt ihm eine Schattenkarte zu.</p>");
            AddHtml("Pommel-pouncer-CoE", "<p class='main-text'>Solange sich Knaufstürzer ohne eine angehängte <b><i>Reittier</i></b>-Zielkarte in der Aufmarschzone befindet, erhält diese Karte: “<b>Erzwungen:</b> Sobald ein Spieler die Kontrolle über eine <b><i>Reittier</i></b>-Zielkarte erhalten würde, hänge diese stattdessen an Knaufstürzer als eine bewachte Zielkarte an.”</p>");
            AddHtml("Spoiled-Pasture-CoE", "<p class='main-text'>X beträgt 2 plus 2 für jede <b><i>Reittier</i></b>-Zielkarte unter der Kontrolle der Spieler.</p><p class='main-text'><b>Erzwungen:</b> Nachdem ein Spieler die Kontrolle über eine <b><i>Reittier</i></b>-Zielkarte verloren hat, erhöht er seinen Bedrohungsgrad um 1.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler erhöht seinen Bedrohungsgrad um 1 für jede <b><i>Reittier</i></b>-Zielkarte unter seiner Kontrolle.</p>");
            AddHtml("Horse-Thieves'-Hovel-CoE", "<p class='main-text'>Sobald die Spieler die Möglichkeit zum Reisen haben, müssen sie zu einem nicht-weitläufigen Ort reisen.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Absteige der Pferdediebe das Spiel als erkundeter Ort verlassen hat, solange sich weniger als 1{PerPlayer} Gegner im Spiel befinden, legt Karten oben vom Begegnungsdeck ab, bis ein Gegner abgelegt wurde. Fügt diesen Gegner der Aufmarschzone hinzu.</p>{victory:2}");
            AddHtml("Horse-Lord's-Lodge-CoE", "<p class='main-text'>Sobald die Spieler die Möglichkeit zum Reisen haben, müssen sie zu einem nicht-weitläufigen Ort reisen.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Loge der Pferdeherren das Spiel als erkundeter Ort verlassen hat, solange sich weniger als 1{PerPlayer} Orte im Spiel befinden, legt Karten oben vom Begegnungsdeck ab, bis ein Ort abgelegt wurde. Fügt diesen Ort der Aufmarschzone hinzu.</p>{victory:2}");
            AddHtml("Thirst-for-Horse-Blood-CoE", "<p class='main-text'><b>Wenn aufgedeckt:</b> Jeder Spieler, der eine <b><i>Reittier</i></b>-Zielkarte kontrolliert, wählt: Entweder deckt er eine Begegnungskarte auf oder wählt den Gegner mit der höchsten Kampfbereitschaft, an den keine <b><i>Reittier</i></b>-Zielkarte angehängt ist, und hängt an diesen eine <b><i>Reittier</i></b>-Zielkarte unter seiner Kontrolle als bewachte Zielkarte an. Falls kein Spieler eine <b><i>Reittier</i></b>-Zielkarte kontrolliert, erhält Durst nach Pferdeblut Nachrüsten.</p><p class='flavor-text'>“Wir werden uns noch Pferdefleisch oder sogar was Besseres schmecken lassen.” —Uglúk, Die Zwei Türme</p>");
            AddHtml("Overburdened-CoE", "<p class='main-text'><b>Wenn aufgedeckt:</b> Jeder Spieler, der mehr als 2 Verstärkungen kontrolliert, muss 1 Verstärkung unter seiner Kontrolle ablegen. (Falls er 5 oder mehr Verstärkungen kontrolliert, legt er stattdessen 2 Verstärkungen ab). Falls durch diesen Effekt keine Verstärkungen abgelegt wurden, erhält Überlastet Nachrüsten.</p>{shadow}<p class='shadow-text'>Schatten: Der verteidigende Spieler legt 1 zufällige Karte von seiner Hand ab.</p>");
            AddHtml("The-Last-Alliance-CoE", "<p class='main-text'>Wähle zwei Merkmale <b><i>A</i></b> und <b><i>B</i></b>. Jeder deiner Starthelden und jeder Verbündete in deinem Deck muss entweder Merkmal <b><i>A</i></b> oder Merkmal <b><i>B</i></b> besitzen, aber nicht beide gleichzeitig. Du musst mindestens 1 Starthelden und 10 Verbündete in deinem Deck mit je einem dieser Merkmale haben.</p><p class='main-text'><b>Vorbereitung:</b> Drehe diese Karte um.</p><p class='flavor-text'>“Früher vermochten die Elben ihm mehr Widerstand zu leisten; und nicht alle Menschen hatten sich von ihnen abgewandt.” —Gandalf, Die Gefährten</p>");
            AddHtml2("The-Last-Alliance-CoE", "<p class='main-text'></b> Solange du mehr <b><i>A</i></b>-Charaktere als <b><i>B</i></b>-Charaktere kontrollierst, reduziere die Kosten des ersten <b><i>B</i></b> -Verbündeten, den du in dieser Runde spielst, um 1, und umgekehrt.</p><p class='main-text'><b>Aktion:</b> Erschöpfe Das Letzte Bündnis, um eine Karte auf deiner Hand oder im Spiel unter deiner Kontrolle zu wählen. Ersetze jede aufgedruckte Instanz von “<b><i>A</i></b>” oder “<b><i>B</i></b>” im Spieltext dieser Karte bis zum Ende der Runde mit “<b><i>A</i></b> oder <b><i>B</i></b>”.</p>");
            AddHtml("Drive-them-Away-CoE", "<p class='flavor-text'>Entlang der Großen Weststraße stoßt ihr auf ein Lager der Rohirrim im Schatten des kahlen grünen Hügels mit dem Leuchtfeuer von Erelas. Der Klang von Waffengewalt und die Schreie von Menschen setzen der Ruhe der Reise ein jähes Ende. Ihr müsst die Feinde vertreiben und das Lager vor weiterer Zerstörung bewahren!</p><p class='main-text'><b></b> Vorbereitung: Legt Rädelsführer der Gesetzlosen als nicht im Spiel befindlich zur Seite. Fügt Geplünderte Waren der Aufmarschzone hinzu. Jeder Spieler durchsucht das Begegnungsdeck nach einem unterschiedlichen Gegner und fügt diesen der Aufmarschzone hinzu. Mischt das Begegnungsdeck.</p>");
            AddHtml2("Drive-them-Away-CoE", "<p class='main-text'></b> <b>Erzwungen:</b> Nachdem ein Gegner getötet worden ist, legt 1 Ressourcenmarker auf diese Karte.</p><p class='main-text'>Begegnungs<b>Aktion:</b> Entfernt 5 Fortschrittsmarker von diesem Abenteuer, um eine Karte in einem Beutestapel zu wählen und abzulegen.Nur einmal pro Runde pro Spieler.</p><p class='main-text'><b>Die Spieler können nicht vorrücken, falls sich nicht X Ressourcenmarker auf diesem Abenteuer befinden, wobei X gleich 1 plus 2{PerPlayer} ist.</b></p>");
            AddHtml("Ambush-CoE", "<p class='flavor-text'>Ihr habt euch bis zum Herzen des Lagers vorgekämpft, aber die Gesetzlosen sammeln sich um ihren Anführer und bereiten sich auf den Angriff vor.</p><p class='main-text'><b></b> <b>Wenn aufgedeckt:</b> Beendet die aktuelle Phase. Fügt Rädelsführer der Gesetzlosen der Aufmarschzone hinzu. Jeder Spieler, der nicht mit einem Gegner in einen Kampf verwickelt ist, durchsucht das Begegnungsdeck und den Begegnungs-Ablagestapel nach einem Gegner und bringt diesen mit sich in einen Kampf verwickelt ins Spiel. Mischt das Begegnungsdeck.</p>");
            AddHtml2("Ambush-CoE", "<p class='main-text'></b> Sobald ein Gegner das Spiel betritt, legt er Kampfproben ab.</p><p class='main-text'><b>Planungs Aktion:</b> Entferne 5 Fortschrittsmarker von diesem Abenteuer, um eine Karte in einem Beutestapel zu wählen. Der Besitzer der Karte kann sie entweder ablegen oder spielen, ohne ihre Kosten zu bezahlen. Nur viermal pro Runde für die Gruppe.</p><p class='main-text'><b>Sobald der Rädelsführer der Gesetzlosen besiegt ist, gewinnen die Spieler das Spiel.</b></p>");
            AddHtml("Battle-for-the-Hill-CoE", "<p class='flavor-text'>Dunländer und verräterische Rohirrim haben das Leuchtfeuer von Erelas erobert. Erobert den Hügel um jeden Preis zurück!</p><p class='main-text'><b></b> Vorbereitung: Legt Heer aus Rohan als nicht im Spiel befindlich zur Seite. Fügt das Leuchtfeuer von Erelas und 1{PerPlayer} Kopie von Wütender Dunländer der Aufmarschzone hinzu. Fügt das doppelseitige Nebenabenteuer mit der Seite “Das Leuchtfeuer Zurückgewinnen” nach oben der Aufmarschzone hinzu. Durchsucht das Begegnungsdeck nach 1 Kopie von Umliegendes Grasland und bringt diese als aktiven Ort ins Spiel. Mischt das Begegnungsdeck.</p>");
            AddHtml2("Battle-for-the-Hill-CoE", "<p class='main-text'></b> <b>Erzwungen:</b> Nachdem Fortschrittsmarker auf dieses Abenteuer gelegt worden sind, wählt jeder Spieler: Entweder erschöpft er einen spielbereiten Charakter, den er kontrolliert, oder er fügt Leuchtfeuer von Erelas 1 Schaden zu.</p><p class='main-text'><b>Dieses Abenteuer kann nicht bewältigt werden, solange die Dunländer das Leuchtfeuer kontrollieren.</b></p>");
            AddHtml("Hold-the-Hilltop-CoE", "<p class='flavor-text'>Während sich eure Feinde zu einem weiteren Angriff auf das Leuchtfeuer versammeln, könnt ihr die Fackeln von Gálmóds Truppen sehen, die sich inmitten der unteren Hügel zusammenziehen.</p><p class='main-text'><b></b> <b>Wenn aufgedeckt:</b> Legt Fortschrittsmarker auf Verteidigt das Leuchtfeuer (der aktive Ort wird dabei umgangen), bis X Fortschrittsmarker darauf liegen, wobei X gleich 2 plus 1{PerPlayer} ist. Mischt den Begegnungs-Ablagestapel in das Begegnungsdeck. Jeder Spieler legt Karten oben vom Begegnungsdeck ab, bis ein Gegner abgelegt wurde, und fügt diesen Gegner der Aufmarschzone hinzu.</p>");
            AddHtml2("Hold-the-Hilltop-CoE", "<p class='main-text'></b> Zeit 3.</p><p class='main-text'><b>Erzwungen:</b> Fügt dem Leuchtfeuer von Erelas am Ende der Runde 1 Schaden zu (stattdessen 2 Schaden, falls sich 3 oder mehr Spieler im Spiel befinden). Falls sich danach keine Zeitmarker auf diesem Abenteuer befinden, rückt sofort zu Abschnitt 3 vor.</p>");
            AddHtml("The-Last-Push-CoE", "<p class='flavor-text'>Während Gálmóds Streitkräfte den Feind zu flankieren versuchen, müsst ihr euch für den letzten großen Nahkampf wappnen.</p><p class='main-text'><b></b> <b>Wenn aufgedeckt:</b> Entfernt alle Fortschrittsmarker von Verteidigt das Leuchtfeuer und dreht jene Karte um. Bringt Heer von Rohan unter der Kontrolle des Startspielers ins Spiel. Mischt den Begegnungs-Ablagestapel in das Begegnungsdeck. Jeder Spieler legt Karten oben vom Begegnungsdeck ab, bis ein Gegner abgelegt wurde, und fügt diesen Gegner der Aufmarschzone zu.</p>");
            AddHtml2("The-Last-Push-CoE", "<p class='main-text'></b> <b>Erzwungen:</b> Fügt Leuchtfeuer von Erelas zu Beginn der Kampfphase 1 Schaden zu.</p><p class='main-text'><b>Erzwungen:</b> Nachdem ein Charakter das Spiel verlassen hat, fügt Leuchtfeuer von Erelas 1 Schaden zu.</p><p class='main-text'><b>Falls die Dunländer am Ende der Runde das Leuchtfeuer kontrollieren, verlieren die Spieler das Spiel. Falls die Spieler am Ende der Runde das Leuchtfeuer kontrollieren, gewinnen sie das Spiel.</b></p>");
            AddHtml("Thieves-and-Coursers-CoE", "<p class='flavor-text'>Orks sind in die Ostfold eingedrungen, haben das Land heimgesucht und König Thengels geliebte Kriegspferde gestohlen.</p><p class='main-text'><b>Vorbereitung:</b> Fügt Gestohlene Rosse der Aufmarschzone hinzu. Legt Thruk, die <b><i>Reittier</i></b>-Zielkarten und die 8 Gegner aus dem Orkstreitmacht-Begegnungsset als nicht im Spiel befindlich beiseite. Mischt das Begegnungsdeck. Der Startspieler deckt Feuersteinhuf und Leuchtmähne auf und fügt sie der Aufmarschzone hinzu. Danach legt jeder Spieler Karten oben vom Begegnungsdeck ab, bis ein Ort oder Gegner abgelegt wurde, und fügt ihn zur Aufmarschzone hinzu.</p>");
            AddHtml2("Thieves-and-Coursers-CoE", "<p class='flavor-text'>Wenn ihr Feuersteinhuf und Leuchtmähne retten könnt, seid ihr vielleicht in der Lage, die Orkstreitmacht zu stoppen, bevor sie Aldburg erreicht.</p><p class='main-text'>Dieser Abschnitt kann nicht bewältigt werden, solange die Spieler nicht mindestens 2 Reittier-Zielkarten kontrollieren.</b></p>");
            AddHtml("The-King's-Stallion-CoE", "<p class='flavor-text'>Kriegshäuptling Thruk betritt das Schlachtfeld. Auf seinem mächtigen Pferd Felaróf reitend, brüllt er Befehle an seine Horden. “Sammelt euch!”, ruft er. “Heute Abend essen wir Pferdefleisch!”</p><p class='main-text'><b></b> <b>Wenn aufgedeckt:</b> Falls die Kampfphase die aktuelle Phase ist, beendet die Phase. Mischt den Begegnungs-Ablagestapel in das Begegnungsdeck. Der Startspieler fügt Thruk der Aufmarschzone hinzu und hängt Felaróf an ihn als bewachte Zielkarte an. Jeder andere Spieler legt Karten oben vom Begegnungsdeck ab, bis ein Gegner abgelegt wurde, und bringt diesen mit sich in einen Kampf verwickelt ins Spiel.</p>");
            AddHtml2("The-King's-Stallion-CoE", "<p class='main-text'></b> Thruk kann keinen Schaden erleiden, solange sich nicht mindestens 4 Fortschrittsmarker auf diesem Abschnitt befinden.</p>");
            AddHtml("The-Sweeping-Tide-CoE", "<p class='flavor-text'>Die volle Macht der Orkstreitmacht hat sich hinter Thruk gesammelt. Euer letzter verzweifelter Vorstoß wird sie in die Hügel treiben.</p><p class='main-text'><b></b> <b>Wenn aufgedeckt:</b> Falls die Kampfphase die aktuelle Phase ist, beendet die Phase. Mischt den Begegnungs-Ablagestapel in das Begegnungsdeck. Durchsucht den Stapel beanspruchter Siegpunkte nach Thruk und fügt ihn der Aufmarschzone hinzu. Jeder Spieler wählt 2 Gegner aus den beiseitegelegten Orkstreitmacht-Karten und bringt sie mit sich in einen Kampf verwickelt ins Spiel. Durch diesen Effekt muss Ork-Bataillon ins Spiel gebracht werden.</p>");
            AddHtml2("The-Sweeping-Tide-CoE", "<p class='main-text'></b> Überspringt den Aufmarschschritt. Sobald das Begegnungsdeck leer ist, mischt den Begegnungs-Ablagestapel in das Begegnungsdeck.</p>");
            //AddHtml("Reclaim-the-Beacon-CoE", "<p class='main-text'>Die Spieler kontrollieren das Leuchtfeuer. Schattenkarten sind immun gegen Spielerkarteneffekte.</p><p class='main-text'>Verteidigt das Leuchtfeuer kann nicht mehr als X Fortschrittsmarker erhalten, wobei X gleich 2 plus 1{PerPlayer} ist.</p><p class='main-text'><b>Reaktion:</b> Entfernt eine beliebigen Anzahl Fortschrittsmarker von Verteidigt das Leuchtfeuer, um eine gleiche Anzahl Schaden, der dem Leuchtfeuer von Erelas zugefügt wird, zu verhindern. Falls sich danach 0 Fortschrittsmarker auf Verteidigt das Leuchtfeuer befinden, drehe diese Karte um.</p>");

        }

        private void TheAldburgPlot()
        {
            AddHtml("Fatty-Bolger-TAP", "<p class='main-text'><b>Vorbereitung:</b> Reduziere deine Bedrohung um 2.</p><p class='main-text'><b>Reaktion:</b> Erhöhe deinen Bedrohungsgrad um 4 und erschöpfe Dick Bolger, um eine nicht-einzigartige Gegner-Karte, die gerade vom Begegnungsdeck aufgedeckt wurde, zu verhindern und sie dem Stapel beanspruchter Siegpunkte hinzuzufügen. (Nur einmal pro Spiel für die Gruppe.)</p><p class='flavor-text'>Dick Bolger war nicht müßig gewesen. Kaum hatte er die dunklen Schatten vom Garten herankriechen sehen, da wusste er, dass er rennen musste, wenn ihm sein Leben lieb war. —Die Gefährten</p>");
            AddHtml("Widfast-TAP", "<p class='main-text'><b>Vorbereitung:</b> Durchsuche deine Sammlung nach einem <b><i>Kreatur</i></b>-Verbündeten und füge ihn deiner Hand hinzu. Senke für die erste Runde seine Kosten um 2.</p><p class='main-text'><b>Reiseaktion:</b> Falls es 1 aktiven Ort gibt, gib 1 Ressource aus Widfasts Ressourcenvorrat aus, um zu einem anderen Ort zu reisen und den Reiseeffekt abzuhandeln. (Es gibt jetzt 2 aktive Orte.)</p>");
            AddHtml("Lily-Cotton-TAP", "<p class='main-text'><b>Aktion:</b> Erschöpfe Lily Hüttinger, um einen anderen <b><i>Hobbit</i></b>-Verbündeten spielbereit zu machen und Lily Hüttingers {Willpower}, {Attack} und {Defense} zur {Willpower}, {Attack} und {Defense} dieses Verbündeten hinzuzufügen. Falls dieser Verbündete am Ende der Phase noch im Spiel ist, gib ihn auf die Hand seines Besitzers zurück. (Nur einmal pro Phase.)</p><p class='flavor-text'>Es ist wenig, sozusagen gar nichts, von Zauberei an ihnen, ausgenommen die alltägliche Gabe, rasch und lautlos zu<br/>verschwinden … —Der kleine Hobbit</p>");
            AddHtml("A-Lesson-in-Caution-TAP", "<p class='main-text'>Heimlichkeit 1.</p><p class='main-text'><b>Aktion:</b> Ziehe 1 Karte. Reduziere dann entweder deine Bedrohung um 2 oder die nächste Karte, die du in dieser Phase spielst, erhält Heimlichkeit 1.</p><p class='flavor-text'>Hobbits haben einen leichten Schritt, und selbst für einen Waldläufer sind ihre Fußspuren nicht leicht zu lesen … —Die zwei Türme</p>");
            AddHtml("There-and-Back-Again-TAP", "<p class='main-text'>Heimlichkeit 1.</p><p class='main-text'><b>Reaktion:</b> Nachdem ein <b><i>Hobbit</i></b>-Verbündeter das Spiel verlassen hat, durchsuche deine Hand und deinen Ablagestapel nach einer Kopie dieses Verbündeten und bringe ihn unter der Kontrolle eines beliebigen Spielers ins Spiel.</p><p class='flavor-text'>“Die gesetzlichen Schwierigkeiten konnten jahrelang nicht aus der Welt geschafft werden, und die Erlaubnis, wieder als durchaus lebendig zu gelten, ließ lange auf sich warten.”<br/>—Der kleine Hobbit</p>");
            AddHtml("Buckland-Shirriff-TAP", "<p class='main-text'>Treu. Fernkampf.</p><p class='main-text'><b>Reaktion:</b> Nachdem ein Gegner, der ein <b><i>Merkmal</i></b> mit einem Gegner im Stapel beanspruchter Siegpunkte gemeinsam hat, der Aufmarschzone hinzugefügt worden ist, gib 1 {sphere:Lore}-Ressource aus, um Landbüttel von Bockland von deiner Hand unter deiner Kontrolle ins Spiel zu bringen.</p>");
            AddHtml("Weep-No-More-TAP", "<p class='main-text'>Es dürfen sich maximal drei Kopien von Weint nicht mehr! im Stapel beanspruchter Siegpunkte befinden.</p><p class='main-text'><b>Reaktion:</b> Nachdem der ‚Wenn aufgedeckt‘-Effekt oder Schatteneffekt einer Verratskarte abgehandelt worden ist, füge Weint nicht mehr! dem Stapel beanspruchter Siegpunkte hinzu, um diese Verratskarte dem Stapel beanspruchter Siegpunkte hinzuzufügen.</p><p class='flavor-text'>“Mag sein, dass wir noch Rache nehmen können. Wir wollen uns gürten und nicht mehr weinen!” —Aragorn, Die Gefährten</p>");
            AddHtml("Fear-Fire-Foes-TAP", "<p class='main-text'>Heimlichkeit 1. Spiele diese Karte nur, wenn du keinen <b><i>Krieger</i></b>-Helden kontrollierst.</p><p class='main-text'><b>Aktion:</b> Wähle einen nicht-einzigartigen Gegner und ein Attribut ({Threat}, {Attack} oder {Defense}). Senke bis zum Ende der Phase das gewählte Attribut dieses Gegners auf 0.</p><p class='flavor-text'>Weit in der Ferne hörte man antwortende Hörner. Der Alarm wurde weitergegeben. —Die Gefährten</p>");
            AddHtml("Horn-call-of-Buckland-TAP", "<p class='main-text'>Hänge diese Karte an einen {sphere:Lore}- oder <b><i>Hobbit</i></b>-Helden an.</p><p class='main-text'><b>Reaktion:</b> Nachdem du einen Gegner, der ein <b><i>Merkmal</i></b> mit einem Gegner im Stapel beanspruchter Siegpunkte gemeinsam hat, in einen Kampf verwickelt hast, erschöpfe Hornruf von Bockland, um den Helden mit dieser Verstärkung spielbereit zu machen. Danach erhält dieser Gegner −1 {Attack} und −1 {Defense} bis zum Ende der Runde.</p><p class='flavor-text'>In diesem Augenblick erklang zwischen den Bäumen nahebei ein Horn. Es zerriss die Nacht wie Feuer auf einem Berggipfel.<br/>—Die Gefährten</p>");
            AddHtml("Young-Tom-TAP", "<p class='main-text'>In der Runde, in der Junger Tom ins Spiel gekommen ist, erhalten Gegner +5 Kampfbereitschaft.</p><p class='flavor-text'>“Nicht alles ist gut dort”, sagte Frodo, “doch Gärtner werden allerdings geehrt.” —Die zwei Türme</p>");
            AddHtml("Gavin-TAP", "<p class='main-text'>Kann keine Verstärkungen haben.</p><p class='main-text'><b>Reaktion:</b> Nachdem der Aufmarsch einer Begegnungskarte ohne Nachrüsten abgehandelt worden ist, erschöpfe Gavin, um dieser Karte Nachrüsten zu geben und 1 Ressource zum Ressourcenvorrat eines <b><i>Späher</i></b>-Helden unter deiner Kontrolle hinzuzufügen. Wenn die nächste aufgedeckt Begegnungskarte kein Ort ist, lege sie ab, ohne ihre Effekte abzuhandeln.</p>");
            AddHtml("Red-Harvest-TAP", "<p class='flavor-text'>Mit ungeheurer Geschwindigkeit fallen die Männer der Flüsterin über euch her. Ihr müsst euch mit allen Mitteln verteidigen, um die Rüstkammer zu erreichen.</p><p class='main-text'><b>Erzwungen:</b> Nachdem ein Gegner einen Spieler in einen Kampf verwickelt hat, fügt dieser Spieler einem Charakter unter seiner Kontrolle 2 Schaden zu.</p><p class='main-text'><b>Erzwungen:</b> Nachdem dieser Abschnitt bewältigt worden ist, mischt den Begegnungs-Ablagestapel in das Begegnungsdeck. Jeder Spieler legt Karten oben vom Begegnungsdeck ab, bis ein Gegner abgelegt worden ist, und fügt diesen Gegner der Aufmarschzone hinzu. Fügt Die Rüstkammer der Aufmarschzone hinzu.</p>{victory:10}");
            AddHtml("The-Prisoner-in-White-TAP", "<p class='flavor-text'>Um seine Spuren zu verwischen, hat sich der Gehilfe des Meisters der Spione in das Gefängnis eingeschlichen.</p><p class='main-text'>Die Spieler können nicht zu Orten reisen oder Orte durch Spielerkarteneffekte zum aktiven Ort machen.</p><p class='main-text'><b>Erzwungen:</b> Nachdem dieser Abschnitt bewältigt worden ist, fügt Ossian der Aufmarschzone hinzu.</p>{victory:10}");
            AddHtml("The-Man-with-the-Twisted-Lip-TAP", "<p class='flavor-text'>Ihr habt begonnen, den geheimnisvollen Meister der Spione von Aldburg aufzuspüren, auch wenn es schwierig ist, zu sagen, wer von euch die Katze und wer die Maus ist.</p><p class='main-text'><b>Erzwungen:</b> Erhöht am Ende der Runde den Bedrohungsgrad jedes Spielers um 1.</p><p class='main-text'><b>Erzwungen:</b> Nachdem dieser Abschnitt bewältigt worden ist, fügt Der Meister der Spione der Aufmarschzone hinzu.</p>{victory:10}");
            AddHtml("A-Fire-Rises-TAP", "<p class='flavor-text'>Etwas Böses ist in Aldburg im Gange. Als ihr gerade die einzelnen Teile zusammenzusetzen beginnt, seht ihr Feuer und Rauch aus einem nahen Gebäude schlagen.</p><p class='main-text'>Erhöht die Ausspielkosten für jedes Ereignis um 1.</p><p class='main-text'><b>Erzwungen:</b> Nachdem dieser Abschnitt bewältigt worden ist, deckt Sich ausbreitende Feuersbrunst auf.</p>{victory:10}");
            AddHtml("A-Case-of-Identity-TAP", "<p class='flavor-text'>Die Identität der Flüsterin bleibt ein Geheimnis. Ihren Mordgesellen nach zu urteilen, die in den Gassen herumschleichen, seid ihr auf der richtigen Spur.</p><p class='main-text'><b>Erzwungen:</b> Legt am Ende des Aufmarschschrittes Karten oben vom Begegnungsdeck ab, bis 1 Gegner abgelegt worden ist. Deckt diesen Gegner auf.</p><p class='main-text'><b>Erzwungen:</b> Nachdem dieser Abschnitt bewältigt worden ist, fügt Große Met-Halle der Aufmarschzone hinzu.</p>{victory:10}");
            AddHtml("Whisperer-in-the-Darkness-TAP", "<p class='flavor-text'>Die Spelunke war voll von Gerüchten über eine Attentäterin, die “Die Flüsterin” genannt wird. Wenn ihr dieses Geheimnis lüften wollt, werdet ihr sie finden und aufhalten müssen, ehe sie zuschlägt.</p><p class='main-text'><b>Erzwungen:</b> Nachdem ein Ort erkundet worden ist, erhöht den Bedrohungsgrad jedes Spielers um 1.</p><p class='main-text'><b>Erzwungen:</b> Nachdem dieser Abschnitt bewältigt worden ist, fügt Die Flüsterin der Aufmarschzone hinzu.</p>{victory:10}");
            AddHtml("Spreading-Inferno-TAP", "<p class='main-text'>Bewacht (Ort).</p><p class='main-text'><b>Erzwungen:</b> Legt zu Beginn der Reisephase den Ort, an den diese Karte angehängt ist, ab, erhöht den Bedrohungsgrad jedes Spielers um 1 und legt den Verbündeten mit den niedrigsten Kosten unter der Kontrolle jedes Spielers ab. Deckt Sich ausbreitende Feuersbrunst auf.</p><p class='main-text'><b>Erzwungen:</b> Sobald der Ort mit dieser Verstärkung erkundet ist, dreht diese Karte um und deckt sie auf.</p>");
            AddHtml("The-Whisperer-TAP", "<p class='main-text'><b>Erzwungen:</b> Legt am Ende der Runde wenn möglich Die Flüsterin zurück in die Aufmarschzone. Die Flüsterin führt sofort einen Angriff gegen den Startspieler durch. Schaden, der durch diesen Angriff zugefügt wird, erhöht stattdessen die Bedrohung des Startspielers um denselben Wert.</p><p class='main-text'><b>Erzwungen:</b> Sobald Die Flüsterin besiegt worden ist, dreht diese Karte um und deckt sie auf.</p>");
            AddHtml("The-Spy-Master-TAP", "<p class='main-text'><b>Erzwungen:</b> Sobald Der Meister der Spione eine Schattenkarte ohne Schatteneffekt zugeteilt worden ist, füge dem verteidigenden Charakter 1 Schaden zu und teile Der Meister der Spione eine zusätzliche Schattenkarte zu. (Nur 2 Mal pro Angriff.)</p><p class='main-text'><b>Erzwungen:</b> Nachdem Der Meister der Spione besiegt worden ist, dreht diese Karte um und deckt sie auf.</p>");
            AddHtml("Ossian-TAP", "<p class='main-text'>Immun gegen Spielerkarteneffekte. Ossian kann nicht mehr als X Schaden pro Runde nehmen, wobei X die Anzahl der <b><i>Hinweis</i></b>-Ziele unter der Kontrolle der Spieler ist.</p><p class='main-text'><b>Erzwungen:</b> Sobald Ossian besiegt worden ist, dreht diese Karte um und deckt sie auf.</p><p class='flavor-text'>Ihr findet Ossian über eine weißgekleidete Leiche gebeugt. Als er euch herankommen hört, dreht er sich um.</p>");
            AddHtml("Garrison-Barracks-TAP", "<p class='main-text'>Immun gegen Spielerkarteneffekte. X ist zweimal die Zahl der <b><i>Hinweis</i></b>-Ziele unter der Kontrolle der Spieler.</p><p class='main-text'><b>Reise:</b> Mischt alle beiseitegelegten <b><i>Dunland</i></b>-Gegner in das Begegnungsdeck.</p><p class='main-text'><b>Erzwungen:</b> Sobald Garnisonskaserne erkundet worden ist, dreht diese Karte um und deckt sie auf.</p><p class='flavor-text'>Die Stadtwache hat ihre Augen und Ohren überall in Aldburg. Aber wer beobachtet sie?</p>");
            AddHtml("The-Horse's-Tail-TAP", "<p class='main-text'>Immun gegen Spielerkarteneffekte. X ist zweimal die Zahl der <b><i>Hinweis</i></b>-Ziele unter der Kotrolle der Spieler.</p><p class='main-text'><b>Reise:</b> Mischt alle beiseitegelegten <b><i>Garnison</i></b>-Gegner in das Begegnungsdeck.</p><p class='main-text'><b>Erzwungen:</b> Sobald Zum Pferdeschwanz erkundet worden ist, dreht diese Karte um und deckt sie auf.</p><p class='flavor-text'>Ihr könntet zwar die Aufmerksamkeit der Stadtwache auf euch ziehen, aber dieses Rätsel wird sich nicht auf gewöhnlichem Wege lösen lassen.</p>");
            AddHtml("The-Armoury-TAP", "<p class='main-text'>Immun gegen Spielerkarteneffekte.</p><p class='main-text'><b>Reise:</b> Jeder Spieler muss den spielbereiten Charakter mit der höchsten {Defense} unter seiner Kontrolle erschöpfen.</p><p class='main-text'><b>Erzwungen:</b> Sobald Die Rüstkammer erkundet worden ist, dreht diese Karte um und deckt sie auf.</p><p class='flavor-text'>Die Flüsterin hat einen unverwechselbaren Dolch benutzt, der euch bekannt vorkommt. Vielleicht kann euch der Zeugmeister der Rüstkammer mehr darüber erzählen.</p>");
            AddHtml("Great-Mead-Hall-TAP", "<p class='main-text'>Immun gegen Spielerkarteneffekte.</p><p class='main-text'><b>Reise:</b> Die Spieler müssen ihre Bedrohung um X erhöhen, wobei X die Anzahl der Gegner in der Aufmarschzone ist.</p><p class='main-text'><b>Erzwungen:</b> Sobald Große Met-Halle erkundet worden ist, dreht diese Karte um und deckt sie auf.</p><p class='flavor-text'>Ihr habt die Spuren der Spione der Flüsterin bis hin zu den Hallen des Marschalls Éomund verfolgt. Wie tief reicht diese Verschwörung?</p>");
            AddHtml("Town-Guard-TAP", "<p class='main-text'>Falls die Spieler 2 oder mehr <b><i>Hinweis</i></b>-Ziele kontrollieren, erhält Stadtwache +2 {Threat}.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Stadtwache angegriffen und einen Charakter unter deiner Kontrolle getötet hat, lege 1 Ressource aus dem Ressourcenvorrat jedes Helden unter deiner Kontrolle mit einem angehängten <b><i>Hinweis</i></b>-Ziel ab.</p><p class='flavor-text'>“Ist meine Hoffnung vergebens, dass Ihr mir gesandt seid als eine Hilfe in Zweifel und Not?” —Éomer, Die zwei Türme</p>");
            AddHtml("Dunlending-Agents-TAP", "<p class='main-text'>Falls die Spieler 2 oder mehr <b><i>Hinweis</i></b>-Ziele kontrollieren, erhält Spione aus Dunland +2 {Attack}.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Spione aus Dunland angegriffen und einen Charakter unter deiner Kontrolle getötet hat, füge jedem Helden unter deiner Kontrolle mit einem angehängten <b><i>Hinweis</i></b>-Ziel 1 Schaden zu.</p><p class='flavor-text'>Die Dunländer und viele Männer der Besatzung der Burg waren am Deich oder auf den Feldern und den beschädigten Mauern dahinter an der Arbeit. —Die Rückkehr des Königs</p>");
            AddHtml("Aldburg-Malcontent-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Falls die Spieler 3 oder mehr <b><i>Hinweis</i></b>-Ziele kontrollieren, erhält Unzufriedener aus Aldburg Nachrüsten.</p>{shadow}<p class='shadow-text'><b>Schatten:</b> Falls die Spieler 2 oder mehr <b><i>Hinweis</i></b>-Ziele kontrollieren, lege den angreifenden Gegner nach diesem Angriff in die Aufmarschzone zurück.</p>");
            AddHtml("Misty-Street-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Legt alle Verstärkungen und alle Marker vom Verbündeten mit den höchsten Kosten unter der Kontrolle des Startspielers ab und hängt ihn verdeckt an Neblige Straße an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem Neblige Straße erkundet worden ist, bringt den angehängten Verbündeten unter der Kontrolle seines Besitzers aufgedeckt und spielbereit ins Spiel.</p>{shadow}<p class='shadow-text'><b>Schatten:</b> Lege eine Nicht-<b><i>Hinweis</i></b>-Verstärkung unter deiner Kontrolle ab.</p>");
            AddHtml("Well-lit-Hall-TAP", "<p class='main-text'>Solange sich Gut beleuchtete Halle in der Aufmarschzone befindet, können nicht mehr als 3 Fortschrittsmarker auf eine Abenteuerkarte gelegt werden, nachdem sich die Spieler erfolgreich dem Abenteuer gestellt haben.</p>{shadow}<p class='shadow-text'><b>Schatten:</b> Der angreifende Gegner erhält +1 {Attack}. (+2 {Attack} stattdessen, wenn an den verteidigenden Charakter eine <b><i>Hinweis</i></b>-Verstärkung angehängt ist.)</p>");
            AddHtml("Decrepit-Hovel-TAP", "<p class='main-text'>Die Ressourcenkosten für Verbündete müssen aus dem Vorrat eines einzelnen Helden gezahlt werden.</p>{shadow}<p class='shadow-text'><b>Schatten:</b> Lege 1 Ressource aus dem Vorrat eines Helden unter deiner Kontrolle ab.</p><p class='flavor-text'>“Aber von da aus streifen sie rum, stehlen oder ‚sammeln‘, wie sie es nennen.”<br/>—Tom Hüttinger, Die Rückkehr des Königs</p>");
            AddHtml("Taken-by-the-Night-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Jeder Spieler muss den Verbündeten mit den niedrigsten aufgedruckten Kosten unter seiner Kontrolle ablegen. Wenn auf diese Weise keine Verbündeten mit aufgedruckten Kosten von 2 oder höher abgelegt wurden, erhält Von der Nacht genommen Nachrüsten.</p>{shadow}<p class='shadow-text'><b>Schatten:</b> Der angreifende Gegner erhält +1 {Attack}. (+2 {Attack} stattdessen, wenn der Gegner aus der Aufmarschzone heraus angreift.)</p>");
            AddHtml("False-Lead-TAP", "<p class='main-text'>Verflucht 1.</p><p class='main-text'><b>Wenn aufgedeckt:</b> Jeder Spieler entfernt wenn möglich einen Helden unter seiner Kontrolle mit einem angehängten <b><i>Hinweis</i></b>-Ziel vom Abenteuer. Dann erschöpft jeder Spieler einen Helden unter seiner Kontrolle, der sich nicht dem Abenteuer stellt.</p><p class='flavor-text'>“… versucht Ihr jetzt, mich mit einer Lüge in die Falle zu locken?” —Frodo Beutlin, Die zwei Türme</p>");
            AddHtml("Sudden-Ambush-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Der Startspieler muss wählen: Erhöhe entweder deine Bedrohung um 4, oder der oberste Gegner im Begegnungs-Ablagestapel verwickelt dich in einen Kampf und führt sofort einen Angriff durch. Du musst, wenn möglich, den spielbereiten Charakter mit der höchsten {Willpower} unter deiner Kontrolle zum Verteidiger gegen diesen Angriff erklären.</p>{shadow}<p class='shadow-text'><b>Schatten:</b> Handle den ‚Wenn aufgedeckt‘-Effekt dieser Karte ab.</p>");
            AddHtml("Evil-Under-the-Moon-TAP", "<p class='flavor-text'>Mit dem Wissen, dass eine Gruppe Aufständischer ihren Sitz in Aldburg genommen hat, bittet euch Ealdwulf, sie aufzuspüren.</p><p class='main-text'><b></b> Vorbereitung: Legt jedes Begegnungs-Nebenabenteuer, jede Kopie von Stadtwache und jede Kopie von Spione aus Dunland als nicht im Spiel befindlich beiseite. Legt jede doppelseitige Begegnungskarte mit der <b><i>Hinweis</i></b>-Seite nach unten als nicht im Spiel befindlich beiseite. Fügt Garnisonskaserne und Zum Pferdeschwanz der Aufmarschzone hinzu. Durchsucht das Begegnungsdeck nach 1 Gegner und fügt ihn der Aufmarschzone hinzu (stattdessen nach 2 unterschiedlichen Gegnern, wenn 3 oder mehr Spieler im Spiel sind). Mischt das Begegnungsdeck. <b></p>");
            AddHtml2("Evil-Under-the-Moon-TAP", "<p class='flavor-text'>Wo sollt ihr mit der Jagd beginnen? Ersucht ihr die Stadtwache um Hilfe oder untersucht ihr die kriminelle Unterwelt in einer zwielichtigen Spelunke?</p><p class='main-text'></b> Gegner können nicht freiwillig in einen Kampf verwickelt werden.</p><p class='main-text'><b>Erzwungen:</b> Erhöht am Ende der Runde den Bedrohungsgrad jedes Spielers um 1.</p><p class='main-text'><b>Wenn die Spieler 1 oder mehr <b><i>Hinweis</i></b>-Ziel kontrollieren, rückt zum nächsten Abschnitt vor.</b></p>");
            AddHtml("Gathering-Clues-TAP", "<p class='flavor-text'>Die rohirrische Stadt von Aldburg scheint voller Geheimnisse zu sein. Hinter jeder Ecke wartet ein neues Rätsel, und hinter jedem Rätsel steckt eine scharfe Klinge der Verzweiflung. Ihr werdet noch vor Sonnenaufgang weiter vordringen müssen, wenn ihr die Wahrheit herausfinden wollt.</p><p class='main-text'></p>");
            AddHtml2("Gathering-Clues-TAP", "<p class='flavor-text'>Es scheint, dass Aldburg die Heimstatt eines doppelgesichtigen Geheimnisses ist. Wenn ihr nur einen einzigen Faden zu fassen bekommen könntet, könntet ihr vielleicht dieses verdorbene und grausame Netz entwirren. Es ist nach Mitternacht. Die Zeit wird knapp.</p><p class='main-text'></b> <b>Reaktion</b>: Falls die Spieler am Ende der Runde mindestens 4 <b><i>Hinweis</i></b>-Zielkarten kontrollieren, dürfen sie zu Abschnitt 3A vorrücken.</p>");
            AddHtml("The-Uncertain-Dawn-TAP", "<p class='flavor-text'>Als die Sonne über den Straßen von Aldburg aufgeht, zeigen eure in die Enge getriebenen Feinde ihr wahres Gesicht. Ihr habt die Hinweise gesammelt. Nutzt sie jetzt, während ihr um euer Leben kämpft – und um die Seele Rohans.</p><p class='main-text'><b></b> <b>Wenn aufgedeckt:</b> Entfernt alle <b><i>Verdächtig</i></b>-Karten und Begegnungs-Nebenabenteuer aus dem Spiel. Fügt wenn möglich jeden beiseitegelegten <b><i>Dunland</i></b>- oder <b><i>Garnison</i></b>-Gegner der Aufmarschzone hinzu. <b></p>");
            AddHtml2("The-Uncertain-Dawn-TAP", "<p class='main-text'></b> Eine ungewisse Dämmerung erhält −5 Abenteuerpunkte für jedes <b><i>Hinweis</i></b>-Ziel, das die Spieler kontrollieren.</p><p class='main-text'><b>Erzwungen:</b> Zu Beginn der Abenteuerphase legt Karten oben vom Begegnungsdeck ab, bis ein Gegner abgelegt wurde. Deckt diesen Gegner auf und fügt ihn der Aufmarschzone hinzu.</p><p class='main-text'><b>Dieser Abschnitt kann nur am Ende der Runde bewältigt werden. Falls die Spieler diesen Abschnitt bewältigen, gewinnen sie das Spiel.</b></p>");
            AddHtml("Spreading-Inferno-TAP", "<p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, lege die obersten 4 Karten deines Decks ab.</p><p class='flavor-text'>Zwischen all der Asche erkennt ihr diese Fibel sofort: Sie gehört dem Hundesohn Gálmód, Königin Morwens “vertrautem” Berater.</p>");
            AddHtml("The-Whisperer-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt Eine Frage der Identität und Rote Ernte der Aufmarschzone hinzu.</p><p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, füge ihm 1 Schaden zu.</p><p class='flavor-text'>Die Flüsterin ist in die Straßen von Aldburg entkommen, aber sie hat eine unverwechselbare und teure Waffe zurückgelassen.</p>");
            AddHtml("The-Spy-Master-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt Ein Feuer bricht aus und Der Gefangene in Weiß der Aufmarschzone hinzu.</p><p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, lege eine Nicht-<b><i>Hinweis</i></b>-Verstärkung von ihm ab.</p><p class='flavor-text'>Verwundet und kriechend, um vielleicht doch noch zu entkommen, scheidet der Meister der Spione mit einem wichtigen Hinweis von euch: Einer seiner Spione ist bereits auf dem Weg zum Stadtgefängnis.</p>");
            AddHtml("Ossian-TAP", "<p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, lege 1 zufällige Karte von deiner Hand ab.</p><p class='flavor-text'>Mit seinem letzten Atemzug enthüllt euch Ossian, dass Gálmód ihm befohlen hatte, ein Mitglied seiner eigenen Éored zu erschlagen, das Zeuge eines schrecklichen Verrats geworden war.</p>");
            AddHtml("Garrison-Barracks-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt Der Mann mit der entstellten Lippe der Aufmarschzone hinzu.</p><p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, lege alle Ressourcen aus seinem Ressourcenvorrat ab.</p><p class='flavor-text'>Der Gefangene hat den Wachen von einem Strippenzieher erzählt, der “Der Meister der Spione” genannt wird. Die einzige Spur ist im Augenblick dieser Ring, der vermutlich ihm gehört.</p>");
            AddHtml("The-Horse's-Tail-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt Die Flüsterin der Aufmarschzone hinzu.</p><p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, erschöpfe einen anderen Charakter, den du kontrollierst.</p><p class='flavor-text'>Eine unbekannte Gestalt stößt an euren Tisch. Unter übermäßigen Entschuldigungsbekundungen stolpert sie in die Nacht. Als ihr den Beutel voller Münzen bemerkt, den sie zurückgelassen hat, ist sie bereits verschwunden.</p>");
            AddHtml("The-Armoury-TAP", "<p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, erhöhe deine Bedrohung um 1.</p><p class='flavor-text'>Der Zeugmeister der Rüstkammer erklärt euch, dass er diesen Dolch wie auch den ungewöhnlichen Pfeil persönlich für den Herrn Gálmód angefertigt hat.</p>");
            AddHtml("Great-Mead-Hall-TAP", "<p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, entferne 2 Fortschrittsmarker von jedem Ort und jeder Abenteuerkarte.</p><p class='flavor-text'>Ihr findet einen versteckten Brief, der in gebrochenem Rohirrisch geschrieben und mit “Grimrede” unterzeichnet ist. Er ist an einen Mann gerichtet, den ihr für euren Freund hieltet – Gálmód.</p>");

            AddHtml("Ruby-Cloak-pin-TAP", "<p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, lege die obersten 4 Karten deines Decks ab.</p><p class='flavor-text'>Zwischen all der Asche erkennt ihr diese Fibel sofort: Sie gehört dem Hundesohn Gálmód, Königin Morwens “vertrautem” Berater.</p>");
            AddHtml("Silver-Dagger-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt Eine Frage der Identität und Rote Ernte der Aufmarschzone hinzu.</p><p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, füge ihm 1 Schaden zu.</p><p class='flavor-text'>Die Flüsterin ist in die Straßen von Aldburg entkommen, aber sie hat eine unverwechselbare und teure Waffe zurückgelassen.</p>");
            AddHtml("Prison-Key-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt Ein Feuer bricht aus und Der Gefangene in Weiß der Aufmarschzone hinzu.</p><p class='main-text'>\r\nFalls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, lege eine Nicht-<b><i>Hinweis</i></b>-Verstärkung von ihm ab.</p><p class='flavor-text'>Verwundet und kriechend, um vielleicht doch noch zu entkommen, scheidet der Meister der Spione mit einem wichtigen Hinweis von euch: Einer seiner Spione ist bereits auf dem Weg zum Stadtgefängnis.</p>");
            AddHtml("Traitor's-Confession-TAP", "<p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, lege 1 zufällige Karte von deiner Hand ab.</p><p class='flavor-text'>Mit seinem letzten Atemzug enthüllt euch Ossian, dass Gálmód ihm befohlen hatte, ein Mitglied seiner eigenen Éored zu erschlagen, das Zeuge eines schrecklichen Verrats geworden war.</p>");
            AddHtml("Raven-Signet-Ring-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt Der Mann mit der entstellten Lippe der Aufmarschzone hinzu.</p><p class='main-text'>\r\nFalls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, lege alle Ressourcen aus seinem Ressourcenvorrat ab.</p><p class='flavor-text'>Der Gefangene hat den Wachen von einem Strippenzieher erzählt, der “Der Meister der Spione” genannt wird. Die einzige Spur ist im Augenblick dieser Ring, der vermutlich ihm gehört.</p>");
            AddHtml("Rohirric-Coins-TAP", "<p class='main-text'><b>Wenn aufgedeckt:</b> Fügt Die Flüsterin der Aufmarschzone hinzu.</p><p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, erschöpfe einen anderen Charakter, den du kontrollierst.</p><p class='flavor-text'>Eine unbekannte Gestalt stößt an euren Tisch. Unter übermäßigen Entschuldigungsbekundungen stolpert sie in die Nacht. Als ihr den Beutel voller Münzen bemerkt, den sie zurückgelassen hat, ist sie bereits verschwunden.</p>");
            AddHtml("Red-Fletched-Arrow-TAP", "<p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, erhöhe deine Bedrohung um 1.</p><p class='flavor-text'>Der Zeugmeister der Rüstkammer erklärt euch, dass er diesen Dolch wie auch den ungewöhnlichen Pfeil persönlich für den Herrn Gálmód angefertigt hat.</p>");
            AddHtml("Letter-from-Dunland-TAP", "<p class='main-text'>Falls diese Karte nicht angehängt ist, hängt sie an den Helden mit den wenigsten angehängten <b><i>Hinweis</i></b>-Zielen an.</p><p class='main-text'><b>Erzwungen:</b> Nachdem der Held mit dieser Verstärkung spielbereit gemacht worden ist, entferne 2 Fortschrittsmarker von jedem Ort und jeder Abenteuerkarte.</p><p class='flavor-text'>Ihr findet einen versteckten Brief, der in gebrochenem Rohirrisch geschrieben und mit “Grimrede” unterzeichnet ist. Er ist an einen Mann gerichtet, den ihr für euren Freund hieltet – Gálmód.</p>");
        }
    }
}
