using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Services.LotR.Templates
{
    public class ItalianTemplateRepository
        : TemplateRepository
    {
        protected override void Initialize()
        {
            //Children of Eorl
            AddHtml("Ingold-CoE", "<p class='main-text'><b>Risposta:</b> Dopo che un alleato <b><i>Gondor</i></b> o <b><i>Guerriero</i></b> è entrato in gioco sotto il tuo controllo, pesca 1 carta. Poi, spendi una risorsa dalla riserva di Ingold oppure incrementa di 1 la tua minaccia. (Solo una volta per fase.)</p><p class='flavor-text'>“Non desideriamo stranieri nel nostro paese, in questi tempi, a meno che non si tratti di poderosi uomini d’arme fedeli e valorosi.”<br/>—Il Ritorno del Re</p>");
            AddHtml("Celador-CoE", "<p class='main-text'>Gittata.</p><p class='main-text'>Riduci di 1 la {Threat} totale dell’area di allestimento per ogni <b><i>Trappola</i></b> non aggregata che controlli.</p><p class='main-text'>Risposta: Dopo che una carta <b><i>Trappola</i></b> che controlli viene aggregata a un nemico, rendi pronto Celador oppure riduci di 1 la tua minaccia.</p><p class='flavor-text'>“Un uomo saggio non si fida degli incontri casuali fatti lungo le strade di questo paese.” —Faramir, Le Due Torri</p>");
            AddHtml("Thengel-CoE", "<p class='main-text'>Risposta: Dopo che un alleato è stato scartato dal gioco, il proprietario di quell’alleato cerca tra le prime 5 carte del suo mazzo un alleato che condivide un <b><i>Tratto</i></b> con l’alleato scartato, lo mette in gioco esausto e rimescola il suo mazzo. (Solo una volta per turno.)</p><p class='flavor-text'>“Amico,” disse Gandalf, “tu avevi cavalli, vantavi azioni di guerra e liberi campi.” —Il Ritorno del Re</p>");
            AddHtml("Herubrand-CoE", "<p class='main-text'>Herubrand prende +1 {Willpower} per ogni eroe che controlli con almeno un aggregato limitato.</p><p class='main-text'>Risposta: Dopo che un nemico è stato distrutto nell’area di allestimento, pesca 1 carta.</p><p class='flavor-text'>“Quale fardello trasportate, Uomini di Rohan?”<br/>—Imrahil, Il Ritorno del Re</p>");
            AddHtml("Deeping-Bowman-CoE", "<p class='main-text'>Devozione. Gittata.</p><p class='main-text'>Azione: Scarta Arciere del Fossato per scegliere un nemico. Fino alla fine della fase, quel nemico non conta la propria {Defense} durante il calcolo del danno da combattimento.</p><p class='flavor-text'>“Scoccammo ogni freccia disponibile, riempiendo la Diga di Orchi.” —Le Due Torri</p>");
            AddHtml("Open-the-Gates-CoE", "<p class='main-text'>Azione: Cerca tra le prime 5 carte del tuo mazzo un alleato che condivide un <b><i>Tratto</i></b> con ciascuno dei tuoi eroi e mettilo in gioco. Rimescola il tuo mazzo. Alla fine della fase, se quell’alleato non ha lasciato il gioco nel frattempo, aggiungilo alla tua mano.</p><p class='flavor-text'>Pareva che la notizia del loro arrivo li avesse preceduti; furono fatti entrare immediatamente, in silenzio e senza interrogatorio. —Il Ritorno del Re</p>");
            AddHtml("Wealth-of-Adventure-CoE", "<p class='main-text'>Azione: Cerca nel tuo mazzo una carta con il tratto <b><i>Abilità</i></b> e aggiungila alla tua mano. Rimescola il tuo mazzo.</p><p class='flavor-text'>“È pericoloso e impegnativo uscire di casa, Frodo”, mi ripeteva sempre. “Cammini per la strada e, se non fai attenzione, chissà fin dove sei trascinato.”<br/>—Frodo, La Compagnia dell’Anello</p>");
            AddHtml("Feast-of-Plenty-CoE", "<p class='main-text'>Devi pagare il costo di Banchetto Generoso dalla riserva di un singolo eroe.</p><p class='main-text'>Azione: Rendi pronti fino a 3 eroi e aggiungi 1 risorsa alla riserva di ciascuno di quegli eroi. I giocatori possono giocare solo 1 copia di Banchetto Generoso per turno.</p><p class='flavor-text'>Il banchetto era allegro e il cibo vario e abbondante come non ne aveva mai visto.<br/>—La Compagnia dell’Anello</p>");
            AddHtml("Deeping-Defender-CoE", "<p class='main-text'>Devozione.</p><p class='main-text'>Risposta: Dopo che Difensore del Fossato ha difeso contro un attacco, fai tornare il nemico attaccante nell’area di allestimento e infliggi 1 danno a quel nemico.</p><p class='flavor-text'>Il tramonto indorava le lance e gli elmi e giocava tra i loro pallidi capelli al vento. —Le Due Torri</p>");
            AddHtml("Morwen-Steelsheen-CoE", "<p class='main-text'>Azione: Metti in gioco Morwen Bagliore d’Acciaio dalla tua mano. Poi, scarta un alleato <b><i>Rohan</i></b> o <b><i>Gondor</i></b> che controlli.</p><p class='main-text'>Risposta: Dopo che un alleato <b><i>Rohan</i></b> o <b><i>Gondor</i></b> lascia il gioco, esaurisci Morwen Bagliore d’Acciaio per curare 2 danni a un personaggio oppure ridurre di 1 la tua minaccia.</p>");
            AddHtml("It-Should-Be-Spared-CoE", "<p class='main-text'>Risposta: Dopo che una carta <b><i>Trappola</i></b> che controlli viene aggregata a un nemico, riprendila in mano. Poi, giocala dalla tua mano senza pagarne il costo.</p><p class='flavor-text'>“Ma non uccido uomo o bestia inutilmente, e mai con piacere, anche se necessario.”<br/>—Faramir, Le Due Torri</p>");
            AddHtml("Spring-the-Trap-CoE", "<p class='main-text'>Risposta: Dopo che una carta <b><i>Trappola</i></b> che controlli viene aggregata a un nemico, metti in gioco un alleato <b><i>Ranger</i></b> dalla tua mano.</p><p class='flavor-text'>“Forse la strada l’attraversa, ma essi non l’attraverseranno mai! Perlomeno finché Faramir è Capitano.” —Mablung, Le Due Torri</p>");
            AddHtml("Squire-of-the-Mark-CoE", "<p class='main-text'>Risposta: Dopo che un alleato <b><i>Rohan</i></b> che controlli è stato scartato dal gioco, aggiungi Scudiero del Mark al riquadro vittoria per rimettere quell’alleato in gioco esausto.</p><p class='flavor-text'>“Ben pochi servigi posso offrire al tuo signore, ma tutto ciò che mi sarà possibile lo farò…”<br/>—Pipino, Il Ritorno del Re</p>");
            AddHtml("Rammas-Lookout-CoE", "<p class='main-text'>Devozione.</p><p class='main-text'>Fintanto che ogni eroe che controlli ha almeno 1 risorsa nella sua riserva, Vedetta del Rammas prende +1 {Willpower} e non si esaurisce per essere coinvolto in una ricerca.</p><p class='flavor-text'>“Accada quel che potrà, è giunta ormai la fine del paese di Gondor quale lo conoscevate voi. Lasciatemi passare!”<br/>—Gandalf, Il Ritorno del Re</p>");
            AddHtml("Theodwyn-CoE", "<p class='main-text'>Risposta: Dopo che Théodwyn entra in gioco, pesca 1 carta oppure aggiungi 1 risorsa alla riserva di un eroe <b><i>Nobile</i></b>.</p><p class='flavor-text'>“Dama dal cuore nobile e senza paura. Tutti la amano. Fa che prenda lei il posto del sire degli Eorlingas durante la nostra assenza.”<br/>—Háma, Le Due Torri</p>");
            AddHtml("Light-footed-Steed-CoE", "<p class='main-text'>Aggregalo a un eroe <b><i>Rohan</i></b>. Limitato.</p><p class='main-text'>Risposta: Dopo che un personaggio che controlli ha lasciato il gioco, esaurisci Lesto Destriero per rendere pronto l’eroe aggregato. Poi, se il personaggio che ha lasciato il gioco era unico, l’eroe aggregato prende +1 {Attack} fino alla fine del turno.</p><p class='flavor-text'>“…e non dimenticare i loro cavalli! Quelli vedono anche la brezza di notte, o così ho sentito dire.”<br/>—Ugluk, Le Due Torri</p>");
            AddHtml("Rammas-Sentry-CoE", "<p class='main-text'>Devozione.</p><p class='main-text'>Fintanto che ogni eroe che controlli ha almeno 1 risorsa nella sua riserva, Sentinella del Rammas guadagna: “Risposta: Cancella 1 danno appena inflitto a un personaggio <b><i>Gondor</i></b>. (Solo una volta per fase).”</p><p class='flavor-text'>“Se cadiamo noi, chi rimarrà in piedi?”<br/>—Beregond, Il Ritorno del Re</p>");
            AddHtml("Live-Bait-CoE", "<p class='main-text'>Gioca solo se controlli una carta <b><i>Trappola</i></b> non aggregata.</p><p class='main-text'>Azione: Scegli un nemico non unico in gioco. Tratta il riquadro di testo di quel nemico come se fosse vuoto (ad eccezione dei <b><i>Tratti</i></b>) fino alla fine del turno. Poi, aggrega una carta <b><i>Trappola</i></b> non aggregata che controlli a quel nemico.</p>");
            AddHtml("Worthy-of-Remembrance-CoE", "<p class='main-text'>Azione di Combattimento: Scarta un alleato <b><i>Rohan</i></b> che controlli per scegliere un nemico. Infliggi 2 danni a quel nemico (4 danni invece se l’alleato scartato era unico).</p><p class='flavor-text'>“Allora il cuore di Éowyn cambiò ad un tratto, e fu ella finalmente a comprenderlo; e improvvisamente il suo inverno scomparve e il sole brillò in lei.”<br/>—Il Ritorno del Re</p>");
            AddHtml("Need-Brooks-No-Delay-CoE", "<p class='main-text'>Riduci di 1 il costo per giocare Il Bisogno non Tollera Attesa per ogni eroe <b><i>Rohan</i></b> che controlli.</p><p class='main-text'>Azione di Pianificazione: Cerca tra le prime 10 carte del tuo mazzo una carta con costo stampato di 2 o inferiore (3 o inferiore se la carta è unica) e mettila da parte. Rimescola il tuo mazzo. Poi, gioca la carta messa da parte senza pagarne il costo e come se fosse nella tua mano.</p>");
            AddHtml("Wild-Country-CoE", "<p class='main-text'>Condanna 1. Vasto.</p><p class='main-text'>Obbligato: Alla fine della fase di viaggio, se il luogo attivo non è vasto, ogni giocatore infligge 1 danno ad un personaggio che controlla.</p>{shadow}<p class='shadow-text'>Ombra: Se il luogo attivo è vasto, infliggi 1 danno al personaggio in difesa.</p>");
            AddHtml("Endless-Grasslands-CoE", "<p class='main-text'>Vasto.</p><p class='main-text'>Obbligato: Alla fine della fase di viaggio, se il luogo attivo non è vasto, ogni giocatore esaurisce un alleato che controlla.</p>{shadow}<p class='shadow-text'>Ombra: Se il luogo attivo è vasto, il nemico attaccante compie un attacco addizionale dopo questo.</p>");
            AddHtml("Windworn-Villages-CoE", "<p class='main-text'>Vasto.</p><p class='main-text'>Obbligato: Alla fine della fase di viaggio, se il luogo attivo non è vasto, ogni giocatore sceglie e scarta 1 carta dalla propria mano.</p>{shadow}<p class='shadow-text'>Ombra: Se il luogo attivo è vasto, scarta 1 aggregato dal personaggio in difesa.</p>");
            AddHtml("Humpbacked-Downs-CoE", "<p class='main-text'>Vasto.</p><p class='main-text'>Obbligato: Alla fine della fase di viaggio, se il luogo attivo non è vasto, ogni giocatore incrementa di 1 la propria minaccia.</p>{shadow}<p class='shadow-text'>Ombra: Se il luogo attivo è vasto, incrementa di 2 la tua minaccia.</p>");
            AddHtml("Ride-Through-the-Night-CoE", "<p class='main-text'>Quando Rivelata: Esaurisci tutti gli aggregati limitati controllati dai giocatori. Se questo effetto non fa esaurire alcun aggregato limitato, Attraverso la Notte guadagna impeto.</p>{shadow}<p class='shadow-text'>Ombra: Se il luogo attivo è vasto, il personaggio in difesa non può essere reso pronto fino alla fine del turno.</p>");
            AddHtml("The-Green-Sea-CoE", "<p class='flavor-text'>L’entroterra è vasto e senza fine, in grado di sfiancare anche i più vigorosi destrieri dell’Ovestfalda.</p><p class='main-text'>Ogni luogo vasto prende +3 punti progresso ed è immune agli effetti delle carte dei giocatori.</p><p class='main-text'>Obbligato: All’inizio della fase di viaggio, se non c’è almeno un luogo vasto nell’area di allestimento, scarta carte dalla cima del mazzo incontri fino a che non viene scartato un luogo vasto e aggiungilo all’area di allestimento.</p>{victory:10}");
            AddHtml("Cold-from-the-Mountains-CoE", "<p class='main-text'>Quando Rivelata: Ogni giocatore che controlla più di 2 alleati deve scartare 1 alleato che controlla (ne deve scartare 2 se controlla più di 5 alleati).</p>{shadow}<p class='shadow-text'>Ombra: Esaurisci un personaggio che controlli.</p><p class='flavor-text'>“Chi vuole lo chiami pur vento…”<br/>—Boromir, La Compagnia dell’Anello</p>");
            AddHtml("Exhausting-Winds-CoE", "<p class='main-text'>Quando Rivelata: Infliggi 1 danno ad ogni personaggio con più di 1 punto ferita rimanente. Esaurisci ogni personaggio non danneggiato da questo effetto.</p>{shadow}<p class='shadow-text'>Ombra: Dopo aver risolto questo attacco, infliggi X danni al personaggio in difesa. X è 1 in meno dei punti ferita rimanenti di quel personaggio.</p>");
            AddHtml("Tired-and-Hungry-CoE", "<p class='main-text'>Fintanto che è aggregata ad un eroe conta come un aggregato <b><i>Condizione</i></b> con il testo: “Obbligato: Quando un luogo viene esplorato, esaurisci l’eroe aggregato.”</p><p class='main-text'>Quando Rivelata: Aggregala ad un eroe pronto senza una copia di Stanchi ed Affamati aggregata. Altrimenti Stanchi ed Affamati guadagna impeto.</p><p class='flavor-text'>“Davanti a noi i nemici e dietro lo spavento, il nostro letto sarà sotto il cielo e nel vento.”<br/>—La Compagnia dell’Anello</p>");
            AddHtml("Exposed-to-the-Elements-CoE", "<p class='flavor-text'>Il vostro gruppo si trova esposto all’inclemenza degli elementi e della fame. Dovete cercare riparo se volete avere anche un solo attimo di tregua.</p><p class='main-text'>Obbligato: Alla fine del passo di allestimento, scarta carte dal mazzo incontri fino a che non viene scartata una carta perfidia. Rivela quella carta.</p>{victory:10}");
            AddHtml("Old-Farmhouse-CoE", "<p class='main-text'>Obbligato: Dopo che Vecchia Fattoria ha lasciato il gioco come luogo esplorato, scarta carte dal mazzo incontri fino a che non scarti un luogo. Aggiungi quel luogo all’area di allestimento.</p><p class='flavor-text'>A un paio di centinaia di metri dalla strada maestra, incontrarono una robusta barricata fatta di vecchi carri capovolti. Furono costretti a fermarsi.<br/>—Il Ritorno del Re</p>");
            AddHtml("Abandoned-Mill-CoE", "<p class='main-text'>Condanna 1. Immune agli effetti delle carte dei giocatori.</p><p class='main-text'>Obbligato: Dopo che Mulino Abbandonato ha lasciato il gioco come luogo esplorato, scarta carte dal mazzo incontri fino a che non scarti un nemico. Aggiungi quel nemico all’area di allestimento.</p><p class='flavor-text'>Per macinare ci vuole grano, e non ve n’era certo più…<br/>—Il Ritorno del Re</p>");
            AddHtml("Dunland-Chieftain-CoE", "<p class='main-text'>Obbligato: Dopo che Capitano Dunlandiano ti ha ingaggiato, scarta 1 carta casuale dalla tua mano. Poi, scarta ogni altra copia di quella carta che si trova nella tua mano o sotto il tuo controllo.</p><p class='flavor-text'>“Ci odiano e sono contenti…”<br/>—Gamling, Le Due Torri</p>{victory:1}");
            AddHtml("Wild-Ravager-CoE", "<p class='main-text'>Obbligato: All’inizio della fase incontri, scegli un giocatore casuale. Devastatore Selvaggio ingaggia quel giocatore.</p>{shadow}<p class='shadow-text'>Ombra: Il nemico attaccante non può subire danni fino alla fine del turno.</p>");
            AddHtml("Dunlending-Berserker-CoE", "<p class='main-text'>Obbligato: Dopo che Berserker del Dunland ti ha ingaggiato, infliggi 1 danno ad un eroe che controlli e 1 danno ad un nemico non unico ingaggiato con te.</p><p class='flavor-text'>“Alba e crepuscolo non li faranno indietreggiare…”<br/>—Gamling, Le Due Torri</p>");
            AddHtml("Hillman-Scout-CoE", "<p class='main-text'>Arciere 2.</p><p class='main-text'>Obbligato: Dopo che Esploratore delle Montagne ti ha ingaggiato, esaurisci l’alleato pronto che controlli con il costo stampato più alto.</p>{shadow}<p class='shadow-text'>Ombra: Esaurisci un personaggio che controlli con 3 o più {Attack}.</p>");
            AddHtml("Surprise-Attack-CoE", "<p class='main-text'>Impeto.</p><p class='main-text'>Quando Rivelata: Il prossimo nemico che viene ingaggiato questo turno non può subire danni fino alla fine del turno e ritorna nell’area di allestimento dopo che ha attaccato questo turno.</p><p class='flavor-text'>Era stato raggiunto dagli altri che gli avevano tagliato la strada. Li vedeva distintamente…<br/>—La Compagnia dell’Anello</p>");
            AddHtml("A-History-of-Strife-CoE", "<p class='flavor-text'>I Dunlandiani covano un antico rancore contro gli estranei che si aggirano nelle loro terre. Cercheranno di cogliervi alla sprovvista e di saccheggiare le vostre provviste prima di lasciarvi ad una morte certa.</p><p class='main-text'>Impeto.</p><p class='main-text'>Ogni nemico <b><i>Dunland</i></b> guadagna “Obbligato: Dopo che questo nemico ti ha ingaggiato, scarta 1 risorsa dalla riserva di un eroe che controlli.”</p>{victory:10}");
            AddHtml("Recreant-Rider-CoE", "<p class='main-text'>Obbligato: Quando entra nell’area di allestimento, Cavaliere Meschino compie un attacco immediato contro il primo giocatore.</p>{shadow}<p class='shadow-text'>Ombra: Il nemico attaccante ritorna nell’area di allestimento dopo questo attacco.</p>");
            AddHtml("Deadly-Defector-CoE", "<p class='main-text'>Obbligato: Alla fine della fase di combattimento, se Disertore Funesto è nell’area di allestimento, esso compie un attacco immediato contro l’ultimo giocatore.</p>{shadow}<p class='shadow-text'>Ombra: Se il nemico attaccante si trova nell’area di allestimento, esso compie un attacco addizionale dopo questo.</p>");
            AddHtml("Orc-Battalion-CoE", "<p class='main-text'>Battaglione Orchesco non può subire danni da combattimento quando viene attaccato da meno di 3 personaggi.</p><p class='main-text'>Obbligato: Dopo che un personaggio viene dichiarato come attaccante contro Battaglione Orchesco, infliggi 1 danno a quel personaggio.</p>");
            AddHtml("Servant-of-the-Eye-CoE", "<p class='main-text'>Condanna 1.</p><p class='main-text'>Obbligato: Quando Servitore dell’Occhio ti attacca, incrementa di 1 la tua minaccia.</p>{shadow}<p class='shadow-text'>Ombra: Incrementa di 2 la tua minaccia.</p>");
            AddHtml("Black-Land-Scouts-CoE", "<p class='main-text'>Obbligato: All’inizio della fase di combattimento, scegli se incrementare di 1 la minaccia di ogni giocatore o se infliggere 4 danni suddivisi tra i personaggi in gioco.</p>{shadow}<p class='shadow-text'>Ombra: Infliggi 2 danni suddivisi tra i personaggi che controlli.</p>");
            AddHtml("Orcish-Horse-butcher-CoE", "<p class='main-text'>Obbligato: Quando Macellatore di Cavalli Orchesco infligge danno a un personaggio, scarta un aggregato da quel personaggio oppure incrementa di 1 la minaccia del giocatore ingaggiato.</p>{shadow}<p class='shadow-text'>Ombra: Scarta un aggregato che controlli oppure incrementa di 3 la tua minaccia.</p>");
            AddHtml("Crimson-Banner-CoE", "<p class='main-text'>Impeto.</p><p class='main-text'>Fintanto che è aggregata ad un nemico, conta come un aggregato <b><i>Condizione</i></b> con il testo: “Obbligato: Alla fine del turno, ogni giocatore incrementa di 1 la propria minaccia per ogni nemico <b><i>Orco</i></b> in gioco.”</p><p class='main-text'>Quando Rivelata: Aggregala al nemico <b><i>Orco</i></b> non unico con il valore di ingaggio più alto.</p>");
            AddHtml("White-Mountain-Reinforcements-CoE", "<p class='flavor-text'>Gli Orchi stanno sciamando dalle caverne sulle montagne, rinforzando l’assalto dei vostri nemici. Se non li bloccherete, presto vi potrebbero soverchiare.</p><p class='main-text'>Quando Rivelata: Ogni giocatore non ingaggiato con un nemico deve cercare un nemico nel mazzo incontri e nella pila degli scarti degli incontri e poi metterlo in gioco ingaggiato con sé. Rimescola il mazzo incontri.</p><p class='main-text'>Ogni carta ombra senza effetto ombra guadagna: “Ombra: Incrementa di 1 la tua minaccia.”</p>{victory:10}");
            AddHtml("Brigand-Ringleader-CoE", "<p class='main-text'>Saccheggiare 3. Immune agli effetti delle carte dei giocatori. Non può subire più di 5 danni ogni turno.</p><p class='main-text'>Obbligato: Alla fine del turno, il giocatore ingaggiato aggiunge la prima carta del proprio mazzo alla pila di saccheggio di Capobanda dei Briganti e guarisce 1 danno da Capobanda dei Briganti per ogni costo differente tra le carte nella sua pila di saccheggio.</p>{victory:10}");
            AddHtml("Plundered-Goods-CoE", "<p class='main-text'>Aggiungi 1 alla {Threat} totale dell’area di allestimento per ogni carta nella pila di saccheggio di Beni Trafugati.</p><p class='main-text'>Obbligato: Quando un nemico lascia il gioco, aggiungi 1 carta dalla sua pila di saccheggio alla pila di saccheggio di Beni Trafugati, poi aggiungi un’altra carta dalla sua pila di saccheggio alla mano del proprietario della carta. Scarta il resto delle carte.</p><p class='flavor-text'>I briganti hanno razziato le scorte di lance e scudi del villaggio, per poi rivolgere le armi contro gli abitanti.</p>");
            AddHtml("Pillaging-Swordsman-CoE", "<p class='main-text'>Saccheggiare 1.</p><p class='main-text'>Spadaccino Saccheggiatore prende +X {Attack}, dove X è il costo stampato più alto tra le carte nella sua pila di saccheggio.</p>{shadow}<p class='shadow-text'>Ombra: Aggiungi le prime 2 carte del tuo mazzo alla pila di saccheggio del nemico attaccante.</p>");
            AddHtml("Grasping-Slaver-CoE", "<p class='main-text'>Saccheggiare 2.</p><p class='main-text'>Obbligato: Dopo che un alleato viene danneggiato o distrutto da un attacco di Schiavista Avido, aggiungi quell’alleato alla pila di saccheggio di Schiavista Avido.</p><p class='main-text'>Obbligato: Dopo che Schiavista Avido attacca, infliggi X danni suddivisi tra i personaggi che controlli. X è il numero di carte alleato nella pila di saccheggio di Schiavista Avido.</p>");
            AddHtml("Vengeful-Bowman-CoE", "<p class='main-text'>Saccheggiare 2. Arciere X.</p><p class='main-text'>X è il numero di tipi differenti di carte dei giocatori nella pila di saccheggio di Arciere Vendicativo.</p>{shadow}<p class='shadow-text'>Ombra: Se questo attacco infligge danni, aggiungi la prima carta del tuo mazzo alla pila di saccheggio del nemico attaccante.</p>");
            AddHtml("Sneaky-Thief-CoE", "<p class='main-text'>Saccheggiare 0. Impeto.</p><p class='main-text'>Obbligato: Quando Ladro Furtivo subirebbe un qualsiasi ammontare di danni, se ha delle carte nella sua pila di saccheggio, invece scarta quelle carte.</p>{shadow}<p class='shadow-text'>Ombra: Se questo attacco distrugge un personaggio, il nemico attaccante compie un attacco addizionale dopo questo.</p>");
            AddHtml("Erelas-Gates-CoE", "<p class='main-text'>Viaggio: Ogni giocatore sceglie un nemico e aggiunge la prima carta del proprio mazzo alla pila di saccheggio di quel nemico.</p>{shadow}<p class='shadow-text'>Ombra: Incrementa di 1 la tua minaccia per ogni carta nella pila di saccheggio del nemico attaccante.</p><p class='flavor-text'>Pilastri contorti e sradicati s’impennavano coi loro fusti scheggiati… —Le Due Torri</p>");
            AddHtml("Crossroads-CoE", "<p class='main-text'>Viaggio: Mescola la pila degli scarti degli incontri nel mazzo incontri e scarta carte fino a che non viene scartato un nemico. Metti quel nemico in gioco ingaggiato con il primo giocatore.</p>{shadow}<p class='shadow-text'>Ombra: Il nemico attaccante prende +X {Attack}, dove X è il numero di sfere differenti tra le carte nella sua pila di saccheggio.</p>");
            AddHtml("Erelas-Stables-CoE", "<p class='main-text'>Viaggio: Fai ritornare un nemico ingaggiato con un giocatore nell’area di allestimento.</p>{shadow}<p class='shadow-text'>Ombra: Se il nemico attaccante non è unico, fallo ritornare nell’area di allestimento dopo questo attacco.</p>");
            AddHtml("Chaos-in-the-Hills-CoE", "<p class='main-text'>Quando Rivelata: Fai ritornare nell’area di allestimento il nemico ingaggiato con il valore di ingaggio più alto. Se nessun nemico ritorna nell’area di allestimento a causa di questo effetto, Caos nelle Colline guadagna impeto.</p>{shadow}<p class='shadow-text'>Ombra: Dopo questo attacco, il nemico attaccante ingaggia il giocatore successivo e compie un attacco immediato.</p>");
            AddHtml("Looted-Weapons-CoE", "<p class='main-text'>Fintanto che è aggregata ad un nemico, conta come un aggregato <b><i>Condizione</i></b> con il testo: “Il nemico aggregato prende +1 {Threat} e +1 {Attack} per ogni aggregato nella sua pila di saccheggio.”</p><p class='main-text'>Quando Rivelata: Aggregala al nemico in gioco con il valore di ingaggio più alto. Poi, ogni giocatore aggiunge un aggregato <b><i>Oggetto</i></b> che controlla alla pila di saccheggio di quel nemico, se possibile. Se non ci sono nemici in gioco Armi Rubate guadagna impeto.</p>");
            AddHtml("Stockpile-Barricade-CoE", "<p class='flavor-text'>Carri e carretti rovesciati formano una robusta barricata che attraversa la strada.</p><p class='main-text'>Impeto.</p><p class='main-text'>Ogni nemico prende +1 {Defense} per ogni aggregato nella propria pila di saccheggio.</p><p class='main-text'>Obbligato: Dopo aver risolto la parola chiave Saccheggiare di un nemico, se non ci sono aggregati nella pila di saccheggio di quel nemico, esso compie un attacco immediato contro il giocatore ingaggiato.</p>{victory:10}");
            AddHtml("Erelas-Beacon-CoE", "<p class='main-text'>Obbligato: Alla fine della fase di combattimento, infliggi 1 danno a Faro di Erelas per ogni nemico nell’area di allestimento.</p><p class='main-text'><b>Faro di Erelas ha X punti ferita, dove X è uguale a 2, più 3{PerPlayer}. Se Faro di Erelas non ha più punti ferita rimanenti, i giocatori hanno perso la partita. </b></p><p class='flavor-text'>Ogni cosa era grigia e immobile, mentre innanzi a loro l’ombra diveniva sempre più tenebrosa ed ogni speranza impallidiva.<br/>—Il Ritorno del Re</p>");
            AddHtml("Host-of-Rohan-CoE", "<p class='main-text'>Sentinella.</p><p class='main-text'>Azione: I giocatori come gruppo possono spendere 2 risorse per rendere pronta Schiera di Rohan. (Limite una volta per fase.)</p><p class='flavor-text'>“La guerra infierisce, ed i Rohirrim, i Signori dei Cavalli, non dormono.”<br/>—Gandalf, Le Due Torri</p>");
            AddHtml("Enraged-Dunlending-CoE", "<p class='main-text'>Obbligato: Dopo che Dunlandiano Furioso ti ha ingaggiato, infliggi 1 danno a Faro di Erelas.</p>{shadow}<p class='shadow-text'>Ombra: Ogni danno inflitto al personaggio in difesa da questo attacco è invece inflitto a Faro di Erelas.</p>");
            AddHtml("Bald-Hill-CoE", "<p class='main-text'>Fintanto che i giocatori controllano il faro, Collina Spoglia prende +3 {Threat}.</p><p class='main-text'>Viaggio: Se i giocatori controllano il faro, infliggi 2 danni a Faro di Erelas.</p><p class='flavor-text'>Giunsero infine in cima al colle grigio, e una brezza improvvisa soffiò tra i loro capelli agitando i loro manti: il frizzante vento dell’alba.<br/>—Le Due Torri</p>");
            AddHtml("Wooden-Barricade-CoE", "<p class='main-text'>Fintanto che Barricata di Legno è nell’area di allestimento guadagna: “Obbligato: Alla fine della fase di combattimento, infliggi 1 danno a Faro di Erelas e piazza 1 segnalino progresso su Barricata di Legno.”</p>{shadow}<p class='shadow-text'>Ombra: Infliggi 1 danno a Faro di Erelas oppure scarta 2 aggregati che controlli.</p>");
            AddHtml("Rocky-Slope-CoE", "<p class='main-text'>Dopo che l’effetto di una carta degli incontri è stato cancellato, infliggi 1 danno a Faro di Erelas.</p><p class='main-text'>Viaggio: Il primo giocatore deve scartare tutte le carte evento dalla sua mano.</p>{shadow}<p class='shadow-text'>Ombra: Infliggi 1 danno a Faro di Erelas oppure scarta tutte le risorse dagli eroi che controlli.</p>");
            AddHtml("Surrounding-Grassland-CoE", "<p class='main-text'>Arciere 1.</p><p class='main-text'>Obbligato: Dopo che Prateria Sconfinata lascia il gioco come luogo esplorato, se non ci sono copie di Prateria Sconfinata nell’area di allestimento, fai tornare questo luogo nell’area di allestimento.</p><p class='flavor-text'>Scorgevano al di là del fiume le verdi praterie di Rohan sbiadire in un lontano grigio.<br/>—Le Due Torri</p>");
            AddHtml("Narrow-Stair-CoE", "<p class='main-text'>Ogni giocatore non può dichiarare più di 1 attacco e non può dichiarare più di 1 attaccante durante ciascuna fase.</p><p class='main-text'>Fintanto che Scala Angusta è il luogo attivo, ogni giocatore non può difendere più di 1 attacco durante ciascuna fase (gli altri attacchi sono considerati incontrastati).</p>{shadow}<p class='shadow-text'>Ombra: Infliggi 1 danno a Faro di Erelas oppure il nemico attaccante prende +3 {Attack}.</p>");
            AddHtml("From-All-Sides-CoE", "<p class='main-text'>Quando Rivelata: Ogni giocatore sceglie: infliggi 1 danno al Faro di Erelas oppure infliggi 1 danno a 4 personaggi differenti che controlli.</p>{shadow}<p class='shadow-text'>Ombra: Dopo questo attacco, infliggi 1 danno a Faro di Erelas oppure scarta il personaggio dichiarato come difensore.</p>");
            AddHtml("Another-Wave-CoE", "<p class='main-text'>Impeto. Condanna 1.</p><p class='main-text'>Quando Rivelata: Se i giocatori controllano il faro, infliggi 2 danni a Faro di Erelas oppure rivela una carta degli incontri.</p>{shadow}<p class='shadow-text'>Ombra: Infliggi 1 danno a Faro di Erelas oppure il nemico attaccante compie un attacco addizionale dopo questo.</p>");
            AddHtml("Assault-Upon-Erelas-CoE", "<p class='main-text'>Quando Rivelata: Il primo giocatore sceglie un nemico ingaggiato con un giocatore e lo fa tornare nell’area di allestimento. Se nessun nemico viene fatto tornare nell’area di allestimento da questo effetto, infliggi 1 danno a Faro di Erelas oppure Assalto ad Erelas guadagna impeto.</p>{shadow}<p class='shadow-text'>Ombra: Infliggi 1 danno a Faro di Erelas oppure incrementa di 4 la tua minaccia.</p>");
            AddHtml("Reclaim-the-Beacon-CoE", "<p class='flavor-text'>Riconquistate il faro, prima che i Dunlandiani lo danneggino o peggio.</p><p class='main-text'>I Dunlandiani controllano il faro. I nemici nell’area di allestimento non possono essere ingaggiati intenzionalmente né subire danni.</p><p class='main-text'>Non può avere più di X segnalini progresso, dove X è pari a 2, più 1{PerPlayer}. Se Riconquistare il Faro ha X segnalini progresso giralo (mantenendo tutti i segnalini progresso).</p>");
            AddHtml("Stolen-Steeds-CoE", "<p class='main-text'>Gli obiettivi <b><i>Cavalcatura</i></b> non possono essere scartati o lasciare il gioco. Se un obiettivo <b><i>Cavalcatura</i></b> non è aggregato, un giocatore deve prenderne il controllo e aggregarlo ad un eroe che controlla.</p><p class='main-text'>Obbligato: Alla fine del turno, aggiungi 1 segnalino progresso alla ricerca principale per ogni obiettivo <b><i>Cavalcatura</i></b> controllato dai giocatori. Poi, incrementa di 1 la minaccia di ciascun giocatore per ogni obiettivo <b><i>Cavalcatura</i></b> in gioco che non è controllato dai giocatori.</p>");
            AddHtml("Flinthoof-CoE", "<p class='main-text'>Protetto (nemico). Limitato.</p><p class='main-text'>Il nemico che protegge Zoccoselce prende +1 {Attack}.</p><p class='main-text'>L’eroe aggregato prende +1 {Attack}.</p><p class='main-text'>Azione di Combattimento: Esaurisci Zoccoselce per infliggere 1 danno ad un nemico in gioco.</p><p class='flavor-text'>Le lunghe code svolazzanti al vento, le criniere sciolte sui loro colli orgogliosi.<br/>—Le Due Torri</p>");
            AddHtml("Brightmane-CoE", "<p class='main-text'>Protetto (luogo). Limitato.</p><p class='main-text'>Il luogo o il nemico che protegge Folgocrino prende +1 {Threat}.</p><p class='main-text'>L’eroe aggregato prende +1 {Willpower}.</p><p class='main-text'>Azione di Ricerca: Esaurisci Folgocrino per guardare la prima carta del mazzo incontri. Se è un luogo, puoi scartarla.</p>");
            AddHtml("Felarof-CoE", "<p class='main-text'>Protetto (nemico). Limitato.</p><p class='main-text'>Obbligato: Quando il nemico che protegge Felaróf attacca, assegnagli 2 carte ombra addizionali.</p><p class='main-text'>Azione di Combattimento: Esaurisci Felaróf per scartare dal gioco una carta ombra a faccia in giù.</p><p class='flavor-text'>“Ma ne scorgo uno cavalcare innanzi: un cavallo assai grande. Mai ne ho veduto uno simile.”<br/>—Legolas, Le Due Torri</p>");
            AddHtml("Thruk-CoE", "<p class='main-text'>Immune agli effetti delle carte dei giocatori. Thruk ingaggia il primo giocatore.</p><p class='main-text'>Obbligato: All’inizio della fase di combattimento, se Thruk non sta proteggendo un obiettivo, Thruk compie un attacco immediato contro il giocatore ingaggiato.</p>{victory:10}");
            AddHtml("Saddle-slasher-CoE", "<p class='main-text'>Arciere X. X è pari a 2, più 1 per ogni obiettivo <b><i>Cavalcatura</i></b> controllato dai giocatori.</p>{shadow}<p class='shadow-text'>Ombra: Se controlli un obiettivo <b><i>Cavalcatura</i></b>, aggregalo al nemico attaccante come obiettivo protetto oppure scarta il personaggio difensore dopo aver risolto questo attacco.</p>");
            AddHtml("Rein-ripper-CoE", "<p class='main-text'>Obbligato: Quando Strappa-redini attacca, assegnagli 2 carte ombra addizionali. Puoi aggregare un obiettivo <b><i>Cavalcatura</i></b> che controlli a Strappa-redini come obiettivo protetto per cancellare questo effetto.</p>{shadow}<p class='shadow-text'>Ombra: Il nemico attaccante prende +1 {Attack} per ogni aggregato <b><i>Cavalcatura</i></b> controllato dai giocatori.</p>");
            AddHtml("Bridle-biter-CoE", "<p class='main-text'>Impeto.</p><p class='main-text'>Quando Rivelata: Recidi-briglie ingaggia il giocatore che controlla più obiettivi <b><i>Cavalcatura</i></b>.</p>{shadow}<p class='shadow-text'>Ombra: Metti Recidi-briglie in gioco ingaggiato con te e assegnagli una carta ombra.</p>");
            AddHtml("Pommel-pouncer-CoE", "<p class='main-text'>Fintanto che è nell’area di allestimento senza un obiettivo <b><i>Cavalcatura</i></b> aggregato, Balza-pomello guadagna: “Obbligato: Quando un giocatore guadagnerebbe il controllo di un obiettivo <b><i>Cavalcatura</i></b>, invece aggrega quell’obiettivo <b><i>Cavalcatura</i></b> a Balza-pomello come obiettivo protetto.”</p>");
            AddHtml("Spoiled-Pasture-CoE", "<p class='main-text'>X è pari a 2, più 2 per ogni obiettivo <b><i>Cavalcatura</i></b> controllato dai giocatori.</p><p class='main-text'>Obbligato: Dopo che un giocatore perde il controllo di un obiettivo <b><i>Cavalcatura</i></b>, incrementa di 1 la minaccia di quel giocatore.</p>{shadow}<p class='shadow-text'>Ombra: Incrementa di 1 la tua minaccia per ogni obiettivo <b><i>Cavalcatura</i></b> che controlli.</p>");
            AddHtml("Horse-Thieves'-Hovel-CoE", "<p class='main-text'>Quando hanno la possibilità di viaggiare, i giocatori devono viaggiare verso un luogo non vasto, se possibile.</p><p class='main-text'>Obbligato: Dopo che Stamberga dei Ladri di Cavalli ha lasciato il gioco come luogo esplorato, se ci sono meno di 1{PerPlayer} nemici in gioco, scarta carte dalla cima del mazzo incontri fino a che non viene scartato un nemico. Aggiungi quel nemico all’area di allestimento.</p>{victory:2}");
            AddHtml("Horse-Lord's-Lodge-CoE", "<p class='main-text'>Quando hanno la possibilità di viaggiare, i giocatori devono viaggiare verso un luogo non vasto, se possibile.</p><p class='main-text'>Obbligato: Dopo che Loggia del Signore dei Cavalli ha lasciato il gioco come luogo esplorato, se ci sono meno di 1{PerPlayer} luoghi in gioco, scarta carte dalla cima del mazzo incontri fino a che non viene scartato un luogo. Aggiungi quel luogo all’area di allestimento.</p>{victory:2}");
            AddHtml("Thirst-for-Horse-Blood-CoE", "<p class='main-text'>Quando Rivelata: Ogni giocatore che controlla un obiettivo <b><i>Cavalcatura</i></b> sceglie: rivela una carta incontro oppure scegli il nemico con il valore di ingaggio più alto senza un aggregato e aggrega un obiettivo <b><i>Cavalcatura</i></b> che controlli a quel nemico come obiettivo protetto. Se nessun giocatore controlla un obiettivo <b><i>Cavalcatura</i></b>, Sete di Sangue di Cavallo guadagna impeto.</p><p class='flavor-text'>“Vedrete che pasteggeremo con carne di cavallo, o con qualcosa di meglio ancora.” —Uglúk, Le Due Torri</p>");
            AddHtml("Overburdened-CoE", "<p class='main-text'>Quando Rivelata: Ogni giocatore che controlla più di 2 aggregati deve scartare 1 aggregato che controlla, se possibile (deve scartare 2 aggregati invece, se possibile, se controlla più di 5 aggregati). Se non vengono scartati aggregati tramite questo effetto, Oberato guadagna impeto.</p>{shadow}<p class='shadow-text'>Ombra: Scarta 1 carta casuale dalla tua mano.</p>");
            AddHtml("The-Last-Alliance-CoE", "<p class='main-text'><b></b> Scegli due tratti, <b><i>A</i></b> e <b><i>B</i></b>. Ciascuno dei tuoi eroi iniziali e ciascun alleato nel tuo mazzo deve avere o il tratto stampato <b><i>A</i></b> o il tratto stampato <b><i>B</i></b>, ma non può averli entrambi. Devi avere almeno 1 eroe iniziale e 10 alleati nel tuo mazzo che possiedano ciascuno dei due tratti.</p><p class='main-text'>Preparazione: Gira questa carta. <b></p><p class='flavor-text'>“Molto tempo fa la forza degli Elfi era più potente di adesso, e ancora non tutti gli Uomini erano ridotti in schiavitù.”<br/>—Gandalf, La Compagnia dell’Anello</p>");
            AddHtml2("The-Last-Alliance-CoE", "<p class='main-text'></b> Fintanto che controlli più personaggi <b><i>A</i></b> che personaggi <b><i>B</i></b>, riduci di 1 il costo del primo alleato <b><i>B</i></b> che giochi questo turno, e viceversa.</p><p class='main-text'>Azione: Esaurisci L’Ultima Alleanza per scegliere una carta nella tua mano o una carta in gioco che controlli. Sostituisci ogni istanza stampata di “<b><i>A</i></b>” o “<b><i>B</i></b>” nel testo di gioco di quella carta con “<b><i>A</i></b> oppure <b><i>B</i></b>” fino alla fine del turno.</p>");
            AddHtml("Drive-them-Away-CoE", "<p class='flavor-text'>Seguendo la Grande Strada Occidentale, siete giunti ad un accampamento dei Rohirrim all’ombra della verde e spoglia collina di Erelas. Ma la quiete del vostro viaggio è stata interrotta da un improvviso attacco dalle ombre! Il rumore stridente dell’acciaio e le grida degli uomini raggiungono presto le vostre orecchie. Dovete respingerli e impedire che l’accampamento venga distrutto!</p><p class='main-text'><b></b> Preparazione: Metti Capobanda dei Briganti da parte, fuori dal gioco. Aggiungi Beni Trafugati all’area di allestimento. Ogni giocatore cerca nel mazzo incontri un nemico differente e lo aggiunge all’area di allestimento. Rimescola il mazzo incontri. <b></p>");
            AddHtml2("Drive-them-Away-CoE", "<p class='main-text'></b> Obbligato: Dopo che un nemico viene distrutto, piazza 1 segnalino risorsa su questa scena.</p><p class='main-text'>Azione di Incontri: Rimuovi 5 segnalini progresso da questa ricerca per scegliere una carta in una pila di saccheggio e scartarla. Massimo una volta per turno per giocatore.</p><p class='main-text'><b>I giocatori non possono avanzare a meno che non ci siano X segnalini risorsa su questa scena, dove X è pari a 1, più 2{PerPlayer} (2 per giocatore).</b></p>");
            AddHtml("Ambush-CoE", "<p class='flavor-text'>Vi siete fatti strada combattendo fino al cuore dell’accampamento, ma i briganti si sono radunati intorno al loro capo e lanciano un feroce contrattacco.</p><p class='main-text'><b></b> Quando Rivelata: Termina la fase attuale. Aggiungi Capobanda dei Briganti all’area di allestimento. Ogni giocatore non ingaggiato con un nemico cerca nel mazzo incontri e nella pila degli scarti degli incontri un nemico e lo mette in gioco ingaggiato con sé. Rimescola il mazzo incontri. <b></p>");
            AddHtml2("Ambush-CoE", "<p class='main-text'></b> Obbligato: Dopo che un nemico entra in gioco, compie delle verifiche di ingaggio.</p><p class='main-text'>Azione di Pianificazione: Rimuovi 5 segnalini progresso da questa scena per scegliere una carta in una pila di saccheggio. Il proprietario di quella carta la può scartare o la può giocare senza pagarne il costo. Massimo quattro volte per turno per il gruppo.</p><p class='main-text'><b>Quando Capobanda dei Briganti viene sconfitto, i giocatori vincono la partita.</b></p>");
            AddHtml("Battle-for-the-Hill-CoE", "<p class='flavor-text'>Dei Dunlandiani e dei Rohirrim traditori hanno catturato il faro di Erelas. Dovete riconquistare la collina a tutti i costi!</p><p class='main-text'><b></b> Preparazione: Metti Schiera di Rohan da parte, fuori dal gioco. Aggiungi Faro di Erelas e 1{PerPlayer} Dunlandiano Furioso all’area di allestimento. Aggiungi la ricerca secondaria a due facce all’area di allestimento, con la faccia Riconquistare il Faro rivolta verso l’alto. Cerca nel mazzo incontri 1 copia di Prateria Sconfinata e rendila il luogo attivo. Rimescola il mazzo incontri. <b></p>");
            AddHtml2("Battle-for-the-Hill-CoE", "<p class='main-text'></b> Obbligato: Dopo aver piazzato un qualsiasi ammontare di segnalini progresso su questa scena, ogni giocatore deve scegliere: esaurisci un personaggio che controlli oppure infliggi 1 danno a Faro di Erelas.</p><p class='main-text'><b>Questa scena non può essere completata fintanto che i Dunlandiani controllano il faro.</b></p>");
            AddHtml("Hold-the-Hilltop-CoE", "<p class='flavor-text'>Mentre i vostri nemici si preparano per assalire nuovamente il faro, potete vedere le luci delle torce delle truppe di Gálmód che si stanno radunando tra le colline sottostanti.</p><p class='main-text'><b></b> Quando Rivelata: Piazza segnalini progresso su Difendere il Faro (ignorando il luogo attivo) fino a che non ha X segnalini progresso, dove X è pari a 2 più 1{PerPlayer}. Rimescola la pila degli scarti degli incontri nel mazzo incontri. Ogni giocatore scarta carte dal mazzo incontri fino a che non viene scartato un nemico e aggiunge quel nemico all’area di allestimento. <b></p>");
            AddHtml2("Hold-the-Hilltop-CoE", "<p class='main-text'></b> Tempo 3.</p><p class='main-text'>Obbligato: Alla fine del turno, infliggi 1 danno a Faro di Erelas (2 danni invece se ci sono 3 o più giocatori nella partita). Poi, se non ci sono più segnalini tempo su questa scena, avanza immediatamente alla scena 3.</p><p class='main-text'>Obbligato: Dopo che Difendere il Faro viene scelta come ricerca attuale, rivela una carta degli incontri.</p><p class='main-text'><b>Se i Dunlandiani controllano il faro, i giocatori perdono la partita.</b></p>");
            AddHtml("The-Last-Push-CoE", "<p class='flavor-text'>Dovete prepararvi a resistere ad un ultimo assalto mentre le forze di Gálmód si apprestano a fiancheggiare i nemici.</p><p class='main-text'><b></b> Quando Rivelata: Rimuovi tutti i segnalini progresso da Difendere il Faro e girala. Metti Schiera di Rohan in gioco sotto il controllo del primo giocatore. Rimescola la pila degli scarti degli incontri nel mazzo incontri. Ogni giocatore scarta carte dalla cima del mazzo incontri fino a che non scarta un nemico e aggiunge quel nemico all’area di allestimento. <b></p>");
            AddHtml2("The-Last-Push-CoE", "<p class='main-text'></b> Aggiungi 2 alla {Threat} totale dell’area di allestimento per ogni danno su Faro di Erelas.</p><p class='main-text'>Obbligato: All’inizio della fase di combattimento, ogni nemico ingaggiato compie un attacco immediato.</p><p class='main-text'>Obbligato: Dopo che un personaggio lascia il gioco, infliggi 1 danno a Faro di Erelas.</p><p class='main-text'><b>Alla fine del turno, se i Dunlandiani controllano il faro, i giocatori perdono la partita, mentre se i giocatori controllano il faro, vincono la partita.</b></p>");
            AddHtml("Thieves-and-Coursers-CoE", "<p class='flavor-text'>Side A: Gli orchi hanno invaso l’Estfalda, razziando queste terre e catturando i preziosi cavalli da guerra di Re Thengel. Side B: Se riuscirete a recuperare Zoccoselce e Folgocrino, potreste riuscire a fermare l’armata principale degli Orchi prima che raggiunga Aldburg.</p><p class='main-text'><b></b> Preparazione: Aggiungi Destrieri Rubati all’area di allestimento. Metti Thruk, gli obiettivi <b><i>Cavalcatura</i></b> e gli 8 nemici del set degli incontri Armata degli Orchi da parte, fuori dal gioco. Rimescola il mazzo incontri. Il primo giocatore rivela Zoccoselce e Folgocrino e li aggiunge all’area di allestimento. Poi, ogni altro giocatore scarta carte dalla cima del mazzo incontri fino a che non viene scartato un nemico o un luogo e aggiunge quella carta all’area di allestimento. <b></p>");
            AddHtml2("Thieves-and-Coursers-CoE", "<p class='main-text'></b> <b>Questa scena non può essere completata a meno che i giocatori non controllino 2 obiettivi <b><i>Cavalcatura</i></b>.</b></p>");
            AddHtml("The-King's-Stallion-CoE", "<p class='flavor-text'>Il condottiero Thruk si è unito alla battaglia, in groppa al poderoso destriero Felaróf, gridando ordini ai suoi sottoposti. “A raccolta!” sbraita. “Stasera banchetteremo con carne di cavallo!”</p><p class='main-text'><b></b> Quando Rivelata: Se è la fase di combattimento, termina la fase. Rimescola la pila degli scarti degli incontri nel mazzo incontri. Il primo giocatore aggiunge Thruk all’area di allestimento e gli aggrega Felaróf come obiettivo protetto. Ogni altro giocatore scarta carta dalla cima del mazzo incontri fino a che non scarta un nemico e mette quel nemico in gioco ingaggiato con sé. <b></p>");
            AddHtml2("The-King's-Stallion-CoE", "<p class='main-text'></b> Thruk non può subire danni a meno che non ci siano almeno 4 segnalini progresso su questa scena.</p><p class='main-text'><b>Questa scena non può essere completata a meno che i giocatori non controllino 3 obiettivi <b><i>Cavalcatura</i></b>.</b></p>");
            AddHtml("The-Sweeping-Tide-CoE", "<p class='flavor-text'>La piena potenza dell’armata degli orchi ha risposto al richiamo urlato da Thruk. Dovete prepararvi a compiere un’ultima carica per respingerli nelle colline.</p><p class='main-text'><b></b> Quando Rivelata: Se è la fase di combattimento, termina la fase. Rimescola la pila degli scarti degli incontri nel mazzo incontri. Cerca Thruk nel riquadro vittoria e aggiungilo all’area di allestimento. Ogni giocatore sceglie 2 nemici dal set degli incontri Armata degli Orchi messo da parte e li mette in gioco ingaggiati con sé. Uno dei nemici messo in gioco da questo effetto deve essere Battaglione Orchesco. <b></p>");
            AddHtml2("The-Sweeping-Tide-CoE", "<p class='main-text'></b> Salta il passo di allestimento. Se in un qualsiasi momento il mazzo incontri è vuoto, rimescola la pila degli scarti degli incontri nel mazzo incontri.</p><p class='main-text'>Obbligato: Quando un nemico compie un attacco, assegnagli una carta ombra addizionale.</p><p class='main-text'><b>Se un obiettivo <b><i>Cavalcatura</i></b> viene aggregato ad un nemico, i giocatori perdono la partita. Se non ci sono nemici in gioco, i giocatori vincono la partita.</b></p>");
            AddHtml("Reclaim-the-Beacon-CoE", "<p class='main-text'>I giocatori controllano il faro. Le carte ombra sono immuni agli effetti delle carte dei giocatori.</p><p class='main-text'>Non può avere più di X segnalini progresso, dove X è pari a 2 più 1{PerPlayer}.</p><p class='main-text'>Risposta: Rimuovi un qualsiasi ammontare di segnalini progresso da Difendere Il Faro per cancellare un pari ammontare di danni appena inflitti a Faro di Erelas. Poi, se Difendere il Faro ha 0 segnalini progresso, giralo.</p>");
        }
    }
}