using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Services.LotR.Templates
{
    public class PolishTemplateRepository
        : TemplateRepository
    {
        protected override void Initialize()
        {
            //Children of Eorl
            AddHtml("Ingold-CoE", "<p class='main-text'><b>Odpowiedz:</b> Kiedy sprzymierzeniec z cecha <b><i>Gondor</i></b> lub <b><i>Wojownik</i></b> wchodzi do gry pod twoja kontrola, dobierz 1 karte. Nastepnie, wydaj 1 zasób z puli zasobów Ingolda lub zwieksz swój poziom zagrozenia o 1. (Limit raz na faze.)</p><p class='flavor-text'>“Nie chcemy w dzisiejszych czasach miec w swoim kraju obcych gosci, chyba ze sa to mezni i zbrojni wojownicy, na których pomocy i wiernosci mozemy polegac.” — Powrót Króla</p>");
            AddHtml("Celador-CoE", "<p class='main-text'>Dystans.</p><p class='main-text'>Zredukuj o 1 calkowity {Threat} strefy przeciwnosci za kazda kontrolowana przez ciebie i nie dolaczona do wroga <b><i>Pulapke</i></b>.</p><p class='main-text'><b>Odpowiedz:</b> Kiedy kontrolowana przez ciebie karta z cecha <b><i>Pulapka</i></b> zostanie dolaczona do jakiegos wroga, przygotuj Celadora lub zmniejsz swój poziom zagrozenia o 1.</p><p class='flavor-text'>“Rozum wzbrania ufac zbytnio obcym, spotkanym przypadkowo w tych okolicach.” — Faramir, Dwie Wieze</p>");
            AddHtml("Thengel-CoE", "<p class='main-text'><b>Odpowiedz:</b> Kiedy sprzymierzeniec zostanie odrzucony z gry, wlasciciel tego sprzymierzenca przeszukuje 5 wierzchnich kart swojej talii i umieszcza w grze sprzymierzenca, który posiada przynajmniej 1 <b><i>Ceche</i></b> odrzuconego sprzymierzenca. Umiesc wybranego sprzymierzenca w grze wyczerpanego. Nastepnie dany gracz tasuje swoja talie. (Limit raz na runde.)</p><p class='flavor-text'>“Przyjacielu! — rzekl Gandalf — Ty miales konie, zbrojne wyprawy, swobode otwartych stepów…” — Powrót Króla</p>");
            AddHtml("Herubrand-CoE", "<p class='main-text'>Herubrand otrzymuje +1{Willpower} za kazdego kontrolowanego przez ciebie bohatera z dolaczonym co najmniej 1 dodatkiem ze slowem kluczowym Ograniczenie.</p><p class='main-text'><b>Odpowiedz:</b> Kiedy w strefie przeciwnosci zostanie zabity wróg, dobierz 1 karte.</p><p class='flavor-text'>“Kogo niesiecie, przyjaciele z Rohanu?” — Imrahil, Powrót Króla</p>");
            AddHtml("Deeping-Bowman-CoE", "<p class='main-text'>Oddany. Dystans.</p><p class='main-text'><b>Akcja:</b> Odrzuc Helmowego Lucznika, aby wybrac wroga. Do konca fazy ten wróg nie wlicza swojej {Defense} kiedy przydzielane sa obrazenia.</p><p class='flavor-text'>“Nie mamy juz ani jednej strzaly w kolczanach, trupami orków wypelnila sie fosa.” — Dwie Wieze</p>");
            AddHtml("Open-the-Gates-CoE", "<p class='main-text'><b>Akcja:</b> Przeszukaj 5 wierzchnich kart swojej talii, wybierz sprzymierzenca dzielacego <b><i>Ceche</i></b> z kazdym z twoich bohaterów i umiesc go w grze. Potasuj swoja talie. Jesli ten sprzymierzeniec pod koniec fazy nadal znajduje sie grze, cofnij go na swoja reke.</p><p class='flavor-text'>“Wiesc o przybyciu gosci musiala ich zapewne wyprzedzic, bo otwarto brame natychmiast, o nic nie pytajac.” — Powrót Króla</p>");
            AddHtml("Wealth-of-Adventure-CoE", "<p class='main-text'><b>Akcja:</b> Przeszukaj swoja talie, wybierz karte z cecha <b><i>Umiejetnosc</i></b> i dodaj ja do swojej reki. Potasuj swoja talie.</p><p class='flavor-text'>“Niebezpiecznie wychodzic za wlasny próg, mój Frodo! — powiadal nieraz. — Trafisz na gosciniec i jezeli nie powstrzymasz swoich nóg, ani sie spostrzezesz, kiedy cie poniosa.”<br/>— Frodo, Druzyna Pierscienia</p>");
            AddHtml("Feast-of-Plenty-CoE", "<p class='main-text'>Swieto Obfitosci musi zostac oplacone z puli zasobów jednego bohatera.</p><p class='main-text'><b>Akcja:</b> Przygotuj do 3 swoich bohaterów nastepnie dodaj 1 zeton zasobów kazdemu z tych bohaterów. (Limit raz na runde na grupe.)</p><p class='flavor-text'>“…uczta byla wesola, a sute dania mogly zadowolic najglodniejszego.” — Druzyna Pierscienia</p>");
            AddHtml("Deeping-Defender-CoE", "<p class='main-text'>Oddany.</p><p class='main-text'><b>Odpowiedz:</b> Kiedy Helmowy Obronca obroni sie przed atakiem, cofnij atakujacego wroga do strefy przeciwnosci i zadaj mu 1 obrazenie.</p><p class='flavor-text'>“Zachodzace slonce zlocilo ich wlócznie i helmy, polyskiwalo na jasnych rozwianych wlosach.”<br/>— Dwie Wieze</p>");
            AddHtml("Morwen-Steelsheen-CoE", "<p class='main-text'><b>Akcja:</b> Umiesc Morwene Kwiat ze Stali w grze ze swojej reki. Odrzuc kontrolowanego przez ciebie sprzymierzenca z cecha <b><i>Rohan</i></b> lub <b><i>Gondor</i></b>.</p><p class='main-text'><b>Odpowiedz:</b> Kiedy sprzymierzeniec z cecha <b><i>Rohan</i></b> lub <b><i>Gondor</i></b> opusci gre, wyczerp Morwene Kwiat ze Stali, aby wyleczyc 2 obrazenia dowolnej postaci lub zmniejszyc swój poziom zagrozenia o 1.</p>");
            AddHtml("It-Should-Be-Spared-CoE", "<p class='main-text'><b>Odpowiedz:</b> Kiedy kontrolowana przez ciebie karta z cecha <b><i>Pulapka</i></b> zostanie dolaczona do jakiegos wroga, cofnij te karte do swojej talii. Nastepnie zagraj te karte nie placac jej kosztu.</p><p class='flavor-text'>“Nie zabijam jednak ani ludzi, ani zwierzat bez potrzeby, a nawet gdy musze, nie sprawia mi to przyjemnosci.” — Faramir, Dwie Wieze</p>");
            AddHtml("Spring-the-Trap-CoE", "<p class='main-text'><b>Odpowiedz:</b> Kiedy kontrolowana przez ciebie karta z cecha <b><i>Pulapka</i></b> zostanie dolaczona do jakiegos wroga, umiesc w grze ze swojej reki sprzymierzenca z cecha <b><i>Straznik</i></b>.</p><p class='flavor-text'>“Nie przejda, póki kapitan Faramir stoi na czele swego oddzialu.” — Mablung, Dwie Wieze</p>");
            AddHtml("Squire-of-the-Mark-CoE", "<p class='main-text'><b>Odpowiedz:</b> Kiedy kontrolowany przez ciebie sprzymierzeniec z cecha <b><i>Rohan</i></b> zostanie odrzucony z gry, dodaj Giermka Marchii do puli zwyciestwa, aby umiescic w grze odrzuconego sprzymierzenca i wyczerpac go.</p><p class='flavor-text'>“Niewielkie uslugi moge oddac waszemu Wladcy, lecz przez pamiec dzielnego Boromira zrobie wszystko, co w mojej mocy.”<br/>— Pippin, Powrót Króla</p>");
            AddHtml("Rammas-Lookout-CoE", "<p class='main-text'>Oddany.</p><p class='main-text'>Kiedy kazdy kontrolowany przez ciebie bohater posiada w swojej puli zasobów co najmniej 1 zeton zasobów, Czujka Rammasu otrzymuje +1{Willpower} i nie zostaje wyczerpana, gdy zostaje przydzielona do wyprawy.</p><p class='flavor-text'>“Cokolwiek bowiem sie zdarzy, zbliza sie koniec Gondoru takiego, jaki znaliscie dotychczas. Nie zatrzymujcie mnie!”<br/>— Gandalf, Powrót Króla</p>");
            AddHtml("Theodwyn-CoE", "<p class='main-text'><b>Odpowiedz:</b> Kiedy Théodwyna wchodzi do gry, dobierz karte lub dodaj 1 zeton zasobów do puli zasobów bohatera z cecha <b><i>Szlachcic</i></b>.</p><p class='flavor-text'>“To serce nieulekle i szlachetne. Wszyscy ja miluja. Niech ona panuje plemieniu Eorla przez czas twojej nieobecnosci, królu!” — Háma, Dwie Wieze</p>");
            AddHtml("Light-footed-Steed-CoE", "<p class='main-text'>Dolacz do bohatera z cecha <b><i>Rohan</i></b>. Ograniczenie.</p><p class='main-text'><b>Odpowiedz:</b> Kiedy kontrolowana przez ciebie postac opusci gre, wyczerp Chyzego Rumaka, aby przygotowac bohatera, do którego dolaczono Chyzego Rumaka. Jesli postac, która opuscila gre byla unikatowa, bohater, do którego dolaczono Chyzego Rumaka otrzymuje +1 {Attack} do konca rundy.</p><p class='flavor-text'>“Nie zapominaj przy tym o ich koniach! Te zwierzaki podobno dostrzegaja nawet drzenie powietrza w ciemnosciach.”<br/>— Ugluk, Dwie Wieze</p>");
            AddHtml("Rammas-Sentry-CoE", "<p class='main-text'>Oddany.</p><p class='main-text'>Kiedy kazdy kontrolowany przez ciebie bohater posiada w swojej puli zasobów co najmniej 1 zasób, Straznik Rammasu otrzymuje: “<b>Odpowiedz:</b> Anuluj 1 obrazenie wlasnie zadane postaci z cecha <b><i>Gondor</i></b>. (Limit raz na faze.)”</p><p class='flavor-text'>“Jesli my sie zalamiemy, któz sie ostoi?” — Beregond, Powrót Króla</p>");
            AddHtml("Live-Bait-CoE", "<p class='main-text'>Zagraj tylko jesli kontrolujesz niedolaczony do zadnej karty dodatek z cecha <b><i>Pulapka</i></b>.</p><p class='main-text'><b>Akcja:</b> Wybierz nieunikatowego wroga znajdujacego sie w grze. Do konca rundy traktuj pole tekstowe tego wroga tak, jakby bylo puste (za wyjatkiem <b><i>Cech</i></b>). Nastepnie dolacz do tego wroga kontrolowany przez ciebie i niedolaczony do zadnej karty dodatek z cecha <b><i>Pulapka</i></b>.</p>");
            AddHtml("Worthy-of-Remembrance-CoE", "<p class='main-text'><b>Akcja Walki:</b> Odrzuc kontrolowanego przez ciebie sprzymierzenca z cecha <b><i>Rohan</i></b> i wybierz wroga. Zadaj 2 obrazenia temu wrogowi (4 obrazenia jesli odrzucony sprzymierzeniec byl unikatowy).</p><p class='flavor-text'>“Nagle serce jej odmienilo sie, a moze tylko w tym momencie zrozumiala, ze odmienilo sie juz przedtem. W nim takze zima ustapila wiosnie.” — Powrót Króla</p>");
            AddHtml("Need-Brooks-No-Delay-CoE", "<p class='main-text'>Zredukuj koszt Lepiej pózno niz nigdy o 1 za kazdego kontrolowanego przez ciebie bohatera z cecha <b><i>Rohan</i></b>.</p><p class='main-text'>Akcja Planowania: Przeszukaj 10 wierzchnich kart swojej talii, wybierz karte o koszcie 2 lub mniej (3 lub mniej jesli wybrana karta jest unikatowa) i umiesc ja na bok, poza gre. Potasuj swoja talie. Zagraj odlozona karte nie placac jej kosztu tak jakby byla na twojej rece.</p>");
            AddHtml("Wild-Country-CoE", "<p class='main-text'>Zguba 1. Rozlegly.</p><p class='main-text'><b>Wymuszony:</b> Pod koniec fazy Podrózy, jesli aktywny obszar nie posiada slowa kluczowego Rozlegly, kazdy gracz zadaje 1 obrazenie kontrolowanej przez siebie postaci.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli aktywny obszar posiada slowo kluczowe Rozlegly, zadaj 1 obrazenie broniacej sie postaci.</p>");
            AddHtml("Endless-Grasslands-CoE", "<p class='main-text'>Rozlegly.</p><p class='main-text'><b>Wymuszony:</b> Pod koniec fazy Podrózy, jesli aktywny obszar nie posiada slowa kluczowego Rozlegly, kazdy gracz wyczerpuje 1 kontrolowanego przez siebie sprzymierzenca.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli aktywny obszar posiada slowo kluczowe Rozlegly, atakujacy wróg atakuje ponownie.</p>");
            AddHtml("Windworn-Villages-CoE", "<p class='main-text'>Rozlegly.</p><p class='main-text'><b>Wymuszony:</b> Pod koniec fazy Podrózy, jesli aktywny obszar nie posiada slowa kluczowego Rozlegly, kazdy gracz odrzuca 1 karte ze swojej reki.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli aktywny obszar posiada slowo kluczowe Rozlegly, odrzuc 1 dodatek z broniacej sie postaci.</p>");
            AddHtml("Humpbacked-Downs-CoE", "<p class='main-text'>Rozlegly.</p><p class='main-text'><b>Wymuszony:</b> Pod koniec fazy Podrózy, jesli aktywny obszar nie posiada slowa kluczowego Rozlegly, kazdy gracz zwieksza swój poziom zagrozenia o 1.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli aktywny obszar posiada slowo kluczowe Rozlegly, podnies swój poziom zagrozenia o 2.</p>");
            AddHtml("Ride-Through-the-Night-CoE", "<p class='main-text'><b>Po odkryciu:</b> Wyczerp kazdy kontrolowany przez graczy dodatek ze slowem kluczowym Ograniczenie. Jesli nie wyczerpano w ten sposób zadnego dodatku, Nocna przejazdzka otrzymuje mroczna fale.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli aktywny obszar posiada slowo kluczowe Rozlegly, broniaca sie postac do konca rundy nie moze zostac przygotowana.</p>");
            AddHtml("The-Green-Sea-CoE", "<p class='flavor-text'>Ziemie Rohanu sa rozlegle i bezkresne, wyczerpujace nawet dla najsilniejszych koni Zachodniej Bruzdy.</p><p class='main-text'>Obszary ze slowem kluczowym Rozlegly otrzymuja +3 punkty wyprawy i sa odporne na efekty kart graczy.</p><p class='main-text'><b>Wymuszony:</b> Jesli na poczatku fazy Podrózy nie ma zadnego obszaru ze slowem kluczo-wym Rozlegly, odrzucaj wierzchnia karte z talii Spotkan, dopóki nie odrzucisz obszaru ze slowem kluczowym Rozlegly. Dodaj ten obszar do strefy przeciwnosci.</p>{victory:10}");
            AddHtml("Cold-from-the-Mountains-CoE", "<p class='main-text'><b>Po odkryciu:</b> Kazdy gracz kontrolujacy wiecej niz 2 sprzymierzenców musi odrzucic kontrolowanego przez siebie sprzymierzenca (2 sprzymierzenców jesli kontroluje wiecej niz 5 sprzymierzenców).</p>{shadow}<p class='shadow-text'><b>Cien:</b> Wyczerp kontrolowana przez ciebie postac.</p><p class='flavor-text'>“Niech sobie ktos nazywa to zawieja, jesli taka jego wola.”<br/>— Boromir, Druzyna Pierscienia</p>");
            AddHtml("Exhausting-Winds-CoE", "<p class='main-text'><b>Po odkryciu:</b> Zadaj 1 obrazenie kazdej postaci z co najmniej 2 punktami wytrzymalosci. Wyczerp kazda postac, która nie otrzymala w ten sposób obrazen.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Po tym ataku przydziel X obrazen broniacej sie postaci. X to pozostale punkty wytrzymalosci tej postaci minus 1.</p>");
            AddHtml("Tired-and-Hungry-CoE", "<p class='main-text'>Kiedy Zmeczony i Glodny jest dolaczony do bohatera, traktuj te karte jako dodatek z cecha <b><i>Stan</i></b> o tresci: “<b>Wymuszony:</b> Kiedy obszar zostanie zbadany, wyczerp bohatera, do którego dolaczono te karte.”</p><p class='main-text'><b>Po odkryciu:</b> Dolacz do przygotowanego bohatera, który nie ma dolaczonej karty Zmeczony i Glodny. W przeciwnym przypadku, Zmeczony i Glodny otrzymuje mroczna fale.</p><p class='flavor-text'>“Przed nami wrogi, za nami — strach,<br/>Pod niebem nieraz przyjdzie nam spac” — Druzyna Pierscienia</p>");
            AddHtml("Exposed-to-the-Elements-CoE", "<p class='flavor-text'>Twoja druzyna jest zdana na laske deszczu i glodu. Musisz szukac schronienia dla chocby odrobiny odpoczynku.</p><p class='main-text'><b>Wymuszony:</b> Pod koniec kroku odkrywania przeciwnosci, odrzucaj karty z talii Spotkan, dopóki nie odrzucisz podstepu. Odkryj ten podstep.</p>{victory:10}");
            AddHtml("Old-Farmhouse-CoE", "<p class='main-text'><b>Wymuszony:</b> Kiedy Stara Farma opusci gre jako zbadany obszar, odrzucaj karty z talii Spotkan, dopóki nie odrzucisz obszaru. Dodaj ten obszar do strefy przeciwnosci.</p><p class='flavor-text'>“…o niespelna cwierc mili od goscinca, zbójcy natkneli sie na przeszkode: droge zagradzal ciezki przewrócony wóz chlopski. To wstrzymalo pochód.” — Powrót Króla</p>");
            AddHtml("Abandoned-Mill-CoE", "<p class='main-text'>Zguba 1. Odporny na efekty kart Graczy.</p><p class='main-text'><b>Wymuszony:</b> Kiedy Opuszczony Mlyn opusci gre jako zbadany obszar, odrzucaj karty z talii Spotkan, dopóki nie odrzucisz wroga. Dodaj tego wroga do strefy przeciwnosci.</p><p class='flavor-text'>“…zeby mlec, trzeba miec ziarno, a do nowego mlyna nie dostarczano go wiecej niz do starego.” — Powrót Króla</p>");
            AddHtml("Dunland-Chieftain-CoE", "<p class='main-text'><b>Wymuszony:</b> Kiedy Dunlandzki Wódz wejdzie z toba w zwarcie, odrzuc losowa karte ze swojej reki. Nastepnie odrzuc wszystkie kopie tej karty ze swojej reki lub znajdujace sie pod twoja kontrola.</p><p class='flavor-text'>“Nienawidza nas i ciesza sie…” – Gamling, Dwie Wieze</p>{victory:1}");
            AddHtml("Wild-Ravager-CoE", "<p class='main-text'><b>Wymuszony:</b> Na poczatku fazy Spotkan, losowo wybierz gracza. Dziki Grabiezca wchodzi w zwarcie z tym graczem.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Atakujacy wróg do konca rundy nie moze otrzymac obrazen.</p>");
            AddHtml("Dunlending-Berserker-CoE", "<p class='main-text'><b>Wymuszony:</b> Kiedy Dunlandzki Berserker wejdzie z toba w zwarcie, zadaj 1 obrazenie kontrolowanemu przez ciebie bohaterowi oraz nieunikatowemu wrogowi znajdujacemu sie z toba w zwarciu.</p><p class='flavor-text'>“Nie ustapia ani o zmierzchu, ani o swicie…”<br/>— Gamling, Dwie Wieze</p>");
            AddHtml("Hillman-Scout-CoE", "<p class='main-text'>Lucznictwo 2.</p><p class='main-text'><b>Wymuszony:</b> Kiedy Zwiadowca ze wzgórz wejdzie z toba w zwarcie, wyczerp kontrolowanego przez ciebie sprzymierzenca o najwyzszym koszcie.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Wyczerp kontrolowana przez ciebie postac z 3 lub wiecej {Attack}.</p>");
            AddHtml("Surprise-Attack-CoE", "<p class='main-text'>Mroczna fala.</p><p class='main-text'><b>Po odkryciu:</b> Nastepny wróg, który wejdzie w zwarcie w tej rundzie, do konca rundy nie moze otrzymywac obrazen i cofa sie do strefy przeciwnosci po wykonaniu ataku.</p><p class='flavor-text'>“…nim dwaj przesladowcy, którzy wypadli z zasadzki, odetna mu droge. Widzial ich teraz wyraznie…”<br/>— Druzyna Pierscienia</p>");
            AddHtml("A-History-of-Strife-CoE", "<p class='flavor-text'>Dunlendingowie zywia zamierzchla uraze do obcych. Chca was zaskoczyc, pladrujac wasze zapasy, zanim zostawia was na smierc.</p><p class='main-text'>Mroczna fala.</p><p class='main-text'>Kazdy wróg z cecha <b><i>Dunland</i></b> otrzymuje: “<b>Wymuszony:</b> Kiedy ten wróg wejdzie z toba w zwarcie, odrzuc 1 zeton zasobów z puli zasobów kontrolowanego przez ciebie bohatera.”</p>{victory:10}");
            AddHtml("Recreant-Rider-CoE", "<p class='main-text'><b>Wymuszony:</b> Kiedy Zdradliwy Jezdziec wchodzi do strefy przeciwnosci, wykonuje natychmiastowy atak przeciwko pierwszemu graczowi.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Po tym ataku cofnij atakujacego wroga do strefy przeciwnosci.</p>");
            AddHtml("Deadly-Defector-CoE", "<p class='main-text'><b>Wymuszony:</b> Pod koniec fazy Walki, jesli Zabójczy Dezerter znajduje sie w strefie przeciwnosci, wykonuje natychmiastowy atak przeciwko pierwszemu graczowi.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli atakujacy wróg znajduje sie w strefie przeciwnosci, wykonuje dodatkowy atak.</p>");
            AddHtml("Orc-Battalion-CoE", "<p class='main-text'>Zastep Orków nie moze otrzymywac obrazen jesli atakuja go mniej niz 3 postacie.</p><p class='main-text'><b>Wymuszony:</b> Kiedy postac zostanie zadeklarowana jako atakujacy przeciwko Zastepowi Orków, zadaj 1 obrazenie tej postaci.</p>");
            AddHtml("Servant-of-the-Eye-CoE", "<p class='main-text'>Zguba 1.</p><p class='main-text'><b>Wymuszony:</b> Kiedy Sluga Oka cie atakuje, podnies swój poziom zagrozenia o 1.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Podnies swój poziom zagrozenia o 2.</p>");
            AddHtml("Black-Land-Scouts-CoE", "<p class='main-text'><b>Wymuszony:</b> Na poczatku fazy Walki podnies swój poziom zagrozenia o 1 lub rozdziel 4 obrazenia znajdujacym sie w grze postaciom.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Zadaj 2 obrazenia kontrolowanej przez ciebie postaci.</p>");
            AddHtml("Orcish-Horse-butcher-CoE", "<p class='main-text'><b>Wymuszony:</b> Kiedy Orkowy Rzeznik Koni zada obrazenia postaci, odrzuc dodatek dolaczony do tej postaci lub podnies o 1 poziom zagrozenia gracza, który kontroluje te postac.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Odrzuc dodatek, który kontrolujesz lub podnies swój poziom zagrozenia o 3.</p>");
            AddHtml("Crimson-Banner-CoE", "<p class='main-text'>Mroczna fala.</p><p class='main-text'>Kiedy Szkarlatny Sztandar jest dolaczony do wroga, traktuj te karte jako dodatek z cecha <b><i>Stan</i></b> o tresci: “<b>Wymuszony:</b> Pod koniec rundy kazdy gracz podnosi swój poziom zagrozenia o 1 za kazdego wroga z cecha <b><i>Ork</i></b> znajdujacego sie w grze.”</p><p class='main-text'><b>Po odkryciu:</b> Dolacz do nieunikatowego wroga z cecha <b><i>Ork</i></b> o najwyzszym koszcie zwarcia.</p>");
            AddHtml("White-Mountain-Reinforcements-CoE", "<p class='flavor-text'>Orkowie zaczeli wyplywac ze swoich górskich jaskin, wzmacniajac ataki waszych wrogów. Jesli ich nie pokonacie, moga wkrótce was przytloczyc.</p><p class='main-text'><b>Po odkryciu:</b> Kazdy gracz, który nie znajduje sie w zwarciu z zadnym wrogiem przeszukuje talie Spotkan i stos odrzuconych kart Spotkan, wybiera wroga i umieszcza go w zwarciu ze soba. Nastepnie potasuj talie Spotkan.</p><p class='main-text'>Kazda karta cienia bez zadnego efektu cienia otrzymuje: “Cien: Podnies swój poziom zagrozenia o 1.”</p>{victory:10}");
            AddHtml("Brigand-Ringleader-CoE", "<p class='main-text'>Zlupienie 3. Odporny na efekty kart Graczy. Nie moze otrzymac wiecej niz 5 obrazen w jednej rundzie.</p><p class='main-text'><b>Wymuszony:</b> Pod koniec rundy gracz, z którym Herszt Rozbójników znajduje sie w zwarciu, dodaje wierzchnia karte ze swojej talii do stosu lupów Herszta Rozbójników i leczy 1 jego obrazenie za kazdy rózny koszt kart w jego stosie lupów.</p>{victory:10}");
            AddHtml("Plundered-Goods-CoE", "<p class='main-text'>Dodaj 1 do {Threat} strefy przeciwnosci za kazda karte w stosie lupów Spladrowanych Dóbr.</p><p class='main-text'><b>Wymuszony:</b> Kiedy wróg opuszcza gre, dodaj 1 karte ze stosu lupów tego wroga do stosu lupów Spladrowanych Dóbr, nastepnie dodaj inna karte ze stosu lupów tego wroga na reke wlasciciela. Odrzuc reszte kart.</p><p class='flavor-text'>Rozbójnicy zbrojnie zaatakowali wioske oraz zwrócili bron przeciwko wiesniakom.</p>");
            AddHtml("Pillaging-Swordsman-CoE", "<p class='main-text'>Zlupienie 1.</p><p class='main-text'>Szermierz Grabiezca otrzymuje +X {Attack}, gdzie X to najwyzszy wydrukowany koszt karty z jego stosu lupów.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Dodaj 2 wierzchnie karty ze swojej talii do stosu lupów atakujacego wroga.</p>");
            AddHtml("Grasping-Slaver-CoE", "<p class='main-text'>Zlupienie 2.</p><p class='main-text'><b>Wymuszony:</b> Kiedy sprzymierzeniec otrzyma obrazenia lub zostaje zabity przez atak Lowcy Niewolników, dodaj tego sprzymierzenca do stosu lupów Lowcy Niewolników.</p><p class='main-text'><b>Wymuszony:</b> Kiedy Lowca Niewolników atakuje, przydziel X obrazen postaciom, które kontrolujesz. X to liczba sprzymierzenców w stosie lupów Lowcy Niewolników.</p>");
            AddHtml("Vengeful-Bowman-CoE", "<p class='main-text'>Zlupienie 2. Lucznictwo X.</p><p class='main-text'>X to liczba róznych typów kart gracza w stosie lupów Msciwego Lucznika.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli ten atak zada obrazenia, dodaj wierzchnia karte ze swojej talii do stosu lupów atakujacego wroga.</p>");
            AddHtml("Sneaky-Thief-CoE", "<p class='main-text'>Zlupienie 0. Mroczna fala.</p><p class='main-text'><b>Wymuszony:</b> Jesli Podstepny Zlodziej ma karty w swoim stosie lupów, zamiast przydzielac mu obrazenia odrzuc wszystkie te karty.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli ten atak zabije postac, atakujacy wróg atakuje ponownie.</p>");
            AddHtml("Erelas-Gates-CoE", "<p class='main-text'><b>Podróz:</b> Kazdy gracz musi wybrac wroga i dodac do jego stosu lupów wierzchnia karte ze swojej talii.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Podnies swój poziom zagrozenia o 1 za kazda karte w stosie lupów atakujacego wroga.</p><p class='flavor-text'>“Pogiete, wylamane filary sterczaly rozszczepionymi glowicami…” — Dwie Wieze</p>");
            AddHtml("Crossroads-CoE", "<p class='main-text'><b>Podróz:</b> Wtasuj stos odrzuconych kart Spotkan do talii Spotkan. Odrzucaj karty, dopóki nie odrzucisz wroga. Umiesc tego wroga w zwarciu z pierwszym graczem.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Atakujacy wróg otrzymuje +X {Attack}, gdzie X to liczba róznych sfer wsród kart w stosie lupów atakujacego wroga.</p>");
            AddHtml("Erelas-Stables-CoE", "<p class='main-text'><b>Podróz:</b> Cofnij wroga bedacego w zwarciu z graczem do strefy przeciwnosci.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli atakujacy wróg nie jest unikatowy, po wykonaniu ataku cofnij go do strefy przeciwnosci.</p>");
            AddHtml("Chaos-in-the-Hills-CoE", "<p class='main-text'><b>Po odkryciu:</b> Cofnij wroga o najwyzszym koszcie zwarcia do strefy przeciwnosci. Jesli w ten sposób zaden wróg nie zostal cofniety do strefy przeciwnosci, Chaos Wsród Wzgórz otrzymuje mroczna fale.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Po tym ataku, atakujacy wróg wchodzi w zwarcie z nastepnym graczem i wykonuje natychmiastowy atak.</p>");
            AddHtml("Looted-Weapons-CoE", "<p class='main-text'>Kiedy Zrabowana Bron jest dolaczona do wroga, traktuj te karte jako dodatek z cecha <b><i>Stan</i></b> o tresci: “Wróg, do którego dolaczono te karte otrzymuje +1{Threat} oraz +1{Attack} za kazdy dodatek w jego stosie lupów.”</p><p class='main-text'><b>Po odkryciu:</b> Dolacz do wroga o najwyzszym koszcie zwarcia. Kazdy gracz dodaje kontrolowany przez siebie dodatek z cecha <b><i>Przedmiot</i></b> do stosu lupów tego wroga. Jesli nie ma zadnych wrogów w grze, Zrabowana Bron otrzymuje mroczna fale.</p>");
            AddHtml("Stockpile-Barricade-CoE", "<p class='flavor-text'>Przewrócone wozy i wózki tworzyly mocna barykade w poprzek drogi.</p><p class='main-text'>Mroczna fala.</p><p class='main-text'>Kazdy wróg otrzymuje +1{Defense} za kazdy dodatek w swoim stosie lupów.</p><p class='main-text'><b>Wymuszony:</b> Jesli podczas rozpatrywania slowa kluczowego Zlupienie z karty wroga nie ma zadnych dodatków w stosie lupów tego wroga, to ten wróg wykonuje natych-miastowy atak przeciwko graczowi, z którym znajduje sie w zwarciu.</p>{victory:10}");
            AddHtml("Erelas-Beacon-CoE", "<p class='main-text'><b>Wymuszony:</b> Pod koniec fazy Walki Wzgórze Sygnalowe Erelas otrzymuje 1 obrazenie za kazdego wroga w strefie przeciwnosci.</p><p class='main-text'><b>Wzgórze Sygnalowe Erelas posiada X punktów wytrzymalosci, gdzie X to 2+3{PerPlayer}. Jesli Wzgórze Sygnalowe Erelas straci wszystkie punkty wytrzymalosci, gracze przegrywaja gre.</b></p><p class='flavor-text'>“Kraj wokól byl szary i cichy, tylko w miare jak sie posuwali, cien gestnial, a nadzieja slabla we wszystkich sercach.”<br/>— Powrót Króla</p>");
            AddHtml("Host-of-Rohan-CoE", "<p class='main-text'>Wartownik.</p><p class='main-text'><b>Akcja:</b> Gracze jako grupa moga wydac 2 zetony zasobów, aby przygotowac Zastep Rohanu. (Limit raz na faze.)</p><p class='flavor-text'>“…w tych stronach trwa wojna, a Rohirrimowie, hodowcy i mistrzowie koni, nie spia…”<br/>— Gandalf, Dwie Wieze</p>");
            AddHtml("Enraged-Dunlending-CoE", "<p class='main-text'><b>Wymuszony:</b> Kiedy Wsciekly Dunlending wejdzie z toba w zwarcie, zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Obrazenia zadane tym atakiem przydziel Wzgórzu Sygnalowemu Erelas.</p>");
            AddHtml("Bald-Hill-CoE", "<p class='main-text'>Kiedy gracze kontroluja Wzgórze Sygnalowe, Lyse Wzgórze otrzymuje +3{Threat}.</p><p class='main-text'><b>Podróz:</b> Jesli gracze kontroluja Wzgórze Sygnalowe, zadaj 2 obrazenia Wzgórzu Sygnalowemu Erelas.</p><p class='flavor-text'>“Kiedy w koncu dotarli na gran szarego wzgórza, nagly powiew rozburzyl im wlosy i zalopotal polami plaszczy. Swit dmuchnal im chlodem w twarze.” — Dwie Wieze</p>");
            AddHtml("Wooden-Barricade-CoE", "<p class='main-text'>Kiedy Drewniana Barykada znajduje sie w strefie przeciwnosci, otrzymuje: “<b>Wymuszony:</b> Pod koniec fazy Walki zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas i umiesc 1 zeton postepu na Drewnianej Barykadzie.”</p>{shadow}<p class='shadow-text'><b>Cien:</b> Odrzuc 2 kontrolowane przez ciebie dodatki lub zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p>");
            AddHtml("Rocky-Slope-CoE", "<p class='main-text'>Kiedy efekt karty Spotkania zostanie anulowany, zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p><p class='main-text'><b>Podróz:</b> Pierwszy gracz musi odrzucic wszystkie karty wydarzen ze swojej reki.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Odrzuc wszystkie zetony zasobów z puli zasobów wszystkich kontrolowanych przez ciebie bohaterów lub przydziel 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p>");
            AddHtml("Surrounding-Grassland-CoE", "<p class='main-text'>Lucznictwo 1.</p><p class='main-text'><b>Wymuszony:</b> Kiedy Okoliczne Pastwiska opuszcza gre jako zbadany obszar, jesli nie ma zadnych kopii Okolicznych Pastwisk w strefie przeciwnosci, cofnij ten Obszar do strefy przeciwnosci.</p><p class='flavor-text'>“…otwieral sie ponad potokiem widok na zielony step Rohanu ginacy w szarej dali.” — Dwie Wieze</p>");
            AddHtml("Narrow-Stair-CoE", "<p class='main-text'>Kazdy gracz moze zadeklarowac nie wiecej niz 1 atak oraz nie wiecej niz 1 atakujacego w kazdej fazie.</p><p class='main-text'>Kiedy Waskie Schody sa aktywnym obszarem, kazdy gracz moze obronic nie wiecej niz 1 atak na faze (pozostale ataki sa niebronione).</p>{shadow}<p class='shadow-text'><b>Cien:</b> Atakujacy wróg otrzymuje +3{Attack} lub zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p>");
            AddHtml("From-All-Sides-CoE", "<p class='main-text'><b>Po odkryciu:</b> Kazdy gracz musi wybrac: przydzielic po 1 obrazeniu 4 róznym kontrolowanym przez siebie postaciom lub zadac 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Po tym ataku, odrzuc broniaca sie postac lub zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p>");
            AddHtml("Another-Wave-CoE", "<p class='main-text'>Mroczna fala. Zguba 1.</p><p class='main-text'><b>Po odkryciu:</b> Jesli gracze kontroluja Wzgórze Sygnalowe, zadaj 2 obrazenia Wzgórzu Sygnalowemu Erelas lub odkryj karte Spotkania.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Atakujacy wróg atakuje ponownie lub zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p>");
            AddHtml("Assault-Upon-Erelas-CoE", "<p class='main-text'><b>Po odkryciu:</b> Pierwszy gracz wybiera wroga bedacego w zwarciu z dowolnym graczem i cofa go do strefy przeciwnosci. Jesli zaden wróg nie zostal w ten sposób cofniety do strefy przeciwnosci, zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas lub Atak na Erelas otrzymuje mroczna fale.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Podnies swój poziom zagrozenia o 4 lub zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p>");
            AddHtml("Reclaim-the-Beacon-CoE", "<p class='flavor-text'>Przejmij Wzgórze Sygnalowe, zeby Dunlendingowie go nie zniszczyli albo gorzej!</p><p class='main-text'>Dunlendingowie kontroluja Wzgórze Sygnalowe. Wrogowie w strefie przeciw-nosci nie moga opcjonalnie wchodzic w zwarcie lub otrzymywac obrazen.</p><p class='main-text'>Nie moze miec wiecej niz X zetonów postepu, gdzie X to 2+1{PerPlayer}. Jesli Odzyskac Wzgórze Sygnalowe ma na sobie X zetonów postepu, odwróc te karte (zachowujac wszystkie zetony postepu).</p>");
            AddHtml("Stolen-Steeds-CoE", "<p class='main-text'>Cele z cecha <b><i>Wierzchowiec</i></b> nie moga zostac odrzucone lub opuscic gry. Jesli cel z cecha <b><i>Wierzchowiec</i></b> nie jest dolaczony do zadnej karty, gracze musza ja zdobyc i dolaczyc do bohatera, którego kontroluja.</p><p class='main-text'><b>Wymuszony:</b> Pod koniec rundy dodaj na glówna wyprawe 1 zeton postepu za kazdy kontrolowany przez graczy cel z cecha <b><i>Wierzchowiec</i></b>. Nastepnie podnies poziom zagrozenia kazdego gracza o 1 za kazdy cel z cecha <b><i>Wierzchowiec</i></b>, którego gracze nie kontroluja.</p>");
            AddHtml("Flinthoof-CoE", "<p class='main-text'>Strzezony (wróg). Ograniczenie.</p><p class='main-text'>Wróg strzegacy Krzemyka otrzymuje +1{Attack}.</p><p class='main-text'>Bohater, do którego dolaczono te karte, otrzymuje +1{Attack}.</p><p class='main-text'><b>Akcja Walki:</b> Wyczerp Krzemyka i zadaj 1 obrazenie wrogowi znajdujacemu sie w grze.</p><p class='flavor-text'>“…dlugie ogony rozwiewaly sie na wietrze, splecione grzywy zdobily dumne karki.” — Dwie Wieze</p>");
            AddHtml("Brightmane-CoE", "<p class='main-text'>Strzezony (obszar). Ograniczenie.</p><p class='main-text'>Obszar lub wróg strzegacy Jasnogrzywego otrzymuje +1{Threat}.</p><p class='main-text'>Bohater, do którego dolaczono te karte, otrzymuje +1{Willpower}.</p><p class='main-text'><b>Akcja Wyprawy:</b> Wyczerp Jasnogrzywego, aby podejrzec wierzchnia karte talii Spotkan. Jesli to obszar, mozesz go odrzucic.</p>");
            AddHtml("Felarof-CoE", "<p class='main-text'>Strzezony (wróg). Ograniczenie.</p><p class='main-text'><b>Wymuszony:</b> Kiedy wróg strzegacy Felarófa atakuje, rozdaj mu 2 dodatkowe karty cienia.</p><p class='main-text'><b>Akcja:</b> Wyczerp Felarófa, aby odrzucic zakryta karte cienia.</p><p class='flavor-text'>“…na przodzie cwaluje inny jeszcze kon, ogromny. Nie spotkalem jeszcze w zyciu takiego rumaka.”<br/>— Legolas, Dwie Wieze</p>");
            AddHtml("Thruk-CoE", "<p class='main-text'>Odporny na efekty kart graczy. Thruk wchodzi w zwarcie z pierwszym graczem.</p><p class='main-text'><b>Wymuszony:</b> Na poczatku fazy Walki, jesli Thruk nie strzeze zadnego celu, wykonuje natychmiastowy atak przeciwko graczowi, z którym znajduje sie w zwarciu.</p>{victory:10}");
            AddHtml("Saddle-slasher-CoE", "<p class='main-text'>Lucznictwo X. X to 2+1 za kazdy cel z cecha <b><i>Wierzchowiec</i></b> kontrolowany przez graczy.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Jesli kontrolujesz cel z cecha <b><i>Wierzchowiec</i></b>, dolacz ten cel do atakujacego wroga lub odrzuc broniaca sie postac po rozstrzygnieciu ataku.</p>");
            AddHtml("Rein-ripper-CoE", "<p class='main-text'><b>Wymuszony:</b> Kiedy Rozpruwacz Cugli atakuje, rozdaj mu 2 dodatkowe karty cienia. Jezeli kontrolujesz cel z cecha <b><i>Wierzchowiec</i></b>, mozesz go dolaczyc do Rozpruwacza Cugli jako strzezony cel, aby anulowac ten efekt.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Atakujacy wróg otrzymuje +1{Attack} za kazdy cel z cecha <b><i>Wierzchowiec</i></b> kontrolowany przez graczy.</p>");
            AddHtml("Bridle-biter-CoE", "<p class='main-text'>Mroczna fala.</p><p class='main-text'><b>Po odkryciu:</b> Kasacz Uzd wchodzi w zwarcie z graczem, który kontroluje najwiecej celów z cecha <b><i>Wierzchowiec</i></b>.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Umiesc Kasacza Uzd w grze z toba w zwarciu i rozdaj mu karte cienia.</p>");
            AddHtml("Pommel-pouncer-CoE", "<p class='main-text'>Kiedy Wysadzacz Jezdzców znajduje sie w strefie przeciwnosci bez dolaczonego do niego celu z cecha <b><i>Wierzchowiec</i></b>, otrzymuje: “<b>Wymuszony:</b> Kiedy gracz mialby przejac kontrole nad celem z cecha <b><i>Wierzchowiec</i></b>, dolacz ten cel z cecha <b><i>Wierzchowiec</i></b> do Wysadzacza Jezdzców jako strzezony cel.”</p>");
            AddHtml("Spoiled-Pasture-CoE", "<p class='main-text'>X to 2+2 za kazdy cel z cecha <b><i>Wierzchowiec</i></b> kontrolowany przez graczy.</p><p class='main-text'><b>Wymuszony:</b> Kiedy gracz straci kontrole nad celem z cecha <b><i>Wierzchowiec</i></b>, podnies jego poziom zagrozenia o 1.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Podnies swój poziom zagrozenia o 1 za kazdy kontrolowany przez ciebie cel z cecha <b><i>Wierzchowiec</i></b>.</p>");
            AddHtml("Horse-Thieves'-Hovel-CoE", "<p class='main-text'>Kiedy gracze maja mozliwosc Podrózy, musza podrózowac na obszar bez slowa kluczowego Rozlegly.</p><p class='main-text'><b>Wymuszony:</b> Kiedy Nora Koniokradów opusci gre jako zbadany obszar, jesli w grze znajduje sie mniej niz 1{PerPlayer} wrogów, odrzucaj karty z talii Spotkan, dopóki nie odrzucisz wroga. Dodaj tego wroga do strefy przeciwnosci.</p>{victory:2}");
            AddHtml("Horse-Lord's-Lodge-CoE", "<p class='main-text'>Kiedy gracze maja mozliwosc Podrózy, musza podrózowac na obszar bez slowa kluczowego Rozlegly.</p><p class='main-text'><b>Wymuszony:</b> Kiedy Kwatera Wladcy Koni opusci gre jako zbadany obszar, jesli w grze znajduje sie mniej niz 1{PerPlayer} obszary, odrzucaj karty z talii Spotkan, dopóki nie odrzucisz obszaru. Dodaj ten obszar do strefy przeciwnosci.</p>{victory:2}");
            AddHtml("Thirst-for-Horse-Blood-CoE", "<p class='main-text'><b>Po odkryciu:</b> Kazdy gracz, który kontroluje cel z cecha <b><i>Wierzchowiec</i></b> wybiera: odkryj karte Spotkan lub wybierz wroga o najwyzszym koszcie zwarcia bez dolaczonego dodatku i dolacza cel z cecha <b><i>Wierzchowiec</i></b> do tego wroga jako strzezony cel. Jesli zaden gracz nie kontroluje celu z cecha <b><i>Wierzchowiec</i></b>, Pragnienie Konskiej Krwi otrzymuje mroczna fale.</p><p class='flavor-text'>“Bedziemy wkrótce ucztowac i zakosztujemy konskiego miesa, a moze tez innego, lepszego jeszcze.” — Uglúk, Dwie Wieze</p>");
            AddHtml("Overburdened-CoE", "<p class='main-text'><b>Po odkryciu:</b> Kazdy gracz, który kontroluje wiecej niz 2 dodatki musi odrzucic kontrolowany przez siebie dodatek (2 dodatki jesli kontroluje wiecej niz 5 dodatków). Jesli w ten sposób zaden dodatek nie zostal odrzucony, Przeciazony otrzymuje mroczna fale.</p>{shadow}<p class='shadow-text'><b>Cien:</b> Odrzuc 1 losowa karte ze swojej reki.</p>");
            AddHtml("The-Last-Alliance-CoE", "<p class='main-text'>Wybierz dwie cechy, <b><i>A</i></b> i <b><i>B</i></b>. Kazdy z twoich startowych bohaterów i kazdy sojusznik w twojej talii musi miec wydrukowana ceche <b><i>A</i></b> lub <b><i>B</i></b>, ale nie moze miec ich obu. Musisz miec co najmniej 1 startowego bohatera i 10 sprzymierzenców w swojej talii kazdej z wybranych cech.</p><p class='main-text'><b>Przygotowanie:</b> Odwróc te karte.</p><p class='flavor-text'>“Dawnymi czasy elfowie byli silniejsi i stawiali mu opór; ludzie wówczas takze nie wszyscy stronili od elfów.” — Gandalf, Druzyna Pierscienia</p>");
            AddHtml2("The-Last-Alliance-CoE", "<p class='main-text'>Kiedy kontrolujesz wiecej postaci z cecha <b><i>A</i></b> niz postaci z cecha <b><i>B</i></b>, obniz o 1 koszt pierwszego sprzymierzenca z cecha <b><i>B</i></b> zagrywanego przez ciebie podczas kazdej rundy i vice versa.</p><p class='main-text'><b>Akcja:</b> Wyczerp Ostatni Sojusz, aby wybrac karte w twojej rece lub pod twoja kontrola. Az do konca rundy zamien kazde wystapienie “<b><i>A</i></b>” lub “<b><i>B</i></b>” w tresci tej karty na “<b><i>A</i></b> lub <b><i>B</i></b>”.</p>");
            AddHtml("Drive-them-Away-CoE", "<p class='flavor-text'>Podrózujac wzdluz Wielkiego Goscinca Zachodniego natrafiasz na obóz Rohirrimów w cieniu zielonego, lysego wzgórza Erelas. Ale spokój twojej podrózy przerywa nagly atak z cienia! Brzek stali i krzyki ludzi wkrótce docieraja do twoich uszu. Musisz wypedzic najezdzców i ochronic obóz przed dalszymi zniszczeniami!</p><p class='main-text'><b>Przygotowanie:</b> Odlóz Herszta Rozbójników na bok, poza gre. Dodaj Spladrowane Dobra do strefy przeciwnosci. Kazdy gracz przeszukuje talie Spotkan w poszukiwaniu innego wroga i dodaje go do strefy przeciwnosci. Potasuj talie Spotkan.</p>");
            AddHtml2("Drive-them-Away-CoE", "<p class='main-text'><b>Wymuszony:</b> Po zabiciu wroga umiesc tutaj 1 zeton zasobów.</p><p class='main-text'><b>Akcja Spotkania:</b> Usun 5 zetonów postepu z tego etapu, aby wybrac karte ze stosu lupów i odrzucic ja. Limit raz na runde na gracza.</p><p class='main-text'><b>Gracze nie moga przejsc dalej, dopóki na tym etapie nie ma X zetonów zasobów, gdzie X to 1+2{PerPlayer}.</b></p>");
            AddHtml("Ambush-CoE", "<p class='flavor-text'>Walczyles w samym sercu obozowiska, ale bandyci gromadza sie wokól swojego przywódcy i przypuszczaja zaciekly atak.</p><p class='main-text'><b>Po odkryciu:</b> Zakoncz biezaca faze. Dodaj Herszta Rozbójników do strefy przeciwnosci. Kazdy gracz, który nie jest w zwarciu z wrogiem, przeszukuje talie Spotkan oraz stos odrzuconych kart Spotkan w poszukiwaniu wroga, który wchodzi z nim w zwarcie. Potasuj talie Spotkan. <b></p>");
            AddHtml2("Ambush-CoE", "<p class='main-text'><b>Wymuszony:</b> Kazdy wróg w momencie wejscia do gry wykonuje natychmiastowy test zwarcia.</p><p class='main-text'><b>Akcja Planowania:</b> Usun 5 zetonów postepu z obecnej karty wyprawy, aby wybrac karte ze stosu lupów. Wlasciciel tej karty moze ja odrzucic lub zagrac bez placenia za jej koszt. Limit cztery razy na runde dla grupy.</p><p class='main-text'><b>Kiedy Herszt Rozbójników zostanie pokonany, gracze wygrywaja.</b></p>");
            AddHtml("Battle-for-the-Hill-CoE", "<p class='flavor-text'>Dunlendingowie i zdradzieccy Rohirrimowie zdobyli wzgórze sygnalowe Erelas. Odzyskaj wzgórze za wszelka cene!</p><p class='main-text'><b>Przygotowanie:</b> Odlóz Zastep Rohanu na bok, poza gre. Dodaj Wzgórze Sygnalowe Erelas i 1{PerPlayer} Wsciekly Dunlending do strefy przeciwnosci. Dodaj poboczna wyprawe Odzyskac Wzgórze Sygnalowe do strefy przeciwnosci. Przeszukaj talie Spotkan w poszukiwaniu 1 kopii karty Okoliczne Pastwiska i uczyn ja aktywnym obszarem. Potasuj talie Spotkan.</p>");
            AddHtml2("Battle-for-the-Hill-CoE", "<p class='main-text'><b>Wymuszony:</b> Po umieszczeniu dowolnej liczby zetonów postepu na tym etapie, kazdy gracz musi wybrac: albo wyczerpuje kontrolowana przez siebie postac, albo zadaje 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p><p class='main-text'><b>Ten etap nie moze zostac ukonczony, jezeli Dunlendingowie kontroluja Wzgórze Sygnalowe.</b></p>");
            AddHtml("Hold-the-Hilltop-CoE", "<p class='flavor-text'>Gdy twoi wrogowie zbieraja sie do kolejnego ataku na wzgórze sygnalowe, mozesz dostrzec pochodnie zolnierzy Gálmóda gromadzacych sie posród wzgórz ponizej.</p><p class='main-text'><b>Po odkryciu:</b> Umiesc zetony postepu na karcie Obronic Wzgórze Sygnalowe (pomijajac aktywny obszar), dopóki nie bedzie na niej X zetonów postepu, gdzie X to 2+1{PerPlayer}. Wtasuj stos odrzuconych kart Spotkan do talii Spotkan. Kazdy gracz odrzuca karty z wierzchu talii Spotkan, dopóki nie zostanie odrzucony wróg, a nastepnie dodaje go do strefy przeciwnosci.</p>");
            AddHtml2("Hold-the-Hilltop-CoE", "<p class='main-text'>Czas 3.</p><p class='main-text'><b>Wymuszony:</b> Na koniec rundy zadaj 1 obrazenie Wzgórzu Sygnalowym Erelas (jesli w grze jest 3 lub wiecej graczy zadaj 2 obrazenia). Nastepnie, jesli na tym etapie nie ma znacznika czasu, natychmiast przejdz do etapu 3.</p><p class='main-text'><b>Wymuszony:</b> Po wybraniu opcji Obronic Wzgórze Sygnalowe jako biezacej przygody odkryj karte spotkania.</p><p class='main-text'><b>Jesli Dunlendingowie kontroluja Wzgórze Sygnalowe, gracze przegrywaja.</b></p>");
            AddHtml("The-Last-Push-CoE", "<p class='flavor-text'>Gdy sily Gálmóda spiesza by oflankowac wroga, musicie przygotowac sie na ostatnia walke.</p><p class='main-text'><b>Po odkryciu:</b> Usun wszystkie zetony postepu z karty Obronic Wzgórze Sygnalowe i odwróc ja. Umiesc Zastep Rohanu w grze pod kontrola pierwszego gracza. Wtasuj stos odrzuconych kart Spotkan do talii Spotkan. Kazdy gracz odrzuca karty z wierzchu talii Spotkan, dopóki nie zostanie odrzucony wróg, a nastepnie dodaje go do strefy przeciwnosci.</p>");
            AddHtml2("The-Last-Push-CoE", "<p class='flavor-text'> Jesli uda ci sie odzyskac Krzemyka oraz Jasnogrzywego, byc moze bedziesz w stanie powstrzymac glówne sily orków, zanim dotra do Aldburga.</p><p class='main-text'>Dodaj 2 do calkowitego {Threat} w strefie przeciwnosci za kazdy zeton obrazen znajdujacy sie na karcie Wzgórze Sygnalowe Erelas.</p><p class='main-text'><b>Wymuszony:</b> Na poczatku fazy walki kazdy wróg bedacy w zwarciu wykonuje natychmiastowy atak.</p><p class='main-text'><b>Wymuszony:</b> Po opuszczeniu gry przez postac zadaj 1 obrazenie Wzgórzu Sygnalowemu Erelas.</p><p class='main-text'><b>Pod koniec rundy, jesli Dunlendingowie kontroluja Wzgórze Sygnalowe – gracze przegrywaja gre, natomiast jesli gracze kontroluja Wzgórze Sygnalowe – wygrywaja.</b></p>");
            AddHtml("Thieves-and-Coursers-CoE", "<p class='flavor-text'>Orkowie zaatakowali Wschodnia Bruzde, szalejac po calej krainie i porywajac cenne konie bojowe króla Thengela.</p><p class='main-text'><b>Przygotowanie:</b> Dodaj Skradzione Rumaki do strefy przeciwnosci. Odlóz Thruka, karty celów z cecha <b><i>Wierzchowiec</i></b> oraz 8 wrogów z zestawu Spotkan Oddzial Orków poza gre. Potasuj talie Spotkan. Pierwszy gracz odkrywa karty Krzemyk oraz Jasnogrzywy i dodaje je do strefy przeciwnosci. Nastepnie kazdy z pozostalych graczy odrzuca karty z wierzchu talii Spotkan, dopóki nie zostanie odrzucony obszar lub wróg, a nastepnie dodaje go do strefy przeciwnosci.</p>");
            AddHtml2("Thieves-and-Coursers-CoE", "<p class='main-text'><b>Ten etap nie moze zostac ukonczony, jesli gracze nie kontroluja 2 kart celu z cecha <b><i>Wierzchowiec</i></b>.</b></p>");
            AddHtml("The-King's-Stallion-CoE", "<p class='flavor-text'>Wódz orków – Thruk, przybyl na pole bitwy, jadac na poteznym koniu Felarófie i wydajac rozkazy swoim pobratyncom. — Do mnie! — krzyknal donioslym glosem. — Dzis wieczorem zasmakujemy konskiego miesa!</p><p class='main-text'><b>Po odkryciu:</b> Jesli jest to faza walki, zakoncz te faze. Wtasuj stos odrzuconych kart Spotkan do talii Spotkan. Pierwszy gracz dodaje Thruka do strefy przeciwnosci, jako wroga strzegacego Felarófa. Nastepnie kazdy z pozostalych graczy odrzuca karty z wierzchu talii Spotkan, dopóki nie zostanie odrzucony wróg. Gracz umieszcza tego wroga w grze, w zwarciu ze soba.</p>");
            AddHtml2("The-King's-Stallion-CoE", "<p class='main-text'>Thruk nie moze otrzymywac obrazen, jesli na tym etapie nie ma co najmniej 4 zetonów postepu.</p><p class='main-text'><b>Ten etap nie moze zostac ukonczony, chyba ze gracze kontroluja 3 karty celu z cecha <b><i>Wierzchowiec</i></b>.</p>");
            AddHtml("The-Sweeping-Tide-CoE", "<p class='flavor-text'>Caly zastep orków odpowiedzial na wezwanie Thruka. Musicie sie zjednoczyc, by wykonac ostatnie natarcie i rozgromic ich na wzgórzach.</p><p class='main-text'><b>Po odkryciu:</b> Jesli jest to faza walki, zakoncz te faze. Wtasuj stos odrzuconych kart Spotkan do talii Spotkan. Przeszukaj pule zwyciestwa w poszukiwaniu Thruka i dodaj go do strefy przeciwnosci. Kazdy gracz wybiera 2 wrogów z odlozonych na bok kart z zestawu Spotkan Oddzial Orków i umieszcza tych wrogów w grze w zwarciu ze soba. Jednym z wrogów dodanych do gry w ten sposób musi byc Zastep Orków.</p>");
            AddHtml2("The-Sweeping-Tide-CoE", "<p class='main-text'>Pomin krok odkrywania przeciwnosci (Faza wyprawy, krok 2). Jesli w dowolnym momencie gry talia Spotkan sie skonczy, nalezy potasowac stos odrzuconych kart Spotkan w nowa talie Spotkan.</p><p class='main-text'><b>Wymuszony:</b> Kiedy wróg wykonuje atak, otrzymuje dodatkowa karte cienia.</p><p class='main-text'><b>Jesli do wroga dolaczona jest karta celu z cecha <b><i>Wierzchowiec</i></b>, gracze przegrywaja gre. Jesli w grze nie ma wrogów, gracze wygrywaja.</b></p>");
            //AddHtml("Reclaim-the-Beacon-CoE", "<p class='flavor-text'>Przejmij Wzgórze Sygnałowe, żeby Dunlendingowie go nie zniszczyli albo gorzej!</p><p class='main-text'></p><p class='main-text'>Dunlendingowie kontrolują Wzgórze Sygnałowe. Wrogowie w strefie przeciwności nie mogą opcjonalnie wchodzić w zwarcie lub otrzymywać obrażeń.</p><p class='main-text'>Nie może mieć więcej niż X żetonów postępu, gdzie X to 2+1{PerPlayer}. Jeśli Odzyskać Wzgórze Sygnałowe ma na sobie X żetonów postępu, odwróć tę kartę (zachowując wszystkie żetony postępu).</p>");
        }
    }
}