using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Services.LotR.Templates
{
    public class SpanishTemplateRepository : TemplateRepository
    {
        protected override void Initialize()
        {
            //áÁéÉíÍóÓùúûüÙÚÛÜñÑ
            CoreSet();

            ChildrenOfEorl();
            TheAldburgPlot();
        }

        private void CoreSet()
        {
            AddHtml("Aragorn-Core", "<p class='main-text'>{keyword:Centinela.}</p><p class='main-text'><b>Respuesta:</b> Después de que Aragorn sea asignado a una misión, gasta 1 recurso de su reserva de Recursos para prepararlo.</p><p class='flavor-text'>&ldquo;Soy Aragorn hijo de Arathorn y si por la vida o por la muerte puedo salvaros, asi lo hare.&rdquo;<br>&ndash;La Comunidad del Anillo</p>");
            AddHtml("Beravor-Core", "<p class='main-text'><b>Acción:</b> Agota a Beravor para elegir un jugador. Ese jugador roba 2 cartas.</p><p class='flavor-text'>Pero en las tierra salvajes más allá de Bree habia nómadas misteriosos. La gente de Bree los llamaba los Montaraces y no sabia de dónde venian.<br>&mdash;La Communidad del Anillo</p>");
            AddHtml("Beorn-Core", "<p class='main-text'><b>Acción:</b> {self} gana +5 {Attack} hasta el final de la fase. Al final de la fase en la que actives este efecto, devuelve a {self} a tu mazo y barajalo. Limite de una vez por ronda.</p><p class='flavor-text'>&ldquo;No necesito vuestro servicio, gracias... pero espero que vosotros necesiteis del mio.&rdquo;<br>&ndash;El Hobbit</p>");
            AddHtml("Brok-Ironfist-Core", "<p class='main-text'><b>Respuesta:</b> Después de que un Héroe {trait:Enano.@Enano} que controles abandone el juego, pon a {self} en jeugo desde tu mano.</p><p class='flavor-text'>...nadie sabe de lo que es capaz en enano, por venganza o por recobrar lo que le pertenece.<br>&mdash;El Hobbit</p>");
            AddHtml("Dungeon-Torch-Core", "<p class='main-text'>{trait:Guarded.@Protegido.} {trait:Restricted.@Restringido.}</p><p class='main-text'><b>Acción:</b> Aumenta en 2 tu Amenaza para reclamar esta carta de Objetivo cuanto esté libre de Encuentros. Cuando sea reclamada, vincula la Antorcha de la Mazmorra a un Héroe que controles. Cuentra como una carta Vinculada. Si es desvinculada, devuelve la Antorcha de la Mazmorra al área de perparación.</p><p class='main-text'><b>Obligado:</b> Al final de cada ronda, aumenta en 2 la Amenaza del controlador del Héroe vinculado.</p>");
            AddHtml("Forest-Spider-Core", "<p class='main-text'><b>Obligado:</b> Después de que la Araña del Bosque se enfrente a un juador, recibe +1 {Attack} hasta el final de la ronda.</p>{shadow}<p class='shadow-text'><b>Somba:</b> El judador defensor debe elegir y descartar 1 carta Vinculada que controle.</p>");
            AddHtml("Guard-of-the-Citadel-Core", "<p class='flavor-text'>&ldquo;Pero los Senores de Minas Tirith continuan<br>luchando, desafiando a nuestros enemigo,<br>guardando el pasaje del rio, desde Argonath al<br>mar.&rdquo; &ndash;Elrond, La Comunidad del Anillo</p>'");
            AddHtml("Horseback-Archer-Core", "<p class='main-text'>{keyword:Ranged.@A distancia.}</p><p class='flavor-text'>Unos pocos de los jintes paracian ser arqueros,<br>capaces de disparar hábilmente desde un<br>caballo a la carrera. &mdash;Las Dos Torres</p>");
            AddHtml("Silverlode-Archer-Core", "<p class='main-text'>{keyword:Ranged.@A distancia.}</p><p class='flavor-text'>&ldquo;Hemos estado vigilando los rios, desde que vimos<br>una gran tropa de orcos yendo al norte hacia Moria,<br>bordeando las mantañas, hace ya muchos días.&rdquo;<br>&mdash;Haldir de Lórien, La Comunidad del Anillo</p>");
        }

        private void ChildrenOfEorl()
        {
            AddHtml("Ingold-CoE", "<p class='main-text'><b>Respuesta:</b> Después de que un aliado <b><i>Gondor</i></b> o <b><i>Guerrero</i></b> entre en juego bajo tu control, roba 1 carta. Luego, gasta 1 recurso de la reserva de Ingold o bien aumenta tu Amenaza en 1. (Límite de 1 vez por fase.)</p><p class='flavor-text'>“No queremos extranjeros en el país en estos tiempos, a menos que se trate de hombres de armas vigorosos, en cuya lealtad y ayuda podamos confiar.”<br/>—El Retorno del Rey</p>");
            AddHtml("Celador-CoE", "<p class='main-text'>A distancia.</p><p class='main-text'>Reduce la {Threat} total del área de preparación en 1 por cada <b><i>Trampa</i></b> no vinculada que controles.</p><p class='main-text'><b>Respuesta:</b> Después de que una carta <b><i>Trampa</i></b> que controles sea vinculada a un Enemigo, prepara a Celador o bien reduce tu Amenaza en 1.</p><p class='flavor-text'>“Un hombre sabio no se fía de un encuentro casual en estas tierras.”<br/>—Faramir, Las Dos Torres</p>");
            AddHtml("Thengel-CoE", "<p class='main-text'><b>Respuesta:</b> Después de que un aliado sea descartado del juego, el propietario de ese aliado busca entre las 5 primeras cartas de su mazo un aliado que comparta un <b><i>Rasgo</i></b> con el aliado descartado, lo pone en juego agotado, y baraja su mazo. (Límite de una vez por ronda.)</p><p class='flavor-text'>“Amigo mío,” dijo Gandalf, “tú tenías tus caballos, tus hazañas de guerra, y el campo libre…”<br/>—El Retorno del Rey</p>");
            AddHtml("Herubrand-CoE", "<p class='main-text'>Herubrand obtiene +1 {Willpower} por cada héroe que controles con al menos una vinculada restringida.</p><p class='main-text'><b>Respuesta:</b> Después de que un enemigo en el área de preparación sea destruido, roba 1 carta.</p><p class='flavor-text'>“¿Qué es esa carga que lleváis, Hombres de Rohan?”<br/>—Imrahil, El Retorno del Rey</p>");
            AddHtml("Deeping-Bowman-CoE", "<p class='main-text'>Devoto. A distancia.</p><p class='main-text'><b>Acción:</b> Descarta al Arquero del Muro del Bajo para elegir a un enemigo. Hasta el final de la fase, ese enemigo no cuenta su {Defense} mientras se determine el daño de combate.</p><p class='flavor-text'>“Hemos agotado nuestras flechas y dejamos en la empalizada un tendal de orcos.”<br/>—Las Dos Torres</p>");
            AddHtml("Open-the-Gates-CoE", "<p class='main-text'><b>Acción:</b> Busca en las 5 primeras cartas de tu mazo un aliado que comparta un <b><i>Rasgo</i></b> con cada uno de tus héroes y ponlo en juego. Baraja tu mazo. Al final de la fase, si ese aliado sigue en juego, devuélvelo a tu mano.</p><p class='flavor-text'>La noticia de la llegada de Gandalf y Pippin había precedido a los viajeros: fueron admitidos inmediatamente, en silencio y sin interrogatorios.<br/>—El Retorno del Rey</p>");
            AddHtml("Wealth-of-Adventure-CoE", "<p class='main-text'><b>Acción:</b> Busca en tu mazo una carta con el rasgo <b><i>Habilidad</i></b> y añádela a tu mano. Baraja tu mazo.</p><p class='flavor-text'>“Es muy peligroso, Frodo, cruzar la puerta”, solía decirme. “Vas hacia el camino y si no cuidas tus pasos no sabes hacia dónde te arrastrarán.”<br/>—Frodo, La Compañía del Anillo.</p>");
            AddHtml("Feast-of-Plenty-CoE", "<p class='main-text'>El coste de recursos del Banquete Abundante debe pagarse usando la reserva de Recursos de un solo Héroe.</p><p class='main-text'><b>Acción:</b> Prepara y añade 1 recurso a la reserva de Recursos de hasta 3 héroes. Los jugadores sólo pueden jugar 1 copia de Banquete Abundante en cada ronda.</p><p class='flavor-text'>La fiesta era alegre y la comida todo lo que un estómago hambriento pudiese desear.<br/>—La Compañía del Anillo</p>");
            AddHtml("Deeping-Defender-CoE", "<p class='main-text'>Devoto.</p><p class='main-text'><b>Respuesta:</b> Después de que el Defensor del Muro del Bajo defienda un ataque, devuelve el enemigo atacante al área de preparación e inflíngele 1 punto de daño.</p><p class='flavor-text'>El sol poniente doraba las lanzas y los cascos y centelleaba sobre los pálidos cabellos flotantes.<br/>—Las Dos Torres</p>");
            AddHtml("Morwen-Steelsheen-CoE", "<p class='main-text'><b>Acción:</b> Pon a Morwen Resplandor del Acero en juego desde tu mano. A continuación, descarta un aliado <b><i>Rohan</i></b> o <b><i>Gondor</i></b> que controles.</p><p class='main-text'><b>Respuesta:</b> Después de que un aliado <b><i>Rohan</i></b> o <b><i>Gondor</i></b> abandone el juego, agota a Morwen Resplandor del Acero para curar 2 de daño de un personaje o bien reducir tu Amenaza en 1.</p>");
            AddHtml("It-Should-Be-Spared-CoE", "<p class='main-text'><b>Respuesta:</b> Después de que una carta <b><i>Trampa</i></b> que controles sea vinculada a un enemigo, devuélvela a tu mano. Entonces, juégala desde tu mano sin coste alguno.</p><p class='flavor-text'>“Pero yo no mato sin necesidad ni a hombre ni a bestia, y cuando es necesario no lo hago con alegría.”<br/>—Faramir, Las Dos Torres</p>");
            AddHtml("Spring-the-Trap-CoE", "<p class='main-text'><b>Respuesta:</b> Después de que una carta <b><i>Trampa</i></b> que controles sea vinculada a un enemigo, pon un aliado <b><i>Montaraz</i></b> en juego desde tu mano.</p><p class='flavor-text'>“¡Puede que el camino la pase, pero ellos no pasarán! No mientras Faramir sea quien conduzca todas las empresas peligrosas.”<br/>—Mablung, Las Dos Torres</p>");
            AddHtml("Squire-of-the-Mark-CoE", "<p class='main-text'><b>Respuesta:</b> Después de que un aliado <b><i>Rohan</i></b> que controles sea descartado del juego, añade a la Escudera de la Marca a la zona de victoria para poner ese aliado en juego agotado.</p><p class='flavor-text'>“No es mucho lo que puedo ofrecerle a tu Señor, pero con gusto haré cuanto esté a mi alcance.”<br/>—Pippin, El Retorno del Rey</p>");
            AddHtml("Rammas-Lookout-CoE", "<p class='main-text'>Devoto.</p><p class='main-text'>Mientras cada héroe que controles tenga al menos 1 recurso en su reserva de recursos, el Vigía de Rammas obtiene +1 {Willpower} y no se agota para ser asignado a una misión.</p><p class='flavor-text'>“Suceda lo que suceda, Gondor ya nunca será el país que habéis conocido. ¡Dejadme pasar!”<br/>—Gandalf, El Retorno del Rey</p>");
            AddHtml("Theodwyn-CoE", "<p class='main-text'><b>Respuesta:</b> Después de que Théodwyn entre en juego, roba 1 carta o bien añade 1 recurso a la reserva de recursos de un héroe <b><i>Noble</i></b>.</p><p class='flavor-text'>“Es valiente y de corazón magnánimo. Todos la aman. Que ella sea el señor de Eorlingas en nuestra ausencia.”<br/>—Háma, Las Dos Torres</p>");
            AddHtml("Light-footed-Steed-CoE", "<p class='main-text'>Vincula esta carta un héroe <b><i>Rohan</i></b>. Restringido.</p><p class='main-text'><b>Respuesta:</b> Después de que un personaje que controles abandone el juego, agota al Corcel Veloz para preparar al héroe vinculado. Luego, si ese personaje era único, el héroe vinculado obtiene +1 {Attack} hasta el final de la ronda.</p><p class='flavor-text'>“…¡y no olvidemos los caballos! Pueden ver la brisa nocturna, se dice por ahí.”<br/>—Uglúk, Las Dos Torres</p>");
            AddHtml("Rammas-Sentry-CoE", "<p class='main-text'>Devoto.</p><p class='main-text'>Mientras cada héroe que controles tenga al menos 1 recurso en su reserva de recursos, el Centinela de Rammas gana el siguiente texto: “<b>Respuesta:</b> Cancela 1 punto de daño que se acabe de infligir a un personaje <b><i>Gondor</i></b>. (Límite de una vez por fase.)”.</p><p class='flavor-text'>“Porque si caemos ¿quién quedará en pie?”<br/>—Beregond, El Retorno del Rey</p>");
            AddHtml("Live-Bait-CoE", "<p class='main-text'>Juega esta carta sólo si controlas una carta vinculada <b><i>Trampa</i></b> sin vincular.</p><p class='main-text'><b>Acción:</b> Elige un enemigo que no sea único en juego. Hasta el final de la ronda, trata el cuadro de reglas impreso del enemigo como si estuviera en blanco (excepto los <b><i>Rasgos</i></b>). Luego, vincula una carta vinculada <b><i>Trampa</i></b> sin vincular que controles a ese enemigo.</p>");
            AddHtml("Worthy-of-Remembrance-CoE", "<p class='main-text'><b>Acción de Combate:</b> Descarta un aliado <b><i>Rohan</i></b> que controles para elegir un enemigo. Inflige 2 puntos de daño a ese enemigo (4 puntos de daño si el aliado era único).</p><p class='flavor-text'>Entonces algo cambió en el corazón de Eowyn… desapareció el invierno que la habitaba, y el sol brilló en ella.<br/>—El Retorno del Rey</p>");
            AddHtml("Need-Brooks-No-Delay-CoE", "<p class='main-text'>Reduce el coste para jugar La Necesidad no Espera en 1 por cada héroe <b><i>Rohan</i></b> que controles.</p><p class='main-text'>Acción de Planificación: Busca entre las 10 primera cartas de tu mazo una carta con un coste impreso de 2 o menos (3 o menos si es única) y ponla aparte. Baraja tu mazo. A continuación, juega la carta puesta aparte sin coste alguno como si estuviera en tu mano.</p>");
            AddHtml("Wild-Country-CoE", "<p class='main-text'>Maldito 1. Vasto.</p><p class='main-text'><b>Obligado:</b> Al final de la fase de viaje, si el lugar activo no es Vasto, cada jugador inflige 1 punto de daño a un personaje que controle.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si el lugar activo es Vasto, inflige 1 punto de daño al personaje defensor.</p>");
            AddHtml("Endless-Grasslands-CoE", "<p class='main-text'>Vasto.</p><p class='main-text'><b>Obligado:</b> Al final de la fase de viaje, si el lugar activo no es Vasto, cada jugador agota un aliado que controle.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si el lugar activo es Vasto, el enemigo atacante realiza un ataque adicional después de éste.</p>");
            AddHtml("Windworn-Villages-CoE", "<p class='main-text'>Vasto.</p><p class='main-text'><b>Obligado:</b> Al final de la fase de viaje, si el lugar activo no es Vasto, cada jugador elige y descarta 1 carta de su mano.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si el lugar activo es Vasto, descarta una vinculada del personaje defensor.</p>");
            AddHtml("Humpbacked-Downs-CoE", "<p class='main-text'>Vasto.</p><p class='main-text'><b>Obligado:</b> Al final de la fase de viaje, si el lugar activo no es Vasto, cada jugador aumenta su Amenaza en 1.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si el lugar activo es Vasto, aumenta tu Amenaza en 2.</p>");
            AddHtml("Ride-Through-the-Night-CoE", "<p class='main-text'><b>Al ser revelada:</b> Agota todas las vinculadas restringidas que los jugadores controlen. Si no se agota ninguna vinculada restringida por este efecto, Cabalgata Nocturna gana oleada.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si el lugar activo es Vasto, el personaje defensor no puede prepararse hasta el final de la ronda.</p>");
            AddHtml("The-Green-Sea-CoE", "<p class='flavor-text'>Las tierras del interior son amplias e interminables, lo que agota incluso a los caballos más incansables del Folde Oeste.</p><p class='main-text'>Los lugares Vasto obtienen +3 puntos de Misión y son inmunes a los efectos de cartas de jugador.</p><p class='main-text'><b>Obligado:</b> Al principio de la fase de viaje, si no hay lugares Vasto en el área de preparación, descarta cartas de la parte superior del mazo de encuentros hasta que un lugar Vasto sea descartado y añádelo al área de preparación.</p>{victory:10}");
            AddHtml("Cold-from-the-Mountains-CoE", "<p class='main-text'><b>Al ser revelada:</b> Cada jugador que controle más de 2 aliados debe elegir y descartar un aliado que controle (descarta 2 aliados si controlas más de 5).</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Agota un personaje que controles.</p><p class='flavor-text'>“Que llamen a esto el viento, si así lo desean.”<br/>—Boromir, La Compañía del Anillo</p>");
            AddHtml("Exhausting-Winds-CoE", "<p class='main-text'><b>Al ser revelada:</b> Inflige 1 punto de daño a cada personaje con más de 1 punto de impacto restante. Agota cada personaje que no haya sido dañado por este efecto.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Después de este ataque, inflige X puntos de daño al personaje defensor. Siendo X los puntos de impacto restantes del personaje menos 1.</p>");
            AddHtml("Tired-and-Hungry-CoE", "<p class='main-text'>Mientras esté vinculado a un héroe, cuenta como una vinculada de <b><i>Estado</i></b> con el texto: “<b>Obligado:</b> Después de que un lugar sea explorado, agota el héroe vinculado.”.</p><p class='main-text'><b>Al ser revelada:</b> Vincula esta carta a un héroe preparado que no tenga una copia de Cansado y Hambriento. Si no se puede vincular, Cansado y Hambriento gana oleada.</p><p class='flavor-text'>“Delante el enemigo y detrás el terror,<br/>dormiremos bajo el dosel del cielo.”<br/>—La Compañía del Anillo</p>");
            AddHtml("Exposed-to-the-Elements-CoE", "<p class='flavor-text'>Tu grupo se encuentra a merced de la lluvia, el aguanieve y el hambre. Deben buscar refugio para encontrar un poco de respiro.</p><p class='main-text'><b>Obligado:</b> Al final del paso de preparación, descarta cartas desde el mazo de encuentros hasta que una traición sea descartada. Revela esa carta.</p>{victory:10}");
            AddHtml("Old-Farmhouse-CoE", "<p class='main-text'><b>Obligado:</b> Después de que la Antigua Granja abandone el juego como lugar explorado, descarta cartas del mazo de encuentro hasta que un lugar sea descartado. Añade ese lugar al área de preparación.</p><p class='flavor-text'>A unas doscientas yardas del camino principal, se toparon con una poderosa barricada levantada con viejos carretones puestos boca abajo. Tuvieron que detenerse.<br/>—El Retorno del Rey</p>");
            AddHtml("Abandoned-Mill-CoE", "<p class='main-text'>Maldito 1. Inmune a efectos de cartas de Jugador.</p><p class='main-text'><b>Obligado:</b> Después de que el Molino Abandonado abandone el juego como lugar explorado, descarta cartas del mazo de encuentros hasta que un enemigo sea descartado. Añade ese enemigo al área de preparación.</p><p class='flavor-text'>Pero para moler se necesita grano; y para el molino nuevo no había más grano que para el viejo.<br/>—El Retorno del Rey</p>");
            AddHtml("Dunland-Chieftain-CoE", "<p class='main-text'><b>Obligado:</b> Después de que el Caudillo de las Tierras Brunas se enfrente a ti, descarta 1 carta al azar de tu mano. A continuación descarta todas las demás copias de esa carta que estén en tu mano o bajo tu control.</p><p class='flavor-text'>“Nos odian y están contentos.”<br/>—Gamelin, Las Dos Torres</p>{victory:1}");
            AddHtml("Wild-Ravager-CoE", "<p class='main-text'><b>Obligado:</b> Al principio de la fase de encuentros, elige un jugador al azar. El Devastador Salvaje se enfrenta a ese jugador.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> El enemigo atacante no puede recibir daño hasta el final de la ronda.</p>");
            AddHtml("Dunlending-Berserker-CoE", "<p class='main-text'><b>Obligado:</b> Después de que el Bersérker Dunlendino se enfrente a ti, inflige 1 punto de daño a un héroe que controles y 1 punto de daño a un enemigo no único enfrentado a ti.</p><p class='flavor-text'>“No los detendrán las luces del alba ni las sombras del crepúsculo.”<br/>—Gamelin, Las Dos Torres</p>");
            AddHtml("Hillman-Scout-CoE", "<p class='main-text'>Tiro con arco 2.</p><p class='main-text'><b>Obligado:</b> Después de que el Explorador Montañés se enfrente a ti, agota al aliado preparado que controles con el coste impreso más alto.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Agota un personaje que controles que tenga 3 o más {Attack}.</p>");
            AddHtml("Surprise-Attack-CoE", "<p class='main-text'>Oleada.</p><p class='main-text'><b>Al ser revelada:</b> El siguiente enemigo que se enfrente en esta ronda no puede recibir daño hasta el final de la ronda y vuelve al área de preparación después de que ataque esta ronda.</p><p class='flavor-text'>No parecía tener ninguna posibilidad de llegar al vado antes que los jinetes emboscados le salieran al encuentro. Podía verlos claramente ahora.<br/>—La Compañía del Anillo</p>");
            AddHtml("A-History-of-Strife-CoE", "<p class='flavor-text'>Los Dunlendinos guardan un antiguo rencor contra los forasteros. Buscan atraparlos desprevenidos, saqueando sus suministros antes de dejarlos por muertos.</p><p class='main-text'>Oleada.</p><p class='main-text'>Cada enemigo <b><i>Tierras Brunas</i></b> gana “<b>Obligado:</b> Después de que este enemigo se enfrente a ti, descarta un recurso de un héroe que controles.”.</p>{victory:10}");
            AddHtml("Recreant-Rider-CoE", "<p class='main-text'><b>Obligado:</b> Después de que el Jinete Abyecto entre en el área de preparación, realiza un ataque inmediato contra el jugador inicial.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Devuelve el enemigo atacante al área de preparación después de este ataque.</p>");
            AddHtml("Deadly-Defector-CoE", "<p class='main-text'><b>Obligado:</b> Al final de la fase de combate, si el Desertor Letal está en el área de preparación, hace un ataque inmediato contra el último jugador.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si el enemigo atacante está en el área de preparación, realiza un ataque adicional después de éste.</p>");
            AddHtml("Orc-Battalion-CoE", "<p class='main-text'>El Batallón de Orcos no puede recibir daño de combate mientras sea atacado por menos de 3 personajes.</p><p class='main-text'><b>Obligado:</b> Después de que un personaje sea declarado como atacante contra el Batallón de Orcos, inflige 1 punto de daño a ese personaje.</p>");
            AddHtml("Servant-of-the-Eye-CoE", "<p class='main-text'>Maldito 1.</p><p class='main-text'><b>Obligado:</b> Cuando el Sirviente del Ojo te ataque, aumenta tu Amenaza en 1.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Aumenta tu Amenaza en 2.</p>");
            AddHtml("Black-Land-Scouts-CoE", "<p class='main-text'><b>Obligado:</b> Al principio de la fase de combate, aumenta la Amenaza de cada jugador en 1 o bien inflige 4 puntos de daño repartidos entre personajes en juego.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Inflige 2 puntos de daño repartidos entre personajes que controles.</p>");
            AddHtml("Orcish-Horse-butcher-CoE", "<p class='main-text'><b>Obligado:</b> Cuando el Carnicero de Caballos Orco inflija daño a un personaje, descarta una vinculada de ese personaje o bien aumenta en 1 la Amenaza del jugador enfrentado.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Descarta una vinculada que controles o bien aumenta tu Amenaza en 3.</p>");
            AddHtml("Crimson-Banner-CoE", "<p class='main-text'>Oleada.</p><p class='main-text'>Mientras esté vinculado a un enemigo, cuenta como una vinculada de <b><i>Estado</i></b> con este texto: “<b>Obligado:</b> Al final de la ronda, cada jugador aumenta su Amenaza en 1 por cada enemigo <b><i>Orco</i></b> en juego.”.</p><p class='main-text'><b>Al ser revelada:</b> Vincula esta carta al enemigo <b><i>Orco</i></b> que no sea único con el mayor coste de enfrentamiento.</p>");
            AddHtml("White-Mountain-Reinforcements-CoE", "<p class='flavor-text'>Los orcos han comenzado a salir de sus cuevas en las montañas, reforzando los ataques de los enemigos. Si no los detienen, pronto los sobrepasarán.</p><p class='main-text'><b>Al ser revelada:</b> Cada jugador que no esté enfrentado a un enemigo debe buscar en el mazo de encuentros y la pila de descartes de encuentros un enemigo y ponerlo en juego enfrentado a él. Baraja el mazo de encuentros.</p><p class='main-text'>Cada carta de sombra que no tenga efecto de sombra gana: “<b>Sombra:</b> Aumenta tu Amenaza en 1.”.</p>{victory:10}");
            AddHtml("Brigand-Ringleader-CoE", "<p class='main-text'>Saqueador 3. Inmune a efectos de cartas de jugador. No puede recibir más de 5 puntos de daño cada ronda.</p><p class='main-text'><b>Obligado:</b> Al final de la ronda, el jugador enfrentado añade la carta superior de su mazo a la pila de botín del Cabecilla de los Bandidos y cura 1 punto de daño del Cabecilla de los Bandidos por cada carta con diferente coste que haya en la pila de botín.</p>{victory:10}");
            AddHtml("Plundered-Goods-CoE", "<p class='main-text'>Añade 1 a la {Threat} total en el área de preparación por cada carta en la pila de botín de Bienes Saqueados.</p><p class='main-text'><b>Obligado:</b> Cuando un enemigo abandone el juego, añade 1 carta de su pila de botín a Bienes Saqueados, A continuación, añade otra carta de su pila de botín a la mano de su propietario. Descarta el resto.</p><p class='flavor-text'>Los bandidos asaltaron el arsenal del pueblo, y usaron las armas contra los aldeanos.</p>");
            AddHtml("Pillaging-Swordsman-CoE", "<p class='main-text'>Saqueador 1.</p><p class='main-text'>El Espadachín Saqueador obtiene +X {Attack}, donde X es el mayor coste impreso entre las cartas en su pila de botín.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Añade las 2 primeras cartas de tu mazo en la pila de botín del enemigo atacante.</p>");
            AddHtml("Grasping-Slaver-CoE", "<p class='main-text'>Saqueador 2.</p><p class='main-text'><b>Obligado:</b> Después de que un aliado sea dañado o destruido por un ataque del Esclavista Avaro, añade a ese aliado a la pila de botín del Esclavista Avaro.</p><p class='main-text'><b>Obligado:</b> Después de que el Esclavista Avaro ataque, inflige X puntos de daño repartidos entre personajes que controles. X es el número de cartas de aliado en la pila de botín de Esclavista Avaro.</p>");
            AddHtml("Vengeful-Bowman-CoE", "<p class='main-text'>Saqueador 2. Tiro con arco X.</p><p class='main-text'>X es el número de tipos de carta de jugador diferentes en la pila de botín del Arquero Vengativo.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si este ataque inflige daño, añade la carta superior de tu mazo a la pila de botín del enemigo atacante.</p>");
            AddHtml("Sneaky-Thief-CoE", "<p class='main-text'>Saqueador 0. Oleada.</p><p class='main-text'><b>Obligado:</b> Cuando el Ladrón Furtivo vaya a recibir cualquier cantidad de daño, si hay cartas en su pila de botín, descarta esas cartas en su lugar.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si este ataque destruye un personaje, el enemigo atacante realiza un ataque adicional.</p>");
            AddHtml("Erelas-Gates-CoE", "<p class='main-text'>Viaje: Cada jugador debe elegir un enemigo y añadir la carta superior de su mazo a su pila de botín.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Aumenta tu Amenaza en 1 por cada carta en la pila de botín del enemigo atacante.</p><p class='flavor-text'>Las columnas asomaban resquebrajadas y torcidas por encima del agua.<br/>—Las Dos Torres</p>");
            AddHtml("Crossroads-CoE", "<p class='main-text'>Viaje: Mezcla la pila de descartes de encuentros en el mazo de encuentros y descarta cartas hasta que se descarte un enemigo. Pon ese enemigo en juego enfrentado al jugador inicial.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> El enemigo atacante obtiene +X {Attack}, donde X es el número de esferas diferentes entre las cartas en su pila de botín.</p>");
            AddHtml("Erelas-Stables-CoE", "<p class='main-text'>Viaje: Devuelve un enemigo enfrentado a un jugador al área de preparación.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si el enemigo atacante no es único, devuélvelo al área de preparación después de este ataque.</p>");
            AddHtml("Chaos-in-the-Hills-CoE", "<p class='main-text'><b>Al ser revelada:</b> Devuelve el enemigo enfrentado con el mayor coste de enfrentamiento al área de preparación. Si ningún enemigo fue devuelto al área de preparación por acción de este efecto, Caos en las Colinas obtiene oleada.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Después de este ataque, el enemigo atacante se enfrenta al siguiente jugador y realiza un ataque inmediato.</p>");
            AddHtml("Looted-Weapons-CoE", "<p class='main-text'>Mientras esté vinculada a un enemigo, cuenta como una vinculada de <b><i>Estado</i></b> con el texto: “El enemigo vinculado obtiene +1 {Threat} y +1 {Attack} por cada carta vinculada en su pila de botín.”.</p><p class='main-text'><b>Al ser revelada:</b> Vincula esta carta al enemigo en juego con el coste de enfrentamiento más alto. Luego, cada jugador añade una vinculada <b><i>Objeto</i></b> que controle a la pila de botín de ese enemigo, si es posible. Si no hay enemigos en juego, Armas Saqueadas gana oleada.</p>");
            AddHtml("Stockpile-Barricade-CoE", "<p class='flavor-text'>Los carros y carretas volcados formaban una rígida barricada al otro lado de la carretera.</p><p class='main-text'>Oleada.</p><p class='main-text'>Cada enemigo obtiene +1 {Defense} por cada vinculada en su pila de botín.</p><p class='main-text'><b>Obligado:</b> Después de resolver la palabra clave Saqueador de un enemigo, si no hay vinculadas en la pila de botín de ese enemigo, realiza un ataque inmediato contra el jugador enfrentado.</p>{victory:10}");
            AddHtml("Erelas-Beacon-CoE", "<p class='main-text'><b>Obligado:</b> Al final de la fase de combate, inflige 1 punto de daño a la Almenara de Erelas por cada enemigo que haya en el área de preparación.</p><p class='main-text'><b>La Almenara de Erelas tiene X puntos de impacto, donde X es igual a 2, más 3{PerPlayer}. Si la Almenara de Erelas no tiene puntos de impacto restantes, los jugadores pierden la partida.</b></p><p class='flavor-text'>Todas las tierras estaban grises y silenciosas; y la sombra crecía sin cesar ante ellos, y la esperanza se debilitaba en todos los corazones.<br/>—El Retorno del Rey</p>");
            AddHtml("Host-of-Rohan-CoE", "<p class='main-text'>Centinela.</p><p class='main-text'><b>Acción:</b> Los jugadores como grupo pueden gastar 2 recursos para preparar a la Hueste de Rohan. (Límite de una vez por fase.)</p><p class='flavor-text'>“Se ha declarado la guerra y los Rohirrim, los Señores de los Caballos, no descansan.”<br/>—Gandalf, Las Dos Torres</p>");
            AddHtml("Enraged-Dunlending-CoE", "<p class='main-text'><b>Obligado:</b> Después de que el Dunlendino Enfurecido se enfrente a ti, inflige 1 punto de daño a la Almenara de Erelas.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Cualquier daño que se vaya a infligir al personaje defensor por este ataque se inflige a la Almenara de Erelas en su lugar.</p>");
            AddHtml("Bald-Hill-CoE", "<p class='main-text'>Mientras los jugadores controlen la Almenara, la Colina Calva obtiene +3 {Threat}.</p><p class='main-text'>Viaje: Si los jugadores controlan la Almenara, inflige 2 de daño a la Almenara de Erelas.</p><p class='flavor-text'>Al fin llegaron a la cima del cerro gris y una brisa repentina les sopló en los cabellos y les agitó las capas: el viento helado del alba.<br/>—Las Dos Torres</p>");
            AddHtml("Wooden-Barricade-CoE", "<p class='main-text'>Mientras la Barricada de Madera esté en el área de preparación, gana el siguiente texto: “<b>Obligado:</b> Al final de la fase de combate, inflige 1 punto de daño a la Almenara de Erelas y pon una ficha de progreso en la Barricada de Madera.”.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Descarta 2 vinculadas que controles o bien inflige 1 punto de daño a la Almenara de Erelas.</p>");
            AddHtml("Rocky-Slope-CoE", "<p class='main-text'>Después de que un efecto de una carta de encuentro sea cancelado, inflige 1 punto de daño a la Almenara de Erelas.</p><p class='main-text'>Viaje: El jugador inicial debe descartarse de todas las cartas de evento de su mano.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Descarta todos los recursos de cada héroe que controles o bien inflige 1 punto de daño a la Almenara de Erelas.</p>");
            AddHtml("Surrounding-Grassland-CoE", "<p class='main-text'>Tiro con arco 1.</p><p class='main-text'><b>Obligado:</b> Después de que los Pastizales Circundantes abandonen el juego como lugar explorado, si no hay copias de Pastizales Circundantes en el área de preparación, devuelve este lugar al área de preparación.</p><p class='flavor-text'>Podían ver más allá del río las campiñas verdes de Rohan que se pierden en la lejanía gris.<br/>—Las Dos Torres</p>");
            AddHtml("Narrow-Stair-CoE", "<p class='main-text'>Cada jugador no puede declarar más de 1 ataque y no puede declarar más de un atacante cada fase.</p><p class='main-text'>Mientras la Escalera Estrecha sea el lugar activo, cada jugador no puede defender más de un ataque cada fase (los demás ataques se consideran sin defensores).</p>{shadow}<p class='shadow-text'><b>Sombra:</b> El enemigo atacante recibe +3 {Attack} o bien inflige 1 punto de daño a la Almenara de Erelas.</p>");
            AddHtml("From-All-Sides-CoE", "<p class='main-text'><b>Al ser revelada:</b> Cada jugador debe elegir: inflige 1 punto de daño a 4 personajes diferentes que controle o bien inflige 1 punto de daño a la Almenara de Erelas.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Después de este ataque, descarta al personaje defensor o inflige 1 punto de daño a la Almenara de Erelas.</p>");
            AddHtml("Another-Wave-CoE", "<p class='main-text'>Oleada. Maldito 1.</p><p class='main-text'><b>Al ser revelada:</b> Si los jugadores controlan la Almenara, inflige 2 puntos de daño a la Almenara de Erelas o bien revela una carta de encuentro.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> El enemigo atacante realiza un ataque adicional o bien inflige 1 punto de daño a la Almenara de Erelas.</p>");
            AddHtml("Assault-Upon-Erelas-CoE", "<p class='main-text'><b>Al ser revelada:</b> El jugador inicial elige 1 enemigo enfrentado a un jugador y lo devuelve al área de preparación. Si ningún enemigo es devuelto al área de preparación por este efecto, inflige 1 punto de daño a la Almenara de Erelas o bien Asalto a Erelas gana oleada.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Aumenta tu Amenaza en 4 o bien inflige 1 punto de daño a la Almenara de Erelas.</p>");
            AddHtml("Reclaim-the-Beacon-CoE", "<p class='flavor-text'>Recuperen la almenara, no sea que los Dunlendinos la dañen, o algo peor.</p><p class='main-text'>Los Dunlendinos controlan la almenara. Los enemigos en el área de preparación no pueden ser enfrentados opcionalmente ni recibir daño.</p><p class='main-text'>No puede tener más de X fichas de progreso, donde X es igual a 2 más 1{PerPlayer}. Si Recupera la Almenara tiene X progresos encima, dale la vuelta (manteniendo las fichas de progreso).</p>");
            AddHtml("Stolen-Steeds-CoE", "<p class='main-text'>Los objetivos <b><i>Montura</i></b> no pueden ser descartados o abandonar el juego. Si un objetivo <b><i>Montura</i></b> no está vinculado, un jugador debe reclamarlo y vincularlo a un héroe que controle.</p><p class='main-text'><b>Obligado:</b> Al final de la ronda, añade 1 ficha de progreso a la misión principal por cada objetivo <b><i>Montura</i></b> que los jugadores controlen. Luego, aumenta la Amenaza de cada jugador en 1 por cada objetivo <b><i>Montura</i></b> en juego que los jugadores no controlen.</p>");
            AddHtml("Flinthoof-CoE", "<p class='main-text'>Protegido (Enemigo). Restringido.</p><p class='main-text'>El enemigo que proteja a Cascoduro obtiene +1 {Attack}.</p><p class='main-text'>El héroe vinculado obtiene +1 {Attack}.</p><p class='main-text'>Acción de Combate: Agota a Cascoduro para infligir 1 punto de daño a un enemigo en juego.</p><p class='flavor-text'>Las largas colas flotaban al viento, las melenas habían sido trenzadas sobre los pescuezos altivos.<br/>—Las Dos Torres</p>");
            AddHtml("Brightmane-CoE", "<p class='main-text'>Protegido (Lugar). Restringido.</p><p class='main-text'>El lugar o el enemigo que proteja a Crinbrillante obtiene +1 {Threat}.</p><p class='main-text'>El héroe vinculado obtiene +1 {Willpower}.</p><p class='main-text'>Acción de Misión: Agota a Crinbrillante para mirar la carta superior del mazo de encuentros. Si es un lugar, puedes descartarlo.</p>");
            AddHtml("Felarof-CoE", "<p class='main-text'>Protegido (Enemigo). Restringido.</p><p class='main-text'><b>Obligado:</b> Cuando el enemigo que proteja a Felaróf ataque, asígnale 2 cartas de sombra adicionales.</p><p class='main-text'>Acción de Combate: Agota a Felaróf para descartar una carta de sombra boca abajo del juego.</p><p class='flavor-text'>Hay otro que encabeza la tropa: un caballo muy grande. Nunca vi ninguno parecido.<br/>—Legolas, Las Dos Torres</p>");
            AddHtml("Thruk-CoE", "<p class='main-text'>Inmune a efectos de cartas de jugador. Thruk se enfrenta al jugador inicial.</p><p class='main-text'><b>Obligado:</b> Al principio de la fase de combate, si Thruk no está protegiendo un objetivo, realiza un ataque inmediato contra el jugador enfrentado.</p>{victory:10}");
            AddHtml("Saddle-slasher-CoE", "<p class='main-text'>Tiro con arco X. X es igual a 2, más 1 por cada objetivo <b><i>Montura</i></b> que los jugadores controlen.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si controlas un objetivo <b><i>Montura</i></b> elige: vincúlalo al enemigo atacante como un objetivo protegido o bien descarta el personaje defensor después de resolver este ataque.</p>");
            AddHtml("Rein-ripper-CoE", "<p class='main-text'><b>Obligado:</b> Cuando Arranca-Riendas ataque, asígnale dos cartas de sombra adicionales. Puedes vincular un objetivo <b><i>Montura</i></b> que controles a Arranca-Riendas como un objetivo protegido para cancelar este efecto.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> El enemigo atacante obtiene +1 {Attack} por cada objetivo <b><i>Montura</i></b> que los jugadores controlen.</p>");
            AddHtml("Bridle-biter-CoE", "<p class='main-text'>Oleada.</p><p class='main-text'><b>Al ser revelada:</b> Muerde-Bridas se enfrenta al jugador que controle más objetivos <b><i>Montura</i></b>.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Pon en juego a Muerde-Bridas enfrentado a ti y asígnale una carta de sombra.</p>");
            AddHtml("Pommel-pouncer-CoE", "<p class='main-text'>Mientras Salta-Pomos esté en el área de preparación sin un objetivo <b><i>Montura</i></b> vinculado, gana el siguiente texto: “<b>Obligado:</b> Cuando un jugador vaya a ganar el control de un objetivo <b><i>Montura</i></b>, vincula ese objetivo <b><i>Montura</i></b> a Salta-Pomos como un objetivo protegido en su lugar.”.</p>");
            AddHtml("Spoiled-Pasture-CoE", "<p class='main-text'>X es igual a 2, más 2 por cada objetivo <b><i>Montura</i></b> que controlen los jugadores.</p><p class='main-text'><b>Obligado:</b> Después de que un jugador pierda el control de un objetivo <b><i>Montura</i></b>, aumenta su Amenaza en 1.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Aumenta tu amenaza en 1 por cada objetivo <b><i>Montura</i></b> que controles.</p>");
            AddHtml("Horse-Thieves'-Hovel-CoE", "<p class='main-text'>Cuando tengan la oportunidad de viajar, los jugadores deben viajar a lugares que no sean Vasto.</p><p class='main-text'><b>Obligado:</b> Después de que el Antro de Ladrones de Caballos abandone el juego como lugar explorado, si hay menos de 1{PerPlayer} enemigos en juego, descarta cartas de la parte superior del mazo de encuentros hasta que un enemigo sea descartado. Añade ese enemigo al área de preparación.</p>{victory:2}");
            AddHtml("Horse-Lord's-Lodge-CoE", "<p class='main-text'>Cuando tengan la oportunidad de viajar, los jugadores deben viajar a lugares que no sean Vasto.</p><p class='main-text'><b>Obligado:</b> Después de que la Logia del Señor de los Caballos abandone el juego como lugar explorado, si hay menos de 1{PerPlayer} lugares en juego, descarta cartas de la parte superior del mazo de encuentros hasta que sea descartado un lugar. Añade ese lugar al área de preparación.</p>{victory:2}");
            AddHtml("Thirst-for-Horse-Blood-CoE", "<p class='main-text'><b>Al ser revelada:</b> Cada jugador que controle un objetivo <b><i>Montura</i></b> elige: revelar una carta de encuentro, o bien elegir el enemigo con el mayor coste de enfrentamiento sin vinculadas y vincularle un objetivo <b><i>Montura</i></b> que controle como objetivo protegido. Si ningún jugador controla un objetivo <b><i>Montura</i></b>, Sed de Sangre de Caballo gana oleada.</p><p class='flavor-text'>“Todavía tendremos un festín de carne de caballo, o de algo mejor.”<br/>—Uglúk, Las Dos Torres</p>");
            AddHtml("Overburdened-CoE", "<p class='main-text'><b>Al ser revelada:</b> Cada jugador que controle más de 2 vinculadas debe descartar 1 vinculada que controle, si es posible (descarta 2, si controlas más de 5 vinculadas). Si ninguna vinculada fue descartada por este efecto, Sobrecargado gana oleada.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Descarta 1 carta al azar de tu mano.</p>");
            AddHtml("The-Last-Alliance-CoE", "<p class='main-text'>Elige dos rasgos, <b><i>A</i></b> y <b><i>B</i></b>. Cada uno de tus héroes iniciales y cada aliado en tu mazo deben tener impreso el rasgo <b><i>A</i></b> o <b><i>B</i></b>, pero no pueden tener los dos. Debes tener al menos 1 héroe inicial y 10 aliados en tu mazo con cada rasgo.</p><p class='main-text'><b>Preparación:</b> Dale la vuelta a esta carta.</p><p class='flavor-text'>“El poder de resistencia de los Elfos era mayor mucho tiempo atrás; y no todos los Hombres se habían apartado de ellos.”<br/>—Gandalf, La Compañía del Anillo</p>");
            AddHtml2("The-Last-Alliance-CoE", "<p class='main-text'>Mientras controles más personajes <b><i>A</i></b> que personajes <b><i>B</i></b>, reduce el coste del primer aliado <b><i>B</i></b> que juegues esta ronda en 1, y viceversa.</p><p class='main-text'><b>Acción:</b> Agota La Última Alianza para elegir una carta de tu mano o una carta bajo tu control. Sustituye cada instancia impresa de “<b><i>A</i></b>” o “<b><i>B</i></b>” en el texto de reglas con “<b><i>A</i></b> o <b><i>B</i></b>” hasta el final de la ronda.</p>");
            AddHtml("Drive-them-Away-CoE", "<p class='flavor-text'>A lo largo del Gran Camino del Oeste, se encuentran con un campamento Rohirrim a la sombra de la verde y calva colina de Erelas. ¡Pero la tranquilidad de su viaje se ve interrumpida por un repentino ataque desde las sombras! El choque del acero y los gritos de los hombres pronto llegan a sus oídos. ¡Deben expulsarlos y evitar una mayor destrucción del campamento!</p><p class='main-text'><b>Preparación:</b> Pon al Cabecilla de los Bandidos aparte, fuera del juego. Añade Bienes Saqueados al área de preparación. Cada jugador busca en el mazo de encuentros un enemigo diferente y lo añade al área de preparación. Baraja el mazo de encuentros.</p>");
            AddHtml2("Drive-them-Away-CoE", "<p class='main-text'> <b>Obligado:</b> Después de que un enemigo sea destruido, pon una ficha de recurso aquí.</p><p class='main-text'>Acción de Encuentro: Quita 5 fichas de progreso de esta etapa para elegir una carta en una pila de botín y descartarla. Límite de una vez por ronda y por jugador.</p><p class='main-text'><b>Los jugadores no pueden avanzar a menos que haya X fichas de recursos en esta etapa, donde X es igual a 1 más 2{PerPlayer} (2 por jugador).</b></p>");
            AddHtml("Ambush-CoE", "<p class='flavor-text'>Han luchado hasta el corazón del campamento, pero los bandidos se unen en torno a su líder y lanzan un feroz ataque.</p><p class='main-text'><b></b> <b>Al ser revelada:</b> Finaliza la fase actual. Añade al Cabecilla de los Bandidos al área de preparación. Cada jugador que no esté enfrentado a ningún enemigo busca en el mazo de encuentros y la pila de descarte de encuentros un enemigo y lo pone en juego enfrentado a él. Baraja el mazo de encuentros.</p>");
            AddHtml2("Ambush-CoE", "<p class='main-text'> <b>Obligado:</b> Después de que un enemigo entre en juego, realiza comprobaciones de enfrentamiento.</p><p class='main-text'>Acción de Planificación: Quita 5 fichas de progreso de esta etapa para elegir una carta en una pila de botín. El propietario de esa carta puede descartarla o jugarla sin coste alguno. Límite de cuatro veces por ronda para el grupo.</p><p class='main-text'><b>Cuando el Cabecilla de los Bandidos sea derrotado, los jugadores ganan la partida.</b></p>");
            AddHtml("Battle-for-the-Hill-CoE", "<p class='flavor-text'>Dunlendinos y traidores Rohirrim han capturado la Almenara en Erelas. ¡Recuperen la colina a cualquier precio!</p><p class='main-text'><b></b> Preparación: Pon la Hueste de Rohan aparte, fuera del juego. Añade la Almenara de Erelas y 1 copia de Dunlendino Enfurecido por jugador al área de preparación. Añade la misión secundaria de doble cara al área de preparación, por el lado Recupera la Almenara boca arriba. Busca en el mazo de encuentros 1 copia de Pastizales Circundantes y ponla en juego como lugar activo. Baraja el mazo de encuentros.</p>");
            AddHtml2("Battle-for-the-Hill-CoE", "<p class='main-text'><b>Obligado:</b> Después de se ponga cualquier cantidad de fichas de progreso en esta etapa, cada jugador debe elegir: agotar un personaje que controle o bien infligir 1 punto de daño a la Almenara de Erelas.</p><p class='main-text'><b>Esta etapa no puede ser superada mientas los Dunlendinos controlen la Almenara.</b></p>");
            AddHtml("Hold-the-Hilltop-CoE", "<p class='flavor-text'>Mientras sus enemigos se reúnen para otro asalto a la almenara, pueden ver las luces de las antorchas de las tropas de Gálmód que se concentran colina abajo.</p><p class='main-text'><b></b> <b>Al ser revelada:</b> Pon progreso en Defiende la Almenara (ignorando el lugar activo) hasta que tenga X fichas de progreso, donde X es igual a 2, más 1{PerPlayer}. Mezcla la pila de descarte de encuentros en el mazo de encuentros. Cada jugador descarta cartas de la parte superior del mazo de encuentros hasta que un enemigo sea descartado y añade ese enemigo al área de preparación.</p>");
            AddHtml2("Hold-the-Hilltop-CoE", "<p class='main-text'>Tiempo 3.</p><p class='main-text'><b>Obligado:</b> Al final de la ronda, inflige 1 punto de daño a la Almenara de Erelas (2 de daño si hay 3 o más jugadores). A continuación, si no hay contadores de tiempo en esta etapa, avanza inmediatamente a la etapa 3.</p><p class='main-text'><b>Obligado:</b> Después de que Defiende la Almenara sea elegida como misión actual, revela una carta de encuentro.</p><p class='main-text'><b>Si los Dunlendinos controlan la Almenara, los jugadores pierden la partida.</b></p>");
            AddHtml("The-Last-Push-CoE", "<p class='flavor-text'>Mientras las fuerzas de Gálmód cabalgan flanqueando al enemigo, deben prepararse para el combate final.</p><p class='main-text'><b></b> <b>Al ser revelada:</b> Quita todo el progreso de Defiende la Almenara y dale la vuelta. Pon la Hueste de Rohan en juego bajo el control del jugador inicial. Mezcla la pila de descarte de encuentros con el mazo de encuentros. Cada jugador descarta cartas de la parte superior del mazo de encuentros hasta que un enemigo sea descartado y lo añade al área de preparación.</p>");
            AddHtml2("The-Last-Push-CoE", "<p class='main-text'>Añade 2 a la {Threat} total del área de preparación por cada punto de daño en la Almenara de Erelas.</p><p class='main-text'><b>Obligado:</b> Al principio de la fase de combate, cada enemigo enfrentado realiza un ataque inmediato.</p><p class='main-text'><b>Obligado:</b> Después de que un personaje abandone el juego, inflige 1 punto de daño a la Almenara de Erelas.</p><p class='main-text'><b>Al final de la ronda, si los Dunlendinos controlan la Almenara, los jugadores pierden la partida, y si los jugadores controlan la Almenara, ganan la partida.</b></p>");
            AddHtml("Thieves-and-Coursers-CoE", "<p class='flavor-text'>Los orcos han invadido el Folde Este, arrasando el país y capturando los preciados caballos de guerra del rey Thengel.</p><p class='main-text'><b></b> Preparación: Añade Corceles Robados al área de preparación. Pon a Thruk, los objetivos <b><i>Montura</i></b>, y los 8 enemigos del conjunto de encuentros Hueste Orca aparte, fuera del juego. Baraja el mazo de encuentros. El primer jugador revela a Cascoduro y Crinbrillante y los añade al área de preparación. A continuación, cada otro jugador descarta cartas del mazo de encuentros hasta que un lugar o un enemigo sea descartado y lo añade al área de preparación.</p>");
            AddHtml2("Thieves-and-Coursers-CoE", "<p class='flavor-text'>Si pueden recuperar a Cascoduro y a Crinbrillante, podrían parar la hueste principal de orcos antes de que lleguen a Aldburg.</p><p class='main-text'><b>Esta etapa no puede ser superada a menos que los jugadores controlen dos objetivos <b><i>Montura</i></b>.</b></p>");
            AddHtml("The-King's-Stallion-CoE", "<p class='flavor-text'>El jefe de guerra Thruk ha llegado a la batalla, montando al poderoso caballo Felaróf aullando órdenes a su paso. “¡Agrúpense!” grita. “¡Esta noche nos daremos un festín con carne de caballo!”.</p><p class='main-text'><b></b> <b>Al ser revelada:</b> Si es la fase de combate, finaliza la fase. Baraja la pila de descartes de encuentros con el mazo de encuentros. El primer jugador añade a Thruk al área de preparación, protegiendo a Felaróf. Cada otro jugador descarta cartas del mazo de encuentros hasta que se descarte un enemigo y lo pone en juego enfrentado a él.</p>");
            AddHtml2("The-King's-Stallion-CoE", "<p class='main-text'>Thruk no puede recibir daño a menos que haya 4 o más fichas de progreso en esta etapa.</p><p class='main-text'><b>Esta etapa no puede ser superada a menos que los jugadores controlen 3 objetivos <b><i>Montura</i></b>.</b></p>");
            AddHtml("The-Sweeping-Tide-CoE", "<p class='flavor-text'>Todo el poder de la hueste Orca ha respondido al grito de guerra de Thruk. Deben unirse en una carga final para dispersarlos por las colinas.</p><p class='main-text'><b></b> <b>Al ser revelada:</b> Si es la fase de combate, finaliza la fase. Baraja la pila de descartes de encuentros con el mazo de encuentros. Añade a Thruk al área de preparación desde la pila de victoria. Cada jugador elige 2 enemigos del conjunto de encuentros Hueste Orca puesto aparte y los pone en juego enfrentados a él. Uno de los enemigos elegidos de esta manera debe ser el Batallón de Orcos.</p>");
            AddHtml2("The-Sweeping-Tide-CoE", "<p class='main-text'> Sáltate el paso de preparación. Si el mazo de encuentros está vacío en cualquier momento, baraja la pila de descartes de encuentros para formar el mazo de encuentros.</p><p class='main-text'><b>Obligado:</b> Cuando un enemigo ataque, asígnale una carta de sombra adicional.</p><p class='main-text'><b>Si un objetivo <b><i>Montura</i></b> se vincula a un enemigo, los jugadores pierden la partida. Si no hay enemigos en juego, los jugadores ganan la partida.</b></p>");
            AddHtml("Defend-the-Beacon-CoE", "<p class='main-text'>Los jugadores controlan la almenara. Las cartas de sombra son inmunes a los efectos de cartas de jugador.</p><p class='main-text'>No puede tener más de X fichas de progreso, donde X es igual a 2, más 1{PerPlayer}.</p><p class='main-text'><b>Respuesta:</b> Elimina cualquier cantidad de progreso de Defiende la Almenara para cancelar la misma cantidad daño que se vaya a infligir a la Almenara de Erelas. A continuación, Si Defiende la Almenara tiene 0 puntos de progreso, dale la vuelta.</p>");
        }

        private void TheAldburgPlot()
        {
            AddHtml("Fatty-Bolger-TAP", "<p class='main-text'><b>Preparación:</b> Reduce tu amenaza en 2.</p><p class='main-text'><b>Respuesta:</b> Aumenta tu amenaza en 4 y agota a Gordo Bolger para cancelar una carta de Enemigo no única que acabe de ser revelada del mazo de encuentros y añadirla a la zona de victoria. (Límite de una vez por partida para el grupo).</p><p class='flavor-text'>Gordo Bolger no había estado inactivo. Tan pronto como vio que las formas oscuras venían arrastrándose por el jardín, supo que tenía que correr, o morir.<br/>—La Comunidad del Anillo</p>");
            AddHtml("Widfast-TAP", "<p class='main-text'><b>Preparación:</b> Busca en tu colección un aliado <b><i>Criatura</i></b> y añádelo a tu mano. Durante la primera ronda, reduce su coste en 2.</p><p class='main-text'>Acción de Viaje: Si hay un Lugar activo, gasta 1 recurso de la reserva de Widfast para viajar a otro Lugar, resolviendo su efecto de <b>Viaje</b>. (Ahora hay dos Lugares activos).</p>");
            AddHtml("Lily-Cotton-TAP", "<p class='main-text'><b>Acción:</b> Agota a Lily Coto para preparar a otro aliado <b><i>Hobbit</i></b> y añadir la {Willpower}, {Attack} y {Defense} de Lily Coto a la {Willpower}, {Attack} y {Defense} respectivamente de ese aliado hasta el final de la fase. Al final de la fase, devuelve ese aliado a la mano de su propietario. (Límite una vez por fase).</p><p class='flavor-text'>Hay poca o ninguna magia en ellos, excepto esa común y cotidiana que los ayuda a desaparecer en silencio y rápidamente…<br/>—El Hobbit</p>");
            AddHtml("A-Lesson-in-Caution-TAP", "<p class='main-text'>En secreto 1.</p><p class='main-text'><b>Acción:</b> Roba 1 carta. Luego, reduce tu amenaza en 2, o bien la siguiente carta que juegues en esta fase gana En secreto 1.</p><p class='flavor-text'>Los hobbits tienen el paso leve y no dejan huellas fáciles de leer, ni siquiera para un Montaraz…<br/>—Las Dos Torres</p>");
            AddHtml("There-and-Back-Again-TAP", "<p class='main-text'>En secreto 1.</p><p class='main-text'><b>Respuesta:</b> Después de que un aliado <b><i>Hobbit</i></b> abandone el juego, ponlo en juego desde tu mano o pila de descartes bajo el control de cualquier jugador.</p><p class='flavor-text'>El problema se prolongó en verdad durante años. Pasó mucho tiempo antes de que el señor Bolsón fuese admitido otra vez en el mundo de los vivos.<br/>—El Hobbit</p>");
            AddHtml("Buckland-Shirriff-TAP", "<p class='main-text'>Devoto. A distancia.</p><p class='main-text'><b>Respuesta:</b> Después de que un enemigo que comparta un <b><i>Rasgo</i></b> con un enemigo en la zona de victoria se añada al área de preparación, gasta 1 recurso {sphere:Lore} para poner en juego al Oficial de los Gamos desde tu mano, bajo tu control.</p>");
            AddHtml("Weep-No-More-TAP", "<p class='main-text'>Límite de 3 copias de Dejemos de Llorar en la zona de victoria.</p><p class='main-text'><b>Respuesta:</b> Después de que se resuelva un efecto de “Al ser revelada” o un efecto de sombra en una carta de traición, añade Dejemos de Llorar a la zona de victoria para añadir esa carta de traición a la zona de victoria.</p><p class='flavor-text'>—Al menos quizá seamos vengados. Apretemos las mandíbulas y dejemos de llorar.<br/>—Aragorn, La Comunidad del Anillo</p>");
            AddHtml("Fear-Fire-Foes-TAP", "<p class='main-text'>En secreto 1. Juega esta carta sólo si no controlas un héroe <b><i>Guerrero</i></b>.</p><p class='main-text'><b>Acción:</b> Elige un enemigo no único y un atributo ({Threat}, {Attack} o {Defense}). Hasta el final de la fase, reduce el atributo elegido de ese enemigo a 0.</p><p class='flavor-text'>Otros cuernos respondieron a lo lejos. La alarma cundía rápidamente.<br/>—La Comunidad del Anillo</p>");
            AddHtml("Horn-call-of-Buckland-TAP", "<p class='main-text'>Vincula esta carta a un héroe {sphere:Lore} o <b><i>Hobbit</i></b>.</p><p class='main-text'><b>Respuesta:</b> Después de que te enfrentes a un enemigo que comparte un <b><i>Rasgo</i></b> con un enemigo en la zona de victoria, agota el Cuerno de los Gamos para preparar al héroe vinculado. A continuación, ese enemigo obtiene −1 {Attack} y −1 {Defense} hasta el final de la ronda.</p><p class='flavor-text'>En ese momento, entre los árboles cercanos, sonó un cuerno. Desgarró la noche como un fuego en lo alto de una loma.<br/>—La Comunidad del Anillo</p>");
            AddHtml("Young-Tom-TAP", "<p class='main-text'>Durante la ronda en la que Joven Tom entre en juego, los enemigos obtienen +5 a su coste de enfrentamiento.</p><p class='flavor-text'>—No todo es allí felicidad —dijo Frodo—, pero es cierto que honramos a los jardineros.<br/>—Las Dos Torres</p>");
            AddHtml("Gavin-TAP", "<p class='main-text'>No puede tener cartas Vinculadas.</p><p class='main-text'><b>Respuesta:</b> Después de resolver los efectos de una carta de encuentro sin oleada, agota a Gavin para dar a esa carta oleada y añadir 1 recurso a la reserva de un héroe <b><i>Explorador</i></b> que controles. Si la siguiente carta de encuentro revelada no es un lugar, descártala sin resolver sus efectos.</p>");
            AddHtml("Red-Harvest-TAP", "<p class='flavor-text'>Con una velocidad brutal, los hombres de La Susurradora caen sobre ustedes. Tendrán que luchar con uñas y dientes para llegar a la armería.</p><p class='main-text'><b>Obligado:</b> Después de que un enemigo se enfrente a un jugador, ese jugador inflige 2 puntos de daño a un personaje que controle.</p><p class='main-text'><b>Obligado:</b> Después de que esta misión sea superada, baraja la pila de descarte de encuentros con el mazo de encuentros. Cada jugador descarta cartas del mazo de encuentros hasta que sea descartado un enemigo y lo añade al área de preparación. Añade La Armería al área de preparación.</p>{victory:10}");
            AddHtml("The-Prisoner-in-White-TAP", "<p class='flavor-text'>En un intento de cubrir sus huellas, el agente del Maestro de Espías se ha infiltrado en la prisión.</p><p class='main-text'>Los jugadores no pueden viajar a lugares o hacer que los lugares sean el lugar activo por efectos de cartas de jugador.</p><p class='main-text'><b>Obligado:</b> Después de que esta misión sea superada, añade a Ossian al área de preparación.</p>{victory:10}");
            AddHtml("The-Man-with-the-Twisted-Lip-TAP", "<p class='flavor-text'>Han comenzado a rastrear al escurridizo Maestro de Espías de Aldburg, aunque es difícil saber cuál de ustedes es el gato y cuál el ratón.</p><p class='main-text'><b>Obligado:</b> Al final de la ronda, aumenta la amenaza de cada jugador en 1.</p><p class='main-text'><b>Obligado:</b> Después de que esta misión sea superada, añade El Maestro de Espías al área de preparación.</p>{victory:10}");
            AddHtml("A-Fire-Rises-TAP", "<p class='flavor-text'>Algo infame está sucediendo en Aldburg. Cuando empiezan a juntar las piezas, ven humo y llamas que se elevan desde un edificio cercano.</p><p class='main-text'>Incrementa el coste de jugar cada evento en 1.</p><p class='main-text'><b>Obligado:</b> Después de que esta misión sea superada, revela Infierno Esparciéndose.</p>{victory:10}");
            AddHtml("A-Case-of-Identity-TAP", "<p class='flavor-text'>El misterio de la verdadera identidad de La Susurradora permanece. Deben estar en el camino correcto, a juzgar por sus asesinos merodeando por los callejones.</p><p class='main-text'><b>Obligado:</b> Al final del paso de preparación, descarta cartas de la parte superior del mazo de encuentros hasta que descartes un enemigo. Revela ese enemigo.</p><p class='main-text'><b>Obligado:</b> Después de que esta misión sea superada, añade el Gran Salón de Hidromiel al área de preparación.</p>{victory:10}");
            AddHtml("Whisperer-in-the-Darkness-TAP", "<p class='flavor-text'>La taberna estaba llena de rumores de una asesina llamada “La Susurradora”. Si quieren desentrañar este misterio, tendrán que buscarla y detenerla antes de que ataque.</p><p class='main-text'><b>Obligado:</b> Después de explorar un lugar, aumenta la amenaza de cada jugador en 1.</p><p class='main-text'><b>Obligado:</b> Después de que esta misión sea superada, añade La Susurradora al área de preparación.</p>{victory:10}");
            AddHtml("Spreading-Inferno-TAP", "<p class='main-text'>Protegido (Lugar).</p><p class='main-text'><b>Obligado:</b> Al principio de la fase de viaje, descarta el lugar vinculado, aumenta la amenaza de cada jugador en 1 y descarta el aliado de menor coste controlado por cada jugador. Revela Infierno Esparciéndose.</p><p class='main-text'><b>Obligado:</b> Después de explorar el lugar vinculado, dale la vuelta a esta carta y revélala.</p>");
            AddHtml("The-Whisperer-TAP", "<p class='main-text'><b>Obligado:</b> Al final de la ronda, devuelve La Susurradora al área de preparación, si puedes. La Susurradora realiza un ataque inmediato contra el jugador inicial. El daño infligido por este ataque se asigna como un aumento a tu amenaza.</p><p class='main-text'><b>Obligado:</b> Después de que La Susurradora sea derrotada, dale la vuelta a esta carta y revélala.</p>");
            AddHtml("The-Spy-Master-TAP", "<p class='main-text'><b>Obligado:</b> Si se adjudica a El Maestro de Espías una carta de sombra sin efecto, inflige 1 de daño al personaje defensor y adjudica a El Maestro de Espías otra carta de sombra (límite de dos veces por ataque).</p><p class='main-text'><b>Obligado:</b> Después de que El Maestro de Espías sea derrotado, dale la vuelta a esta carta y revélala.</p>");
            AddHtml("Ossian-TAP", "<p class='main-text'>Inmune a efectos de cartas de jugador. Ossian no puede recibir más de X puntos de daño en cada ronda, donde X es el número de objetivos <b><i>Pista</i></b> controlados por los jugadores.</p><p class='main-text'><b>Obligado:</b> Cuando Ossian sea derrotado, dale vuelta a esta carta y revélala.</p><p class='flavor-text'>Encuentran a Ossian inclinado sobre un cadáver vestido de blanco. Al escuchar que se aproximan, se vuelve hacia ustedes.</p>");
            AddHtml("Garrison-Barracks-TAP", "<p class='main-text'>Inmune a efectos de cartas de jugador. X es el doble del número de objetivos <b><i>Pista</i></b> controlados por los jugadores.</p><p class='main-text'>Viaje: Baraja todos los enemigos <b><i>Tierras Brunas</i></b> puestos aparte en el mazo de encuentros.</p><p class='main-text'><b>Obligado:</b> Cuando el Cuartel de la Guarnición abandone el juego como lugar explorado, dale la vuelta a esta carta y revélala.</p><p class='flavor-text'>La guardia de la ciudad tiene ojos y oídos en todo en Aldburg. Pero, ¿quién los vigila a ellos?</p>");
            AddHtml("The-Horse's-Tail-TAP", "<p class='main-text'>Inmune a efectos de cartas de jugador. X es el doble del número de objetivos <b><i>Pista</i></b> controlados por los jugadores.</p><p class='main-text'>Viaje: Baraja todos los enemigos <b><i>Guarnición</i></b> puestos aparte en el mazo de encuentros.</p><p class='main-text'><b>Obligado:</b> Cuando La Cola de Caballo abandone el juego como lugar explorado, dale la vuelta a esta carta y revélala.</p><p class='flavor-text'>Puede despertar la sospecha de la guardia de la ciudad, pero este misterio no se resolverá por medios ordinarios.</p>");
            AddHtml("The-Armoury-TAP", "<p class='main-text'>Inmune a efectos de cartas de jugador.</p><p class='main-text'>Viaje: Cada jugador debe agotar al personaje preparado que controle con la mayor {Defense}.</p><p class='main-text'><b>Obligado:</b> Cuando La Armería abandone el juego como lugar explorado, dale la vuelta a esta carta y revélala.</p><p class='flavor-text'>La Susurradora empuñaba una daga distintiva y de aspecto familiar. Quizás el intendente de la armería pueda decirte algo al respecto.</p>");
            AddHtml("Great-Mead-Hall-TAP", "<p class='main-text'>Inmune a efectos de cartas de jugador.</p><p class='main-text'>Viaje: Los jugadores deben aumentar su amenaza en X, donde X es el número de enemigos en el área de preparación.</p><p class='main-text'><b>Obligado:</b> Cuando el Gran Salón de Hidromiel abandone el juego como lugar explorado, dale la vuelta a esta carta y revélala.</p><p class='flavor-text'>Han rastreado a los agentes de La Susurradora hasta los mismos salones del Mariscal Eomund. ¿Hasta dónde llega esta conspiración?</p>");
            AddHtml("Town-Guard-TAP", "<p class='main-text'>Si los jugadores controlan 2 o más objetivos <b><i>Pista</i></b>, Guardia de la Ciudad obtiene +2 {Threat}.</p><p class='main-text'><b>Obligado:</b> Después de que el Guardia de la Ciudad ataque y destruya a un personaje que controles, descarta 1 recurso de cada héroe que controles con un objetivo <b><i>Pista</i></b> vinculado.</p><p class='flavor-text'>—¿Es vana mi esperanza de que hayas sido enviado para ayudarme en estas dudas y aprietos?<br/>—Éomer, Las Dos Torres</p>");
            AddHtml("Dunlending-Agents-TAP", "<p class='main-text'>Si los jugadores controlan 2 o más objetivos <b><i>Pista</i></b>, Agentes Dunlendinos obtienen +2 {Attack}.</p><p class='main-text'><b>Obligado:</b> Después de que los Agentes Dunlendinos ataquen y destruyan a un personaje que controles, inflige 1 punto de daño a cada héroe que controles con un objetivo <b><i>Pista</i></b> vinculado.</p><p class='flavor-text'>Los Dunlendinos y numerosos hombres de la guarnición del Fuerte estaban trabajando.<br/>—El Retorno del Rey</p>");
            AddHtml("Aldburg-Malcontent-TAP", "<p class='main-text'><b>Al ser revelada:</b> Si los jugadores controlan 3 o más objetivos <b><i>Pista</i></b>, Descontento de Aldburg gana oleada.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Si los jugadores controlan 2 o más objetivos <b><i>Pista</i></b>, devuelve el enemigo atacante al área de preparación después de este ataque.</p>");
            AddHtml("Misty-Street-TAP", "<p class='main-text'><b>Al ser revelada:</b> Descarta todas las vinculadas y las fichas del aliado de mayor coste que controle el jugador inicial y colócalo boca abajo bajo la Calle Brumosa.</p><p class='main-text'><b>Obligado:</b> Cuando la Calle Brumosa abandone el juego como lugar explorado, devuelve el aliado vinculado a su propietario, boca arriba y preparado.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Descarta una carta Vinculada que no sea <b><i>Pista</i></b> que controles.</p>");
            AddHtml("Well-lit-Hall-TAP", "<p class='main-text'>Mientras el Salón Bien Iluminado esté en el área de preparación, no se pueden colocar más de 3 fichas de progreso en una carta de misión como resultado de ir a la misión con éxito.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> El enemigo atacante obtiene +1 {Attack} (+2 {Attack} en su lugar si el personaje defensor tiene una vinculada <b><i>Pista</i></b>).</p>");
            AddHtml("Decrepit-Hovel-TAP", "<p class='main-text'>El coste de recursos de cada aliado debe pagarse con la reserva de recursos de un solo héroe.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Descarta 1 recurso de un héroe que controles.</p><p class='flavor-text'>—Salen de correrías, a robar y a “recolectar”, como ellos dicen.<br/>—Tom Coto, El Retorno del Rey</p>");
            AddHtml("Taken-by-the-Night-TAP", "<p class='main-text'><b>Al ser revelada:</b> Cada jugador debe descartar el aliado de menor coste que controle. Si no se descarta ningún aliado con coste 2 o superior de esta forma, Secuestrado por la Noche gana oleada.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> El enemigo atacante obtiene +1 {Attack} (+2 {Attack} en su lugar si este enemigo está atacando desde el área de preparación).</p>");
            AddHtml("False-Lead-TAP", "<p class='main-text'>Maldito 1.</p><p class='main-text'><b>Al ser revelada:</b> Cada jugador retira a un héroe que controle de la misión con un objetivo <b><i>Pista</i></b> vinculado, si puede. Luego, cada jugador agota a un héroe que controle que no esté asignado a la misión.</p><p class='flavor-text'>¿O es que me mientes para tenderme una trampa?<br/>—Frodo Bolsón, Las Dos Torres</p>");
            AddHtml("Sudden-Ambush-TAP", "<p class='main-text'><b>Al ser revelada:</b> El jugador inicial debe elegir: o bien aumenta su amenaza en 4, o el enemigo que se encuentre más cerca de la parte superior de la pila de descartes de encuentros se enfrenta a él y realiza un ataque inmediato. Debe declarar al personaje preparado que controle con la mayor {Willpower} como defensor de este ataque, si es posible.</p>{shadow}<p class='shadow-text'><b>Sombra:</b> Resuelve el efecto “Al ser revelada” de esta carta.</p>");
            AddHtml("Evil-Under-the-Moon-TAP", "<p class='flavor-text'>Side A: Con el conocimiento de que una facción de rebeldes está instalada en Aldburg, Ealdwulf les ruega que la eliminen. Side B: ¿Dónde empezar la caza? ¿Buscarán la ayuda de los guardias de la ciudad o investigarán el inframundo criminal en una taberna sórdida?</p><p class='main-text'><b></b> <b>Preparación:</b> Pon cada misión secundaria de encuentro, cada copia de Guardia de la Ciudad y cada copia de Agentes Dunlendinos aparte, fuera del juego. Pon cada carta de encuentro de doble cara aparte, fuera del juego, con la cara <b><i>Pista</i></b> boca abajo. Añade el Cuartel de la Guarnición y La Cola de Caballo al área de preparación. Busca un enemigo en el mazo de encuentros (2 enemigos diferentes si hay 3 o más jugadores) y añádelo al área de preparación. Baraja el mazo de encuentros. <b></p>");
            AddHtml2("Evil-Under-the-Moon-TAP", "<p class='main-text'></b> Los enemigos no pueden ser enfrentados opcionalmente.</p><p class='main-text'><b>Obligado:</b> Al final de la ronda, aumenta la amenaza de cada jugador en 1.</p><p class='main-text'><b>Si los jugadores controlan 1 o más objetivos Pista, avanza a la siguiente etapa</b>.</p>");
            AddHtml("Gathering-Clues-TAP", "<p class='flavor-text'>Side A: La ciudad Rohirrim de Aldburg está llena de misterio. A la vuelta de cada esquina espera un nuevo acertijo, y detrás de cada acertijo hay una hoja afilada y desesperada. Antes del amanecer, deben llegar hasta el final para descubrir la verdad. Side B: Parece que Aldburg está albergando un misterio de dos cabezas. Si pueden entender un solo hilo, es posible que sean capaces de desenredar esta red corrupta y amarga. Es pasada la medianoche. El tiempo se está agotando.</p><p class='main-text'><b></b>  <b></p>");
            AddHtml2("Gathering-Clues-TAP", "<p class='main-text'></b> <b>Respuesta:</b> Al final de la ronda, si los jugadores controlan al menos 4 objetivos <b><i>Pista</i></b>, pueden avanzar a la etapa 3A.</p>");
            AddHtml("The-Uncertain-Dawn-TAP", "<p class='flavor-text'>Cuando el sol asoma por las calles de Aldburg, sus enemigos acorralados se revelan. Han reunido sus pistas. Ahora, tráiganlas mientras luchan por su vida y por el alma de Rohan.</p><p class='main-text'><b></b> <b>Al ser revelada:</b> Retira todas las cartas <b><i>Sospechoso</i></b> y cartas de misión secundarias de encuentro del juego. Añade cualquier enemigo puesto aparte <b><i>Tierras Brunas</i></b> o <b><i>Guarnición</i></b> al área de preparación, si es posible. <b></p>");
            AddHtml2("The-Uncertain-Dawn-TAP", "<p class='main-text'></b> El Amanecer Incierto obtiene –5 puntos de misión por cada objetivo <b><i>Pista</i></b> que controlen los jugadores.</p><p class='main-text'><b>Obligado:</b> Al comienzo de la fase de misión, descarta cartas de la parte superior del mazo de encuentros hasta que descartes a un enemigo. Revela a ese enemigo y añádelo al área de preparación.</p><p class='main-text'><b>Esta etapa solo puede ser superada al final de cada ronda. Si los jugadores superan esta etapa ganan la partida.</b></p>");
            AddHtml("Spreading-Inferno-TAP", "<p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta las 4 primeras cartas de tu mazo.</p><p class='flavor-text'>Entre las cenizas, reconocen este alfiler de inmediato. Pertenece al canalla de Gálmód, el consejero de confianza de la reina Morwen.</p>");
            AddHtml("The-Whisperer-TAP", "<p class='main-text'><b>Al ser revelada:</b> Añade Un Caso de Identidad y Cosecha Roja al área de preparación.</p><p class='main-text'>Si no está vinculado, vínculalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, inflígele 1 punto de daño.</p><p class='flavor-text'>La Susurradora se ha escapado entre las calles de Aldburg, pero ha dejado un arma distintiva y cara.</p>");
            AddHtml("The-Spy-Master-TAP", "<p class='main-text'><b>Al ser revelada:</b> Añade Un Fuego se Propaga y El Prisionero de Blanco al área de preparación.</p><p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pistas</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta una Vinculada de este héroe que no sea <b><i>Pista</i></b>.</p><p class='flavor-text'>Herido y luchando por escapar, El Maestro de Espías deja escapar un detalle clave: uno de sus agentes ya está en movimiento y se dirige a la prisión de la ciudad.</p>");
            AddHtml("Ossian-TAP", "<p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta una carta al azar de tu mano.</p><p class='flavor-text'>Con su último aliento, el traidor Ossian revela que Gálmód le ordenó matar a uno de los miembros de su propio éored: un testigo de una terrible traición.</p>");
            AddHtml("Garrison-Barracks-TAP", "<p class='main-text'><b>Al ser revelada:</b> Añade El Hombre del Labio Torcido al área de preparación.</p><p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta todos los recursos de su reserva de recursos.</p><p class='flavor-text'>El prisionero les ha contado a los guardias de un agente llamado El Maestro de Espías. Actualmente, la única pista es este anillo, que se cree le pertenece.</p>");
            AddHtml("The-Horse's-Tail-TAP", "<p class='main-text'><b>Al ser revelada:</b> Añade Susurradora en la Oscuridad al área de preparación.</p><p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, agota otro personaje que controles.</p><p class='flavor-text'>Una figura desconocida choca contra su mesa. Disculpándose profusamente, se marcha tropezando en la noche. Para cuando notan el saco de monedas que dejó, ya se ha ido.</p>");
            AddHtml("The-Armoury-TAP", "<p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, aumenta tu amenaza en 1.</p><p class='flavor-text'>El intendente de la armería les informa que él personalmente forjó la daga, así como esta flecha inusual, para Lord Gálmód.</p>");
            AddHtml("Great-Mead-Hall-TAP", "<p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta 2 fichas de progreso de cada lugar y carta de misión.</p><p class='flavor-text'>Escondida, encuentran una carta sellada escrita en Rohirrim entrecortado, firmada “Grimrede”. Está dirigida a un hombre que pensaban que era su amigo: Gálmód.</p>");
            
            AddHtml("Ruby-Cloak-pin-TAP", "<p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta las 4 primeras cartas de tu mazo.</p><p class='flavor-text'>Entre las cenizas, reconocen este alfiler de inmediato. Pertenece al canalla de Gálmód, el consejero de confianza de la reina Morwen.</p>");
            AddHtml("Silver-Dagger-TAP", "<p class='main-text'><b>Al ser revelada:</b> Añade Un Caso de Identidad y Cosecha Roja al área de preparación.</p><p class='main-text'>Si no está vinculado, vínculalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, inflígele 1 punto de daño.</p><p class='flavor-text'>La Susurradora se ha escapado entre las calles de Aldburg, pero ha dejado un arma distintiva y cara.</p>");
            AddHtml("Prison-Key-TAP", "<p class='main-text'><b>Al ser revelada:</b> Añade Un Fuego se Propaga y El Prisionero de Blanco al área de preparación.</p><p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pistas</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta una Vinculada de este héroe que no sea <b><i>Pista</i></b>.</p><p class='flavor-text'>Herido y luchando por escapar, El Maestro de Espías deja escapar un detalle clave: uno de sus agentes ya está en movimiento y se dirige a la prisión de la ciudad.</p>");
            AddHtml("Traitor's-Confession-TAP", "<p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta una carta al azar de tu mano.</p><p class='flavor-text'>Con su último aliento, el traidor Ossian revela que Gálmód le ordenó matar a uno de los miembros de su propio éored: un testigo de una terrible traición.</p>");
            AddHtml("Raven-Signet-Ring-TAP", "<p class='main-text'><b>Al ser revelada:</b> Añade El Hombre del Labio Torcido al área de preparación.</p><p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta todos los recursos de su reserva de recursos.</p><p class='flavor-text'>El prisionero les ha contado a los guardias de un agente llamado El Maestro de Espías. Actualmente, la única pista es este anillo, que se cree le pertenece.</p>");
            AddHtml("Rohirric-Coins-TAP", "<p class='main-text'><b>Al ser revelada:</b> Añade Susurradora en la Oscuridad al área de preparación.</p><p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, agota otro personaje que controles.</p><p class='flavor-text'>Una figura desconocida choca contra su mesa. Disculpándose profusamente, se marcha tropezando en la noche. Para cuando notan el saco de monedas que dejó, ya se ha ido.</p>");
            AddHtml("Red-Fletched-Arrow-TAP", "<p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, aumenta tu amenaza en 1.</p><p class='flavor-text'>El intendente de la armería les informa que él personalmente forjó la daga, así como esta flecha inusual, para Lord Gálmód.</p>");
            AddHtml("Letter-from-Dunland-TAP", "<p class='main-text'>Si no está vinculado, vincúlalo al héroe con la menor cantidad de objetivos <b><i>Pista</i></b> vinculados.</p><p class='main-text'><b>Obligado:</b> Después de que el héroe vinculado se prepare, descarta 2 fichas de progreso de cada lugar y carta de misión.</p><p class='flavor-text'>Escondida, encuentran una carta sellada escrita en Rohirrim entrecortado, firmada “Grimrede”. Está dirigida a un hombre que pensaban que era su amigo: Gálmód.</p>");
            
        }
    }
}