using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Models.LotR
{
    public enum EncounterCategory
    {
        None = 0,
        When_Revealed,
        Forced,
        Travel,
        Triggered_By_Engagement,
        Targets_Each_Player,
        Targets_First_Player,
        Targets_Engaged_Player,
        Exhaustion,
        Willpower_Reduction,
        Attack_Reduction,
        Defense_Reduction,
        Direct_Damage,
        Optional_Surge,
        Reveal_Additional_Cards,
        Player_Threat_Raise,
        Trample,
        Cannot_Engage,
        Cannot_Draw_Cards,
        Cannot_Spend_Resources,
        Cannnot_Play_Events,
        Cannot_Play_Allies,
        Staging_Area_Threat_Raise,
        While_In_Staging,
        While_Engaged,
        While_Active,
        Immediate_Attack,
        Return_to_Staging_Area,
        Enemy_Threat_Boost,
        Enemy_Attack_Boost,
        Enemy_Defense_Boost,
        Shadow_Card_Synergy,
        Remove_From_Quest,
        Unsuccessful_Questing,
        Targets_Quester,
        Targets_Attacker,
        Targets_Defender,
        Targets_Non_Quester,
        Card_Discard,
        Chosen_Card_Discard,
        Random_Card_Discard,
        Character_Discard,
        Attachment_Discard,
        Progress_Removal, 
        Forced_Travel,
        Targets_Exhausted_Characters,
        Targets_Heroes,
        Targets_Allies,
        Targets_Characters,
        High_Player_Threat,
        Encounter_Recursion,
        Condition_Attachment,
        Text_Blanking,
        Effect_Immunity,
        Attachment_Immunity,
        Scales_To_Number_of_Players,
        Bring_Enemies_Into_Play
    }
}