using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Models.Characters
{
    public class CirdanTheShipwrightCharacter : Character
    {
        public CirdanTheShipwrightCharacter()
            : base("Círdan the Shipwright", "Círdan the Shipwright", "Sindar Elf")
        {
            Bio =
@"<blockquote>
&ldquo;As they came to the gates Círdan the Shipwright came forth to greet them. Very tall he was, and his beard was long, and he was grey and old, save that his eyes were keen as stars; and he looked at them and bowed, and said 'All is now ready.'&rdquo;
<br>― The Lord of the Rings, The Grey Havens
</blockquote>
<p>Círdan (S, pron. [ˈkiːrdan]) was a Sinda, and Lord of the Falathrim during the First Age. He was one of the wisest and most foresighted of the Elves, and by the Second Age the oldest known elf in Middle-earth, to remain so throughout that age and the Third Age. He was also awarded Narya, one of the Three Rings, until he surrendered it to Gandalf. He was one of the last elves in Middle-earth, sailing West at last probably sometime in the Fourth Age.</p>
<p>The Quenya form of Círdan's name is Ciryatan (pron. [ˈkirʲatan]).</p>
<h3>History</h3>
<h4>Early History</h4>
<p>Círdan, born Nowë[3] (Q, pron. [ˈnowe]), was kin of both Elwë and Olwë, a lord in the host of the former. During the push westward, seeking to go to Valinor, Nowë and his followers kept going where most of his kin fell away throughout the journey. Despite Nowë's great eagerness to see the light of Valinor (his 'greatest desire'),[4] he loyally searched for Elwë upon his disappearance. Because of this the Teleri missed the first trip on Tol Eressëa to Valinor, on which went their close friends the Noldor and the Vanyar. They took for their king Olwë, and while waiting for Ulmo to return for them, Nowë headed the art of making and sailing ships, growing impatient. From this profession he took the name Círdan which means 'shipwright' in Sindarin. The Teleri also developed a great friendship with Ossë. At the same time, although most of the Teleri had given up, Círdan sought Elwë longer and harder than most of his kin, partly because of his love for him and his allegiance.</p>
<p>Because of this, Círdan came to the shores too late during the second embarking of Eressëa. He came to the sands to find them departed, and as he stood forlorn he saw far-off a glimmer of light upon Eressëa as it vanished into the West over Belegaer. Then he cried aloud:</p>
<blockquote>
&ldquo;I will follow that light, alone if none will come with me, for the ship that I have been building is now almost ready.&rdquo;
<br>― Círdan, Last Writings
</blockquote>
<p>But into his heart came a message from the Valar which warned him that his ship could not endure the voyage, nor would any ship for many years: 'Abide now that time, for when it comes then will your work be of utmost worth, and it will be remembered in song for many ages after.' Círdan answered 'I obey', and saw a vision of a ship.</p>
<h4>Foundation and Return of the Noldor</h4>
<p>Círdan therefore remained with those Teleri who had chosen to stay east of the Sea for love of Ossë, and became their lord. The folk became known as the Falathrim, 'people of the foaming shore', and dwelt in the Falas by the sea. There they built many ships, and the cities Eglarest and Brithombar, and found pearls which they sent to their overlord, King Thingol of Doriath, who was once Elwë.</p>
<p>When Belegurth broke forth in the First Battle of Beleriand in Y.T. 1497, Círdan was cut off and unable to come to Thingol’s aid. Further, although Thingol conquered with the help of the Laiquendi, the Falathrim were driven to the very edge of the sea, where they were besieged for some months, until the Return of the Noldor, when Fëanor struck Morgoth from the north. The siege of the Falas was abandoned as the Orcs were ordered northward to help their master, where they were all destroyed by Celegorm. The Falas were saved.</p>
<p>Círdan attended the Mereth Aderthad with many of his people, where he swore oaths of friendship with the Noldor, and quite possibly met and befriended his later neighbors and friends Turgon and Finrod. Although Turgon eventually moved from Vinyamar to faraway Gondolin, Círdan’s friendship with Finrod was lasting,[6] and Círdan became a close advisor to the Noldo. Círdan was, after all, a relative of his, being related (probably quite closely) to Olwë, Finrod’s grandfather.</p>
<h4>Early First Age</h4>
<p>When the tales began spreading (sown by Belegurth) of the Kinslaying of Alqualondë, Círdan, being very wise even at that time, was greatly troubled, feeling that these rumors sprouted from great malice. Knowing the jealousy and dissention among the Noldor, he guessed that the malice was that of the kinslayers. Therefore he dutifully sent messages to his overlord Thingol, telling him all that he had heard. This resulted in the banishment of Quenya, and greater strife between the Sindar and the Noldor.</p>
<p>Círdan may have assisted in the Dagor Aglareb, but this is unknown. Nevertheless he did not take part in the Dagor Bragollach, as he was far away and not directly attacked, if even he had time to come to the aid of his allies. Nevertheless Círdan made up for his lack of participation in the Second Assault on Hithlum, coming to the timely aid of Fingon when he was most needed. They sailed up the Firth of Drengist, then struck the unsuspecting orcs from the west, giving victory to the elves.</p>
<p>After the Nirnaeth Arnoediad, many fugitives came for shelter in the Falas. The Falathrim mariners harassed the orcs in guerilla attacks from the sea. But it was only a matter of time before Morgoth attacked. Then came the disastrous Fall of the Falas. Though both Brithombar and Eglarest were strong, with mighty walls, both fell one at a time due to the impressive array of siege-masters Morgoth had in his train. The elves fought valiantly, but the walls were broken and most of the Falathrim killed or enslaved. Barad Nimras was cast down, and the Falas laid to waste. But Círdan and some of his followers escaped by sea, and he took with him Gil-galad, one of the last of the princes of the Noldor. They came to the Isle of Balar and founded a new kingdom, but kept a foothold at the Mouths of Sirion, keeping ships hidden in the reeds there, making a refuge for all who fled there.</p>
<h4>Lord of Balar</h4>
<p>Turgon, receiving the dreadful news, requested that Círdan send mariners to seek Valinor and the aid of the Valar. Círdan built seven swift ships, and sent them westward. None returned, save for only one mariner of the Gondolindrim. The way to the West was closed.</p>
<p>Eventually Círdan served as messenger, when Ulmo delivered him a message for Orodreth, warning of the doom of Nargothrond, and ordering him to shut his gates and cast down the bridge. The warning went unheeded, resulting of the Fall of Nargothrond.</p>
<p>After news came to Balar of the Fall of Gondolin, Gil-galad was proclaimed High King of the Noldor. Círdan soon after became a fast friend of the young half-elf Eärendil son of Tuor and Idril, who had grown up essentially under his shadow, and was apprenticed to him. Círdan aided Eärendil in building the ship Vingilot, giving him advice and help. Círdan doubtless remembered his vision, and this ship was indeed a fulfillment of it.</p>
<p>Círdan and Gil-galad came with their armies from the Isle of Balar too late to prevent the disastrous Third Kinslaying, when the Havens of Sirion were ambushed and many fell. But Eärendil was not there, rather on a voyage, and the Silmaril of Beren and Lúthien had been spirited away by Elwing his wife. Thus, wielding the Silmaril, Eärendil came to Valinor and found the forgiveness of the Valar.[9] From that time on, Círdan was given foresight surpassing that of any of the elves,[4] perhaps some special grace of the Valar for his deeds in this world-changing episode (like the return of Glorfindel, who also contributed significantly). After the War of Wrath, Círdan, heeding the bidding of the Valar long ago, once more obediently abstained from finding his heart’s desire and going West, but with a small following remained in Middle-earth.</p>
<h4>Second Age</h4>
<p>The continents were shifted, but Círdan still took up his abode by the sea, in Harlindon with Celeborn and Galadriel.[10] Harlindon was located south of the Gulf of Lune, to the north of which was Forlindon, where Gil-galad and Elrond dwelt. There he welcomed the friendly and then-unfallen Númenóreans, making friends with Vëantur, chief of the mariners of Tar-Elendil, and later teaching Aldarion his grandson of ships (both management and construction) and seaside architecture,[11] doubtless being the foremost authority on both. At some point he moved to Mithlond.</p>
<p>Círdan advised against the creation of the Rings of Power when Annatar came, but, like Galadriel, his counsel went unheeded in the midst of the joy and enthusiasm of the Eregion-elves, and especially Celebrimbor. Nevertheless, when the Three Rings escaped the Sack of Eregion, Celebrimbor had appointed him to inherit one of them. He received Narya, the Ring of Fire.[12] Sauron, having revealed himself in the destruction of Eregion and empowered by the One Ring he had forged, invaded Eriador in the same blow. Nevertheless, though he killed many elves, he dared not attempt to take Mithlond or Lindon, feeling they were too strong and because they had the help of the Númenóreans. Indeed, they were his bane in that chapter of history, for the Númenóreans came and pushed him back beyond the Misty Mountains, ending the Dark Years.</p>
<p>Eventually there came the Fall of Númenor, when the great man-isle of Númenor was overturned and Aman removed from the circles of the world. But Elendil escaped with his sons to Middle-earth and founded the Two Kingdoms over a vast space of land, on both sides of the Misty Mountains.[13] This new kingdom of men profoundly impacted the lives of the elves of Lindon, as is seen in the War of the Last Alliance.</p>
<p>Círdan joined the alliance, and fought steadily beside his friends and comrades. Many fell there, including Gil-galad and Elendil. Yet again Círdan outlived those around him, and survived the battle. With Elrond he urged Isildur, Elendil’s first-born, to throw the captured One Ring into Orodruin, where it would be unmade. But Isildur refused.</p>
<h4>Third Age</h4>
<p>The early years of the Third Age were, for Círdan and the elves, mostly a time to catch their breaths after the fall of Sauron in the War of the Alliance. For more than a thousand years they went undisturbed,[15] but at around T.A. 1050 a shadow began to lengthen. Though many deemed that Sauron was defeated forever, for the first time in many centuries some evil was stirring, and awake. It was at this time the Istari, sent by the Valar, came. Though the Blue Wizards and Glorfindel may have come earlier during the Second Age, and Círdan most probably greeted them in Mithlond, it is known for sure that he met Gandalf there. Círdan was one of the few of the Wise left; of the other ancient elves, only Celeborn, Galadriel, Glorfindel (who was resurrected), and Elrond remained. He was the most foresighted of all of them, and alone knew the true purpose of the Istari. He also saw deep into the future of Gandalf, and gave him Narya, his greatest possession and one of the most secret and sought-after treasures in the world.</p>
<blockquote>
&ldquo;Take this ring, Master… for your labours will be heavy; but it will support you in the weariness that you have taken upon yourself. For this is the Ring of Fire, and with it you may rekindle hearts in a world that grows chill. But as for me, my heart is with the Sea, and I will dwell by the grey shores until the last ship sails. I will await you.&rdquo;
<br>― Círdan, Appendix B
</blockquote>
<p>In T.A. 1409, Círdan aided King Araphor of Arnor in battle against Angmar during the Fall of Rhudaur, after Weathertop was burned. With Círdan’s help, young Araphor drove the wraith’s armies from Fornost and the North Downs.[16] The second time Círdan came to the aid of men was four and a half centuries later, in T.A. 1975, when Círdan sent a ship north to Forochel to rescue the lost Arnorian king Arvedui. The crew endured a perilous journey, but found Arvedui. Yet Arvedui rashly attempted to return that winter, and all aboard perished.[16] The next year Círdan mustered the elves to join with the Dúnedain in the victorious Battle of Fornost. Later Círdan took control of the abandoned Elendil Stone on Emyn Beraid, which could gaze into the lost west and was without link to the other palantíri.</p>
<p>Círdan was invited onto the White Council when it was formed in T.A. 2463 in response to the rise of the Necromancer, whose identity was at that point concealed. Throughout all the recorded history of the White Council, his actions go unrecorded. His role may have only been passive; as an advisor rather than a planner. At any rate, nothing more is mentioned of his actions until the War of the Ring in T.A. 3018 and later T.A. 3021. Galdor was his messenger to Rivendell, though for reasons unknown. It may be that he, too, felt the growing shadow, even as his friend Gandalf did. Sent by Círdan 'on errand', Galdor attended the Council of Elrond, speaking with authority on his lord’s behalf.</p>
<p>The last mention of Círdan came with the end of the Third Age. When the Ringbearers came to Mithlond, Círdan greeted them before the gates. Although Gandalf, Galadriel, and Elrond passed west on the ship he had built for them, Círdan seems to have remained for a time. Eventually, however, he passed west on the last ship, fulfilling his heart’s desire that had waited so long.</p>
<h4>Characteristics and Impact</h4>
<p>In the last years of the Third Age, Círdan appeared very old save for his eyes which 'were keen as stars', wearing a long beard. Likely, he had grown a beard since having reached his third cycle of life.</p>
<p>Círdan had a profound effect upon the course of Middle-earth history. He was a loyal servant and friend of Elwë, sacrificing his heart’s desire in search of him.[4] This loyalty and sense of duty shows up numerous times over the course of history, including his second sacrifice in his submission to the Valar,[4] and his sending of troubling and potentially destructive rumors to his overlord Thingol. He was also the most foresighted of the elves, a gift from the Valar.[15][4] He conceivably saved Elven civilization with the founding of the havens at the Mouths of Sirion,[8] and with the fostering of both Gil-galad and Eärendil.[9] His precious gift of Narya to Gandalf was also timely and valuable.[15] He was clearly favored by Ulmo, seen by the number of messages passed through him.</p>";
            BioSourceUrl = "http://tolkiengateway.net/wiki/Cirdan";
            ImageArtist = Artist.Quinton_Hoover;

            addFriend("Elrond", "Elrond");
            addFriend("Gandalf", "Gandalf");
            addFriend("Galdor of the Havens", "Galdor-of-the-Havens");

            addGroup("The White Council", "The-White-Council");
            addGroup("The Grey Havens");

            addItem("Narya", "Narya-TGH");
        }
    }
}
