using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Models.Characters
{
    public class EomerCharacter : Character
    {
        public EomerCharacter()
            : base("Éomer", "Éomer, son of Éomund", "Man")
        {
            Bio =
@"<p>Éomer Éadig, of the House of Eorl, was the eighteenth King of Rohan, and first of the Third Line. He was the son of Théodwyn, sister of King Théoden of Rohan, and Éomund, a Chief Marshal of the Riddermark. After he and his sister Éowyn were orphaned Théoden adopted them as his own children.</p>
<h3>History</h3>
<h4>Early Years</h4>
<p>Éomer was born in T.A. 2991 as son of Éomund and Théodwyn. When he was eleven years old his father was slain by Orc raiders in the Emyn Muil. His mother fell ill and died soon after. His uncle Théoden adopted him and his sister Éowyn as his own children and they went to live at Meduseld.</p>
<p>Éomer grew strong and tall and became a valiant and skilled warrior and rider. Théoden made him Third Marshal of the Riddermark and he was in command of the East-mark like his father. He had his home at Aldburg in the Folde, one of the oldest towns of Rohan. With his Éored he defended Rohan mainly against Orcs from Mordor.</p>
<h4>Struggle Against Saruman</h4>
<p>But Rohan's enemies were not only at the borders but also within. Gríma Wormtongue, the King's advisor, was secretly a spy of the wizard Saruman, who dwelled at Isengard and had become a servant of Sauron. Gríma in secret worked to weaken Théoden and his kingdom and Théoden fell deeply under his influence. Éomer fell into the King's disfavor, but Gríma did not manage to destroy Éomer's loyalty to Théoden; nor to his cousin, Prince Théodred, whom Éomer regarded as his brother.</p>
<p>In the summer of 3018 Boromir, son of Denethor II, crossed Rohan on his way to Rivendell. Éomer learned from him about the dream of Isildur's Bane. Soon after September, evil Men, Orcs and Wargs in Saruman's service began to fight openly against the Rohirrim. Saruman claimed lordship over Rohan and blocked the Gap of Rohan.</p>
<p>The chief obstacles to an easy conquest of Rohan by Saruman were Théodred and Éomer. So came the first great battle in the conflict, the First Battle of the Fords of Isen, on 25 February 3018. After untiring assaults on Théodred's position, the Prince was finally killed, leaving Éomer as the only obstacle.</p>
<p>The day after the battle Èomer gained knowledge of a troop of Orcs entering Rohan from the east. Unbeknownst to Éomer, they were the same Orcs that had taken Meriadoc Brandybuck and Peregrin Took captive. Suspecting an alliance between Saruman and Sauron, he wanted to hunt them down. Under the strong influence of Grima, Théoden forbade Éomer to pursue the Orcs because Edoras would have been unguarded. But Éomer neglected the order since he already suspected Grima's treachery. On 27 February he set out with his Éored.[5] At the end of the next day they caught sight of the Orcs at the border of Fangorn Forest. They surrounded them and remained watchful throughout the night. With several small attacks they weakened the troop till another Orc band from Isengard arrived. But the Rohirrim succeeded in defeating them and surrounded the first troop even closer.</p>
<p>With the first light of the new day the Rohirrim proceeded to attack. They killed all the Orcs and Éomer himself slew their leader Uglúk. The hobbits meanwhile were able to flee into Fangorn Forest. Fifteen men and 12 horses did not survive the assault. They were buried in a mound encircled with fifteen spears.</p>
<p>On the way back to Edoras the Rohirrim met Aragorn, Gimli and Legolas. Éomer demanded their names and business. Fighting almost broke almost out between them, but Aragorn prevented this. He then told Éomer his true name and showed him his sword, Andúril. Éomer now listened to the story of their journey, and learned about the losses of Gandalf and Boromir. When Aragorn revealed that they had tracked the band of Orcs all the way from the Emyn Muil in the hope of rescuing the hobbits, Éomer was astonished and gave Aragorn the name 'Wingfoot', recognizing the difficulty of crossing so much terrain in so little time. He revealed that his men had destroyed the band of Orcs, and that it was fruitless to go searching for his friends. He instead urged Aragorn to return with him to Edoras to help the people of Rohan in their need, but Aragorn refused and insisted that he be able to continue his search for the hobbits. Although he was counteracting the law of Rohan by letting Aragorn go free, Éomer decided to trust him and he even lent him and his companions two horses, Hasufel and Arod, to help them in their search, but he asked them to prove his trust by bringing them back to Edoras when their search was over.</p>
<p>Upon his return to Edoras, Éomer threatened Gríma, but Grìma arrested him and accused him of breaking the law because he had pursued the Orcs and had allowed strangers to roam freely without Théoden's permission.</p>
<p>Éomer was released after Gandalf healed Théoden from the influence of Gríma. He was delighted to see that his king was recovering quickly from his weakness. Now Grima's treachery was revealed and only owing to Gandalf's intervening he was not killed but expelled from the Golden Hall. Théoden, now realizing the situation, decided to lead the Rohirrim into battle against Saruman instantly. The Three Hunters and Gandalf accompanied them when they left Edoras the same day.</p>
<p>The following day they met the scout Ceorl who had been sent out by Erkenbrand to warn Éomer. He was surprised to come across King Théoden's army riding north and brought news that Saruman had let loose his forces and that the Rohirrim had been forced to retreat across the Isen with great losses. These tidings caused Théoden to reconsider his strategy. After consultation with Gandalf he decided to ride to join Erkenbrand at Helm's Deep while the wizard left them saying that he would meet them there.</p>
<p>They arrived at Helm's Deep on the night of 3 March and Éomer oversaw the preparations for the great battle. In the middle of the night the siege began and when battering rams attacked the gates Éomer and Aragorn led a sortie through a passage on the side of the Hornburg that drove the enemies threatening the doors away. In the course of this Gimli saved Éomer's life when he killed two Orcs who had ambushed Éomer. The battle continued throughout the night and ever more attackers scaled the walls with large ladders. Aragorn and Éomer had to repeatedly move the defenders, who were getting weary, to repel the Orcs. With the help of a device of Saruman's the Orcs caused an explosion under the wall that made a wide hole in it. From then on the attackers could not be stopped and the defenders were separated. Éomer and Gimli retreated to the Glittering Caves whereas Aragorn and Legolas defended the Hornburg.</p>
<p>The battle seemed lost when at dawn Gandalf returned with Erkenbrand and 1000 riders from the Westfold. Together they drove the enemies out of the deep and into a forest of Huorns that had arrived during the night and from which no Orcs returned.[9] After the end of the battle Éomer accompanied his king to Isengard.[10] There they met Saruman who tried to enthral Théoden with his magic voice. But both Éomer and Théoden saw through him and his dark designs. Théoden said that Rohan would have no peace until Saruman and his works had perished. Gandalf then broke Saruman's staff and cast him from the Order of Wizards and the White Council.</p>
<h4>The Battle of the Pelennor Fields</h4>
<p>On 5 March the company set out to Helm's Deep. While they rested in the night Pippin took the palantír of Orthanc from the sleeping Gandalf, looked in it and was confronted by Sauron. Knowing the peril Pippin was in Gandalf said farewell to the others and departed with Pippin towards Minas Tirith.[12] The Three Hunters and the Rohirrim continued their journey towards Helm's Deep where they arrived on 6 March. Now Aragorn looked into the palantír and revealed himself to Sauron. Because of what he glimpsed in the palantír, he left the Rohirrim, and took the Paths of the Dead with the Grey Company. Éomer was afraid of never seeing him again, but Aragorn predicted that they would 'meet again, though all the hosts of Mordor should stand between.' before setting out.</p>
<p>Éomer accompanied his king to the muster of Dunharrow where he met his sister Éowyn again. Then the Red Arrow of Gondor which requested Rohan's aid was brought by a messenger and the Rohhirim set out in great haste to Minas Tirith.[14] They used narrow mountain paths and on 13 March reached Drúadan Forest where they met Ghân-buri-Ghân the chief of the Drúedain. He agreed to lead the Rohirrim by a secret road past the Orc hosts that laid siege to Minas Tirith.</p>
<p>So the Rohirrim arrived on the battleground of the Pelennor Fields at dawn on 15 March. Éomer led the first Éored that should follow the king's banner in the centre.[15] The Rohirrim were strong and filled with wrath and many enemies were slain. The Rohirrim went hither and thither at their will and so Éomer was only brought to Théoden when the king was already mortally wounded. Before his death Théoden hailed Éomer as King of the Mark and Éomer and those who stood by wept. When Éomer recognized Éowyn lying nearby a cold fury rose in him and without taking counsel or waiting for the approach of the men of the City he led his men across the field slaying all enemies in their path. As they charged he shouted out 'Death! Ride, ride to ruin and the world's ending!'.</p>
<p>But soon fortune turned against Éomer and he and his men were encircled. Just in time came the aid of the horsemen of Gondor among them Hirluin of the Green Hills and Imrahil prince of Dol Amroth came. But ever more enemies came from Osgiliath and when the black ships of the Corsairs came up the Anduin the battle seemed lost. Éomer rallied the Rohirrim for a last fight against the Corsairs when he realized the standard of Aragorn unfurling on the first ship.</p>
<p>The enemies fled when they saw that their own ships were filled with foes and so Éomer met Aragorn in the midst of the battlefield as Aragorn had predicted.</p>
<p>The battle ended in victory and Éomer learned that Éowyn was not dead but lay gravely ill in the Houses of Healing. He also learned that the contact with the Lord of the Nazgul was not the only reason for her sickness but that also her despair had worsened it. Aragorn managed to heal Éowyn and she awoke at her brother's call. Meriadoc Brandybuck was also healed and Éomer made him a Knight of the Riddermark in return for his aid for Éowyn and Théoden.</p>
<p>The next day Éomer took part in the debate of the Captains of the West. There Gandalf told that their hope now lay with Frodo Baggins and Sam Gamgee, who had gone to Mordor to destroy the One Ring wrought by Sauron. Gandalf councelled that they should ride to the Black Gate in order to force Sauron to empty his land and to give the Ring-bearers their only chance. Aragorn agreed and Éomer decided to follow his friend in return for his aid in their time of need.</p>
<p>On 18 March the Host of the West, Gandalf, the Three Hunters and Éomer among them, set out towards the Black Gate. They arrived there on 25 March and withstood the forces of the enemy until the Ring was destroyed and Sauron and his servants and works perished.</p>
<p>After the great victory Aragorn set up his camp on the Field of Cormallen in North Ithilien and Éomer took part in the celebrations there.[20] Together with the other Captains of the West he returned to Minas Tirith and attended the coronation of Aragorn on 1 May. A week later he set out to Rohan with Éowyn for there was much to organize and to set in order. Before his departure he renewed the Oath of Eorl for Aragorn and both swore everlasting friendship between Rohan and Gondor.[21] Éomer returned in July and brought Théoden's body back to Edoras. On 10 August there the funeral of Théoden took place and Éomer announced the betrothal of Éowyn to Faramir, the Steward of Gondor and Prince of Ithilien. When the feast was over, Éomer and Éowyn gave Merry the name Holdwine, 'loyal friend,' of the Mark, and the ancient Horn of the Mark, an heirloom of the House of Eorl.</p>
<h4>King of the Mark</h4>
<p>But though Sauron had perished the King of the West had many enemies to destroy before the White Tree could grow in peace. So Éomer often fulfilled the Oath of Eorl and went with King Elessar far into the East and South of Middle-earth. He was known as Éomer Éadig, or 'the Blessed', because during his reign Rohan recovered from the hurts of the War and became a rich and fruitful land again. In T.A. 3021 he wedded Princess Lothíriel, daughter of Prince Imrahil of Dol Amroth, whom he had met during his stay in Gondor and she bore him a son Elfwine the Fair.</p>
<p>In Fourth Age 63 Éomer asked his Knight Merry Brandybuck to visit him one last time. Both Merry and his friend Pippin came to Rohan and stayed for a while. In the autumn of that year, King Éomer died and his son Elfwine the Fair became King of Rohan. King Éomer had reigned for 65 years, longer than any other King of Rohan save Aldor the Old.</p>
<h4>Personality</h4>
<p>He was tall, strong and possessed of great passion and also was considered a valiant and splendid warrior and a discerning and decent man. Éomer became a great, wise and skilled warrior and rider. In a note written well after the initial publication of The Lord of the Rings, Tolkien gave Éomer's height as 'of like height with Aragorn', due to his grandmother Morwen Steelsheen, who was of Númenórean descent. Aragorn's height has been estimated at 6 feet, 6 inches.</p>
<h4>Weapon</h4>
<p>Éomer's sword was called Gúthwinë, which is Old English for 'battle-friend'.</p>
<h4>Etymology</h4>
<p>His name is likely derived from the Anglo-Saxon words eoh ('war-horse'), and mere, ('grand, excellent, famous'). He adopted the epithet Éadig during his kingship, which is an Old English word meaning 'happy, wealthy' and usually translated as 'blessed', used for saints in medieval literature.</p>
<h4>Inspiration</h4>
<p>Eomer is an Old English name appearing in Beowulf. Eomer is also an ancestor of Offa of Mercia.</p>";
            BioSourceUrl = "http://tolkiengateway.net/wiki/Eomer";
            ImageArtist = Artist.Magali_Villeneuve;

            TheTwoTowers();
            TheReturnOfTheKing();

            Alias("Éadig");
            Alias("Third Marshal of the Riddermark");
            Alias("King of Rohan");

            addFamily("Éomund (Father)", "Eomund");
            addFamily("Théodwyn (Mother)");
            addFamily("Lothíriel (Wife)", "Lothiriel");
            addFamily("Éowyn (Sister)", "Eowyn");
            addFamily("Théoden (Uncle)", "Theoden");
            addFamily("Théodred (Cousin)", "Theodred");

            addGroup("The Rohirrim", "The-Rohirrim");

            addItem("Firefoot", "Firefoot-TDT");
            addItem("Gúthwinë", "Guthwine-TMoF");
        }
    }
}