using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Models.Characters
{
    public class GandalfCharacter : Character
    {
        public GandalfCharacter()
            : base("Gandalf", "Gandalf", "Maia")
        {
            Bio =
@"<blockquote>
&ldquo;Gandalf was shorter in stature than the other two; but his long white hair, his sweeping silver beard, and his broad shoulders, made him look like some wise king of ancient legend. In his aged face under great snowy brows his eyes were set like coals that could suddenly burst into fire.&rdquo;
<br>― The Fellowship of the Ring, Many Meetings
</blockquote>
<p>Gandalf was one of the five Istari sent to Middle-earth by the Valar in the Third Age. In Valinor he was known as Olórin. Gandalf was instrumental in bringing about the demise of Sauron in T.A. 3019, chiefly by encouraging others and dispensing his wisdom at pivotal times. Gandalf was originally robed in grey, and second to Saruman in the Order of wizards. After his fall in Moria, Gandalf returned to Middle-earth as head of the Order, robed in white. Gandalf was noteworthy for his keen interest in Hobbits.</p>
<h4>History</h4>
<p>The wisest of the Maiar, Gandalf was created by Ilúvatar before the Music of the Ainur.[4] At the beginning of Time, he was amongst the Ainur who entered into Eä.[5] Here he became one of the Maiar of Manwë, Varda, Irmo and Nienna named Olórin. By Nienna he learned pity and patience.</p>
<p>He loved the Elves but he walked unseen among them, or wore a fana that appeared like an Elf, and sent them fair visions in their hearts that made them wiser. Like Nienna, he took pity on the sorrows of the Children of Ilúvatar and drove those who listened to him out of despair.</p>
<p>During the Third Age, while Sauron's 'dark spirit of malice' was increasing over Middle-earth, the Valar chose five emissaries from among the Maiar to go and help the peoples. Manwë selected Olórin, who, at first, did not wish to go, as he feared Sauron. However, Manwë said that that was all the more reason why he should go.[7]. Furthermore, the One Ring, the location of much of Sauron's power, presumably still existed somewhere in Middle-earth.</p>
<p>Olórin submitted to the will of Manwë, and departed Valinor to Mithlond in the year T.A. 1000.[7] He arrived after the others, Curumo, Aiwendil, Pallando, and Alatar, at about the same time the Necromancer appeared in Mirkwood.</p>
<h4>Coming to Middle-earth</h4>
<p>Olórin , like the other Wizards, took the shape of an old man. He was robed in grey and went about as a wanderer and counselor.</p>
<p>At Mithlond he was welcomed by Glorfindel, his friend from Valinor, sent earlier on a similar mission, and Círdan the shipwright, who possessed Narya, one of the Three Elven Rings of power. Círdan divined in Olórin a sense of strength and power despite his appearance as a bent and aged old man. Círdan gave Narya to Olórin with a prediction of his future struggles with evil, and a promise that it would support and aid him in his labors. Then Círdan said &ldquo;But as for me, my heart is with the Sea, and I will dwell by the grey shores until the last ship sails. I will await you.&rdquo;
<p>Gandalf then began his sojourn in Middle-earth. Unlike Saruman, Gandalf did not take up a single permanent residence. Gandalf never went to the east[9] and apparently restricted his activities to the Westlands of Middle-earth, where the remnants of the Dúnedain and the Eldar remained to oppose Sauron. He was known by many names during the long years he remained in Middle-earth: Elves named him Mithrandir, the Grey Pilgrim, while the men of Arnor named him Gandalf, which became his most common name. He was also known as Incánus (in the south), and Tharkûn to the Dwarves.</p>
<p>A legend says that Gandalf was given by Yavanna the Elfstone of Eärendil, to bring to the peoples of Middle-earth as a token that the Valar had not forsaken them. He gave it to Galadriel, and remarked prophetically that she would in turn pass it to an individual who would also be called Elessar.</p>
<h4>Early Vigilance</h4>
<p>Around T.A. 1100,[8] the Istari and the Eldar discovered that some evil entity resided at Dol Guldur in Mirkwood. Dark shapes moved in the forest and evil began to multiply in the woods. Some thought a Nazgûl had returned to torment the world, or some new evil was arising. Gandalf was unsure, and feared that perhaps Sauron himself might have returned.</p>
<p>Over the next two hundred years the evil continued to grow, as well as the source directing it. Orcs were multiplying in the Misty Mountains and elsewhere. The Witch-king, the mightiest of the Nazgûl, had built a fortress in Angmar in the Northern wastelands and waged unending war against the Kingdom of Arnor. Meanwhile Moria and Minas Ithil fell under a shadow, while other wars, plagues, and catastrophes occurred across Middle-earth. Gandalf went to Dol Guldur in 2063 to discover its secret.[8] An entity known only as the 'Necromancer' fled before him preventing Gandalf from identifying him.[11] After Gandalf's incursion, the evil there seemed to desist, and its absence allowed for some centuries of calmness.</p>
<p>That peaceful period was known as the Watchful Peace and lasted for almost four hundred years, but the Nazgûl had used this period to prepare for Sauron's return, in 2460.[8] Realising the returning evil, the Wise formed the White Council three years later. Galadriel, bearer of one of the Three Elven Rings and mighty among the Eldar, wished Gandalf to be the chief of the Council, but it was Saruman who took this place-- because of his vast knowledge, but also because Gandalf refused this position, wishing to set down no roots and to maintain his independence.</p>
<p>During his wanderings in Eriador, Gandalf met and befriended the isolated and secretive people of the Hobbits in their country, The Shire. During the Long Winter of 2758 Gandalf came to their aid.[8] It was then when he witnessed and admired the pity and courage the humble Hobbits reserved in their hearts.</p>
<p>When King Thráin II, a dwarf of the royal line of Lonely Mountain, disappeared on journey to Erebor, Gandalf looked for him. At some point after 2845 he entered the abandoned city of Khazad-dûm. After his vain search the Wizard exited through the Doors of Durin; however this experience did not help him know how to open the doors from the outside.</p>
<p>In 2850, his quest led him once more to Dol Guldur, this time in secrecy.[8] He found Thráin in the dungeons, who gave the Wizard his last possessions, the map and key to Erebor[14]. Most importantly, he found that the Necromancer was no Nazgûl – it was Sauron himself, and he had taken the last of the Seven Rings from the Dwarf King; Sauron was gathering the remaining Rings of Power and possibly searching for his lost One Ring.</p>
<p>Gandalf escaped Dol Guldur and returned to the White Council.[11] After relating his discoveries, he urged the council to attack Sauron while the One Ring was still lost and Sauron's power immature. But Saruman said that it was better to watch and wait; that the One Ring had long ago rolled from Anduin to the Sea. The majority of the council agreed with Saruman. Elrond Half-elven, a powerful member of the council, later privately told Gandalf he had a foreboding that the Ring would be found, and that the war to end the age was coming. Indeed, he added, he feared that it would end in darkness and despair. Gandalf encouraged him, saying there were many 'strange chances,' and that, 'help oft shall come from the hands of the weak'. Gandalf did not yet realize that Saruman now wanted the ring for himself and was secretly searching for it along the banks of river Anduin.</p>
<h4>The Quest for Erebor</h4>
<p>Gandalf would visit the Shire occasionally and participate in the Midsummer-eve parties of the Old Took where he impressed young Hobbits with his fireworks, and his stories about Dragons, Goblins and princesses.[12] He was thus known to be &ldquo;responsible for so many quiet lads and lasses going off into the Blue for mad adventures&rdquo;. He also met a relatively adventurous Hobbit named Bilbo Baggins although he was far from 'adventuresome.'
<p>Gandalf was concerned about the weak state of the North. Smaug the Dragon had destroyed both the Kingdom under the Mountain and the town of Dale, and Gandalf feared that Sauron might use the desolation around Erebor to regain the northern passes in the mountains and the old lands of Angmar. Gandalf knew that Dwarf lord Thorin planned to battle against Smaug, but he knew that it would not be enough. In 2941,[8] while staying the night in Bree, Gandalf happened across the exiled King of Durin's Folk Thorin Oakenshield.[12] Thorin initiated conversation; he had been having a strange feeling urging him to seek Gandalf. Gandalf was intrigued, for he had thought to seek Thorin as well. They found they were taking the same road for a while (Thorin passing through the Shire on his way to the Ered Luin), and they agreed to travel together. Thorin wanted advice, and Gandalf in turn wanted to discuss the Dragon Smaug with Thorin.</p>
<p>Ultimately, Gandalf concocted a plan wherein Thorin could destroy Smaug and recover his family fortune, albeit with a 'burglar' of Gandalf's own choosing. Gandalf had a feeling that a Hobbit should be involved, and he remembered Bilbo Baggins. At first he found only Holman Cotton as Bilbo had left on the occasion of the Elven new year, something that persuaded Gandalf that Bilbo was the right person for the job.[12] He visited Bilbo later, bringing along the kinsmen of Thorin.[3] In the end Gandalf convinced the reluctant Baggins to become a burglar for Thorin. Gandalf then accompanied Thorin and Company to Rivendell. During the journey Gandalf was instrumental in saving the travelers' lives from several calamities.</p>
<p>Gandalf saved them from a trio of Stone-trolls, and later obtained the legendary sword Glamdring from their Troll-hoard; Gandalf bore it thenceforth.[15] He also helped Thorin and Company through the Misty Mountains; when unknowingly they camped in the Front Porch of the Goblin-town the Goblins captured the whole company except Gandalf, who surprised them much later, killing the Great Goblinand then leading the Dwarves to the exit.[16] It was during this time that Bilbo obtained a 'magic ring'.[17] Bilbo initially claimed he 'won' it from the creature 'Gollum' while the company was under the Misty Mountains.[18] The ring conferred invisibility on Bilbo when he wore it, and he kept it secret from Gandalf for some time.</p>
<p>On their escape out, the Company was saved by the Eagles of the Misty Mountains; Gandalf once had healed the Great Eagle from a poisoned wound, and thenceforth they became friends. The Eagles picked them up to their eyrie, and the next day they dropped them to the other side of the Mountains.</p>
<p>Gandalf then sought the hospitality of Beorn, persuading him to welcome and host the whole Company in his hall. But then he left the quest prior to its completion; after leading the Company to the outskirts of the Forest Gate, he gave them some final advice (but little did he know that the lands had changed by then) before they'd enter Mirkwood, and went to attend other obligations.[19] The White Council had met under the gravest of circumstances: Sauron's vast power was returning, even without his Ring. Gandalf at last convinced the Council to attack Dol Guldur, to which even Saruman agreed (as by now he feared Sauron as a rival, and wished to delay his search for the Ring). Gandalf joined his peers in assailing Dol Guldur, ridding Mirkwood of the Necromancer's presence, who fled to Mordor.[20] When he was about to finish his task, news about what happened to Thorin's Company in Mirkwood reached him, and realized that the instructions he gave did not help them; they had lost their way, and then vanished from the imprisonment of the Wood-elves, who had captured them. He was anxious to get back to them as soon as possible.</p>
<p>Meanwhile Thorin's quest was successful: Erebor was retaken and Smaug was killed,[22] but when Gandalf finally arrived to the area, he found the Dwarves of Erebor and the Iron Hills preparing for an attack by the Lake-men and the Elves of Mirkwood. He was with Bard and Thranduil and revealed his presence trying to reason with Thorin. When the attack was beginning, Gandalf halted them, to warn that the Orcs and Wargs were coming to claim the treasure. He invited Dáin Ironfoot for council, and soon Dwarves, Elves and Men formed an alliance, and defeated the Orcs of the Misty Mountains in the Battle of Five Armies.</p>
<p>King Thorin was mortally wounded and after his funeral and the reestablishment of Erebor under Dáin, Bilbo and Gandalf followed their way back; they celebrated Yule at Beorn's, and then returned to Rivendell, where he discussed with Elrond the events of Dol Guldur and the Lonely Mountain. Gandalf had accomplished his immediate goal, which was to destroy Smaug, who could have been used to disastrous effect by Sauron. A large number of Orcs and Wargs also were killed in the North, removing threats to Rivendell and Lothlórien.[12] But they both agreed that it would be better if the Necromancer were banished from the world altogether.</p>
<p>As Gandalf and Bilbo passed by the site of their former encounter with the stone-trolls, they made sure to recover the gold of the troll-hoard they had buried.</p>
<p>Gandalf, for his part, found himself amazed by the hobbit; until then the wise had paid no attention to hobbits and knew little of them. For the rest of his sojourn in Middle-earth, Gandalf took a special interest in hobbits, and particularly in the Baggins family.</p>
<h4>The Return of the Shadow</h4>
<p>Despite the Council's hopes, Sauron was not weakened by this attack. He had foreseen the move that drove him from Mirkwood, and his retreat was but a feint. Ten years after the attack, Sauron declared himself openly in Mordor in 2951and rebuilt the Barad-dûr. The White Council met for one last time in 2953 to debate about the Rings of Power. Saruman quieted his peers claiming to have the knowledge that the One Ring was lost in the Belegaer. After their meeting, Saruman, jealous and afraid of Gandalf, set spies to watch all his movements; this would affect the peaceful Hobbits, as Saruman thus discovered the existence and noted Gandalf's interest in the Shire, and started sending agents in Breeand the Southfarthing.</p>
<p>Meanwhile Sauron began reassembling his forces for the final blow against the hated West. Easterlings from Khand and beyond the Sea of Rhûn, joined by men from Harad reinforced his stronghold in Mordor; Orcs, trolls, and other foul beasts were multiplying while his minions were searching the Anduin for any sign of his precious One Ring.</p>
<p>Gandalf met Aragorn, the hidden Heir of Isildur in 2956, and soon became friends with him. From that point on Aragorn and Gandalf often worked together towards a common end - the defeat of Sauron.</p>
<p>During this period Gandalf visited the Shire frequently, especially his friend Bilbo Baggins, and his younger cousin, Frodo. He noted Bilbo's unusual youthfulness, despite his advancing age; the suspicious 'magic ring' that Bilbo had acquired during his adventure began to weigh on his mind. Gandalf recalled the deceit Bilbo used in originally claiming it for his own-- Bilbo had later admitted to stealing it from Gollum. Gandalf could see that Bilbo was now very preoccupied with the ring. Such un-hobbitlike behaviour aroused his suspicions. In 3001 he organized for him the Bilbo's Farewell Party, and before leaving the Shire, he convinced Bilbo to leave the Ring for Frodo. He then emphatically warned Frodo not to use it; Gandalf had begun to suspect that the 'magic ring' was indeed a ring of power.</p>
<p>Keen now to find out more about Gollum, he sought Aragorn's help to capture him, a quest that lasted for years all around Rhovanion and the confines of Mordor.[8] Studying the records in Minas Tirith, he found the Scroll of Isildur and pieced together the missing history of the One Ring; on his way back to the Shire he got word from the Galadhrim that Aragorn had finally captured Gollum and he went to Mirkwood to meet him. For days he interrogated him in order to verify what he already knew, in 3017. A great fear came over him when he learned that Gollum had been to the Barad-dûr. Sauron had tortured Gollum and learned not only of the 'magic ring', but also the names 'Shire' and 'Baggins'. Gandalf now returned in haste to the Shire, certain that Frodo's ring was not simply a ring of power: it was the One Ruling Ring of Sauron.</p>
<h4>The War of the Ring</h4>
<p>After Gandalf’s fears were confirmed, he returned to the Shire and advised Frodo to leave as soon as possible, promising to return before a farewell party for Bilbo in autumn of that year (3018), and to escort him to Rivendell. Gandalf also told Frodo about the creature Gollum, to which Frodo exclaimed that he should have been killed. Gandalf speculated that perhaps Gollum would have a part to play before the end, and in any case, it was not for them to decide who should live and who should die.</p>
<p>While in the Shire, he had a sense of foreboding and in the aftermath of Sauron's attack on Osgiliath he heard disturbing news about war in Gondor and a Black Shadow. He started wandering around Eriador hearing news from the refugees who had a fear they could not speak about, until he met Radagast who brought a message of Saruman that he must seek him at once; and a warning that the Ringwraiths are looking for the Shire.[25] He went to the Prancing Pony at Bree. Believing that he would not be able to return to Frodo in time, he wrote a letter, urging him to move as soon as possible for Rivendell, and seek someone 'Strider' whose real name is Aragorn, with a riddle to identify him; Gandalf would then try to catch up with them when available. He also instructed Barliman Butterbur to send the letter to Hobbiton and to expect a Mr. Baggins that will come under the name of 'Mr. Underhill'. He left the inn, but Barliman would forget to send the letter.</p>
<h4>The Treachery of Saruman</h4>
<p>Soon thereafter Gandalf arrived at Isengard. At their meeting, Saruman at last revealed his desire for the One Ring. He offered to his 'old friend and helper' that they take the Ring for themselves and seize power from Sauron. Gandalf rejected this with horror, and was imprisoned by Saruman on the pinnacle of Orthanc. Gwaihir, chief of the Eagles, soon arrived and helped Gandalf escape. Gandalf knew he must return quickly to the Shire, as Frodo (and the ring) were in grave danger from both Sauron's Nazgûl and now Saruman's treacherous desire for the ring.</p>
<p>Gandalf hurriedly went to Rohan, desiring to find a strong steed; there he obtained Shadowfax from King Théoden, who later resented the gift. This lord of horses and Gandalf forged a special bond, and Gandalf made quick use of Shadowfax's incredible strength and endurance.</p>
<p>Gandalf sped to the Shire. Fortunately, Frodo had already left the Shire without waiting for Gandalf, and was seeking the refuge of Rivendell. Upon arrival Gandalf learned that the Nazgûl, arrayed as Black Riders, had been searching the area. Dismayed, he set out for Bree; Barliman apologised to Gandalf for forgetting to send the letter, worried that the hobbits had left with Strider, the suspicious Ranger. But for Gandalf this was a hope which far exceeded his expectations. After congratulating a puzzled Barliman, and blessing his beer, Gandalf then made for Weathertop, a high point in the region, to observe the surrounding area.</p>
<p>There he was assaulted at night by the Nazgûl, but drove them off after a great battle of light and flame. These phenomena were seen by Aragorn and the hobbits from afar, without knowing it was Gandalf. Before leaving, he marked some stones with the certh G for them to find.</p>
<p>He then went directly to Rivendell, where he welcomed Glorfindel, Aragorn and the hobbits upon their arrival several days later, Frodo being sorely wounded but still in possession of the ring.</p>
<h4>The Fellowship of the Ring</h4>
<p>Elrond called a council after Frodo was healed to consider the momentous decision regarding the ring. By chance, representatives of most of the free peoples happened to be in Rivendell already for various reasons. Elrond and Gandalf advised that the Ring should be destroyed in the fires of Orodruin, where it was made. Others dissented or objected, but eventually submitted to Gandalf's plan. Ultimately, Elrond appointed the Fellowship of the Ring as nine walkers, numerically set against Sauron's nine Nazgûl. The relatively small number reflected the realization by Elrond and the other council members that the quest of Mount Doom would not rely upon strength of arms, but on stealth and good fortune. Gandalf was chosen to lead the company, which included Aragorn, Boromir, Legolas the Elf, Gimli the Dwarf, and the hobbits Frodo Baggins, Samwise Gamgee, Peregrin Took, and Meriadoc Brandybuck.</p>
<p>Several obstacles stood in the company's way. The vast Misty Mountains had to be crossed, for Gandalf was determined not to lead the company near Isengard. Gandalf decided to take a southern route to the Redhorn Pass and there to cross the Misty Mountains near Caradhras, thereby traversing the mountain range and avoiding Isengard. When this attempt failed due to a terrible storm he then decided to take the Fellowship through the ruins of Moria, where the remains of the great Dwarf city of Khazad-dûm was now a labyrinth of tunnels under the mountains. Others in the company were loathe enter the maze, as it was now the lair of orcs and something known only as 'Durin's Bane'.</p>
<p>At the Doors of Durin on the west side of the mountains, Gandalf, after some delay, spoke the password and led the company into the dark. Having been in Moria on an earlier perilous errand, he was somewhat familiar with the underground passages. Eventually the party came to the Chamber of Mazarbul, where Gandalf read the Book of Records, which revealed the fate of Balin, the leader of an ill-fated attempt to re-colonize Moria. Soon after, the party was attacked by orcs, and forced to flee the chamber. By then Gandalf was well aware of their location, and he led the party quickly towards the eastern exit.</p>
<p>Unfortunately Durin's Bane caught up to the group at the Bridge of Khazad-dûm. Gandalf and Legolas immediately realized what it was: a Balrog of Morgoth, a servant of the first dark lord. In a spectacular display of bravery Gandalf faced the demon and broke the bridge both stood upon, leaving the beast to fall into a seemingly bottomless chasm. But the Balrog's whip lashed out, and grasped Gandalf by the knees, causing him to fall into the pit. While falling, Gandalf shouted 'Fly, you fools' and vanished into the abyss.</p>
<p>Yet Gandalf did not die; he and the Balrog fought long in the bowels and deep places of Arda. After restless pursuit over the course of eight days, Gandalf and the beast finally came to the summit of the Endless Stair upon the peak of Celebdil, where he fought the demon for two days and nights. The Balrog had burst into flame anew when it exited the stairs; ice, wind, and smoke swirled about them as they dueled. Gandalf used his last measure of strength to slay the Balrog, throwing him down the mountainside in ruin. Gandalf's spirit then left his body, having sacrificed himself to save the Fellowship.</p>
<h4>Gandalf the White</h4>
<p>But Gandalf's spirit did not depart Middle-earth forever at this time. As the only one of the five Istari to stay true to his errand, Olórin/Gandalf was sent back to mortal lands by Eru, and he became Gandalf once again. Yet, as he was now the sole emissary of the Valar to Middle-earth, he was granted the power to 'reveal' more of his inner Maiar strength. This naked power that lay within him was seldom used during the remainder of his time in Middle-earth, as his mission was essentially the same: to support and succor those who opposed Sauron. Nevertheless, when Gandalf's wrath was kindled his 'unveiled' strength was such that few of Sauron's servants could withstand him.</p>
<p>As he lay on the mountaintop, the great eagle Gwaihir came up and bore him to Lothlórien, where he was clothed and replenished, and given a new staff by Galadriel. Gandalf soon learned that Frodo and Sam had left the Fellowship and were attempting the quest of Mount Doom alone. As Frodo was beyond his assistance now, Gandalf promptly went south to Fangorn Forest, where he met the Three Hunters: Aragorn, Legolas, and Gimli, and gave them messages from Galadriel. Then he called forth Shadowfax, and rode with them to Edoras. There he found that Saruman's spy Gríma Wormtongue had deceived King Théoden into hopeless impotence. Gandalf quickly deposed Wormtongue and encouraged Théoden to ride west to war against Saruman. Gandalf by now was keenly aware that the great war to end the age was beginning; if Saruman conquered Rohan then Gondor would be alone with enemies on all sides.</p>
<p>At Gandalf's encouragement King Théoden went west to Helm's Deep where he was quickly besieged; Gandalf then searched for Erkenbrand and the forces of the Westfold, which he later found and led to the Deep, thus breaking the siege. Meanwhile, the Ents (along with the hobbits Merry and Pippin) moved against Saruman and sent Huorns against the orcs, resulting in the utter ruin of the outer walls of Isengard and the complete annihilation of Saruman's orcs. After the battle, Gandalf went to Orthanc with Théoden, Aragorn, and a small group. There Saruman rejected Gandalf's offer of forgiveness with contempt. Gandalf then broke Saruman's staff and cast him from the Order and the Council. Gandalf imposed a strict watch on Isengard by the Ents and then advised King Théoden to ride to Gondor's defense as soon as possible. The wizard's mind had already turned to Gondor and the coming climactic battle in the east.</p>
<h4>The Siege of Minas Tirith</h4>
<p>As a 'reward' for Pippin, who had foolishly gazed into a palantír, Gandalf took the Hobbit with him to Minas Tirith, the last bastion of the west. Soon after arriving, Gandalf confronted Denethor II, the Ruling Steward, and learned that he was near despair over the death of his eldest son, Boromir. Pippin entered the Steward's service in payment of the debt that he and Merry owed, the death of Boromir. Ostensibly they were allies, but the Steward treated him with disrespect and suspicion. When Faramir, the Steward's younger son, returned from Osgiliath and was attacked by Nazgûl, Gandalf upon Shadowfax drove them away by revealing the power within him; later Faramir told him that Frodo and Sam were still alive and headed towards Mordor.</p>
<p>The city was soon besieged by a vast force from Mordor, led by the Witch-king. An ill-advised counter attack resulted in Faramir receiving a wound from a poisoned dart; he lay near death inside the Tower. Still, Gandalf encouraged the men of Minas Tirith to have hope, and dispelled the fear of the Ringwraiths by his very presence. But Sauron's catapults hurled flaming bolts upon the city; soon the first circle of the city burned unchecked. Denethor now lost all heart as the city burned and his only remaining son hovered near death; he abandoned his leadership of the city. Gandalf then took it upon himself to direct the defense of the city. When the gigantic ram Grond destroyed the ancient entrance to the city, Gandalf placed himself alone at the ruined gateway. The Witch-king then appeared in the midst of the blasted gate upon a black horse and threatened Gandalf with death; but Gandalf did not move — seated upon Shadowfax he defied the mightiest of Sauron's minions. However, the stand-off ended inconclusively, as the morning arrived along with the host of the Rohirrim. Hearing the horns of the Riders of Rohan, the Witch-king departed.</p>
<p>But Gandalf did not pursue his foe, for Pippin brought him news that Denethor was about to commit suicide in the high tower, burning himself and his son Faramir on a pyre like the heathen Kings of old. Gandalf rushed to stop this madness and was able to save Faramir, but not Denethor, whose despair and grief had overcome his mind. Gandalf also learned how it was that Denethor's will had been broken: Denethor clutched a palantír in his hands as he burned. Clearly Denethor had been using the stone's special properties for some time — extending his vision far beyond those of mannish eyes, but also wrestling in thought with Sauron. And even though Sauron could not completely overwhelm Denethor's mind, his courage was daunted by knowledge of the vast might of Mordor. Thus the shadow entered into the capital of Gondor.</p>
<p>Nevertheless, and against all hope, the siege was broken. Éowyn of Rohan and the hobbit Merry defeated the Witch-king, whose last wail was heard by many as he was reduced to impotence. Soon after, Lord Aragorn arrived with a large valour of men from the southern fiefs upon a captured pirate fleet from Umbar. The forces of the men of the west then utterly defeated Sauron's attack against Minas Tirith, relieving the city and killing virtually all of the invaders. Gandalf's carefully laid plans and words of wisdom, along with acts of heroism not seen since the elder days, had defeated Sauron's first move.</p>
<h4>The Last Battle</h4>
<p>But the attack against Minas Tirith was only a part of Sauron's plan to devastate the west and make himself the ruler of Middle-earth. Other armies moved in the north against Erebor and the Kingdom of Thranduil, as well as against Lothlórien and other points along the Anduin. Still commanding vast armies of orcs and men, the Dark Lord soon would move against Gondor again; the remnants of the Edain and their allies had little hope against his almost limitless resources.</p>
<p>In Minas Tirith, Gandalf was selected by Aragorn, Imrahil, and Éomer (the remaining lords of the west) to be their leader in the coming final battles. This would be the culmination of Gandalf's efforts in Middle-earth. Fully aware that the west would stand or fall on the outcome of Frodo's mission, he advised the lords to drive north to the Morannon, thereby drawing Sauron's eye away from Frodo's likely location. This plan surely would result in a catastrophic loss for the outnumbered army, but it gave Frodo a chance to achieve the quest of Mount Doom.</p>
<p>Led by Gandalf and Aragorn, the army of the West crossed the Anduin and marched north, pausing occasionally to announce their coming and to dispatch small numbers of men to lesser tasks. Upon arriving at the Black Gate, the forces halted and prepared for battle. As they ordered their companies, the foul Mouth of Sauron rode forth to parley with them; he revealed Frodo's mithril-coat and Arnor-blade and implied that their owner was captured and tortured. The emissary of Sauron then proposed that the forces of the west surrender; Gandalf however was undaunted, and, seizing his friend's belongings, rejected Sauron's offer. In shock, the Mouth of Sauron turned back towards the Black Gate, which slowly opened to reveal a vast army of orcs and trolls advancing on the lords of the west. Sauron's trap was sprung.</p>
<p>Yet Sauron himself became the victim of Gandalf's trap. Unbeknownst to all, Frodo and Sam had succeeded in scaling Mount Doom and even as the Battle of Morannon began Frodo stood at the Crack of Doom. But the power and lure of the ring finally overcame his will and he placed the ring upon his finger, claiming it as his own. Immediately the Nazgûl were summoned by their lord, as he in terror realized his blunder: his enemies intended to destroy his ring.</p>
<p>But Gandalf's foresight proved accurate again as the creature Gollum, who had been doggedly following the Ring-bearer, seized the ring from Frodo, and, while celebrating his reunion with 'his precious,' unwittingly fell into the fires of Orodruin. The ring was unmade as the fiery mountain erupted. The tower of Barad-dûr and the Towers of the Teeth began to collapse, their foundations crumbling, the Ring-wraiths burned out like shooting stars, and Sauron was reduced to a mere shadow of malice, never to torment the world again.</p>
<p>With Sauron gone, his forces scattered like frightened insects; the Men of the West now set upon them with fury. Gandalf announced the success of the Ring-bearer and the end of Sauron; the quest had been fulfilled. Seeing that victory was achieved, Gandalf then mounted on Gwaihir the Eagle for a third time, and set out to see if Frodo and Samwise had survived the tumults of Mount Doom. To his great relief, the two were found on the slopes of Orodruin, clinging to life amid the volcanic eruptions. The great quest was over.</p>
<h4>End of the Order</h4>
<p>In Minas Tirith, Gandalf and the remaining members of the Fellowship reunited. At the coronation of King Elessar, Gandalf (at Aragorn’s request) set the crown upon the King’s head, and declared &ldquo;Now come the days of the King, and may they be blessed while the thrones of the Valar endure!&rdquo;. Thus Gandalf ushered in the new age of men.</p>
<p>After the coronation and wedding of Aragorn to Arwen, Gandalf left with the rest of the remaining Fellowship on the journey home. For Gandalf, it was his last long journey in Middle-earth. His errand to Arda had been fulfilled; Sauron had been defeated. He said farewell to his friends one by one until at last only the four Hobbits remained at his side. At the borders of the Shire he, too, turned away. He left the Hobbits to settle with the Shire, for the shattered pieces of evil still remaining in the world were no longer his concern, and went to talk to Tom Bombadil.</p>
<p>What Gandalf did during the next two years is unknown; it is possible that his 'long talk' with Bombadil was just that. At any rate, on 29 September 3021, he met Frodo at Mithlond, ready to take the White Ship over the sea to Aman. He wore Narya openly on his finger, and Shadowfax was beside him (perhaps even to take ship with him). His mission was over, and his homecoming after more than 2000 years was nigh. He bade farewell to Samwise, Merry, and Pippin (the latter two of which he had forewarned of the passage), then mounted the Grey Ship beside Frodo, Bilbo, Elrond, and Galadriel. The ship passed west upon the sea, and then took the hidden straight path to Valinor: Gandalf became Olórin once more. There, presumably, he dwells still in the gardens of Irmo. Olórin, the wisest of the Maiar and the sole Istar to remain true to his mission, had successfully kindled the hearts of the free people in Middle-earth to overcome the evil of their time. In a large way, it was his victory.</p>
<h4>Personality</h4>
<p>Gandalf is often described in The Lord of the Rings as quick to anger, and equally quick to laugh.[28] His deep wisdom clearly derived from the patience he learned in Valinor, just as his care for all creatures of good will must have come from his strong sense of pity for the weak. Both his patience and sense of pity were revealed again and again, extending even to the servants of his enemies.</p>
<p>Keen observers of Gandalf often detected a veiled power, usually revealed in his eyes, which appeared deep and wise. He was alternately affectionate and brusque; he often surprised others with his bluntness when time was of the essence. Gandalf consistently upbraided foolish behavior, but also richly rewarded those who acted with good intentions.</p>
<p>Hobbits appealed to him more than to the other Wizards, and he went often to the Shire for respites from his errands. It may be that he was amused by their nature. It may also be because they were untouched by the great evils of the world, and were more in touch with nature than Men; perhaps their agrarian lifestyle appealed to Gandalf's innate spirit and reminded him of the gardens of Valinor.</p>
<h4>Appearance</h4>
<p>The first description of Gandalf is preserved in the initial pages of The Hobbit, written in the early 1930s. Gandalf's fame is alluded to even before his physical description ('Tales and adventures sprouted up all over the place wherever he went, in the most extraordinary fashion'), while the protagonist's ('unsuspecting Bilbo') impression is that of:</p>
<blockquote>
...an old man with a staff. He had a tall pointed blue hat, a long grey cloak, a silver scarf over which a white beard hung down below his waist, and immense black boots.
<br>—J.R.R. Tolkien
</blockquote>
<p>Later, Tolkien wrote:</p>
<blockquote>
...a figure strongly built and with broad shoulder, though shorter than the average of men and now stooped with age, leaning on a thick rough-cut staff as he trudged along... Gandalf's hat was wide-brimmed [...] with a pointed conical crown, and it was blue; he wore a long grey cloak, but this would not reach much below his knees. It was of an elven silver-grey hue, though tarnished by wear - as is evident from the general use of grey in the book... But his colours were always white, silver-grey, and blue - except for the boots he wore when walking in the wild...Gandalf even bent must have been at least 5 ft. 6... Which would make him a short man even in modern England, especially with the reduction of a bent back.
<br>—J.R.R. Tolkien
</blockquote>
<p>Although some of the Wise know his true nature, his 'wizard-like' appearance causes many to mistake him for a simple conjurer. After his return his 'signature colour' changes from grey to white, for he has been sent back to replace the corrupt Saruman as the chief of the Wizards. In the book he claims that in some ways he now 'was Saruman', or rather Saruman as he should have been.</p>
<p>Círdan the Shipwright seemed to have foreseen this, for he entrusted the care of Narya, one of the Three Rings of the Elves to Gandalf rather than Saruman.</p>
<h4>Powers and Abilities</h4>
<p>Gandalf demonstrated extensive knowledge of the land and an assortment of magical abilities from trivial to essential. For example he would use his powers for entertainment, by blowing glowing smoke rings that moved around a room at his direction, and Bilbo Baggins remembered him for his fantastic fireworks displays. He created blinding flashes and other pyrotechnics to distract the goblins of the Misty Mountains, aiding the dwarves in their escape from Goblin-town. On the eastern slopes, he turned pine cones into flaming projectiles that threw hot sparks and started fires that would not easily go out. He was also able to come and go from the presence of Thorin and Company without being noticed.</p>
<p>He again displayed his proficiency with pyrotechnics at Bilbo's Farewell Party. When the Fellowship is attacked by Wargs in Hollin Gandalf speaks words of power to inflame the trees on the hillock where the company had camped. He was also able to start fires under blizzard conditions, create light of varying intensity for the journey through Moria, magically secure doors, and break the Bridge of Khazad-dûm. When angered or aroused for battle, he seemed to grow in height and assume a terrifying aspect. He fought the Balrog of Moria and killed his opponent, although he did not himself survive the battle.</p>
<p>Sent back to Middle-earth as Gandalf the White, he possessed greater charisma and a limited degree of clairvoyance, although he was unable to peer into the land of Mordor to see the progress of Frodo and Sam. His power and authority had increased so that he could break Saruman's staff with a spoken command, showing his authority to throw the treacherous wizard out of the order.</p>
<p>Gandalf was the bearer of Narya, the Ring of Fire, and described himself as the 'servant of the Secret Fire' and 'wielder of the flame of Anor'. Most times Gandalf displayed his power, this had to do with fire. It is not known whether his possession of Narya had any merit to his abilities.</p>
<h4>Special Equipment</h4>
<p>It is unknown whether Gandalf required his staff to exercise certain powers. At times it appeared to focus or extend his powers, such as when it emanated light. Exactly how much it aided him in the use of magic is unknown, but Gríma Wormtongue tried to forbid Gandalf from bringing it into Edoras, clearly under the impression that without it Gandalf's power would be limited.</p>
<p>When he arrived in Middle-earth, Gandalf received the Elven ring Narya from Círdan. It is clear that Gandalf wore this ring from that time to the end of the Third Age but how he used its powers is not known.</p>
<p>In T.A. 2941, Gandalf acquired the Elven sword Glamdring from the treasure hoard of a band of trolls. He continued to wield this weapon throughout The Lord of the Rings, in particular during his fight with the Balrog in Moria.</p>
<p>Throughout his time in Middle-earth Gandalf often was seen with a pipe, the use of which clearly brought him immense enjoyment.</p>
<h4>Other Versions of the Legendarium</h4>
<p>In early manuscripts of The Hobbit, the name Bladorthin was used by Tolkien for the character who later would be named Gandalf. The name Gandalf was instead used for the character known as Thorin in the published works.</p>
<h4>Names</h4>
<p><b>Olórin</b>, his original name in Valinor. It is Quenya, and its meaning is associated with the Quenya word olos or olor, meaning 'dream' or 'vision / of mind'. In a draft manuscript of The Lord of the Rings, occurs the spelling Olórion.</p>
<p><b>Mithrandir</b>, ([miˈθrandir]), his Sindarin name, used in Gondor and meaning 'Grey Pilgrim' or 'Grey Wanderer' (mith 'grey' + randir 'pilgrim, wandering man').</p>
<p><b>Incánus</b>, his name 'in the south' (probably meaning no further south than Gondor or the Near Harad[1]), gained during his long travels in Middle-earth in the mid-Third Age.</p>
<p><b>Tharkûn</b>, the name given to Gandalf by the Dwarves.[6] Tharkûn is Khuzdul, meaning either 'Grey-man' or 'Staff-man'. The word possibly derives from the unattested word thark 'staff' + a nominal ending -ûn.[7] In a draft manuscript of The Lord of the Rings, occurs the spelling Sharkûn.</p>
<p><b>The White Rider</b>, his name while riding the great horse Shadowfax.</p>
<p><b>Greyhame</b> or <b>Gandalf Greyhame</b> was one of Gandalf's many titles and surnames, used particularly in the country of Rohan.</p>
<p><b>Stormcrow</b> was a name given to Gandalf by King Théoden in Rohan, a reference to his arrival being associated with times of trouble.</p>
<p><b>Láthspell</b> was a name given to Gandalf by Gríma Wormtongue when the former arrived at Meduseld.</p>
<blockquote>
Láthspell I name you, Ill-news; and ill news is an ill guest they say.
<br>—Gríma Wormtongue
</blockquote>
<h4>Etymology</h4>
<p>Within the legendarium, Gandalf translates an unknown name of the meaning 'Elf-of-the-wand (or cane/staff)', or more literary 'Wand-elf', in old northern Mannish. Most denizens of Middle-earth incorrectly assumed Gandalf was a Man, although he was really a Maia spirit (approximately equivalent to an angel). However, a less common misconception that occurred during the beginning of his career in Middle-earth was that for someone to be immortal and use as much magic as he did, he must have been an Elf. Although it soon became apparent to all that he could not be an Elf, as he was old and Elves do not generally age, the nickname stuck with him. He later gave it as his name to others he met who did not know its original meaning.</p>";

            BioSourceUrl = "http://tolkiengateway.net/wiki/Gandalf";
            ImageArtist = Artist.Magali_Villeneuve;

            TheFellowshipOfTheRing();
            TheTwoTowers();
            TheReturnOfTheKing();

            Alias("Greyhame");
            Alias("Tharkûn");
            Alias("The Grey Pilgrim");
            Alias("Stormcrow");
            Alias("Gandalf the Grey");
            Alias("The White Rider");
            Alias("Olórin");
            Alias("Gandalf the White");
            Alias("Láthspell");
            Alias("Incánus");
            Alias("Mithrandir", "Mithrandir's-Advice-TSF");

            LotRCard("Gandalf-Core");
            LotRCard("Gandalf-THOHaUH");
            LotRCard("Gandalf-RD");
            LotRCard("Gandalf-1-TPLES");
            LotRCard("Gandalf-2-TPLES");
            
            addFriend("Aragorn", "Aragorn");
            addFriend("Bilbo Baggins", "Bilbo-Baggins");
            addFriend("Radagast", "Radagast");
            addFriend("Galadriel", "Galadriel");

            addItemThing("Glamdring");
            addItem("Narya", "Narya-TGH");
            addItem("Shadowfax", "Shadowfax-ToS");

            addGroup("The White Council", "The-White-Council");
            addGroup("Thorin's Company", "Thorin's-Company");
            addGroup("The Council of Elrond", "The-Council-of-Elrond");
            addGroup("The Fellowship", "The-Fellowship");
        }
    }
}