using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Models.Characters
{
    public class SarumanCharacter : Character
    {
        public SarumanCharacter()
            : base("Saruman", "Saruman the White", "Istari")
        {
            Bio =
@"<blockquote>
&ldquo;[Saruman] is great among the Wise. He is the chief of my order and the head of the Council. His knowledge is deep, but his pride has grown with it, and he takes ill any meddling. The lore of the Elven-rings, great and small, is his province. He has long studied it, seeking the lost secrets of their making (....)&rdquo;
<br>― Gandalf, The Shadow of the Past
</blockquote>
<p>Saruman the White (Third Age c. 1000 – 3019, existed in Middle-earth for 2019 years) was the first of the order of Wizards (or Istari) who came to Middle-earth as Emissaries of the Valar in the Third Age. He was the leader of the White Council. In Sindarin his name was Curunír, which meant 'Man of Skill'.</p>
<h4>Origins</h4>
<p>The Ainur existed before Arda was created. Maiar were angelic creatures of lower order than the Valar. Curumo and Mairon were powerful Maiar of Aulë, until the latter fell and became Sauron.</p>
In Valinor, a council was called by Manwë. This was likely in the middle of the Second Age, shortly after the creation of the Rings of Power. It was decided to send five emissaries to Middle-earth. These should be 'mighty, peers of Sauron, yet forgo might, and clothe themselves in flesh' — Istari, or Wizards. One of those who went was Curumo (later in Sindarin Curunír, or in Westron Saruman).</p>
<p>Saruman was one of those who volunteered, whereas the last one, Olórin, (later Gandalf) was commanded by Manwë to go. Saruman's jealousy of Gandalf began even here, when Varda said of Gandalf, who went as the third Istar that he was 'not the third'. Saruman was charged to take Aiwendil with him to please Yavanna, which he did not wish to do, and this led to contempt for the latter Wizard.</p>
<h4>Arrival in Middle-earth</h4>
<p>Saruman arrived alone in a ship at Mithlond (the Grey Havens) in Lindon around the year 1000 of the Third Age, and only Círdan knew his identity and his origin.</p>
<p>He went into the East of Middle-earth, as did the two Blue Wizards. After one and a half millennia he returned to the West, just as Sauron's power was growing again in Dol Guldur.</p>
<p>When the White Council was formed around T.A. 2463[4], Saruman was appointed its leader. Even then, he had begun to sense the resurgence of Sauron and to envy and desire his power, and especially his One Ring. Coincidentally, in that same year the One Ring was found by the creature Gollum[4], drawing the Dark Lord closer to the conflict that would eventually prove Saruman's undoing.</p>
<h4>Chief of the White Council</h4>
<p>When Saruman returned from his travels into the east of Middle-earth, he spent years in Minas Tirith examining its archives. It is possible that there he surmised that a palantír would still be located in Orthanc. He offered to make Isengard his home and to command the defences of the West. This was welcomed by King Fréaláf of Rohan and Steward Beren of Gondor alike. In T.A. 2759, Saruman was given the Key of Orthanc in the ring of Isengard his abode, hoping that he would prove an important ally. There he became important in the defence of the free lands of the West. In Orthanc he came upon the Orthanc-stone, one of the seven seeing stones, but kept it secret and hidden, particularly from the White Council. He would later betray the Council by concealing his use of it.</p>
<p>In T.A. 2851, the White Council met and Gandalf revealed that the evil presence in Dol Guldur was indeed Sauron and that he had returned, and urged an attack there. Saruman however believed that Sauron would be useful in his quest: allowing Sauron to build up his strength, the One Ring would reveal itself, and Saruman hoped to have sufficient strength to seize it first himself until that event. With this strategy in mind, Saruman overruled Gandalf. It soon became clear that Saruman desired to possess the One Ring himself.</p>
<p>He soon found that Sauron had more knowledge of the possible location of the One Ring than he expected, and in T.A. 2941 he finally consented to an Attack on Dol Guldur against Sauron at which point Sauron retreated to Mordor.</p>
<p>In T.A. 2953, the Wise gathered once more to debate about the Rings of Power. Saruman quieted the Council claiming to have the knowledge that the One Ring was lost forever in the Belegaer. Following their final meeting, Saruman took Isengard for his own and fortified it. Saruman, jealous and afraid of Gandalf, set spies to watch all his movements; thus he discovered the existence of the Shire and noted Gandalf's interest in it, and started sending agents in Bree and the Southfarthing. As Lord of Isengard, Saruman began to bring trouble to Rohan by aiding its enemies.[7] Saruman's corruption was complete when, in circa T.A. 3000, he used the palantír of Orthanc and was enticed by Sauron.</p>
<p>Saruman did not reveal his true intentions until Gandalf presented him with the discovery and location of the One Ring. On 10 July, T.A. 3018, Gandalf arrived at Isengard.[9] Saruman demanded that Gandalf submit to him and Sauron or fail. Saruman then stood forth as Saruman of Many Colours, and when Gandalf refused to join with him, he held him captive in Isengard.</p>
<p>It must have been during Gandalf's captivity in Orthanc that Saruman began to build his army of Orcs, Dunlendings, and Uruk-hai, since Gandalf came to an as yet undestroyed Isengard. From the pinnacle of the tower Gandalf could see that Saruman was gathering an army of orcs and wolves in his pits and forges.[10] One can speculate that if matters had developed a little more slowly, his puppet Gríma would have gained full control over Rohan, and the Rohirrim would have been enslaved or destroyed.</p>
<p>Saruman's plans likely failed because he, like Sauron, was forced to reveal his hand early by Gandalf's subsequent escape, and therefore he had little time to perfect his plans. As Saruman considered himself 'unfallen', he honestly believed he had a chance of converting Gandalf to his side, and felt honestly betrayed by Gandalf when he was refused.</p>
<p>Gandalf later escaped, and so Saruman's treachery became known to the rest of the White Council when Gandalf reported it during the subsequent Council of Elrond.</p>
<p>Saruman soon also betrayed his new master Sauron by lying to the Witch-king when he arrived at Isengard. Sauron had sent the Nazgûl searching for Baggins, who had found the One Ring years before, and the Shire, his home. Saruman pretended to know nothing about the Shire. But the Lord of Morgul and his company did not have the strength to assault the Ring of Isengard. Saruman told them that he believed Gandalf knew the whereabouts of the Ring and the Riders departed.</p>
<p>In September of T.A. 3018 the Nazgûl captured one of his Shire spies who told the Witch-king everything, betraying Saruman, and exposing Saruman's double treachery. They also seized some maps and information about the Shire and Baggins.[11] Caught now between both sides as a known traitor to both, Saruman put all efforts into obtaining the One Ring for himself.</p>
<p>The failure to capture the Ring at Emyn Muil further ruined Saruman's plans, as he was revealed as a traitor to Mordor now as well.</p>
<p>Saruman implemented a strategy of attacking Rohan, endeavouring to kill the King's son Théodred, sending spies to waylay Frodo Baggins on his flight from the Shire, and dispatching raiding parties on likely routes a company of the Ring might take to Gondor. Ironically, one of these parties captured Peregrin Took and Meriadoc Brandybuck and transported them to Fangorn Forest in time to mobilize the Ents. Gandalf also suspected Saruman had found (and destroyed) the remains of Isildur, who had worn the Ring before it had been lost.</p>
<p>Saruman's Shire network failed to capture Frodo Baggins, Gandalf rallied Rohan to victory, Éomer stopped his only partially successful raiding party, and control of Isengard was lost to the Ents. Aware he was utterly defeated, Saruman briefly considered repenting for his deeds, but at the last moment could not go through with it. Whether he had hope he could escape, whether he was too proud to surrender to Gandalf, or whether he simply feared Sauron's retribution for his treachery, Saruman refused to leave the confines of his fortress. Saruman made a final attempt to woo Théoden and Gandalf to his cause but failed: his staff was broken and he was dismissed from the order of the Istari.</p>
<p>Left out of the final stages of the War of the Ring, he eventually managed to convince his captors, the Ents, into letting him leave Isengard, as apparently the magic of his voice still remained.</p>
<p>On their way, they were confronted by Gandalf, Celeborn, Galadriel and the Hobbits on their way to northern Dunland. They found them as traveling beggars and Saruman kicked Gríma to move on, as he exclaimed how he hated his master. Gandalf told Gríma that he was free to leave him but he did not reply. As Saruman was considered powerless, there was little concern for his escape.[13] He then went to the Shire, which his agent Lotho Sackville-Baggins (undisturbed by events elsewhere) had brought under control. He established himself in Hobbiton and spent his final days as a small-time thug lord whom his ruffians called Sharkey. But even this operation fell apart after Frodo and Samwise Gamgee returned; he was eventually betrayed and killed by his own servant Gríma on 3 November, T.A. 3019.</p>
<p>Saruman, who was a Maia, had lost his shape with his 'death'. As a discorporated spirit, he should have been called to Mandos, but a wind came from the West and pushed it away. Apparently his spirit was left naked, powerless and wandering in Middle-earth; perhaps not unlike Sauron after the One Ring was destroyed.</p>
<h4>Characteristics</h4>
<p>In appearance, Saruman was as an old man with black hair. At the end of the Third Age, his hair and beard had turned mostly white — he had only black hairs about his lips and ears. He was tall, his face was long, and his eyes were deep and dark. He would appear in a white cloak, a habit he later changed into a cloak that changed colours as he moved.</p>
<p>He was not actually a Man, or even an Elf (as Men often suspected), but a Maia clothed in flesh — an Istar ((see Origins below). As such, he was immortal and extremely powerful, yet had limits on how far these powers could be used. His two most salient powers were his knowledge and his voice.</p>
<h4>Powers</h4>
<p>Knowledge of the 'deep arts' (or magic, such as it is in Middle-earth) was of particular interest to Saruman, especially when relating to power—such as the Rings of Power and the far seeing palantíri. He was also deeply learned in ancient lore regarding powerful kingdoms such as Númenor, Gondor, and Moria.</p>
<p>His voice and speech were extremely convincing, more powerful than mere rhetoric. When he focused this power on a person or a group of people, he could sway their hearts, plant fears and sow lies as he pleased. According to the stature of the listener, this spell could last as long as the speech did, or it could take root in them and last forever. Saruman's voice was so powerful that he was able to convince the Witch-king that he knew nothing of the One-Ring or the Shire. His voice was not hypnotic, however, rather it was persuasive; and the real danger the voice posed to the listener was not them falling into a trance, but agreeing with it.</p>
<p>Aside from his voice, Saruman has other subtle abilities such as giving great speed and motivation to his orcs at a distance and setting his will against all those in his dominion that might oppose him. Aragorn takes note of this ability while tracking the party of orcs holding Merry and Pippin hostage. Saruman also seems to be able to move around totally unheard by others, as there are numerous examples of him using this ability. Several examples include his sneaking up on Aragorn, Gimli and Legolas's camp in The Riders of Rohan, his wholly unheard entrance in The Voice of Saruman and his quiet but sudden appearance to the hobbits in The Scouring of the Shire.</p>
<p>Other powers include knowledge of machinery and chemistry, probably separable from explicit magic (for instance, the 'blasting fire' employed by his Uruk-hai army in the battle of Helm's Deep, was probably some kind of explosive). Machinery and engines characterized both his fortified Isengard and his altered Shire. In this, he probably sought to emulate Sauron. His science also extended to biological areas. He is believed to have crossbred Men and Orcs, creating a new race of Orcs unafraid of daylight. His mannish spies in Bree were said to have Orc blood. He also employed birds in his service, although this might also be attributed to Radagast the Brown, ordering them to report to Orthanc, Saruman's stronghold.</p>
<p>Being regarded as more powerful than Gandalf (at least before Gandalf's 'rebirth'), it's fair to assume he would also wield explicit magic similar to Gandalf, such as artificial light, locking spells, creating fire, etc.</p>
<p>Saruman, in his desire to imitate Sauron, attemped to forge for himself a Ring of Power. This he wore during the War of the Ring which he revealed when he called himself 'Saruman the Ring-maker'. He had great knowledge and lore of the magic rings created by Sauron and by the Elven-smiths, though at this time the full art of ring-making was lost and known only to Sauron and so Saruman's knowledge of the craft was incomplete. It is assumed that Saruman's Ring was the equivalent of one of the lesser rings in power and the any details of this power is not mentioned. It is also assumed that it too lost its power, if it had any, when the One Ring was destroyed, since Saruman's craft of ring-making was still based on Sauron's. When Gandalf was given Narya, the Ring of Fire, Saruman learned of the gift and resented it. This may be another reason why Saruman desired to have a ring of his own.</p>
<h4>Personality</h4>
<p>Saruman resembled Gandalf not only in appearance, but originally also somewhat in character, but unlike Gandalf, Saruman was proud. He saw himself as the most powerful of the Istari, expressing clear contempt for Radagast the Brown. Saruman was no fool (though he saw Radagast as one); he realized Gandalf's power, and eventually came to see him as an equal, and later as a superior, much to his distress. He became jealous of Gandalf, eventually convincing himself that Gandalf was scheming against him, which justified his own scheming against Gandalf and the rest of the White Council.</p>
<p>Saruman likely was true to his mission in the beginning, and actually believed in working to stop Sauron, but his pride and later arrogance (as well as his jealousy towards Gandalf) turned him into a traitor to the cause he had once served. Saruman's betrayal was not sudden, but slowly grew over time, until at last he had convinced himself that he could not have taken any other path, and that it was too late now to repent. This false belief kept him from taking his last chance at redemption, and because he must have realized this he only became more bitter, blaming Gandalf more than anyone else for his own downfall.</p>
<h4>Etymology</h4>
<p>Saruman is a Mannish translation of Quenya Curumo, his original name in Valinor as a Maia; and Sindarin Curunír which is supposedly the same name (with the ending -ndîr 'man'). All names mean 'Skilled Man' or 'Cunning One' (root curu 'skill').</p>
<p>Saruman is derived from Old English: the root word searu means 'device, design, contrivance, art' and the whole name means 'man of skill'.</p>
<p>His name in Sindarin was Curunír 'Lân.</p>";
            BioSourceUrl = "http://tolkiengateway.net/wiki/Saruman";
            ImageArtist = Artist.Matt_Stewart;

            Alias("Curumo");
            Alias("Curunír");
            Alias("Ring-maker");
            Alias("Of many colours");
            Alias("Sharkey");

            addFriend("Gandalf", "Gandalf");
            addFriend("Radagast", "Radagast");
            addFriend("Gríma", "Grima");
            addFriend("Théoden", "Theoden");

            addItem("Saruman's Staff", "Saruman's-Staff-ToS");
            addItem("Saruman's Voice", "Saruman's-Voice-ToS");

            addGroup("The Istari");

            LotRCard("Saruman-VoI");
            LotRCard("Saruman-ToS");
        }
    }
}