using System;

namespace HallOfBeorn.Models.LotR.Sets.DoomMastered
{
    public class TheBetrayalOfMim
        : CardSet
    {
        private const string setName = "The Betrayal of Mîm";
        private const string cycleName = "Doom Mastered";

        protected override void Initialize()
        {
            Name = setName;
            Abbreviation = "TBoM";
            Number = 9004;
            SetType = Models.SetType.First_Age;
            Cycle = cycleName;

            addEnemy("Orc Scout", EncounterSet.TheBetrayalOfMim, 18, 3, 3, 2, 3)
                .WithTraits("Orc.")
                .WithTextLine("Forced: After Orc Scout engages a player, either add 1 encounter card to a random non-unique location or Orc Scout makes an immediate attack.")
                .WithShadow("Shadow: Either discard 2 cards from your hand or the attacking enemy makes an additional attack after this one.")
                .WithInfo(173, 5, Artist.JB_Casacop); //(2/23)
            addEnemy("Poison Archer", EncounterSet.TheBetrayalOfMim, 38, 2, 4, 1, 4)
                .WithTraits("Orc.")
                .WithKeywords("Archery 1.")
                .WithTextLine("Archery 1.")
                .WithTextLine("Forced: After Poison Archer damages a character, that character cannot ready until the end of the round.")
                .WithFlavorLine("...and in that foray he was struck by a poisoned orc-arrow, and was brought back dying in pain...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(174, 4, Artist.Unknown); //Arkiniano (3/23)
            addEnemy("Angband Spy", EncounterSet.TheBetrayalOfMim, 35, 3, 3, 3, 4)
                .WithTraits("Orc.")
                .WithTextLine("Forced: After an ally is played from hand, either add 1 encounter card to the staging area of a random non-unique location or raise each player's threat by 1.")
                .WithFlavorLine("...and ere long Amon Rûdh was surrounded by spies, lurking unobserved in the wilderness...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(175, 4, Artist.Unknown); //Omer88 (4/23)
            addEnemy("Wolf-sentinel", EncounterSet.TheBetrayalOfMim, 30, Card.VALUE_X, 5, 1, 6)
                .WithTraits("Creature.", "Wold.")
                .WithTextLine("X is equal to the number of characters committed to the quest by the first player.")
                .WithFlavorLine("...the Orcs made their encampment in a bare dale, and set wolf-sentinels all about its rim.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(176, 4, Artist.Unknown); //Fleurdelyse (5/23)
            addEnemy("Angband Warrior", EncounterSet.TheBetrayalOfMim, 28, 2, 4, 3, 5)
                .WithTraits("Orc.")
                .WithTextLine("Forced: After Angband Warrior destroys a character, either add 1 encounter card to the staging area of a random non-unique location or reveal an encounter card.")
                .WithShadow("Shadow: The attacking enemy gets +1 Attack (+2 Attack instead if the quest stage is 2B).")
                .WithInfo(177, 5, Artist.Unknown); //Kikie Ianjur (6/23)
            addLocation("Amon Rûdh", EncounterSet.TheBetrayalOfMim, 5, Card.VALUE_NA)
                .WithUnique()
                .WithSlugSuffix("Discovered")
                .WithTraits("Discovered.", "Dor-Cúarthol.")
                .WithTextLine("Immune to player card effects.")
                .WithTextLine("Forced: At the beginning of the encounter phase, discard the top X cards of the encounter deck. Each player adds an enemy discarded from this effect to the staging area. X is 2 more than the number of players in the game.")
                .WithFlavorLine("...but that steep as were its sides men could reach the summit by climbing a stair cut into the rock...")
                .WithFlavorLine("-The Children of Húrin") //(7/23)
                .WithInfo(178, 1, Artist.Anke_Eissmann);
            addLocation("Amon Rûdh", EncounterSet.TheBetrayalOfMim, 2, Card.VALUE_NA)
                .WithUnique()
                .WithSlugSuffix("Hidden")
                .WithTraits("Hidden.", "Dor-Cúarthol.")
                .WithTextLine("Immune to player card effects.")
                .WithTextLine("While Amon Rûdh is the active location, it gains: \"After a character readies during the refresh phase, heal 1 damage from the character.\"")
                .WithFlavorLine("\"We have seen it, but never nearer...\"")
                .WithFlavorLine("-Androg, The Children of Húrin")
                .WithInfo(178, 1, Artist.Unknown); //(7/23)
            addLocation("Gate of the Garth", EncounterSet.TheBetrayalOfMim, 4, 8)
                .WithTraits("Dor-Cúarthol.")
                .WithTextLine("Forced: After an encounter card is added to the staging area of Gate of the Garth outside of the quest phase, each player raises he threat by 2.")
                .WithTextLine("Response: After Gate of the Garth is explored, reduce each player's threat by 5.")
                .WithFlavorLine("\"Not the door of the house, but the gate of the garth...\"")
                .WithFlavorLine("-Mîm, The Children of Húrin")
                .WithInfo(179, 1, Artist.Unknown); //Mr. Cube (8/23)
            addLocation("Stony Heath", EncounterSet.TheBetrayalOfMim, 5, 6)
                .WithTraits("Dor-Cúarthol.")
                .WithTextLine("While Stony Heath is the active location, enemies get +1 Attack.")
                .WithTextLine("Response: After Stony Heath is explored, add 1 resource to the resource pool of each hero.")
                .WithFlavorLine("They passed over the tumbled stones, and began to climb; for Amon Rûdh stood upon the eastern edge of the high moorlands that rose between the vales of Sirion and Narog...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(180, 1, Artist.Unknown); //(9/23)
            addLocation("Broken Land", EncounterSet.TheBetrayalOfMim, 3, 9)
                .WithTraits("Dor-Cúarthol.")
                .WithTextLine("While Broken Lands is the active location, it gainsd, \"Forced: After any amount of progress is placed on Broken Lands, deal 1 damage to each questing character.\"")
                .WithTextLine("Response: After Broken Land is explored, each player draws 3 cards.")
                .WithFlavorLine("Upon the eastern side a broken land climbed slowly up to the high ridges among knots of birch and rowan, and ancient thorn-tress rooted in rock.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(181, 1, Artist.Unknown); //Concept Cube (10/23)
            addLocation("Holly-thicket", EncounterSet.TheBetrayalOfMim, 3, 10)
                .WithTraits("Dor-Cúarthol.", "Forest.")
                .WithTextLine("While Holly-thicket is the active location, the player attack step of the combat phase happens first.")
                .WithTextLine("Travel: Each player must discard an attachment he controls.")
                .WithFlavorLine("Soon after, it chanced that as the grey light of a day of rain was falling Túrin and his men were sheltering in a holly-thicket...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(182, 1, Artist.Unknown); // (11/23)
            addLocation("Dark Dells", EncounterSet.TheBetrayalOfMim, 4, 7)
                .WithTraits("Dor-Cúarthol.")
                .WithTextLine("While Dark Dells is the active location, each non-objective ally's text box is treated as if it were blank, except for traits.")
                .WithTextLine("Response: After Dark Dells is explored, you may look at the facedown encounter cards in an adjacent location's staging area.")
                .WithInfo(183, 1, Artist.Unknown); //Sinate (12/23)
            addTreachery("Secret Stair", EncounterSet.TheBetrayalOfMim)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("When Revealed: Attach to an enemy in play. (Counts as a Condition attachment with the text: \"Limit 1 per enemy. Each enemy in play gains relentless.\")")
                .WithShadow("Shadow: If this attack destroys a character, add 1 encounter card to the staging area of a random non-unique location.")
                .WithInfo(184, 3, Artist.Unknown); //Tomasz Alen Kopera (13/23)
            addTreachery("Rains Out of Season", EncounterSet.TheBetrayalOfMim)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: Each non-objective character gets -1 Willpower, -1 Attack, -1 Defense until the end of the round. You may cancel this effect on a character if you immediately deal 1 damage to that character.")
                .WithShadow("Shadow: The defending character gets -2 Defense.")
                .WithInfo(185, 2, Artist.Unknown); //(14/23)
            addLocation("Steep Slopes", EncounterSet.TheBetrayalOfMim, 3, 8)
                .WithTraits("Dor-Cúarthol.")
                .WithTextLine("While Steep Slopes is the active location, it gains: \"Forced: When a character or an enemy takes damage, discard the top card of the encounter deck. If it is a treachery, double the damage dealt.\"")
                .WithFlavorLine("...the land ran down into wastes of great stones with falls and holes masked by bramble and thorn.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(186, 1, Artist.Unknown); //JB Concept (15/23)
            addTreachery("More Hunted Than Hunters", EncounterSet.TheBetrayalOfMim)
                .WithTextLine("When Revealed: End the quest phase without resolving the quest. Treat the engagement cost of all enemies as 0 until the end of the round. If it is stage 2B, search the encounter deck and discard pile for an enemy and add it to the staging area.")
                .WithShadow("Shadow: Until the end of the phase, reveal an encounter card after this enemy is destroyed.")
                .WithInfo(187, 2, Artist.Unknown); //Vablo (16/23)
            addTreachery("Ill-content", EncounterSet.TheBetrayalOfMim)
                .WithTextLine("When Revealed: Deal 1 Corruption to each character with at least 1 damage. If no Corruption is dealt by this effect, Ill-content gains surge.")
                .WithShadow("Shadow: If this attack destroys a character, deal X Corruption among heroes the defending player controls (X is equal to the cost of the destroyed character).")
                .WithInfo(188, 3, Artist.Unknown); //Nequarilj (17/23)
            addTreachery("Captive Son", EncounterSet.TheBetrayalOfMim)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("When Revealed: If Mîm's objective side is faceup, add 1 progress token to Mîm if this is the first copy of Captive Son revealed this round. Then, if the number of progress tokens on Mîm is equal to or greater than his Willpower, flip him.")
                .WithFlavorLine("It was the capture of his son and their threat to torture him that led Mîm to his treachery.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(189, 4, Artist.Jordy_Lakiere); //(18/23)
            addTreachery("Sleepless Eyes", EncounterSet.TheBetrayalOfMim)
                .WithTextLine("When Revealed: Each player must choose and exhaust X non-objective characters, where X is the number of Grievance objectives attached to Mîm (if it is stage 2B, treat X as 3 instead). Deal 1 damage to each character exhausted in this way.")
                .WithFlavorLine("And those who were on the watch saw him sitting on through the night silent and still as a stone, save for his sleepless eyes that glinted as they roved in the dark.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(190, 3, Artist.Unknown); //88grzes (19/23)
            addTreachery("Curse of a Dwarf", EncounterSet.TheBetrayalOfMim)
                .WithTraits("Curse.")
                .WithTextLine("When Revealed: Attach to the hero with the highest printed Attack. (Counts as a Condition attachment with the text: \"Limit 1 per hero. Forced: After the attached hero destroys an enemy, deal damage to the attached hero equal to that hero's printed Attack. Then, discard Curse of a Dwarf.\")")
                .WithInfo(191, 2, Artist.Unknown); //Peet (20/23)
            addObjective("Sack of Roots", EncounterSet.TheBetrayalOfMim)
                .WithTraits("Grievance.")
                .WithTextLine("Action: Attach Sack of Roots to Mîm to choose and discard a Condition attachment from play. Any player may trigger this action.")
                .WithFlavorLine("But he marked, and others also, that Mîm set more store by the sack and his load than it seemed worth to the eye.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(192, 1, Artist.Unknown); //John Stone Art (21/23)
            addObjective("Bound", EncounterSet.TheBetrayalOfMim)
                .WithTraits("Grievance.")
                .WithTextLine("While Bound is attached to Mîm, it gains, \"Ignore the forced effect on the attached character. The attached character cannot ready.\"")
                .WithTextLine("Action: Attach Bound to Mîm and exhaust him, if able. Any player may trigger this action.")
                .WithFlavorLine("Then Mîm opened his eyes and pointed to his bonds; and when he was released he spoke fiercely. 'Learn this, fools!' he said. 'Do not put bonds on a Dwarf! He will not forgive it.'")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(193, 1, Artist.Anke_Eissmann); //(22/23)
            addObjectiveAlly("Khîm", EncounterSet.TheBetrayalOfMim, 0, 0, 1, 3)
                .WithUnique()
                .WithTraits("Grievance.", "Dwarf.")
                .WithTextLine("Immune to player card effects. The first player gains control of Khîm.")
                .WithTextLine("Forced: At the end of the combat phase, raise your threat by 2. You may declare an attack against Khîm with a non-objective character as a response. If that attack deals damage, cancel this effect.")
                .WithTextLine("Forced; After Khîm is destroyed, attach Khîm to Mîm.")
                .WithInfo(194, 1, Artist.Unknown); //Anmazol (23/23)
            addTreachery("Unfading Grief", EncounterSet.TheBetrayalOfMim)
                .WithTraits("Doom.")
                .WithTextLine("When Revealed: Attach to the hero with Curse of Morgoth attached. (Counts as a Condition attachment with the text: \"The cost of the first card you play each round is increased by one.\")")
                .WithFlavorLine("...and that grief was graven on the face of Túrin and never faded.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(195, 1, Artist.Steamey); 
            addAttachment("Chest of Stone and Wood", 0, Sphere.Neutral, false)
                .WithBoon()
                .WithTraits("Item.", "Cache.")
                .WithKeywords("Guarded.")
                .WithTextLine("Guarded.")
                .WithTextLine("Setup: Shuffle Chest of Stone and Wood into the encounter deck.")
                .WithTextLine("Action: Exhaust a hero to claim this attachment when its free of encounters.")
                .WithTextLine("Action: Discard Chest of Stone and Wood to either draw 2 cards or add 2 resources to attached hero's resource pool.")
                .WithInfo(196, 1, Artist.Unknown);
            addEnemy("Mîm", EncounterSet.TheBetrayalOfMim, 45, 3, 2, 1, 6)
                .WithSlugSuffix("Enemy")
                .WithUnique()
                .WithTraits("Dwarf.")
                .WithTextLine("Mîm engages the first player.")
                .WithTextLine("Forced: After Mîm is flipped, remove all damage from Mîm and remove the Grievance objectives from the game. If it is stage 1B, add 1 encounter card to the staging area of each non-unique location, ignoring any damage tokens.")
                .WithTextLine("Forced: When a character you control delcares an attack, deal 1 damage to that character.")
                .WithVictoryPoints(1)
                .WithInfo(197, 1, Artist.Unknown); //(1/23)
            addObjectiveAlly("Mîm", EncounterSet.TheBetrayalOfMim, 3, 2, 1, 5)
                .WithSlugSuffix("Objective-Ally")
                .WithUnique()
                .WithTraits("Dwarf.")
                .WithTextLine("The first player gains control of Mîm.")
                .WithTextLine("Mîm gets -1 Willpower for each attached Grievance objective. If his Willpower is 0, flip Mîm.")
                .WithTextLine("Forced: At the end of the refresh phase, add 1 encounter card to the staging area of a random non-unique location.")
                .WithTextLine("If Mîm is destroyed, flip Mîm.")
                .WithInfo(197, 1, Artist.Unknown); //(1/23)
            addQuest("The Land of Bow and Helm", EncounterSet.TheBetrayalOfMim, 1, 'A', Card.VALUE_NA)
                .WithKeywords("Time 6.")
                .WithFlavorLine("The Gaurwaith have accepted your leadership, and you have led them away from the homes of Men. However, the ways of the outlaws are not easily changed. Even worse, the weather has been merciless and the Orcs have come down from the North in ever-growing numbers. By chance one day, your scouts capture a strange group of Petty-dwarves, led by one called Mîm. He is indignant at first and protests his captivity, but eventually offers to show you a place of rest and refuge as ransom.")
                .WithTextLine("When Revealed: Set up the Dor-Cúarthol area (see rules). The first player takes control of Mîm, as an ally. Place the 3 Grievance objectives in the staging area. (They are considered to be in every location's staging area.")
                .WithOppositeFlavorLine("You have made the House of Ransom a heart of resistance against the forces of Morgoth. But danger lurks, as the Enemy's servants seeks to find this secret haven, and it is only a matter of time before it is discovered. Even worse, the loyalty of Mîm is ever uncertain...")
                .WithOppositeTextLine("Time 6.")
                .WithOppositeTextLine("Forced: At the end of the refresh phase, add 1 encounter card to a random non-unique location for each player in the game. A location may not have a number of encounter cards greater than its Threat plus the number of players.")
                .WithOppositeTextLine("When the last time counter is removed, advance to the next stage.")
                .WithInfo(198, 1, Artist.Steamey);
            addQuest("The Wrath of Angband", EncounterSet.TheBetrayalOfMim, 2, 'A', Card.VALUE_NA)
                .WithFlavorLine("By fate or treachery, the Orcs of Morgoth have discovered the location of Bar-en-Danwedh, the House of Random. Now you must fight for your very life against the tide of foes suddenly at your door.")
                .WithTextLine("When Revealed: Flip Amon Rûdh and make it the active location. If Mîm's objective side is faceup, flip him.")
                .WithOppositeTextLine("Skip the staging step of the quest phase. Encounter cards cannot be added to the staging area of non-unique locations. Players cannot travel.")
                .WithOppositeTextLine("Forced: At the beginning of the quest phase, move all cards in a location's staging are one location to the left, if able.")
                .WithOppositeTextLine("If there are no encounter cards in a staging area and non enemies engaged with a player, the players have won the game.")
                .WithInfo(199, 1, Artist.Unknown);
            addScenario(setName, 3, cycleName)
                .WithTextLine("Creating the Dor-Cúarthol Area")
                .WithTextLine("To create the Dor-Cúarthol area, place Amon Rûdh (Hidden side faceup) in the staging area. Then, place Gate of Garth immediately to its right. Then, shuffle the remaining locations and place them in a sequence to the right of Gate of Garth. Finally, choose one location to be the active location.")
                .WithTextLine("A resource token is placed on a location to indicate that it is the active location. The active location contributes its threat to the staging area. Each location has its own staging area. Only the encounter cards added to a staging area of the active location are considered to be in the staging area. When you are instructed to add a card to the staging area of a location, place an encounter card facedown underneath it.")
                .WithOppositeTextLine("If a location is the active location when an encounter card is added to its staging area, immediately reveal and resolve that card during staging. During the staging step of the quest phase, any cards revealed are considered to be added to the active location's staging area.")
                .WithOppositeTextLine("You may place progress on the active location as normal through questing. When a number of progress tokens are placed on the active location equal to its quest points, it is considered to be explored. Place a damage token on it. A location with a damage token can no longer have progress added or removed from it.")
                .WithOppositeTextLine("During the travel phase, the players may travel to any location, even if the current active location has not been explored. Similarly, you may remain at a location that has already been explored. Player card effects that discard or switch locations cannot be used. When the players travel to a location, first place any cards in the staging are facedown underneath the old active location. Then, immediately reveal and resolve any facedown encounter cards under the new active location.")
                .WithOppositeTextLine("If a location has a damage token on it, encounter cards cannot be added to its staging area (any encounter cards already in the staging area of a location when it is explored remain in play). Note that this applies to the staging step of questing as well (since treacheries are not added to the staging area, they will still resolve as normal). Since cards cannot be added to such a location's staging area, when adding a card to a random non-unique location, do not add a card to a location with a damage token if it is randomly selected.")
                .WithInfo(200, 1, Artist.Unknown);
            addCampaign(setName, EncounterSet.TheBetrayalOfMim, cycleName)
                 .WithTextLine("You are playing Campaign Mode.")
                 .WithTextLine("Action: Discard a hero you control to discard 2 facedown encounter cards from the staging area of a location. Any player may trigger this action. (Limit once per game.)")
                 .WithFlavorLine("So it was that Mîm came into the Tale of the Children of Húrin. For he stumbled up on his knees before Túrin's feet and begged for his life. 'I am old,' he said, 'and poor. Only a Dwarf, as you say, not an Orc. Mîm is my name. Do not let them slay me, master, for no cause, as Orcs would.'")
                 .WithFlavorLine("-The Children of Húrin")
                 .WithOppositeTextLine("Resolution: If no Grievance objectives were attached to Mîm, the players may either remove one burden from the campaign pool or add Chest of Stone and Wood to the campaign pool. If only one Grievance objective was attached to Mîm you may add Chest of Stone and Wood to the campaign pool. If more than one Grievance objective was attached to Mîm, add Unfading Grief to the campaign pool.")
                 .WithOppositeFlavorLine("When morning came the storm was passed away eastward over Lothlann, and the sun of autumn rose hot and bright; but the Orcs hating this almost as much as thunder, and believing that Túrin would have fled far from that place and all trace of his flight be washed away, they departed in haste, eager to return to Angband. Far off Gwindor saw them marching northward over the steaming sands of Anfauglith. Thus it came to pass that they returned to Morgoth empty-handed, and left behind them the son of Húrin, who sat crazed and unwitting on the slopes of Taur-nu-Fuin, bearing a burden heavier than their bonds.")
                 .WithOppositeFlavorLine("-The Children of Húrin")
                 .WithInfo(201, 1, Artist.Steamey); //Steamey
            addHero("Galadriel", 8, Sphere.Mastery, 3, 1, Card.VALUE_X, 4)
                .WithTraits("Noldor.", "House of Finarfin.", "Noble.")
                .WithTextLine("X is the Threat of the active location.")
                .WithTextLine("Response: After an encounter card is revealed from the encounter deck, deal 3 Corruption to Galadriel to cancel its effects and add it the the victory display.")
                .WithFlavorLine("...for she yearned to see the wide unguarded landed and to rule there a realm at her own will.")
                .WithFlavorLine("-The Silmarillion")
                .WithInfo(202, 1, Artist.Weta_Workshop);
            addAlly("Gaurwaith Watchman", 0, Sphere.Mastery, false, 2, 2, 0, 2)
                .WithTraits("Gaurwaith.")
                .WithKeywords("Ransom 3.")
                .WithTextLine("Ransom 3.")
                .WithTextLine("Quest Action: Deal 1 Corruption to Gaurwaith Watchman to name an encounter card type. Until the end of the phase, when the first card of that type is revealed, shuffle it back into the encounter deck and reveal the next encounter card.")
                .WithInfo(203, 3, Artist.Unknown); //Laura Tolton
            addAlly("Soldier of the Fountain", 4, Sphere.Tactics, false, 0, 3, 2, 3)
                .WithTraits("Noldor.", "House of the Fountain.")
                .WithTextLine("Reduce the cost to play Soldier of the Fountain if you are engaged with an enemy with printed hit points of 5 or more.")
                .WithFlavorLine("There shinning fountains played, and in the courts of Turgon stood images of the Trees of old...")
                .WithFlavorLine("-The Silmarillion")
                .WithInfo(204, 3, Artist.Unknown); //LordHayabusa357
            addAlly("Elf-maiden of Nargothrond", 2, Sphere.Spirit, false, 1, 0, 1, 1)
                .WithTraits("Noldor.")
                .WithTextLine("Action: Discard the top 2 cards of your deck. Then, if any of the discarded cards do not have a Spirit resource icon, Elf-maiden of Nargothrond gets -1 Willpower until the end of the phase. Otherwise, place 1 progress token on a location and Elf-maiden of Nargothrond gets +1 Willpower until the end of the phase. (Limit once per round.)")
                .WithInfo(205, 3, Artist.Unknown); //Icy Maiden
            addAlly("Gwindor", 4, Sphere.Leadership, true, 2, 2, 1, 3)
                .WithTraits("Noldor.")
                .WithTextLine("Response: After an ally you control is destroyed, exhaust Gwindor to add +1 Attack to each character you control until the end of the phase. (Limit once per round.)")
                .WithFlavorLine("Now his wrath was kindled to madness, and he leapt forth on horseback, and many riders with him...")
                .WithFlavorLine("-The Silmarillion")
                .WithInfo(206, 3, Artist.Unknown); //Peet
            addAlly("Ulfang the Black", 2, Sphere.Mastery, true, 1, 3, 3, 3)
                .WithTraits("Easterling.")
                .WithTextLine("Forced: At the end of the round, discard the top card of your deck. Then, if the top card of your discard pile is an ally, deal 1 Corruption to Ulfang the Black.")
                .WithFlavorLine("In this hour the plots of Ulfang were revealed.")
                .WithFlavorLine("-The Silmarillion")
                .WithInfo(207, 3, Artist.Unknown); //Frank Frazetta
            addAttachment("Fëanorian Lamp", 2, Sphere.Neutral, true)
                .WithTraits("Item.")
                .WithTextLine("Attach to a Noldor hero.")
                .WithTextLine("Action: Exhaust Fëanorian Lamp to choose a non-unique location. That location gets -2 Threat until the end of the round. (Discard Fëanorian Lamp to also treat the location's text box as blank until the end of the round.)")
                .WithFlavorLine("...for they were made of old in Valinor, and neither wind nor water could quench them...")
                .WithFlavorLine("-Unfinished Tales")
                .WithInfo(208, 3, Artist.Unknown);
            addAttachment("Gorthol", 1, Sphere.Mastery, true)
                .WithTraits("Name.")
                .WithTextLine("Attach to Túrin Turambar. Limit 1 Name in play.")
                .WithTextLine("Túrin Turambar gains a Leadership resource icon.")
                .WithTextLine("Action: Raise your threat by 2 to ready an ally. (Limit once per round.)")
                .WithInfo(209, 3, Artist.Unknown); //Snake9008
            addAttachment("Smoking Axe", 1, Sphere.Tactics, false)
                .WithTraits("Item.", "Weapon.")
                .WithKeywords("Restricted.")
                .WithTextLine("Restricted. May be played without a resource match for 1 additional resource.")
                .WithTextLine("Attach to an enemy in play.")
                .WithTextLine("Attached hero gets +1 Attack.")
                .WithTextLine("Response: After the attached enemy is destroyed, attach it to a hero that participated in the attack and ready that hero.")
                .WithInfo(210, 3, Artist.Unknown);
            addEvent("Trained to Wariness", 0, Sphere.Lore)
                .WithTextLine("Quest Action: Exhaust a character with the Ranger trait. Then, until the end of the phase, after the first enemy is revealed from the encounter deck, lower your threat by X, where X is the Threat of the revealed enemy.")
                .WithFlavorLine("But Túrin, trained in the wild to wariness, saw him from the corner of his eye...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(211, 3, Artist.Unknown); //AlMaNeGrA
            addEvent("Hounding to his Death", 0, Sphere.Mastery)
                .WithTextLine("Combat Action: Choose a character you control. That character deals X damage to an enemy engaged with you. X is the character's printed Attack. Then, that chracter becomes corrupted.")
                .WithFlavorLine("..but Túrin came after him like a hound, and however he ran, or swerved, still the sword was behind him to egg him on.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(212, 3, Artist.Ted_Nasmith);
            addEvent("Arts of the Enemy", 1, Sphere.Mastery)
                .WithTextLine("Response: Deal 1 Corruption to a hero to cancel a shadow effect just triggered during combat. Move that shadow card to a character. When that character attacks, apply the shadow effect, applying any text that refers to \"attacking enemy\" to the attacking character and any text that refers to the \"defending character\" to the defending enemy, if able.")
                .WithInfo(213, 3, Artist.Unknown); //Ethalen Skye
        }
    }
}