using System;

namespace HallOfBeorn.Models.LotR.Sets.DoomMastered
{
    public class TheFallOfNargothrondSet
        : CardSet
    {
        private const string setName = "The Fall of Nargothrond";
        private const string cycleName = "Doom Mastered";

        protected override void Initialize()
        {
            Name = setName;
            Abbreviation = "TFoN";
            Number = 9005;
            SetType = Models.SetType.First_Age;
            Cycle = cycleName;

            addScenario(setName, 4, cycleName)
                .WithTextLine("Glaurung Deck")
                .WithTextLine("Take all treacheries with the Glaurung trait and shuffle them together to form the Glaurung deck.")
                .WithTextLine("Additional Setup")
                .WithTextLine("All of the non-unique enemies from the Trial Upon the Marches set are included in the encounter deck for this scenario.")
                .WithTextLine("Raid")
                .WithTextLine("Note: Raid in this scenario works slightly differently than it did in Trial Upon the Marches.")
                .WithTextLine("At the end of the round, if one or more encounter cards in the staging area have the raid keyword, discard the top X cards from the encounter deck. X is equal to the highest threat among these encounter cards. When an enemy with the raid keyword is engaged with a player at the end of the round, that player must discard the top X cards of the encounter deck. X is equal to the enemy's threat strength.")
                .WithTextLine("Relentless")
                .WithTextLine("An enemy with Relentless cannot have its attack canceled or be prevented from attacking by any player card effect. It still can be targeted by other effects that do not specifically prevent attacks.")
                .WithOppositeTextLine("Ransom")
                .WithOppositeTextLine("When a character with the Ransom keyword enters play, the player who controls it may discard a number of resources from the resource pools of heroes they control equal to the Ransom value. If they choose not to satisfy this requirement, then that player card loses the \"ally\" trait and gains the \"enemy\" trait, immediately engaging the player who played it. Its threat is equal to its willpower and its engagement cost is 0. If this enemy is defeated, remove all damage from it and return it to the player's control as an ally.")
                .WithInfo(0, 1, Artist.Unknown);
            addEnemy("Glaurung", EncounterSet.TheFallOfNargothrond, 40, 5, 8, 7, Card.VALUE_NA)
                .WithUnique()
                .WithTraits("Dragon.")
                .WithKeywords("Indestrutible.", "Raid.", "Relentless.")
                .WithTextLine("Indestrutible. Raid. Relentless.")
                .WithTextLine("Forced: After Glaurung attacks, reveal the top card of the Glaurung deck.")
                .WithTextLine("Action: Remove X damage from Glaurung to remove an attached Innocent objective and place it under The Hopes of Nargothrond. X is 5 times the number of players. Any player may trigger this action.")
                .WithInfo(314, 1, Artist.Unknown); //(1/24)
            addQuest("Only In Secrecy Lies Hope", EncounterSet.TheFallOfNargothrond, 1, 'A', Card.VALUE_NA)
                .WithFlavorLine("After surviving Mîm's betrayal, you have made your way to the Elven kingdom of Nargothrond. It is one of the three protected fortresses of the Elves, and Morgoth is seeking ever to find and destroy it. The ruler of Nargothrond, Orodreth, seeks your counsel. Should the Elves of Nargothrond continue to hide and ambush the Enemy only when prudent? Or should they gather arms and boldly assault the Enemy?")
                .WithTextLine("Setup: Create the Glaurung deck (see rules). Set Glaurung, Deep River, Mighty Bridge, The Hopes of Nargothrond, and The Ruin of Nargothrond aise, out of play. Shuffle the 10 Innocent objectives into a separate innocent deck. The first player must choose: either trust to secrecy and advance to stage 1B, or take an aggressive approach and advance to stage 2A.")
                .WithOppositeTextLine("You have advised Orodreth to keep his forces out of sight and only strike when necessary. With this approach, you hope to delay the hour of the Enemy's arrival. Still, his forces gather and the hammer will fall soon on Nargothrond. Hopefully, the natural defenses of the fortress will hold.")
                .WithOppositeTextLine("Skip the quest and combat phase this round.")
                .WithOppositeTextLine("When Revealed: Reduce each player's threat by 10. Add Deep River to the staging area.")
                .WithOppositeTextLine("Forced: At the end of the round, advance to stage 3A.")
                .WithInfo(315, 1, Artist.Elena_Kukanova);
            addQuest("Arms Are The Only Wall", EncounterSet.TheFallOfNargothrond, 2, 'A', Card.VALUE_NA)
                .WithFlavorLine("\"If you do nothing to halt him, all Beleriand will fall under his shadow before many years are passed, and then one by one he will smoke you out of your earths. And what then? A pitiable remnant will fly south and west, to cover on the shores of the Sea, caught between Morgoth and Osse. Better then to win a time of glory, though it be short-lived; for the end will be no worse. You speak of secrecy, and say that therein lies the only hope; but could you ambush and waylay every scout and spy of Morgoth to the last and least, so that none came every back with tidings to Angband, yet from that he would learn that you lived and guess where.")
                .WithFlavorLine("-Túrin Turambar, The Children of Húrin")
                .WithOppositeTextLine("Following your advice, Orodreth has ordered the construction of a large bridge spanning the river Narog. With this in place, the armies of Nargothrond now freely make war against the Orcs of Morgoth, drawing the enemies attention to this one spot in Beleriand...")
                .WithOppositeTextLine("Skip the quest and combat phase this round.")
                .WithOppositeTextLine("When Revealed: Each player may search the top 15 cards of their deck for one Weapon or Armor attachment and one ally. These cards may be immediately played for no cost. Add Mighty Bridge to the staging area.")
                .WithOppositeTextLine("Forced: At the end of the round, advance to stage 3A.")
                .WithInfo(316, 1, Artist.Unknown); //Art of Juhani
            addQuest("The Doors of Felagund", EncounterSet.TheFallOfNargothrond, 3, 'A', Card.VALUE_NA)
                .WithFlavorLine("Five years have passed since you came to Nargothrond. In that time, small victories against the forces of Morgoth have been won. However, as the year turns to autumn, reports of a great host reach your ears.")
                .WithFlavorLine("Morgoth has finally loosed the army he has long prepared. At the head of this army is Glaurung, the Father of Dragons. The warriors of Nargothrond are valiant, but they are vastly outnumbered. The proud Elven host begins to fall back upon the field of Tumhalad. Even worse, Glaurung is a fearsome force of death, beyond terror and beyond comprehension. None can withstand his approach. You must defend the Doors of Felagund to buy time for the innocent to escape.")
                .WithTextLine("When Revealed: The first player adds Glaurung, The Hopes of Nargothrond, and The Ruin of Nargothrond to the staging area. Each other player searches the encounter deck and discard pile for a copy of Great Host and adds it to the staging area.")
                .WithOppositeTextLine("when resolving the raid keyword, divide the enemy's Threat in half (rounding up).")
                .WithOppositeTextLine("Forced: At the end of the round, add 1 damage to this stage (add 2 damage instead if there are more non-unique enemies in play than the number of players). If the number of damage tokens is equal to or greater than 5, advance to stage 4A.")
                .WithOppositeTextLine("Forced: At the end of the round, if there are fewer non-unique enemies in play than the number of players, search the encounter deck and discard pile for 1 enemy and add it to the staging area, if able.")
                .WithInfo(317, 1, Artist.Unknown); //Jonathan Guzi
            addQuest("The Sack of Nargothrond", EncounterSet.TheFallOfNargothrond, 4, 'A', Card.VALUE_NA)
                .WithFlavorLine("The Doors of Felagund have falles, and the host of Morgoth has begun pouring into Nargothrond. As the great halls and chambers are ransacked, you see Orcs herding those maidens and children that have survived into a crowd. They are destined to be slaves enduring unbearable torment in Angband unless you can rescue them from their fate.")
                .WithTextLine("When Revealed: Return Glaurung to the staging area if he is engaged with a player. Glaurung makes an immediate attack against each playe, in turn order (do not deal a shadow card or trigger the forced effect on Glaurung for this attack).")
                .WithOppositeTextLine("Glaurung cannot leave the staging area and is considered to be engaged with each player.")
                .WithOppositeTextLine("Forced: At the end of the round, add 1 damage to this stage (add 2 damage instead if there are more non-unique enemies in the staging area than the number of players). If the number of damage tokens is equal to or greater than 6, the players lose.")
                .WithOppositeTextLine("If the players complete the victory condition on The Hopes of Nargothrond, they win.")
                .WithInfo(318, 1, Artist.Helge_C_Balzer);
            addEnemy("Great Host", EncounterSet.TheFallOfNargothrond, 38, 3, 5, 3, 8)
                .WithTraits("Orc.")
                .WithKeywords("Raid.")
                .WithTextLine("Raid.")
                .WithTextLine("Forced: After Great Host engages a player, exhaust the ready character they control with the highest Defense.")
                .WithShadow("Shadow: The defending player exhausts a character they control.")
                .WithInfo(319, 4, Artist.John_Howe); //(2/24)
            addLocation("Mighty Bridge", EncounterSet.TheFallOfNargothrond, 1, Card.VALUE_NA)
                .WithUnique()
                .WithTraits("Nargothrond.", "River.")
                .WithTextLine("Immune to player card effects. The players cannot travel to Mighty Bridge.")
                .WithTextLine("Forced: After an enemy engages a player, that enemy gets +1 Attack and +1 Defense until the end of the round.")
                .WithFlavorLine("...for it was great and mightily made and could not swiftly be destroyed, and thus the enemy came readily over the deep river...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(320, 1, Artist.Unknown); //Indecipherable (3/24)
            addLocation("Field of Tumhalad", EncounterSet.TheFallOfNargothrond, 3, 4)
                .WithTraits("Nargothrond.")
                .WithTextLine("While Field of Tumhalad is in the staging area, each enemy gets +1 Threat.")
                .WithShadow("Shadow: The attacking enemy gets +X Attack, where X is equal to its Threat.")
                .WithFlavorLine("The Elves were driven back and defeated on the field of Tumhalad; and there all the pride and host of Nargothrond withered away.")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(321, 4, Artist.Unknown); //Indecipherable (4/24)
            addObjective("The Ruin of Nargothrond", EncounterSet.TheFallOfNargothrond)
                .WithTraits("Nargothrond.")
                .WithTextLine("Forced: After one or more cards with an (Innocent) icon are discarded by the raid keyword on an enemy, reveal the top card of the innocent deck and attach it to that enemy as a guarded objective.")
                .WithTextLine("If there are 6 or more Innocent objectives under The Ruin of Nargothrond, the players lose the game.")
                .WithInfo(322, 1, Artist.Unknown); //Indecipherable (5/24)
            addLocation("Deep River", EncounterSet.TheFallOfNargothrond, 1, Card.VALUE_NA)
                .WithTraits("Nargothrond.", "River.")
                .WithTextLine("Immune to player card effects. The players cannot travel to Deep River.")
                .WithTextLine("Forced: When any number of damage tokens would be placed on the quest stage, cancel that damage and remove Deep River from the game instead.")
                .WithFlavorLine("The doors of Nargothrond opened onto the gorge of the river...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(323, 1, Artist.Alan_Lee); //(6/24)
            addObjective("The Hopes of Nargothrond", EncounterSet.TheFallOfNargothrond)
                .WithUnique()
                .WithTraits("Nargothrond.")
                .WithTextLine("Action: Remove 10 progress from the main quest to reveal the top card of the innocent deck and place it beneath The Hopes of Nargothrond. Any player may trigger this effect.")
                .WithTextLine("If there are 6 or more Innocent objective under The Hopes of Nargothrond, the players win the game.")
                .WithInfo(324, 1, Artist.Unknown); //(7/24)
            addLocation("Retreating Soldiers", EncounterSet.TheFallOfNargothrond, 2, 6)
                .WithTraits("Nargothrond.", "Battleground.")
                .WithTextLine("Response: After Retreating Soldiers is explored as the active location, the first player takes control of this card as an ally with 1 Willpower, 3 Attack, 3 Defense, and 3 hit points.")
                .WithFlavorLine("Then Túrin sped back to Nargothrond, mustering such of the rout as he met with on the way...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(325, 2, Artist.Ted_Nasmith); //(8/24)
            addLocation("Unmanned Ballista", EncounterSet.TheFallOfNargothrond, 3, 7)
                .WithTraits("Nargothrond.", "Ballista.")
                .WithTextLine("Response: After Unmanned Ballista is explored as the active location, attach it to a hero controlled by the first player. While attached to a hero, Unmanned Ballista gains: \"Combat Action: Exhaust Unmanned Ballista and attached hero to deal 2 damage to an enemy in play.\"")
                .WithInfo(326, 2, Artist.Unknown); //Indecipherable (9/24)
            addLocation("Leaderless Archers", EncounterSet.TheFallOfNargothrond, 2, 5)
                .WithTraits("Nargothrond.", "Battlefield.")
                .WithTextLine("Response: After Leaderless Archers is explored as the active location, ignore the raid keyword on enemies until the end of the round.")
                .WithShadow("Shadow: The defending player may spend 2 Tactics resources to deal 2 damage to the attacking enemy.")
                .WithInfo(327, 3, Artist.Unknown); //(10/24)
            addLocation("Besieged Defenses", EncounterSet.TheFallOfNargothrond, 4, 4)
                .WithTraits("Nargothrond.", "Battleground.")
                .WithTextLine("Response: After Besieged Defenses is explored as the active location, each character gets +2 Defense until the end of the round.")
                .WithFlavorLine("...and they were even then ransacking the great halls and chambers, plundering and destroying...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(328, 3, Artist.Unknown); //(11/24)
            addTreachery("Not All Can Fight", EncounterSet.TheFallOfNargothrond)
                .WithKeywords("Doomed 2.")
                .WithTextLine("Doomed 2.")
                .WithTextLine("When Revealed: Either deal 1 damage to each Innocent objective in play or deal 1 damage to each character in play.")
                .WithTextLine("(Innocent)")
                .WithInfo(329, 2, Artist.Ted_Nasmith); //(12/24)
            addTreachery("Your Shadow Lies Upon Them", EncounterSet.TheFallOfNargothrond)
                .WithTextLine("When Revealed: Each player must deal 1 Corruption to a character they control. Then, each palyer must assign X Corruption among characters they control, where X is the number of corruption tokens they control with the most Corruption.")
                .WithTextLine("(Innocent)")
                .WithShadow("Shadow: The defending player must either deal 1 Corruption to the defending character or reveal the top card of the encounter deck.")
                .WithInfo(330, 2, Artist.Unknown); //Indecipherable (13/24)
            addTreachery("The Hate of Morgoth", EncounterSet.TheFallOfNargothrond)
                .WithKeywords("Doomed 1.")
                .WithTextLine("Doomed 1.")
                .WithTextLine("When Revealed: Each player exhaust a character and discards the top card of the encounter deck. If the Threat of the discarded card is greater than the Willpower of the exhausted character, that character becomes immediately corrupted.")
                .WithTextLine("(Innocent)")
                .WithShadow("Shadow: The defending character must either take 1 Corruption or take 1 damage.")
                .WithInfo(331, 3, Artist.Unknown); //Indecipherable (14/24)
            addTreachery("Driven Back", EncounterSet.TheFallOfNargothrond)
                .WithTextLine("When Revealed: The first player discards cards from the top of the encounter deck until an enemy is discarded, and adds that enemy to the staging area. Then, the players must remove X characters from the quest, where X is the number of enemies in the staging area.")
                .WithShadow("Shadow: The attacking enemy gets +1 Attack. If this attack destroys a character, remove 5 progress from the quest.")
                .WithInfo(332, 4, Artist.Unknown); //Indecipherable (15/24)
            addTreachery("Mustered Strength", EncounterSet.TheFallOfNargothrond)
                .WithTextLine("When Revealed: Discard cards from the top of the encounter deck until an enemy is discarded. Put the discarded enemy into play engaged with the last player and attach Mustered Strength to it. Mustered Strength gains, \"Forced: When a character is declared as an attacker against this enemy, deal 1 damage to that character.\"")
                .WithShadow("Shadow: The attacking enemy makes an additional attack after this one.")
                .WithInfo(333, 3, Artist.Unknown); //Indecipherable (16/24)
            addTreachery("Dreadful Spell", EncounterSet.TheFallOfNargothrond)
                .WithTraits("Glaurung.")
                .WithTextLine("When Revealed: Attach Dreadful Spell to a hero controlled by the defending player. (Counts as a Condition attachment with the text: \"The attached character cannot ready. At the end of the round, discard the top card of the encounter. If the Threat of the discarded card is lower than the attached character's Willpower, discard Dreadful Spell.\")")
                .WithFlavorLine("...he was yet held by the eyes of Glaurung in torment of mind...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(334, 1, Artist.Unknown); //Indecipherable (17/24)
            addTreachery("Full Fire", EncounterSet.TheFallOfNargothrond)
                .WithTraits("Glaurung.")
                .WithTextLine("When Revealed: Deal 1 damage to each ally controlled by the defending playuer. The defending player may exhaust a character to cancel the damage dealt to that character.")
                .WithFlavorLine("")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(335, 1, Artist.Unknown); //Indecipherable (18/24)
            addTreachery("Fell Voice", EncounterSet.TheFallOfNargothrond)
                .WithTextLine("When Revealed: Randomly select 1 ally controlled by the defending player, if able. Discard the top card of the encounter deck. If the Threat of the discarded card is greater than the Willpower of the selected ally, that ally is immediately corrupted. If no ally is selected by this effect, Fell Voice gains doomed 3.")
                .WithFlavorLine("And Túrin being under the spell of Glaurung hearkened to his words, and he saw himself as in a mirror reshaped by malice...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(336, 2, Artist.Unknown); //Indecipherable (19/24)
            addTreachery("Coiling Swiftly", EncounterSet.TheFallOfNargothrond)
                .WithTraits("Glaurung.")
                .WithTextLine("When Revealed: Glaurung gets +2 Defense until the end of the phase.")
                .WithFlavorLine("But Túrin drawing back his sword stabbed at his eyes, and Glaurung coiling back swiftly toward above him...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(337, 2, Artist.Unknown); //(20/24)
            addObjectiveAlly("Maiden of Nargothrond", EncounterSet.TheFallOfNargothrond, 0, 0, 0, 2)
                .WithTraits("Innocent.")
                .WithTextLine("Forced: At the end of the refresh phase, place a damage token on Maiden of Nargothrond if she is attached to an enemy. If Maiden of Nargothrond is destroyed, place her under The Ruin of Nargothrond.")
                .WithTextLine("Forced: When Maiden of Nargothrond is free of encounters, place it under The Hopes of Nargothrond.")
                .WithInfo(338, 7, Artist.Unknown); //Indecipherable (21/24)
            addObjectiveAlly("Finduilas", EncounterSet.TheFallOfNargothrond, 0, 0, 0, 3)
                .WithTraits("Innocent.")
                .WithTextLine("Forced: At the end of the refresh phase, place a damage token on Finduilas if she is attached to an enemy. If Finduilas is destroyed, place her under The Ruin of Nargothrond and place 1 Corruption on each hero.")
                .WithTextLine("Forced: When Finduilas is free of encounters, place her under The Hopes of Nargothrond.")
                .WithInfo(339, 1, Artist.Unknown); //Indecipherable (22/24)   
            addTreachery("Dark Doom", EncounterSet.TheFallOfNargothrond)
                .WithBurden()
                .WithKeywords("Fate -1.", "Surge.")
                .WithTextLine("Fate -1. Surge.")
                .WithTextLine("When Revealed: The first player must either deal X Corruption among heroes they control or deal X damage among heroes they control (X is the number of damage tokens on Doom Mastered).")
                .WithShadow("Shadow: Resolve the keywords on this card.")
                .WithInfo(340, 1, Artist.Unknown); //Indecipherable
            addTreachery("Fateful Words", EncounterSet.TheFallOfNargothrond)
                .WithBurden()
                .WithKeywords("Fate -1.")
                .WithTextLine("Fate -1.")
                .WithTextLine("When Revealed: Attach this card to the hero with the highest threat cost. (Counts as a Condition attachment with the text: \"Forced: After a character is destroyed, deal 1 Corruption to the attached hero.\")")
                .WithFlavorLine("\"Evil have been all you ways, son of Húrin")
                .WithFlavorLine("-Glaurung, The Children of Húrin")
                .WithInfo(341, 1, Artist.Unknown); //Indecipherable
            addObjective("Doom Mastered", EncounterSet.TheFallOfNargothrond)
                .WithSlugSuffix("Objective")
                .WithBurden()
                .WithTraits("Doom.")
                .WithTextLine("At the end of the game, record the number of damage or progress tokens on Doom Mastered in the campaign log.")
                .WithTextLine("Setup: Place the number of damage or progress tokens on Doom Mastered equal to the total listed in the campaign log from the previous quest.")
                .WithFlavorLine("A Túrin Turambar...")
                .WithFlavorLine("-The Children of Húrin")
                .WithInfo(342, 1, Artist.Unknown); //Indecipherable
            addHero("Finarfin", 11, Sphere.Leadership, 3, 1, 4, 4)
                .WithTraits("Noldor.", "House of Finarfin.", "Noble.")
                .WithKeywords("Sentinel.")
                .WithTextLine("Sentinel.")
                .WithTextLine("While Finarfin is defending, he gains: \"Response: Cancel a shadow effect just triggered. Then, cancel all damage dealt to the attacking enemy until the end of the round. (Limit once per round.)\"")
                .WithFlavorLine("But Finarfin spoke softly, as was his wont, and sought to calm the Noldor, persuading them to pause and ponder ere deeds were done that could not be undone...")
                .WithFlavorLine("-The Silmarillion")
                .WithInfo(343, 1, Artist.Elena_Kukanova);
            addAlly("Guard of the Drúedain", 2, Sphere.Lore, false, 1, 1, 2, 3)
                .WithTraits("Drúedain.")
                .WithTextLine("Response: After an enemy engages you, exhaust Guard of the Drúedain to lower that enemy's Attack by 1 until the end of the phase (lower its Attack by 2 instead if the attacking enemy is an Orc.) The targeted enemy cannot be targeted again by the ability of a Guard of the Drúedain this round.")
                .WithFlavorLine("...nothing passed or came near that was not marked and remembered.")
                .WithFlavorLine("-Unfinished Tales")
                .WithInfo(344, 3, Artist.Unknown);
            addAlly("Shieldmaiden of Haleth", 3, Sphere.Spirit, false, 2, 1, 2, 2)
                .WithTraits("Edain.", "House of Haleth.")
                .WithTextLine("Response: After Shieldmaiden of Haleth quests successfully, place 1 resource token on it.")
                .WithTextLine("Response: After a hero is damaged by an enemy attack, exhaust Shieldmaiden of Haleth and remove 3 progress tokens from it to cancel all damage from that attack.")
                .WithInfo(345, 3, Artist.Unknown);
            addAlly("Noldor Oathkeeper", 4, Sphere.Mastery, false, 1, 1, 2, 3)
                .WithTextLine("If each hero you control has at least 1 Corruption, Noldor Oathkeeper does not exhaust to defend.")
                .WithTextLine("Response: When you play Noldor Oathkeeper from your hand, place 1 Corruption on a hero you control to reduce its cost by 1.")
                .WithInfo(346, 3, Artist.Unknown);
            addAlly("Amon Ethir Sentry", 3, Sphere.Tactics, false, 0, 2, 2, 3)
                .WithTraits("Noldor.", "Warrior.")
                .WithTextLine("Response: After Amon Ethir Sentry enters play, choose an enemy in the staging area. Then, you may either engage that enemy or that enemy does not make engagement checks until the end of the round.")
                .WithInfo(347, 3, Artist.Unknown);
            addAlly("Andvír", 0, Sphere.Mastery, true, 1, 1, 1, 2)
                .WithTraits("Gaurwaith.")
                .WithKeywords("Ransom 3.")
                .WithTextLine("Ransom 3.")
                .WithTextLine("Response: After a treachery is revealed, exhaust Andvír to choose an ally. That ally readies and gets +1 Willpower until the end of the round.")
                .WithInfo(348, 3, Artist.Andreia_Ugrai);
            addAttachment("Gilded Mask", 2, Sphere.Mastery, true)
                .WithTraits("Item.", "Armor.")
                .WithKeywords("Restricted.")
                .WithTextLine("Attach to a hero. Restricted.")
                .WithTextLine("While the attached hero is committed to the quest, Gilded Mask gains, \"Response: When an enemy with lower Threat than the number of Corruption tokens on the attached hero is revealed from the encounter deck, exhaust Gilded Mask to discard that enemy (canceling all of its effects). Reveal the next card of the encounter deck instead.\"")
                .WithInfo(349, 3, Artist.Unknown); //Peet
            addAttachment("Hidden Way", 2, Sphere.Spirit, false)
                .WithTraits("Path.")
                .WithTextLine("Attach to a location.")
                .WithTextLine("Response: After attached location is explored, reduce the first player's threat by X, where X is the attached location's printed quest points (up to a limit of 5.)")
                .WithInfo(350, 3, Artist.John_Howe);
            addAttachment("Seal of the Queen", 2, Sphere.Leadership, true)
                .WithTraits("Item.", "Boom.")
                .WithTextLine("Attach to a hero.")
                .WithTextLine("Attached hero gets +1 Willpower.")
                .WithTextLine("Action: Exhaust Seal of the Queen and name a number to search the top 3 cards of your deck. You may choose one of those cards with cost equal to the named number and add it to your hand. Shuffle the rest back into your deck.")
                .WithInfo(351, 3, Artist.Elena_Kukanova);
            addEvent("Unnumbered Tears", 2, Sphere.Tactics)
                .WithTextLine("Response: After a character is destroyed, ready each character you control that shares a trait with that character.")
                .WithFlavorLine("Then in the plain of...")
                .WithFlavorLine("-The Simlarillion")
                .WithInfo(352, 3, Artist.Unknown);
            addEvent("Friend of Birds and Beasts", 1, Sphere.Lore)
                .WithTextLine("Action: Place the top 3 cards of the encounter deck facedown under this card. Each facedown card acts as an ally with 1 Willpower, 1 Attack, 1 Defense, 1 hit point, and the Creature trait. Discard this card and call facedown cards underneath it at the end of the round.")
                .WithInfo(353, 3, Artist.Unknown);
            addEvent("Kingly Judgement", 1, Sphere.Mastery)
                .WithTraits("Doom.")
                .WithTextLine("Action: Choose a character with at least 1 Corruption and choose one: deal 1 damage to that character to remove 1 Corruption from that character to play an attachment of X cost or lower on that character for free, where X is the number of Corruption tokens on that character.") 
                .WithInfo(354, 3, Artist.Steamey);
            addAttachment("Silmaril of the Sky", 2, Sphere.Neutral, true)
                .WithTraits("Item.", "Artifact.")
                .WithTextLine("Attach to a hero with at least 1 Corruption. Limit 1 per deck.")
                .WithTextLine("Action: Exhaust Silmaril of the Sky and deal 1 Corruption to a character you control to (choose 1): discard a shadow card from a non-unique enemy, choose an enemy to get -2 Attack until the end of the phase, or ready attached hero.")
                .WithInfo(355, 3, Artist.Steamey);
            addCampaign(setName, EncounterSet.TheFallOfNargothrond, cycleName)
                .WithTextLine("You are playing Campaign mode.")
                .WithTextLine("Setup: Shuffle Fateful Woords and Dark Doom into the encounter deck. Add Doom Mastered to the staging area.")
                .WithTextLine("Response: After Finduilas is placed beneath The Hopes of Nargothrond, the players gain 1 fate.")
                .WithTextLine("Action: Remove X damage from Glaurung to gain 1 fate for the players. X is equal to 5 times the number of players. Any player may trigger this action.")
                .WithFlavorLine("\"In the autumn of the year, biding his hour, Morgoth loosed upon the people of Narog the great host that he had long prepared...\"")
                .WithFlavorLine("-The Children of Húrin")
                .WithOppositeTextLine("Resolution: Follow the instructions on Doom Mastered and record the number of damage or progress tokens on that card. If at least 1 damage is recorded, then add Dark Doom to the the campaign pool. If at least 2 damage is recorded, then add both Dark Doom and Fateful Words to the campaign pool.")
                .WithInfo(356, 1, Artist.Unknown); //Helge C. Balzer
            addEncounterSideQuest("A Grave Wound", EncounterSet.TheFallOfNargothrond, 5)
                .WithFlavorLine("One of your allies has been laid low upon the battlefield. You must decide whether to tend to their wounds or continue to rescue the innocents of Nargothrond.")
                .WithTextLine("When Revealed: The first player loses control of their highest cost ally and places it underneath this stage. That ally has been \"wounded.\" When this stage is defeated, the first player takes control of the \"wounded\" ally. If no allies are placed underneath this card by this effect, discard A Grave Wound and it gains surge.")
                .WithTextLine("Forced: At the end of the round, deal 1 damage to the \"wounded\" ally. If that ally leaves play, discard a Grave Wound.")
                .WithVictoryPoints(1)
                .WithInfo(357, 1, Artist.Unknown); //LB82 (23/24)
            addObjectiveAlly("Child of Nargothrond", EncounterSet.TheFallOfNargothrond, 0, 0, 0, 1)
                .WithTraits("Innocent.")
                .WithTextLine("Forced: At the end of the refresh phase, place a damage token on Child of Nargothrond if he is attached to an enemy. If Child of Nargothrond is destroyed, place him under The Ruin of Nargothrond.")
                .WithInfo(358, 2, Artist.Adele_Lorienne); //(24/24)
            addAttachment("Favor of Indis", 0, Sphere.Leadership, false)
                .WithTraits("Condition.")
                .WithTextLine("Attach to a House of Fingolfin or House of Finarfin hero. Limit 1 per hero.")
                .WithTextLine("Attached hero gains +1 Defense for each resource on Favor of Indis.")
                .WithTextLine("Response: At the end of the combat phase, add 1 resource to Favor of Indis if you are engaged with an enemy and did not destroy an enemy this phase. (Limit 3 resources on Favor of Indis.)")
                .WithTextLine("Forced: After you destroy an enemy, remove 1 resource from Favor of Indis.")
                .WithInfo(359, 3, Artist.Unknown); //Cale
        }
    }
}
