/* Generated CardSet class: The Lost Realm */

using System;

namespace HallOfBeorn.Models.LotR.Sets.TheLostRealm
{
    public class TheLostRealmSet : CardSet
    {
        protected override void Initialize()
        {
            Name = "The Lost Realm";
            Abbreviation = "TLR";
            Number = 29;
            SetType = Models.SetType.Deluxe_Expansion;

            addHero("Aragorn", 12, Sphere.Tactics, 2, 3, 2, 5)
                .WithTraits("Dúnedain.", "Ranger.", "Warrior.")
                .WithTextLine("Each enemy engaged with you gets -1 Defense.")
                .WithTextLine("Response: After Aragorn participates in an attack that destroys an enemy, choose an enemy not engaged with you and engage that enemy.")
                .WithFlavorLine("\"I serve no man,\" said Aragorn; \"but the servants of Sauron I pursue into whatever land they may go.\" -The Two Towers")
                .WithInfo(1, 1, Artist.Sebastian_Giacobino);
            addHero("Halbarad", 10, Sphere.Leadership, 2, 2, 2, 4)
                .WithTraits("Dúnedain.", "Ranger.")
                .WithTextLine("While you are engaged with any enemy, Halbarad does not exhaust to commit to a quest.")
                .WithTextLine("You may optionally engage 1 additional enemy during the encounter phase.")
                .WithFlavorLine("\"Little do they know of our long labour for the safekeeping of their borders, and yet I grudge it not.\" -The Return of the King")
                .WithInfo(2, 1, Artist.Smirtouille);
            addAlly("Weather Hills Watchman", 2, Sphere.Leadership, false, 1, 1, 0, 2)
                .WithTraits("Dúnedain.")
                .WithTextLine("Response: After Weather Hills Watchman enters play, search the top 5 cards of your deck for a Signal card and add it to your hand. Shuffle the other cards back into your deck.")
                .WithFlavorLine("\"Rangers use runes, and they come here sometimes.\" -Aragorn, The Fellowship of the Ring")
                .WithInfo(3, 3, Artist.Kim_Sokol);
            addAlly("Dúnedain Hunter", 0, Sphere.Tactics, false, 1, 3, 1, 3)
                .WithTraits("Dúnedain.", "Ranger.")
                .WithTextLine("Forced: After Dúnedain Hunter enters play, search the top 5 cards of the encounter deck for a non-unique enemy and put it into play engaged with you. If no enemy enters play by this effect, discard Dúnedain Hunter. Shuffle the encounter deck.")
                .WithInfo(4, 3, Artist.Louis_Green);
            addAlly("Sarn Ford Sentry", 3, Sphere.Lore, false, 2, 1, 0, 2)
                .WithTraits("Dúnedain.", "Scout.")
                .WithTextLine("Response: After Sarn Ford Sentry enters play, draw 1 card for each enemy engaged with you.")
                .WithFlavorLine("\"Lonely men are we, Rangers of the wild, hunters but hunters ever of the servants of the Enemy...\" -Aragorn, The Fellowship of the Ring")
                .WithInfo(5, 3, Artist.Smirtouille);
            addAlly("Warden of Annúminas", 4, Sphere.Spirit, false, 0, 2, 2, 3)
                .WithTraits("Dúnedain.", "Ranger.")
                .WithTextLine("Warden of Annúminas gets +1 Willpower for each enemy engaged with you.")
                .WithFlavorLine("Rangers passed at times beyond the hills, but they were few and did not stay. -The Fellowship of the Ring")
                .WithInfo(6, 3, Artist.Smirtouille);
            addEvent("Ranger Summons", 1, Sphere.Leadership)
                .WithTraits("Signal.")
                .WithTextLine("Play only if you control a Dúnedain hero.")
                .WithTextLine("Planning Action: Shuffle 1 of your set aside Ranger of the North allies with the encounter keyword into the encounter deck. Then, remove Ranger Summons from the game.")
                .WithFlavorLine("\"We rode as swiftly as we might when your summons came.\" -Halbarad, The Return of the King")
                .WithInfo(7, 3, Artist.Smirtouille);
            addEvent("Tireless Hunters", 1, Sphere.Tactics)
                .WithTextLine("Play only before the resolving enemy attacks step.")
                .WithTextLine("Combat Action: Choose an enemy not engaged with you. Engage that enemy. Then, discard a shadow card from that enemy, if able.")
                .WithFlavorLine("\"Many evil things there are that your strong walls and bright swords do not stay.\" -Aragorn, The Fellowship of the Ring")
                .WithInfo(8, 3, Artist.Ilich_Henriquez);
            addEvent("Expert Trackers", 0, Sphere.Lore)
                .WithTextLine("Response: After you engage an enemy, exhaust a Scout or Ranger character to place X progress tokens on a location. X is the engaged enemy's printed Threat.")
                .WithFlavorLine("\"At last!\" said Aragorn. \"Here are the tracks that we seek!\" -The Two Towers")
                .WithInfo(9, 3, Artist.Alexandr_Shaldin);
            addAttachment("Heir of Valandil", 2, Sphere.Leadership, true)
                .WithTraits("Title.")
                .WithTextLine("Attach to a Dúnedain hero.")
                .WithTextLine("Planning Action: Exhaust Heir of Valandil to reduce the cost of the next Dúnedain ally you play this phase by 1 for each enemy engaged with you.")
                .WithFlavorLine("\"But my home, such as I have, is in the North. For here the heirs of Valandil have ever dwelt in long line unbroken from father unto son for many generations.\" -Aragorn, The Fellowship of the Ring")
                .WithInfo(10, 3, Artist.Smirtouille);
            addAttachment("Athelas", 1, Sphere.Lore, false)
                .WithTraits("Item.")
                .WithTextLine("Attach to a Dúnedain or Healer character.")
                .WithTextLine("Action: Discard Athelas and exhaust attached character to heal all damage on a character. You may discard a Condition attachment from that character.")
                .WithFlavorLine("\"...it is a healing plant that the Men of the West brought to Middle-earth. Athelas they named it...\" -Aragorn, The Fellowship of the Ring")
                .WithInfo(11, 3, Artist.Cristi_Balanescu);
            addAttachment("Secret Vigil", 1, Sphere.Tactics, false)
                .WithTraits("Condition.")
                .WithTextLine("Attach to an enemy. Limit 1 per enemy.")
                .WithTextLine("Attached enemy gets -1 Threat.")
                .WithTextLine("Response: When attached enemy is destroyed, reduce each player's threat by the attached enemy's printed Threat.")
                .WithFlavorLine("\"If simple folk are free from care and fear, simple they will be, and we must be secret to keep them so.\" -Aragorn, The Fellowship of the Ring")
                .WithInfo(12, 3, Artist.Piya_Wannachaiwong);
            addAttachment("Star Brooch", 1, Sphere.Spirit, false)
                .WithTraits("Item.")
                .WithTextLine("Attach to a Dúnedain or Noldor hero. Limit 1 per hero.")
                .WithTextLine("While you are engaged with an enemy, attached hero gets +1 Willpower and cannot have its Willpower reduced.")
                .WithFlavorLine("...each cloak was pinned upon the left shoulder by a brooch of silver shaped like a rayed star. -The Return of the King")
                .WithInfo(13, 3, Artist.Alexandr_Elichev);
            addPlayerSideQuest("Gather Information", 0, Sphere.Neutral, 4)
                .WithTextLine("Limit 1 per deck.")
                .WithTextLine("Response: After this stage is defeated, each player may search his deck for 1 card and add it to his hand. Each player shuffles his deck.")
                .WithFlavorLine("Aragorn halted and examined the tracks closely. -The Tower Towers")
                .WithVictoryPoints(1)
                .WithInfo(14, 3, Artist.Smirtouille);
            addAlly("Ranger of the North", 255, Sphere.Neutral, false, 2, 2, 2, 3)
                .WithTraits("Dúnedain.", "Ranger.")
                .WithKeywords("Encounter.", "Surge.", "Ranged.", "Sentinel.")
                .WithTextLine("Encounter. Surge. Ranged. Sentinel.")
                .WithTextLine("When Revealed: The first player chooses a player to take control of Ranger of the North. Then, either deal 2 damage to an enemy or place 2 progress tokens on a location.")
                .WithInfo(15, 3, Artist.Alvaro_Calvo_Escudero);
            addObjectiveAlly("Iârion", EncounterSet.Iarion, Card.VALUE_X, Card.VALUE_X, Card.VALUE_X, 4)
                .WithTraits("Dúnedain.", "Ranger.")
                .WithTextLine("X is the number of quest cards in play.")
                .WithTextLine("The first player gains control of Iârion.")
                .WithTextLine("Response: After a side quest is revealed from the encounter deck, ready Iârion.")
                .WithTextLine("If Iârion leaves play, the players lose the game.")
                .WithInfo(16, 1, Artist.JB_Casacop);
            addEnemy("Orc War Party", EncounterSet.IntrudersInChetwood, 40, 3, 6, 3, 6)
                .WithTraits("Orc.")
                .WithTextLine("Cannot have attachments.")
                .WithTextLine("While Orc War Party is in the staging area, enemies in the staging area cannot take damage.")
                .WithTextLine("The players cannot win the game while Orc War Party is in play.")
                .WithFlavorLine("They kept no order, thrusting, jostling, and cursing; yet their speed was very great. -The Two Towers")
                .WithEasyModeQuantity(1)
                .WithInfo(17, 3, Artist.Anthony_Feliciano);
            addLocation("Chetwood Forest", EncounterSet.IntrudersInChetwood, 3, 3)
                .WithTraits("Arnor.", "Forest.")
                .WithTextLine("Travel: One player chooses and engages an enemy in the staging area.")
                .WithShadow("Shadow: Defending player either exhausts a hero he controls, or returns attacking enemy to the staging area after this attack.")
                .WithEasyModeQuantity(2)
                .WithInfo(18, 3, Artist.Michael_Wolmarans);
            addLocation("Borders of Bree-land", EncounterSet.IntrudersInChetwood, 2, 4)
                .WithTraits("Arnor.")
                .WithTextLine("While Borders of Bree-land is in the staging area it gains: \"Forced: At the beginning of the quest phase, return 1 enemy engaged with a player to the staging area.\"")
                .WithShadow("Shadow: Defending character gets -1 Defense for each quest stage in play.")
                .WithInfo(19, 2, Artist.Jake_Bullock);
            addLocation("Outlying Homestead", EncounterSet.IntrudersInChetwood, 2, 8)
                .WithTraits("Arnor.")
                .WithKeywords("Doomed 1.")
                .WithTextLine("Doomed 1.")
                .WithTextLine("While Outlying Homestead is in the staging area, players cannot reduce their threat.")
                .WithTextLine("Travel: Reveal a card from the encounter deck.")
                .WithFlavorLine("They were far beyond the borders of the Bree-land, out in the pathless wilderness... -The Fellowship of the Ring")
                .WithEasyModeQuantity(2)
                .WithInfo(20, 3, Artist.Ed_Mattinian);
            addTreachery("Sudden Assault", EncounterSet.IntrudersInChetwood)
                .WithTextLine("When Revealed: If the total Willpower of character committed to the quest is greater than the total Threat in the staging area, each enemy in the staging area makes an immediate attack against the first player. If no attach is made this way, search the encounter deck and discard pile for an Orc War Party and add it to the staging area. Shuffle the encounter deck. This effect cannot be canceled.")
                .WithEasyModeQuantity(0)
                .WithInfo(21, 2, Artist.Jon_Bosco);
            addTreachery("Surprising Speed", EncounterSet.IntrudersInChetwood)
                .WithTextLine("When Revealed: Each player returns 1 enemy engaged with him to the staging area. If no enemy was returned to the staging area this way, Surprising Speed gains surge and doomed 1.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack. Return attacking enemy to the staging area after this attack.")
                .WithEasyModeQuantity(2)
                .WithInfo(22, 3, Artist.Matthew_Cowdery);
            addEncounterSideQuest("Orc Rearguard", EncounterSet.IntrudersInChetwood, 3)
                .WithTextLine("No more than 3 progress tokens can be placed on the current quest each round.")
                .WithTextLine("While Orc Rearguard is the current quest it gains: \"Forced: At the end of the staging step, reveal 1 card from the encounter deck.\"")
                .WithFlavorLine("Some of the Orcs have broken from the war party to hinder your pursuit. Until you deal with them, it will be difficult to continue your chase...")
                .WithVictoryPoints(10)
                .WithInfo(23, 1, Artist.Jon_Bosco);
            addEncounterSideQuest("Rescue Iârion", EncounterSet.IntrudersInChetwood, 6)
                .WithKeywords("Time 4.")
                .WithTextLine("Time 4. When Revealed: The first player loses control of Iârion and places him facedown underneath this stage. When this stage is defeated, the first player takes control of Iârion and exhausts him.")
                .WithTextLine("Forced: After the last time counter is removed from this stage, discard Iârion.")
                .WithFlavorLine("While scouting ahead, Iârion is ambushed by several Orcs. The Ranger is knoced unconscious and dragged away by the Orcs. You must rescue him!")
                .WithVictoryPoints(10)
                .WithInfo(24, 1, Artist.JB_Casacop);
            addEnemy("Cornered Orc", EncounterSet.TheWeatherHills, 20, 2, 2, 1, 2)
                .WithTraits("Orc.")
                .WithTextLine("Forced: After Corned Orc engages a player, it makes an immediate attack.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack (+2 Attack instead if the defending character is damaged).")
                .WithEasyModeQuantity(4)
                .WithInfo(25, 5, Artist.Tey_Bartolome);
            addLocation("Amon Forn", EncounterSet.TheWeatherHills, 4, 6)
                .WithUnique()
                .WithTraits("Arnor.", "Ruins.")
                .WithTextLine("Immune to player card effects.")
                .WithTextLine("While Amon Forn is the active location, it gains: \"Forced: After an Orc enemy is added to the staging area, it makes an immediate attack against the first player.\"")
                .WithTextLine("The players cannot win while Amon Forn is in play.")
                .WithVictoryPoints(3)
                .WithInfo(26, 1, Artist.Dimitri_Bielak);
            addLocation("Weathered Hilltop", EncounterSet.TheWeatherHills, 1, 5)
                .WithTraits("Arnor.", "Hills.")
                .WithTextLine("Weathered Hilltop gets +1 Threat for each resource token on it.")
                .WithTextLine("Forced: After a Weather treachery is revealed from the encounter deck, place 1 resource token here.")
                .WithFlavorLine("\"There is little shelter or defence here...\" -Aragorn, The Fellowship of the Ring")
                .WithInfo(27, 3, Artist.Ed_Mattinian);
            addLocation("Exposed Ridge", EncounterSet.TheWeatherHills, 3, 3)
                .WithTraits("Arnor.", "Hills.")
                .WithTextLine("While Exposed Ridge is the active location, it gains: \"Forced: At the end of the refresh phase, each player deals 1 damage to a character he controls.\"")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack for each damaged character the defending player controls.")
                .WithEasyModeQuantity(2)
                .WithInfo(28, 3, Artist.Alyn_Spiller);
            addLocation("Sheltered Valley", EncounterSet.TheWeatherHills, 2, 4)
                .WithTraits("Arnor.", "Hills.")
                .WithTextLine("While Sheltered Valley is the active location, it gains: \"Response: When Sheltered Valley is explored, heal all damage from 1 character.\"")
                .WithTextLine("Travel: Remove 1 resource token from the Mission objective.")
                .WithInfo(29, 2, Artist.Juan_Carlos_Barquet);
            addLocation("Concealed Orc-camp", EncounterSet.TheWeatherHills, 2, 2)
                .WithTraits("Arnor.", "Hills.")
                .WithTextLine("While Concealed Orc-camp is the active location is gains: \"Response: When Concealed Orc-camp is explored, place 1 resource token on the Mission objective.\"")
                .WithTextLine("Travel: The first player searches the encounter deck and discard pile for an Orc enemy and put it into play engaged with him. Shuffle the encounter deck.")
                .WithInfo(30, 3, Artist.Mariusz_Gandzel);
            addTreachery("Ice Storm", EncounterSet.TheWeatherHills)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: Each player assigns X damage among characters he controls, where X is the number of quest cards in play. Then, exhaust each damaged character.")
                .WithShadow("Shadow: Assign X damage among characters you control. X is the number of quest cards in play.")
                .WithEasyModeQuantity(1)
                .WithInfo(31, 2, Artist.Romana_Kendelic);
            addEncounterSideQuest("Find Shelter", EncounterSet.TheWeatherHills, 6)
                .WithKeywords("Surge.", "Time 4.")
                .WithTextLine("Surge. Time 4.")
                .WithTextLine("Forced: After the last time counter is removed from this quest cards, each player deals 4 damage to a hero he controls. Then, place 4 time counters on this quest card.")
                .WithFlavorLine("The weather is growing steadily worse, and black clouds loom on the horizon. You must find a safe place to shelter or be caught in the storm...")
                .WithVictoryPoints(10)
                .WithInfo(32, 1, Artist.Smirtouille);
            addEnemy("Thaurdir", EncounterSet.DeadmensDike, 1, 4, 6, 4, 9)
                .WithUnique()
                .WithTraits("Undead.", "Wraith.")
                .WithKeywords("Indestructible.")
                .WithTextLine("Indestructible. Cannot have attachments.")
                .WithTextLine("Forced: After a treachery card with the Sorcery trait is revealed from the encounter deck, Thaurdir makes an immediate attack against the first player.")
                .WithInfo(33, 1, Artist.Joel_Hustak);
            addEnemy("Thaurdir's Damned", EncounterSet.DeadmensDike, 35, 3, 5, 2, 6)
                .WithTraits("Undead.", "Wraith.")
                .WithTextLine("Forced: After Thaurdir's Damned engages you, discard the top 2 cards of your deck and assign X damage among characters you control. X is the combined printed cost of the discarded cards.")
                .WithFlavorLine("\"I saw them; grim faces and evil...\" -Frodo, The Two Towers")
                .WithEasyModeQuantity(1)
                .WithInfo(34, 3, Artist.Jim_Pavelec);
            addEnemy("Baleful Shade", EncounterSet.DeadmensDike, 30, 2, 2, 1, 5)
                .WithTraits("Undead.", "Wraith.")
                .WithTextLine("Forced: When Baleful Shade attacks, the defending player discards the top card of his deck. If the discarded card is an ally, Baleful Shade gets +2 Attack for this attack.")
                .WithShadow("Shadow: Exhaust a character you control.")
                .WithInfo(35, 4, Artist.Florian_Devos);
            addLocation("Broken Battlements", EncounterSet.DeadmensDike, 2, 6)
                .WithTraits("Fornost.", "Ruins.")
                .WithKeywords("Time 3.")
                .WithTextLine("Time 3. Forced: After the last time counter is removed from Broken Battlements, each player discards the top 5 cards of his deck and places 1 time counter here.")
                .WithTextLine("Travel: Each player discard the top card of his deck.")
                .WithFlavorLine("\"Men call it Deadman's Dike, and they fear to tread there.\" -Elrond, The Fellowship of the Ring")
                .WithEasyModeQuantity(2)
                .WithInfo(36, 3, Artist.Juan_Carlos_Barquet);
            addLocation("Norbury Tombs", EncounterSet.DeadmensDike, 2, 5)
                .WithTraits("Fornost.", "Ruins.")
                .WithTextLine("While Norbury Tombs is the active location, it gains: \"Response: When Norbury Tombs is explored, each player shuffles the top 5 cards of his discard pile into his deck.\"")
                .WithTextLine("Travel: Return the topmost enemy in the encounter discard pile to the staging area.")
                .WithInfo(37, 2, Artist.Julian_Kok);
            addLocation("Fornost Square", EncounterSet.DeadmensDike, 1, 4)
                .WithTraits("Fornost.", "Ruins.")
                .WithTextLine("Fornost Square gets +1 Threat for each resource token on it.")
                .WithTextLine("Forced: After the first player discards any number of cards from the top of his deck, place 1 resource token here.")
                .WithFlavorLine("\"...the heirs of Valandil removed and dwelt at Fornost on the high North Downs, and that now too is desolate.\" -Elrond, The Fellowship of the Ring")
                .WithInfo(38, 3, Artist.Mariusz_Gandzel);
            addLocation("Haunted Keep", EncounterSet.DeadmensDike, 3, 3)
                .WithTraits("Fornost.", "Ruins.")
                .WithTextLine("While Haunted Keep is the active location, the first Undead enemy revealed each round gains surge.")
                .WithShadow("Shadow: Defending player discards the top card of his deck. Attacking enemy gets +X Attack where X is the discarded card's printed cost.")
                .WithEasyModeQuantity(2)
                .WithInfo(39, 3, Artist.Dimitri_Bielak);
            addLocation("Deadmen's Gate", EncounterSet.DeadmensDike, 4, 4)
                .WithTraits("Fornost.", "Ruins.")
                .WithTextLine("While Deadmen's Gate is the active location, it gains: \"Forced: After a player triggers an 'Action' or 'Response' effect, he must discard the top card of his deck.\"")
                .WithShadow("Shadow: Discard an attachment you control.")
                .WithEasyModeQuantity(1)
                .WithInfo(40, 2, Artist.Michael_Wolmarans);
            addTreachery("Unnatural Fog", EncounterSet.DeadmensDike)
                .WithTraits("Sorcery.")
                .WithKeywords("Doomed 2.")
                .WithTextLine("Doomed 2.")
                .WithTextLine("When Revealed: Each player must either discard 1 card from the top of his deck for each questing character he controls, or remove each character he controls from the quest.")
                .WithFlavorLine("The mist was flowing past him now in shreds and tatters. -The Fellowship of the Ring")
                .WithEasyModeQuantity(1)
                .WithInfo(41, 2, Artist.Joel_Hustak);
            addEncounterSideQuest("The Shadow World", EncounterSet.DeadmensDike, 5)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Forced: At the end of the refresh phase, each player discards the top X cards of his deck, where X is the number of Undead enemies engaged with him.")
                .WithFlavorLine("The more you struggle against the undead, the deeper you are drawn into the wraith-world. You must escape before madness or despair takes you...")
                .WithVictoryPoints(10)
                .WithInfo(42, 1, Artist.Guillaume_Ducos);
            addEnemy("Angmar Orc", EncounterSet.AngmarOrcs, 25, 2, 2, 3, 3)
                .WithTraits("Orc.")
                .WithTextLine("When Revealed: Either discard 1 ally from play, or reveal an additional encounter card.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack. If this attack destroys an ally, return attacking enemy to the staging area.")
                .WithInfo(43, 3, Artist.Tey_Bartolome);
            addEnemy("Angmar Marauder", EncounterSet.AngmarOrcs, 30, 3, 3, 2, 4)
                .WithTraits("Orc.")
                .WithTextLine("Forced: After Angmar Marauder attacks and destroys an ally, return it to the staging area.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack for each ally the defending player controls.")
                .WithEasyModeQuantity(2)
                .WithInfo(44, 3, Artist.Anthony_Feliciano);
            addEnemy("Angmar Captain", EncounterSet.AngmarOrcs, 35, 3, 5, 2, 5)
                .WithTraits("Orc.")
                .WithTextLine("Forced: After Angmar Captain attacks and destroys an ally, discard the top card of the defending player's deck. If the discarded card is an ally, Angmar Captain makes an additional attack against the defending player.")
                .WithFlavorLine("In the twilight he saw a large black Orc... -The Two Towers")
                .WithEasyModeQuantity(1)
                .WithInfo(45, 2, Artist.Joel_Hustak);
            addEncounterSideQuest("Orc Ambush", EncounterSet.AngmarOrcs, 4)
                .WithTextLine("Each Orc enemy gets +1 Threat, +1 Attack and +1 Defense.")
                .WithTextLine("When Revealed: Each player must search the encounter deck and discard pile for an Orc enemy and put it into play engaged with him. Shuffle the encounter deck.")
                .WithFlavorLine("Several Orcs spring upon you from their hiding place! Their surprise attack puts you on the defensive. You must fight to gain the upper hand.")
                .WithVictoryPoints(10)
                .WithInfo(46, 1, Artist.Mark_Bulahao);
            addLocation("Rugged Country", EncounterSet.EriadorWilds, 2, 3)
                .WithTraits("Arnor.")
                .WithTextLine("If the current quest is a side quest, Rugged Country gets +2 Threat.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack for each quest card in play.")
                .WithInfo(47, 3, Artist.Juan_Carlos_Barquet);
            addLocation("Shrouded Hills", EncounterSet.EriadorWilds, Card.VALUE_X, 5)
                .WithTraits("Arnor.", "Hills.")
                .WithTextLine("X is the number of quest cards in play.")
                .WithTextLine("While there is only 1 quest card in play, Shrouded Hills gains surge.")
                .WithFlavorLine("As the sun rose and passed noon they glimpsed far off in the east the grey-green lines of the Downs... -The Fellowship of the Ring")
                .WithEasyModeQuantity(1)
                .WithInfo(48, 2, Artist.Alvaro_Calvo_Escudero);
            addTreachery("Pressing Needs", EncounterSet.EriadorWilds)
                .WithKeywords("Doomed 2.")
                .WithTextLine("Doomed 2.")
                .WithTextLine("When Revealed: Either search the encounter deck and discard pile for an encounter side quest and reveal it, or choose a different quest card in play to be the current quest until the end of the phase. Shuffe the encounter deck.")
                .WithFlavorLine("\"But often I must put mirth aside.\" -Aragorn, The Fellowship of the Ring")
                .WithEasyModeQuantity(1)
                .WithInfo(49, 2, Artist.Mark_Bulahao);
            addTreachery("Weight of Responsibility", EncounterSet.EriadorWilds)
                .WithTextLine("When Revealed: Reveal 1 encounter card for each quest card in play.")
                .WithShadow("Shadow: Defending player discards 1 attachment for each quest card in play.")
                .WithEasyModeQuantity(1)
                .WithInfo(50, 2, Artist.Dleoblack);
            addEncounterSideQuest("Lost in the Wilderness", EncounterSet.EriadorWilds, 4)
                .WithTextLine("When Revealed: Each player places all cards in his hand facedown underneath Lost in the Wilderness.")
                .WithTextLine("Forced: When Lost in the Wilderness is defeated, return each card underneath it to its owner's hand.")
                .WithFlavorLine("You've lost your way in the vastness of Arnor. You must search around until you find your trail again.")
                .WithVictoryPoints(10)
                .WithInfo(51, 1, Artist.Alvaro_Calvo_Escudero);
            addTreachery("Biting Wind", EncounterSet.FoulWeather)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: Assign X damage among characters commited to the quest. X is the number of characters committed to the quest.")
                .WithShadow("Shadow: Deal 1 damage to the defending character.")
                .WithEasyModeQuantity(2)
                .WithInfo(52, 3, Artist.Tommy_Arnold);
            addTreachery("Freezing Blast", EncounterSet.FoulWeather)
                .WithTraits("Weather.")
                .WithKeywords("Doomed 2.")
                .WithTextLine("Doomed 2.")
                .WithTextLine("When Revealed: Remove each damaged character from the quest.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack for each damaged character the defending player controls.")
                .WithEasyModeQuantity(1)
                .WithInfo(53, 2, Artist.Bill_Thompson);
            addTreachery("Cold from Angmar", EncounterSet.FoulWeather)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: Each player deals 1 damage to a hero he controls. Attach Cold from Angmar to the current quest. (Counts as a Condition attachment with the text: \"Treat each damaged character's printed text box as if it were blank, except for keywords and Traits.\")")
                .WithFlavorLine("\"...the weather may prove a more deadly enemy than any.\" -Gandalf, The Fellowship of the Ring")
                .WithEasyModeQuantity(2)
                .WithInfo(54, 3, Artist.Florian_Devos);
            addEncounterSideQuest("Make Camp", EncounterSet.FoulWeather, 6)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Characters cannot be healed.")
                .WithTextLine("Response: After Make Camp is defeated, each player heals up to 3 damage from a hero he controls.")
                .WithFlavorLine("Your companions are exhausted from tireless effort, but you must find a safe place to make camp before you can tend to their needs.")
                .WithVictoryPoints(10)
                .WithInfo(55, 1, Artist.Romana_Kendelic);
            addLocation("Ruins of Arnor", EncounterSet.RuinsOfArnor, 2, 3)
                .WithTraits("Arnor.", "Ruins.")
                .WithTextLine("Forced: After the \"when revealed\" effect of a treachery card is canceled, raise each player's threat by 2.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack. If this attack destroys a character, the defending player raises his threat by 2.")
                .WithEasyModeQuantity(2)
                .WithInfo(56, 3, Artist.Dimitri_Bielak);
            addLocation("Ancient Causeway", EncounterSet.RuinsOfArnor, 3, 2)
                .WithTraits("Arnor.", "Ruins.")
                .WithTextLine("Forced: When Ancient Causeway is explored, raise each player's threat by 2.")
                .WithFlavorLine("...on either side of it there were lines of large boulders and hewn stones that screened the travellers almost like a hedge. -The Fellowship of the Ring")
                .WithInfo(57, 2, Artist.Trudi_Castle);
            addTreachery("Tragic Discovery", EncounterSet.RuinsOfArnor)
                .WithTextLine("When Revealed: Raise each player's threat by the Threat of the active location.")
                .WithShadow("Shadow: Defending player either raise his threat 3, or this attack is considered undefended.")
                .WithInfo(58, 2, Artist.Dimitri_Bielak);
            addEncounterSideQuest("Search the Ruins", EncounterSet.RuinsOfArnor, 8)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Forced: At the end of the refresh phase, raise each player's threat by 2.")
                .WithTextLine("Response: After Search the Ruins is defeated, reduce each player's threat by 3.")
                .WithFlavorLine("Your enemies lurk somewhere in the decrepit ruins around you: a constant threat until you search them out...")
                .WithVictoryPoints(10)
                .WithInfo(59, 1, Artist.Alexandr_Elichev);
            addEnemy("Dead Lord", EncounterSet.CursedDead, 33, 3, 4, 2, 3)
                .WithTraits("Undead.")
                .WithTextLine("Forced: After Dead Lord engages you, put the topmost Undead enemy in the discard pile into play engaged with you.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack. If this attack destroys a character, reveal 1 encounter card.")
                .WithEasyModeQuantity(1)
                .WithInfo(60, 2, Artist.Florian_Devos);
            addEnemy("Cursed Dead", EncounterSet.CursedDead, 27, 1, 3, 1, 2)
                .WithTraits("Undead.")
                .WithTextLine("When Revealed: Put each copy of Cursed Dead in the discard pile into play in the staging area.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack (+2 Attack instead if there is a copy of the defending character in its owner's discard pile).")
                .WithEasyModeQuantity(4)
                .WithInfo(61, 5, Artist.Helge_C_Balzer);
            addTreachery("Restless Evil", EncounterSet.CursedDead)
                .WithTextLine("When Revealed: Each Undead enemy gets +1 Threat, +1 Attack, and +1 Defense until the end of the round. If there are no Undead enemies in play, Restless Evil gains surge.")
                .WithShadow("Shadow: Each Undead enemy engaged with you gets +1 Attack and +1 Defense until the end of the round.")
                .WithEasyModeQuantity(1)
                .WithInfo(62, 2, Artist.Alvaro_Calvo_Escudero);
            addEncounterSideQuest("Seal the Tomb", EncounterSet.CursedDead, 6)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Forced: At the end of the refresh phase, discard the top 3 cards of the encounter deck. Return the topmost Undead enemy in the encounter discard pile to the staging area.")
                .WithFlavorLine("The undead keep rising from the grave. For each one that you strike down, another takes its place. You must do something to stem the tide...")
                .WithVictoryPoints(10)
                .WithInfo(63, 1, Artist.Guillaume_Ducos);
            addTreachery("Terror of the North", EncounterSet.DarkSorcery)
                .WithTraits("Sorcery.")
                .WithTextLine("When Revealed: Each player discards the top 3 cards of his deck. Until the end of the round, add 2 to the total Threat in the staging area for each different card type discarded this way.")
                .WithShadow("Shadow: Defending player discards the top 3 cards of his deck. Attacking enemy gets +1 Attack for each different card type discarded this way.")
                .WithEasyModeQuantity(2)
                .WithInfo(64, 3, Artist.Alvaro_Calvo_Escudero);
            addTreachery("Dark Sorcery", EncounterSet.DarkSorcery)
                .WithTraits("Sorcery.")
                .WithKeywords("Doomed 2.")
                .WithTextLine("Doomed 2.")
                .WithTextLine("When Revealed: Each player discards each ally he controls that has the same title as a card in his discard pile.")
                .WithEasyModeQuantity(1)
                .WithInfo(65, 2, Artist.Lukasz_Jaskolski);
            addTreachery("Heavy Curse", EncounterSet.DarkSorcery)
                .WithTraits("Sorcery.")
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("When Revealed: Attach to the current quest. (Counts as a Condition attachment with the text: \"When a player plays a card, increase its cost by 1 if there is a card that has the same title in its owner's discard pile.\")")
                .WithFlavorLine("\"Earth, air and water all seem accursed. But so our path is laid.\" -Frodo, The Two Towers")
                .WithEasyModeQuantity(1)
                .WithInfo(66, 3, Artist.Tommy_Arnold);
            addEncounterSideQuest("The Power of Angmar", EncounterSet.DarkSorcery, 8)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Cards in each player's discard pile cannot leave that player's discard pile by player card effect.")
                .WithTextLine("Forced: After this stage is defeated, each player shuffles the top 5 cards of his discard pile back into his deck.")
                .WithFlavorLine("You must uncover the source of this evil that sets its will against yours.")
                .WithVictoryPoints(10)
                .WithInfo(67, 1, Artist.Matt_Stewart);
            addQuest("Stop the War Party", EncounterSet.IntrudersInChetwood, 1, 'A', 30)
                .WithTextLine("Setup: Put Iârion into play. Add 1 ~Orc War Party to the staging area. Each players adds 1 different location to the staging area. Shuffle the encounter deck.")
                .WithFlavorLine("Rangers have sighted a large group of Orcs making its way towards Bree-land. The Dúnedain, Iârion, has asked you to help him intercept the war party before it can reach the quiet village. The Orcs are a day ahead of you and moving fast, but there is hope you can catch them with the Ranger's tracking skill...")
                .WithOppositeTextLine("Enemies do not make engagement checks.")
                .WithOppositeTextLine("Forced: At the end of the refresh phase, raise each player's threat by 1 for each enemy in the staging area.")
                .WithOppositeTextLine("The players cannot defeat this stage unless the first player controls Iârion. If the players defeat this stage, they win the game.")
                .WithOppositeFlavorLine("You must move swiftly to prevent the Orcs from reaching Bree-land!")
                .WithIncludedEncounterSets(EncounterSet.Iarion, EncounterSet.EriadorWilds, EncounterSet.AngmarOrcs)
                .WithInfo(68, 1, Artist.Nicholas_Gregory);
            addQuest("Scattered Among the Hills", EncounterSet.TheWeatherHills, 1, 'A', Card.VALUE_NA)
                .WithTextLine("Setup: Set Orc Ambush and Amon Forn aside, out of play. Create the Orc deck (see insert) and set it next to the quest deck. Make Exposed Ridge the active location. Add Hunting the Orcs and 1 Weather Hilltop to the staging area. Shuffle the encounter deck.")
                .WithFlavorLine("You've pursued the remnants of an Orc war party east from the borders of Bree-land and into the wilderness beyond. Their trail climbs out of the lowlands and into the Weather Hills.")
                .WithOppositeTextLine("The first Weather treachery card revealed each round gains surge.")
                .WithOppositeTextLine("Forced: After the active location is explored, reveal the top card of the Orc deck and resolve it as if it was just revealed from the encounter deck (reveal the top 2 cards instead if there are 3 or more players in the game).")
                .WithOppositeFlavorLine("As you pursue the Orcs, the weather itself turns against you. Now you must contend with the elements while you hunt the enemy.")
                .WithIncludedEncounterSets(EncounterSet.AngmarOrcs, EncounterSet.FoulWeather, EncounterSet.RuinsOfArnor)
                .WithInfo(69, 1, Artist.Juan_Carlos_Barquet);
            addQuest("Cornered Animals", EncounterSet.TheWeatherHills, 2, 'A', 20)
                .WithTextLine("When Revealed: End the current phase. Shuffle the encounter discard pile and the Orc deck into the encounter deck. Reveal Orc Ambush and Amon Forn and add them to the staging area.")
                .WithFlavorLine("You've hunted the Orcs to their secret gathering place on the northern edge of the Weather Hills: the old Dúnedain border fort of Amon Forn. With nowhere left to run, the Orcs turn and fight with desperate savagery.")
                .WithOppositeTextLine("Each damaged character gets -1 Willpower.")
                .WithOppositeTextLine("Forced: At the beginning of the quest phase, either discard 1 resource token from Savage Counter-attack, or reveal an additional encounter card this phase.")
                .WithOppositeTextLine("If the players defeat this stage, they win the game.")
                .WithOppositeFlavorLine("Already weary from days of travel through harsh weather, you are hard pressed to match the Orcs' ferocity. You must rally your men or see them fall!")
                .WithIncludedEncounterSets(EncounterSet.AngmarOrcs, EncounterSet.FoulWeather, EncounterSet.RuinsOfArnor)
                .WithInfo(70, 1, Artist.Anthony_Feliciano);
            addObjective("Hunting the Orcs", EncounterSet.TheWeatherHills)
                .WithTraits("Mission.")
                .WithTextLine("Forced: After an enemy is defeated, place 1 resource token here. Then, if there are at least X resource tokens here, flip Hunting the Orcs and place each resource token that was on it on Savage Counter-attack. X is 3 more than the number of players in the game.")
                .WithInfo(71, 1, Artist.Jason_Ward);
            addObjective("Savage Counter-attack", EncounterSet.TheWeatherHills)
                .WithTraits("Mission.")
                .WithTextLine("Forced: After Savage Counter-attack enters play, advance to stage 2A.")
                .WithTextLine("Forced: After an enemy attacks and destroys a character, discard 1 resource token from Savage Counter-attack.")
                .WithTextLine("If there are no resource tokens here, the players lose the game.")
                .WithInfo(72, 1, Artist.Jon_Bosco);
            addQuest("The Shades of Angmar", EncounterSet.DeadmensDike, 1, 'A', 11)
                .WithTextLine("Setup: Put Iârion into play. Set Thaurdir aside, out of play. Add 1 copy of Fornost square to the staging area. Shuffle the encounter deck.")
                .WithFlavorLine("You've brought the prisoners you rescued from the Weather Hills to Fornost. The Rangers gathered there are shocked to hear what you discovered at Amon Forn. Before their Chieftain can decide what to do, an unnatural fog covers the ruins in darkness, and the spectres of dead warriors emerge from the mists to attack you!")
                .WithOppositeTextLine("When Revealed: Each player must search the encounter deck for a Baleful Shade and put it into play engaged with him. Shuffle the encounter deck and reveal 1 encounter card per player.")
                .WithOppositeTextLine("Forced: At the end of the refresh phase, each player discards the top card of his deck.")
                .WithOppositeTextLine("If a player has no cards in his deck, he is eliminated from the game.")
                .WithIncludedEncounterSets(EncounterSet.Iarion, EncounterSet.DarkSorcery, EncounterSet.CursedDead)
                .WithInfo(73, 1, Artist.Joel_Hustak);
            addQuest("A Fell Wraith", EncounterSet.DeadmensDike, 2, 'A', 13)
                .WithTextLine("When Revealed: Add Thaurdir to the staging area. Then, reveal 1 encounter card per player.")
                .WithFlavorLine("The foul sorcery that drives the ghouls against you attacks your mind as well, and you fight to master your fear in the face of an unrelenting enemy. The question of who works the evil spell is answered by the appearance of a dark figure. The old man you had thought to be the Orcs' prisoner has revealed himself to be a powerful wraith. He must be stopped!")
                .WithOppositeTextLine("Forced: After Thaurdir attacks and destroys a character, that character's controller must either discard the top 3 cards of his deck, or return Thaurdir to the staging area.")
                .WithOppositeTextLine("If a player has no cards in his deck, he is eliminated from the game. The players cannot defeat this stage while Thaurdir has any hit points remaining. If the players defeat this stage, they win the game.")
                .WithIncludedEncounterSets(EncounterSet.Iarion, EncounterSet.DarkSorcery, EncounterSet.CursedDead)
                .WithInfo(74, 1, Artist.Sebastian_Giacobino);
        }
    }
}
