using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HallOfBeorn.Models
{
    public enum CardStat : ushort
    {
        None = 0,
        Threat_Cost_0,
        Threat_Cost_5,
        Threat_Cost_6,
        Threat_Cost_7,
        Threat_Cost_8,
        Threat_Cost_9,
        Threat_Cost_10,
        Threat_Cost_11,
        Threat_Cost_12,
        Threat_Cost_13,
        Threat_Cost_14,
        Resource_Cost_0,
        Resource_Cost_1,
        Resource_Cost_2,
        Resource_Cost_3,
        Resource_Cost_4,
        Resource_Cost_5,
        Resource_Cost_6,
        Resource_Cost_X,
        Resource_Cost_Nil,
        Engagement_Cost_0,
        Engagement_Cost_1,
        Engagement_Cost_4,
        Engagement_Cost_5,
        Engagement_Cost_8,
        Engagement_Cost_10,
        Engagement_Cost_11,
        Engagement_Cost_12,
        Engagement_Cost_13,
        Engagement_Cost_15,
        Engagement_Cost_16,
        Engagement_Cost_17,
        Engagement_Cost_18,
        Engagement_Cost_20,
        Engagement_Cost_21,
        Engagement_Cost_22,
        Engagement_Cost_23,
        Engagement_Cost_24,
        Engagement_Cost_25,
        Engagement_Cost_26,
        Engagement_Cost_27,
        Engagement_Cost_28,
        Engagement_Cost_29,
        Engagement_Cost_30,
        Engagement_Cost_31,
        Engagement_Cost_32,
        Engagement_Cost_33,
        Engagement_Cost_34,
        Engagement_Cost_35,
        Engagement_Cost_36,
        Engagement_Cost_37,
        Engagement_Cost_38,
        Engagement_Cost_39,
        Engagement_Cost_40,
        Engagement_Cost_42,
        Engagement_Cost_43,
        Engagement_Cost_44,
        Engagement_Cost_46,
        Engagement_Cost_48,
        Engagement_Cost_50
    }
}
