using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HallOfBeorn.Models.LotR.Characters
{
    public class FrodoBagginsCharacter : Character
    {
        public FrodoBagginsCharacter()
            : base("Frodo Baggins", "Frodo Baggins", "Hobbit")
        {
            Bio =
@"<blockquote>
&ldquo;And though all the mighty elf-friends of old, Hador, and Húrin, and Túrin, and Beren himself were assembled together, your seat should be among them.&rdquo;
<br>― Elrond to Frodo Baggins
</blockquote>
<p>Frodo Baggins was a hobbit of the Third Age, the most famous of all Hobbits in the histories for his leading role in the Quest of the Ring. During this epic quest, he bore the One Ring to Mount Doom and there destroyed it, giving him renown like no other Halfling throughout Middle-earth. He is also peculiar for being, as a Ring-bearer, one of the three Hobbits who sailed from Middle-earth to Aman, there to die in peace.</p>
<h3>History</h3>
<h4>Childhood and Youth</h4>
<p>Frodo, the child of the respectable Drogo Baggins and Primula Brandybuck, was born on 22 September of S.R. 1368. After his parents died in a boating accident, Frodo went to live in Brandy Hall with his mother’s relatives, the Brandybucks. He grew up under the guardianship of the Master of Buckland Rorimac 'Goldfather' Brandybuck, who was his uncle. Frodo was a bit of a troublesome lad; he was once caught stealing mushrooms from Farmer Maggot, who in return thrashed Frodo and set his three dogs to chase Frodo from Bamfurlong to Bucklebury Ferry.</p>
<p>Frodo stayed in Buckland until his uncle Bilbo adopted him and took him in to live at Bag End, Bilbo's estate in Hobbiton. He enjoyed life with his 'queer' Uncle Bilbo, with whom he shared the same birthday; Bilbo taught him to read, and told him stories of the past, even giving him some instruction in the elvish tongue. It is possible Bilbo even took his young cousin to see the Elves that wandered about outside the Shire. Bilbo made Frodo his heir, frustrating the attempts of the disagreeable Sackville-Bagginses, who coveted the estate of Bag End.</p>
<p>Frodo and Bilbo were comfortable and well off until T.A. 3001. At this time, Bilbo threw an enormous party to celebrate his 111th birthday, and Frodo's 33rd, the date of Frodo's coming of age. At this party Bilbo gave his farewell speech, and made his long planned 'disappearance' and withdrawal from the Shire. Frodo, who had been informed beforehand of the 'joke', as Bilbo called it, was spared the shock that afflicted the other assembled Hobbits. Frodo returned home as the new Master of Bag End, per Bilbo's will. He was greeted there by Gandalf, who informed him that, among other things, Frodo had inherited Bilbo's magic ring.</p>
<h4>Master of Bag End</h4>
<p>Frodo took charge of distributing the presents Bilbo had left for the other hobbits, a long and tiring task. The Baggins' old friend Gandalf the Wizard, who had come for the festivities, warned Frodo not to use the magic ring, and to keep it secret and safe. He then left back into the wide world, curiosity nagging his mind about the ring.</p>
<p>Frodo, meanwhile, was quite well off. He lived in peace and respectability for seventeen years, when Gandalf returned with the dreadful revelation that the 'magic ring' was really the One Ring of Sauron, a thing of evil power thousands of years old. Furthermore, the Dark Lord was now aware of its survival, and would be searching for it, as Gollum had now revealed under torture that it was to be found in the Shire. After a long discussion and a test by fire, the two agreed that Frodo would have to leave the Shire for his own safety and Samwise Gamgee the gardener would go with him. Gandalf recommended Rivendell as a destination, as the road was likely safe and the haven good. He told Frodo to take the alias Underhill abroad. Frodo was reluctant, but bought a house in Crickhollow as an excuse to head east.</p>
<p>Gandalf stayed for two months while Frodo worked out the details. At the end of that time he left to 'get some news', as rather disturbing tidings had come to his ears. He promised to be back for the farewell party. Meanwhile, Frodo was not aware that some of his closest friends were watching him; Fredegar 'Fatty' Bolger, his cousins Peregrin 'Pippin' Took, and Meriadoc 'Merry' Brandybuck, and Sam himself, knew that Frodo and Gandalf were in some trouble concerning the Ring, and that Frodo was preparing for a long adventure.</p>
<p>As autumn passed, Frodo was waiting for Gandalf who did not return, and Frodo grew quite anxious. Merry and Fatty drove the cart of Frodo's belongings ahead, while Frodo still waited for Gandalf. At the last possible day he departed with Pippin and Sam.</p>
<h4>Hobbiton to Crickhollow</h4>
<p>Less than a day into their journeying, Frodo, strangely nervous, requested that the threesome hide upon the approach of a horseman. The rider was dressed in black, upon a black horse, making queer sniffing noises. Frodo felt the urge to put on the Ring and vanish, but just as he was giving in the rider departed at a trot. Samwise then remarked upon the Black Rider that had spoken to his father, Gaffer Gamgee, some time earlier. This made Frodo wish that he had waited for Gandalf.</p>
<p>That night, they were again overtaken by a Black Horseman. This time it seemed to be able to sniff out their hiding place. But as it approached, it was driven away by the song of a group of Elves. Their leader, Gildor, greeted the hobbits warmly, and lauded Frodo for his knowledge of their tongue. Frodo tried to get information from Gildor on the Black Riders, but the elf would tell him very little. Gildor foresaw that Frodo would have many dealings with the Riders in the future, and urged him to flee them whenever he met them. He and his party left the Hobbits before daybreak, while they slept.</p>
<p>The next day the threesome agreed to stay off the road. After a brief scare when Sam sighted a Rider, they worried about losing their way. That evening they heard a terrible wail, and Frodo distinguished words in it. Before long they came to Bamfurlong, the property of Farmer Maggot. Although Pippin knew Maggot, Frodo recalled a scare he had received at a young age after caught stealing the farmer’s mushrooms, being threatened with the dogs. He froze when the dogs came forth from the house, but Maggot's hospitality soon won him over. When Maggot told of a Black Rider who had stopped at his house asking for 'Baggins,' and made several shrewd guesses, Frodo grew uncomfortable. Maggot took them to Bucklebury Ferry in his wagon. There they joined up with Merry. As they were ferried across into Buckland, they caught sight of a dark shape on the landing from which they had come.</p>
<h4>Crickhollow to Bree</h4>
<p>When they reached the house in Crickhollow, the other hobbits reveal their knowledge of the One Ring, and promise to stick with him on the road to Rivendell. The next morning, leaving Fatty to keep house, they plunged into the Old Forest. In time they were driven by the trees down to the Withywindle, where they were ensnared by Old Man Willow. Rescued by Tom Bombadil, the hobbits came to his house. There they met Tom's wife, Goldberry, and Frodo was moved to poetry over her loveliness. He was interested in Bombadil himself, and several times tried to learn who he was. That night he dreamed of a white-haired figure on a pinnacle of stone, borne away by an eagle.</p>
<p>The next day Frodo tried on the Ring, after finding it had no effect on Bombadil. Tom nevertheless could see him, for he was not subjected to the Ring’s power. That night he dreamed once more, a dream he never forgot.</p>
<blockquote>
Frodo heard a sweet singing running in his mind: a song that seemed to come like a pale light behind a grey rain-curtain, and growing stronger to turn the veil all to glass and silver, until at last it was rolled back, and a far green country opened before him under a swift sunrise.
<br>—The Fellowship of the Ring, Fog on the Barrow-downs
</blockquote>
<p>After bidding Goldberry and Tom farewell, the Hobbits went on and passed through the barrow-downs. Getting lost in the mist, however, they were taken by the barrow-wights, Frodo last of all. Frodo woke in the barrow to find the barrow-wight bending over his three friends. He rose and in a tremendous act of bravery and resilience took a sword and smote off the wight's hand. Then he summoned Bombadil with a song taught him, and Bombadil drove the wight away. Bombadil helped him wake Merry, Pippin, and Sam, gave them their ponies, and escorted them all to the road before turning his face back toward Withywindle. The hobbits, meanwhile, entered Bree and took lodging (at Bombadil’s recommendation) at The Prancing Pony inn, Frodo under the name of Underhill, as Gandalf had suggested.</p>
<h4>Strider and Weathertop</h4>
<p>While Merry went out to take a walk in the night air, the other hobbits came down to the common-room and were introduced by the landlord Barliman Butterbur to the gathering, Frodo under his alias. Frodo asked if Gandalf was present in Bree, only to learn that he had not yet arrived. While Pippin and Sam enjoyed the drink and conversation, Frodo remained withdrawn, soon falling into conversation with a curious ranger called Strider, who gave him a warning about letting his friends talk to much. Pippin began to tell about Bilbo's Birthday Party, and Frodo, at Strider’s encouragement and in an attempt to prevent the name of Baggins from being raised, began to sing The Man in the Moon Stayed Up Too Late. This proved popular with the gathering, but unfortunately, as Frodo relaxed, he fell from the table and the Ring slipped on his finger, causing him to vanish.</p>
<p>Frodo crawled over to Strider's corner and slipped off the Ring, and said that he had rolled quickly to the side. The suspicious Breelanders, however, grew angry or frightened, and eventually all left the common-room. Frodo and his comrades retired to their room, where they found Strider waiting to talk to them. Strider was honest and blunt, telling what he had overheard and what he knew of them, as well as warning them of the Black Riders and traitors in Bree. He urged them to accept his aide by inviting him into the company. Frodo was leaning to believe the ranger when Butterbur broke in, giving Frodo the long-awaited letter from Gandalf, undelivered by Butterbur’s forgetfulness. After some little bit of light was shed on the situation to the innkeeper, he swore to help the hobbits in any way he could, as a friend of Gandalf and one very much afraid of Mordor. Frodo, reading the letter, learned that Gandalf recommended Strider as one to whom Frodo could go for help. After some further debate, Frodo agreed to let Strider lead them to Rivendell.</p>
<p>Strider arranged for a deception, by moving them to a different room. The next morning, their ponies were gone and the room was ravaged. Butterbur paid for a replacement pony, and the four hobbits and ranger set out into the Wilds. They passed through Chetwood and Midgewater Marshes, and finally to the Weather Hillsbefore coming up to Weathertop. Black Riders were sighted from the top of the cairn, and Strider counseled to remain where they were. Shortly after the Black Riders came, and Frodo was stricken down. In desperation he put on the Ring and saw the Nazgûl in their true forms. Frodo then tried to attack in Elbereth’s name, but their leader, the Witch-king of Angmar, stabbed Frodo in the shoulder with a Morgul-knife, before being driven away by Strider.</p>
<h4>Weathertop to Rivendell</h4>
<p>Because of a piece of the knife embedded in his shoulder, Frodo started to become ill, so his companions hurried to take him to the House of Elrond. After journeying for 12 days, they were found by Glorfindel, one of the High Elves, who was sent by Elrond to help Frodo after he heard of him from Gildor. Glorfindel, seeing that Frodo was starting to fade, put him upon his horse, Asfaloth, and ordered him to go on when the Ringwraiths approached. Asfaloth outran the steeds of the Nazgul and bore Frodo across the Ford of Bruinen, but Frodo, who was on the brink of becoming a wraith, turned around at the other side and defied the Nine. The Riders, were driven into the River by Glorfindel, Strider and the three hobbits, where they were swept away by the ensuing waters.[3] As a sign that Frodo was shifting to the Wraith-world, he could see the Unseen luminous form of Glorfindel.</p>
<p>Unconscious, Frodo was carried inside Rivendell, where Elrond removed the fragment of the knife from his shoulder. He awoke two days later, mostly recovered, and was delighted to find that Gandalf had arrived. Frodo's recovery was celebrated with a feast during which he met Glóin and asked concerning the Dwarves of Erebor. Afterwards, Elrond led his guests to the Hall of Fire, where Frodo found Bilbo, whom he hadn't seen in 17 years. Bilbo asked to see the Ring and was saddened to see Frodo's negative reaction. The two hobbits then enjoyed talking about Bilbo's works on lore and the Shire.</p>
<h4>The Fellowship of the Ring</h4>
<p>During the Council of Elrond, it was decided that the Ring must be destroyed by casting it into the Cracks of Doom. Frodo volunteered to be the Ring-bearer, and a Fellowship was formed to protect him; the fellowship included Gandalf, Aragorn (Strider's real name), Boromir of Gondor, Legolas of the Woodland Realm, Gimli of Erebor, and Frodo's friends Sam, Merry and Pippin.[2] Before their departure, Bilbo gave Sting to Frodo, and his coat of mithril mail, to protect him on the perilous journey to Mount Doom that lay ahead.</p>
<p>On December 25, the fellowship left Rivendell, and headed south along the west side of the Misty Mountains. They attempted to cross them by the Redhorn gate, but were thwarted by a fierce blizzard [5] and had to go back. After surviving a Warg attack, Gandalf persuaded the company to go through the abandoned Dwarf kingdom of Moria. Just before entering Moria, Frodo was attacked by the Watcher in the Water and barely escaped. During the journey through Moria, Frodo began to suspect that something was tracking them. Later, inside the chamber of Mazarbul, the Fellowship was attacked by Orcs, and Frodo was struck by an Orc spear but was saved by the mithril coat he wore. The company escaped the chamber, and were close to exiting Moria, when Durin's Bane appeared and pursued them to the bridge of Khazad-dûm where Gandalf held him off so the rest of the Fellowship could escape. After breaking the bridge, both he and the Balrog fell and disappeared into the chasm below, after which Aragorn took over as leader.</p>
<p>Eventually they reached Lothlórien, and were housed by the elves at Caras Galadhon. During their rest there, Galadriel allowed Frodo and Sam to look into the Mirror of Galadriel, in which they saw many things. When leaving the Woods, Galadriel gave Frodo a vial with light from the Silmaril of Eärendil.</p>
<p>They travelled down the Anduin river in boats given to them by the elves. On their trip down the river, Frodo confirmed his suspicion that they were being trailed by Gollum. At Amon Hen, the Ring's corrupting power caused Boromir to try to take the Ring from Frodo, who escaped by putting it on. Seeing the corrupting influence of the ring on Boromir, he then decided to leave the Fellowship and go on alone, but he was thwarted in this when Sam discovered him attempting to cross the Nen Hithoel, and insisted on accompanying him.</p>
<h4>Emyn Muil to Ithilien</h4>
<p>The two companions reached Amon Lhaw and toiled through the Emyn Muil. Soon after, they found Gollum following them, and they captured him with the Elven rope.</p>
<p>Frodo decided to trust Gollum to be their guide. He led the Hobbits out of the Emyn Muil and through the Dead Marshes. During their route, they were delayed several times by a Nazgûl flying on a fell beast. The Hobbits reached Carchost, the western Tower of the Teeth, where Frodo had intended to enter Mordor, but Gollum persuaded Frodo to follow him to a safer entrance, the pass of Cirith Ungol. During the next night's march they passed into North Ithilien, and by daylight of March 7 they reached the stream of Henneth Annûn.</p>
<p>Their camp fire attracted the Rangers of Ithilien, and their leader, Faramir (Boromir's brother), considered them spies and questioned Frodo concerning their errand, who recounted the journeys of the Fellowship, but said nothing about the Ring. Faramir informed Frodo of Boromir's death, implying Frodo's involvement. Faramir blindfolded the Hobbits and led them to Henneth Annûn, a secret Gondorian outpost, and questioned them further in private. After a meal, Sam accidentally revealed that Frodo had the Ring, but Faramir denied its lure, and thus gained the trust of the hobbits.</p>
<p>During the night, Faramir called Frodo and Sam to him, and showed them Gollum, who had found his way to Henneth Annûn, and (ignorant of their presence) was hunting for fish. Faramir, suspecting that Frodo had lied about Gollum's involvement in their quest, threatened to kill him for fear that he might reveal the location of their outpost to the enemy. Frodo confessed to the part of Gollum in their errand, and begged Faramir not to slay him. Gollum was caught and questioned and then surrendered to Frodo. The following morning Faramir released the three travellers, warning them strongly against taking the pass of Cirith Ungol.</p>
<h4>Entering Mordor</h4>
<p>After two marches they came to the valley of the Morgulduin and continued east. On 'The Dawnless Day' Gollum lead them east to the Southward Road and reached the Cross-roads just as the sun was setting.[9] They reached just opposite the north-facing gate of Minas Morgul and they saw the Morgul-host march forth.</p>
<p>In that night they ascended the Straight Stair and reached the top of the Winding Stair at dawn of March 11 where they were woken by Gollum. He led the up the to the entrance to Shelob's Lair. Inside the tunnel Gollum betrayed Frodo and Sam to Shelob the spider, who stung Frodo after he left the tunnel. Sam saved Frodo from being eaten by Shelob, but thought him dead and took the Ring from him, resolving to continue the Quest alone. However Frodo (who was still alive) was captured by Orcs and taken to the Tower of Cirith Ungol.</p>
<h4>Cirith Ungol to Mount Doom</h4>
<p>Learning of this, Sam rescued Frodo and on early March 15 the Hobbits escaped and jumped into the ravine west of the Morgai and crossed the valley. The next day they attempted to climb the Morgai, but had to retrace their steps and reached the north end of the valley, and on March 18 they set out on the road that ran to the Isenmouthe. There they were overtaken by an Orc troop and had to follow their trot.</p>
<p>As Sauron's troops moved at night, the hobbits continued their journey in daytime towards Mount Doom. During the morning of March 25 they reached the Crack of Doom where, at the last moment, Frodo, under the influence of the Ring, claimed it as his own. However, at that moment he was attacked by Gollum, who seized the Ring and then fell into the fire with it, thus destroying the Ring.</p>
<h4>Return Home</h4>
<p>Frodo and Sam were rescued by Gwaihir, Landroval and Meneldor and taken to Ithilien. After being healed and having rested for a month, the Ring-bearers were honored on the Field of Cormallen. The following months the Hobbits witnessed the coronation of their companion Aragorn as King Elessar, and were present at his marriage to Arwen that summer. Arwen renounced her immortality and gave to Frodo her place to sail into the West.</p>
<p>Frodo and his company left Minas Tirith on July 19 for Edoras and the funeral of King Théoden, then set out for Helm's Deep and eventually Isengard. They parted there from Legolas, Gimli, and Aragorn.</p>
<p>After overtaking Saruman and Wormtongue, they reached the Mountains of Moria; and when they approached Lothlórien, Celeborn and Galadriel parted from their company. The hobbits, with Gandalf and other Elves, reached Rivendell on September 21, where Frodo met Bilbo once again.</p>
<p>They stayed there until October 5 and eventually visited the Prancing Pony in Bree before reaching the Shire. At the Buckland Gate Gandalf left them to go and have a talk with Tom Bombadil. Once in the Shire, they reached Frogmorton where they were arrested. The next day they reached Bywater where they defeated the ruffians who had overtaken their land. The leader of the ruffians was revealed to be Saruman, and Frodo decided to let him live, even after he had tried to stab him with a knife. But Saruman did not live much longer, for his servant, Wormtongue, killed him himself (before being killed by the hobbits), thus ending the War of the Ring.</p>
<h4>Later Years</h4>
<p>Over the next two years, the travelers reordered the Shire and their lives; but Frodo was still troubled by his wounds. Frodo served as Mayor of Michel Delving until Will Whitfoot was restored. Having no family of his own, Frodo left his estate (Bag End) and passed on the Red Book to Samwise Gamgee, who named his son after Frodo.</p>
<p>On September 21 of T.A. 3021 Frodo set out for the Grey Havens. Going south to Woody End he met the Last Riding of the Keepers, Elrond, Galadriel, and Bilbo. On September 29 they came to the firth of Lhûn where Gandalf awaited them, and on the White Ship they crossed the Straight Road into the West. Frodo would spend the rest of his life in the bliss of Valinor.</p>
<p>Sam followed Frodo across the sea 61 years later, following the death of his wife Rose (née Cotton).</p>
<h4>Description and Equipment</h4>
<p>The only real description of Frodo's appearance is given only once by Gandalf in his letter to Barliman Butterbur, in which he is declared a 'stout fellow with red cheeks, taller than some (hobbits), and fairer than most', with a cleft chin, a bright eye, and a perky personality.[1] Although Frodo is apparently fairly stout before his journey, he seems to have lost a significant amount of weight on his trip from Hobbiton to Rivendell.[4] Also, at a later point, Sam remarks that Frodo is 'Too thin and drawn' for a hobbit.</p>
<p>Frodo carried a small Elven sword (actually a dagger) called Sting and wore a coat of Dwarven chainmail made of mithril under his clothes, both given to him by Bilbo. At Lothlórien, Galadriel gave him an Elven cloak that blended him in with the natural surroundings and a phial carrying the light of the Star of Eärendil to aid him on his quest.</p>
<p>Before Frodo went back to the Shire (after the Quest of the Ring was completed), Arwen Evenstar, wife of Aragorn and daughter of Elrond, gave Frodo a white stone to wear around his neck.</p>
<h4>Etymology and Translations</h4>
<p>The name Frodo Baggins is an English translation of his Westron name Maura Labingi. The name Maura has the element maur- (wise, experienced), which Tolkien equivalated to the Germanic element frod- of the same meaning. Frodo's name in Sindarin was Iorhael ('old-wise') although in some instance he is mentioned as Daur (probably lenited form of taur).</p>
<p>In the German translation he is called Frodo Beutlin, in Spanish, Frodo Bolsón, in French, Frodon Sacquet, in Norwegian, Frodo Lommelun, in Danish, Frodo Sækker, in Faroese, Fróði Pjøkin, in Finnish, Frodo Reppuli, in Swedish, Frodo Secker, in Portuguese Frodo Bolseiro, and in Dutch, Frodo Balings. In one of three Polish translations he is called Frodo Bagosz, but he keeps his original name in the other two.</p>
<h4>Names and Epithets</h4>
<ul>
<li>Frodo Baggins - fród means 'wise by experience' in Old English. Baggins may have been a reference to Bag End or may come from 'bagging' which means 'eating between meals' in northern England.</li>
<li>Ring-bearer - he bore the One Ring to Mount Doom.</li>
<li>Elf-friend - given to him by Gildor Inglorion.</li>
<li>Mr. Underhill - used during his stay in the Prancing Pony to conceal his identity.</li>
<li>The Halfling - a name used for him from Boromir's dream.</li>
<li>Master - given to Frodo by both Samwise Gamgee as Sam was his gardener, and Gollum, as Frodo was the Master of the Precious.</li>
<li>Nine-fingered Frodo\Frodo of the Nine Fingers - given to Frodo after Gollum bit off his finger.</li>
<li>Deputy Mayor of Michel Delving - he was the Deputy from November 3019 through Mid-Year's Day in 3020</li>
<li>Daur - which translates to 'noble' and was given to Frodo at the Field of Cormallen.</li>
<li>Iorhael - the Sindarin name for Frodo which comes from ior meaning 'old' and hael meaning 'wise,'</li>
<li>Maura Labingi - the Hobbit name for Frodo.</li>
<li>Bingo Baggins - Frodo's name in the early drafts of The Lord of the Rings.</li>
<li>Bronwe athan Harthad - a name given to Frodo by Gandalf in an early version of The Lord of the Rings, revealed in The History of Middle-earth. It means 'Endurance beyond Hope'.</li>
</ul>";

            BioSourceUrl = "http://tolkiengateway.net/wiki/Frodo";
            ImageArtist = Artist.Jake_Murray;

            TheFellowshipOfTheRing();
            TheTwoTowers();
            TheReturnOfTheKing();

            Alias("Mr. Underhill", "Mr-Underhill-TBR");
            Alias("The Ring-bearer");

            addFamily("Bilbo Baggins (Cousin)", "Bilbo-Baggins");

            addFriend("Sam Gamgee", "Sam-Gamgee");
            addFriend("Merry", "Merry");
            addFriend("Pippin", "Pippin");
            addFriend("Fatty Bolger", "Fatty-Bolger");
            addFriendCard("Farmer Maggot", "Farmer-Maggot-TBR");
            addFriendCard("Barliman Butterbur", "Barliman-Butterbur-TBR");

            addGroup("The Conspiracy");
            addGroup("The Council of Elrond", "The-Council-of-Elrond");
            addGroup("The Fellowship", "The-Fellowship");

            addItemThing("The One Ring");
            addItem("Sting", "Sting-RD");
            addItem("Mithril Shirt", "Mithril-Shirt-RD");
            addItem("Phial of Galadriel", "Phial-of-Galadriel-RD");

            Card("Frodo-Baggins-CatC");
            Card("Frodo-Baggins-TBR");
            Card("Frodo-Baggins-RD");
            Card("Frodo-Baggins-ToS");
            Card("Frodo-Baggins-TMoF");
        }
    }
}