/* Generated CardSet class: The Grey Havens */

using System;

namespace HallOfBeorn.Models.LotR.Sets.TheGreyHavens
{
    public class TheGreyHavensSet : CardSet
    {
        protected override void Initialize()
        {
            Name = "The Grey Havens";
            Abbreviation = "TGH";
            Number = 35;
            SetType = Models.SetType.Deluxe_Expansion;

            addHero("Círdan the Shipwright", 12, Sphere.Spirit, 4, 2, 2, 4)
                .WithTraits("Noldor.", "Noble.")
                .WithTextLine("Draw 1 additional card at the beginning of the resource phase.")
                .WithTextLine("Forced: After drawing cards at the beginning of the resource phase, choose and discard 1 of those cards.")
                .WithFlavorLine("Very tall he was, and his beard was long, and he was grey and old, save that his eyes were keen as stars...")
                .WithFlavorLine("-The Return of the King")
                .WithInfo(1, 1, Artist.Aleksander_Karcz);
            addHero("Galdor of the Havens", 9, Sphere.Lore, 2, 2, 1, 4)
                .WithTraits("Noldor.")
                .WithTextLine("Response: After drawing your setup hand, instead of taking a mulligan, you may discard any number of cards from your hand. Then, draw that many cards.")
                .WithTextLine("Action: If you have no cards in your hand, draw 6 cards. (Limit once per game.)")
                .WithFlavorLine("\"What power still remains lies with us...\"")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithInfo(2, 1, Artist.Lukasz_Jaskolski);
            addAlly("Mithlond Sea-watcher", 2, Sphere.Tactics, false, 1, 1, 0, 2)
                .WithTraits("Noldor.", "Warrior.")
                .WithTextLine("While the top card of your discard pile is an ally, Mithlond Sea-watcher gets +2 Attack and gains ranged.")
                .WithFlavorLine("But it was an old tradition that away over there stood the Grey Havens, from which at times elven-ships set sail, never to return.")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithInfo(3, 3, Artist.Owen_William_Weber);
            addEvent("Skyward Volley", 2, Sphere.Tactics)
                .WithTextLine("As an additional cost to play Skyward Volley, exhaust a ranged character you control.")
                .WithTextLine("Combat Action: Deal 2 damage to an enemy engaged with a player. Resolve that effect again for each copy of Skyward Volley currently in your discard pile (you may choose different targets).")
                .WithInfo(4, 3, Artist.Christina_Davis);
            addAttachment("Grappling Hook", 1, Sphere.Tactics, false)
                .WithTraits("Item.")
                .WithTextLine("Attach to a character.")
                .WithTextLine("Quest Action: Discard Grappling Hook and exhaust attached character to commit attached character to the quest, using its Attack instead of its Willpower (or instead of its Defense if the current quest has the siege keyword).")
                .WithInfo(5, 3, Artist.Kara_Williams);
            addAlly("Warden of the Havens", 2, Sphere.Leadership, false, 0, 1, 1, 3)
                .WithTraits("Noldor.", "Warrior.")
                .WithTextLine("While the top card of your discard pile is an attachment, Warden of the Havens gets +2 Defense and gains sentinel.")
                .WithFlavorLine("\"...and if he comes, assailing the White Towers and the Havens, hereafter the Elves may have no escape from the lengthening shadows of Middle-earth.\"")
                .WithFlavorLine("-Galdor, The Fellowship of the Ring")
                .WithInfo(6, 3, Artist.Dleoblack);
            addEvent("Anchor Watch", 2, Sphere.Leadership)
                .WithTextLine("Response: After an enemy is declared as an attacker against you, declare an exhausted character you control as the defender. Resolve that effect again for each copy of Anchor Watch currently in your discard pile (all chosen characters are defending against this attack).")
                .WithInfo(7, 3, Artist.Adam_Schumpert);
            addAttachment("Mariner's Compass", 1, Sphere.Leadership, false)
                .WithTraits("Item.")
                .WithTextLine("Attach to a Leadership or a Scout character.")
                .WithTextLine("Response: At the beginning of the travel phase, exhaust Mariner's Compass and attached character to search the top 5 cards of the encounter deck for a location. Switch that location with a location in the staging area. Shuffle the encounter deck.")
                .WithInfo(8, 3, Artist.Lucas_Durham);
            addAlly("Lindon Navigator", 2, Sphere.Lore, false, 2, 1, 1, 2)
                .WithTraits("Noldor.", "Scout.")
                .WithTextLine("Lindon Navigator does not exhaust to commit to a quest, and can commit to quests while exhausted.")
                .WithTextLine("Forced: After resolving a quest to which Lindon Navigator was committed, either discard it from play or discard 1 card from your hand.")
                .WithInfo(9, 3, Artist.Tiziano_Baracchi);
            addEvent("The Evening Star", 2, Sphere.Lore)
                .WithTextLine("Action: Place 2 progress on any location. Resolve that effect again for each copy of The Evening Star currently in your discard pile (you may choose new targets).")
                .WithFlavorLine("...for ever still a herald on")
                .WithFlavorLine("ar errand that should never rest")
                .WithFlavorLine("to bear his shining lamp afar,")
                .WithFlavorLine("the Flammifer of Westernesse.")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithInfo(10, 3, Artist.Katy_Grierson);
            addAttachment("Explorer's Almanac", 0, Sphere.Lore, false)
                .WithTraits("Item.")
                .WithTextLine("Attach to a location in the staging area.")
                .WithTextLine("Progress from questing successfully may be placed on the attached location before it is placed on the current quest.")
                .WithInfo(11, 3, Artist.Ed_Mattinian);
            addAlly("Sailor of Lune", 2, Sphere.Spirit, false, 1, 1, 0, 2)
                .WithTraits("Noldor.", "Scout.")
                .WithTextLine("While the top card of your discard pile is an event, Sailor of Lune gets +1 Willpower and gains: \"Cannot be damaged while committed to the quest.\"")
                .WithFlavorLine("\"They are sailing, sailing, sailing over the Sea, they are going into the West and leaving us,\" said Sam, half chanting the words, shaking his head sadly and solemnly.")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithInfo(12, 3, Artist.Owen_William_Weber);
            addEvent("Elwing's Flight", 2, Sphere.Spirit)
                .WithTextLine("Quest Action: Ready a questing character and give that character +1 Willpower until the end of the phase. Resolve that effect again for each copy of Elwing's Flight currently in your discard pile (you may choose different targets).")
                .WithFlavorLine("There flying Elwing came to him")
                .WithFlavorLine("and flame was in the darkness lit;")
                .WithFlavorLine("more bright than light of diamond")
                .WithFlavorLine("the fire upon her carcanet.")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithInfo(13, 3, Artist.A_M_Sartor);
            addAttachment("To the Sea, to the Sea!", 1, Sphere.Spirit, true)
                .WithTraits("Song.")
                .WithTextLine("Attach to a Noldor character.")
                .WithTextLine("Action: Exhaust To the Sea, to the Sea! and discard X cards from your hand to reduce the cost of the next Noldor ally played this phase by X (to a minimum of 1).")
                .WithFlavorLine("To the Sea, to the Sea! The white gulls are crying,")
                .WithFlavorLine("The wind is blowing, and the white foam is flying.")
                .WithFlavorLine("-The Return of the King")
                .WithInfo(14, 3, Artist.Tawny_Fritzinger);
            addAttachment("Narya", 2, Sphere.Neutral, true)
                .WithTraits("Ring.", "Artifact.")
                .WithTextLine("Attach to Círdan the Shipwright or Gandalf.")
                .WithTextLine("Attached character gains a Leadership resource icon.")
                .WithTextLine("Action: Exhaust Narya and attached character to choose and ready up to 2 allies. Each of those allies gets +1 Attack and +1 Defense until the end of the phase.")
                .WithFlavorLine("\"For this is the Ring of Fire, and with it you may rekindle hearts in a world that grows chill.\"")
                .WithFlavorLine("-Círdan, The Return of the King")
                .WithInfo(15, 3, Artist.Lucas_Durham);
            addQuest("Departure from the Havens", EncounterSet.VoyageAcrossBelegaer, 1, 'A', 8)
                .WithKeywords("Sailing.")
                .WithTextLine("Setup: Prepare the Corsair deck. Players prepare their fleet. Shuffle each stage 2 card in the quest deck so that their order is random, leaving stage 3 on the bottom. Search the encounter deck for 1 copy of Rolling Seas and 1 copy of Scouting Ship, and add them to the staging area. Shuffle the encounter deck.")
                .WithFlavorLine("The Dream-chaser and her fleet depart from the Grey Havens, in search of the island from Calphon's dreams. Only a week out from the coast, the black sails of Corsair can be seen in pursuit!")
                .WithOppositeTextLine("Sailing.")
                .WithOppositeTextLine("While you are on-course, each Ship objective gets +2 Willpower.")
                .WithOppositeTextLine("When this stage is defeated, if you are on course (Sunny), look at the top 2 stages of the quest deck and advance to one of your choice, placing the other on the bottom of the quest deck. Otherwise, advance to the top state of the quest deck.")
                .WithVictoryPoints(3)
                .WithIncludedEncounterSets(EncounterSet.VastOceans, EncounterSet.StormyWeather, EncounterSet.UmbarFleet, EncounterSet.CorsairPirates, EncounterSet.TheDreamChasersFleet)
                .WithInfo(16, 1, Artist.Matt_Stewart);
            addQuest("Into the Storm", EncounterSet.VoyageAcrossBelegaer, 2, 'A', 2)
                .WithTextLine("When Revealed: Search the encounter deck and discard pile for 1 copy of Waterspout and add it to the staging area. Shuffle the encounter deck.")
                .WithFlavorLine("Calphon squints at dark storm clouds on the horizon. \"In my dream, the skies were dark and full of wrath... Perhaps the island lies within that squall?\"")
                .WithFlavorLine("You hesitate. Guiding your ship into a deadly storm is foolish, at best... But what if he’s right?")
                .WithOppositeTextLine("Forced: At the end of the quest phase, if you are off-course (Cloudy, Rainy, Stormy), each player must distribute 5 damage among characters he controls.")
                .WithOppositeTextLine("When this stage is defeated, if you are on course (Sunny), look at the top 2 stages of the quest deck and advance to one of your choice, placing the other on the bottom of the quest deck. Otherwise, advance to the top stage of the quest deck.")
                .WithVictoryPoints(3)
                .WithIncludedEncounterSets(EncounterSet.VastOceans, EncounterSet.StormyWeather, EncounterSet.UmbarFleet, EncounterSet.CorsairPirates, EncounterSet.TheDreamChasersFleet)
                .WithInfo(17, 1, Artist.Nicholas_Gregory);
            addQuest("Cursed Mists", EncounterSet.VoyageAcrossBelegaer, 2, 'A', 6)
                .WithKeywords("Sailing.")
                .WithTextLine("When Revealed: Search the encounter deck and discard pile for 1 copy of Fog Bank and add it to the staging area. Shuffle the encounter deck.")
                .WithFlavorLine("After days of aimless travel at sea, a dark mist settles along the ocean's surface, obscuring your visibility and frightening your ships’ crew. \"Wait,\" Calphon says, \"this happened in my dream, too... I think if we find a way through this mist, we shall be one step closer to the island.\"")
                .WithOppositeTextLine("Sailing.")
                .WithOppositeTextLine("While you are off-course (Cloudy, Rainy, or Stormy), each non-Ship ally gets –2 Willpower.")
                .WithOppositeTextLine("When this stage is defeated, if you are on-course (Sunny), look at the top 2 stages of the quest deck and advance to one of your choice, placing the other on the bottom of the quest deck. Otherwise, advance to the top stage of the quest deck.")
                .WithVictoryPoints(3)
                .WithIncludedEncounterSets(EncounterSet.VastOceans, EncounterSet.StormyWeather, EncounterSet.UmbarFleet, EncounterSet.CorsairPirates, EncounterSet.TheDreamChasersFleet)
                .WithInfo(18, 1, Artist.Yoann_Boissonnet);
            addQuest("Calphon's Divination", EncounterSet.VoyageAcrossBelegaer, 2, 'A', 4)
                .WithKeywords("Sailing.")
                .WithTextLine("When Revealed: Search the encounter deck and discard pile for 1 copy of Scouting Ship and add it to the staging area. Shuffle the encounter deck.")
                .WithFlavorLine("Calphon bursts into one of the heroes’ quarters in the middle of the night, sweating profusely and breathing heavily. “I saw it again!” he cries. “It was the same island as before, only the sun was rising behind it, bathing the sky in orange. It must be to the east!” You can change course to follow Calphon’s vision, but you risk being discovered by the Corsairs chasing you...")
                .WithOppositeTextLine("Sailing.")
                .WithOppositeTextLine("While you are off-course (Cloudy, Rainy, or Stormy), each Ship enemy gains Boarding 1.")
                .WithOppositeTextLine("When this stage is defeated, if you are on-course (Sunny), look at the top 2 stages of the quest deck and advance to one of your choice, placing the other on the bottom of the quest deck. Otherwise, advance to the top stage of the quest deck.")
                .WithVictoryPoints(3)
                .WithIncludedEncounterSets(EncounterSet.VastOceans, EncounterSet.StormyWeather, EncounterSet.UmbarFleet, EncounterSet.CorsairPirates, EncounterSet.TheDreamChasersFleet)
                .WithInfo(19, 1, Artist.Juan_Carlos_Barquet);
            addQuest("The Star's Guidance", EncounterSet.VoyageAcrossBelegaer, 2, 'A', 4)
                .WithKeywords("Sailing.")
                .WithTextLine("When Revealed: Search the encounter deck and discard pile for 1 copy of Starlit Sea and add it to the staging area. Shuffle the encounter deck.")
                .WithFlavorLine("Calphon recognizes a bright star in the night sky, pointing to it. \"There! That star! I remember that star from my vision. I believe we must follow that star if we are to reach the island.\" Calphon’s guidance has led you this far. But none of your maps or almanacs make any mention of this bright star...")
                .WithOppositeTextLine("Sailing.")
                .WithOppositeTextLine("While you are off-course (Cloudy, Rainy, or Stormy), each Ocean location gets +1 Threat.")
                .WithOppositeTextLine("When this stage is defeated, if you are on-course, look at the top 2 stages of the quest deck and advance to one of your choice, placing the other on the bottom of the quest deck. Otherwise, advance to the top stage of the quest deck.")
                .WithVictoryPoints(3)
                .WithIncludedEncounterSets(EncounterSet.VastOceans, EncounterSet.StormyWeather, EncounterSet.UmbarFleet, EncounterSet.CorsairPirates, EncounterSet.TheDreamChasersFleet)
                .WithInfo(20, 1, Artist.Nate_Abell);
            addQuest("Corsair Pursuit", EncounterSet.VoyageAcrossBelegaer, 3, 'A', 10)
                .WithKeywords("Sailing.")
                .WithTextLine("When Revealed: Search the encounter deck or discard pile for the Ship enemy with the highest Threat and add it to the staging area (the 2 Ship enemies with the highest Threat instead if there are 3 or more players in the game). Shuffle the encounter deck.")
                .WithFlavorLine("Calphon insists you are very close to finding the island, but Corsairs still shadow your fleet. You must either fight them or outpace them before you can reach the island and weigh anchor.")
                .WithOppositeTextLine("Sailing.")
                .WithOppositeTextLine("You cannot place progress on Corsair Pursuit unless you are on-course (Sunny).")
                .WithOppositeTextLine("If there are no Ship enemies in play, you have defeated your pursuers, and win the game.")
                .WithOppositeTextLine("If this stage has 10 or more progress on it, you have lost your pursuers, and win the game.")
                .WithIncludedEncounterSets(EncounterSet.VastOceans, EncounterSet.StormyWeather, EncounterSet.UmbarFleet, EncounterSet.CorsairPirates, EncounterSet.TheDreamChasersFleet)
                .WithInfo(21, 1, Artist.Nicholas_Gregory);
            addShipEnemy("Scouting Ship", EncounterSet.VoyageAcrossBelegaer, 35, 2, 5, 2, 7)
                .WithTraits("Corsair.", "Ship.")
                .WithKeywords("Boarding 1.")
                .WithTextLine("Boarding 1.")
                .WithTextLine("Cannot have attachments. Scouting Ship gets -15 engagement cost while you are off course (Cloudy, Rainy, or Stormy).")
                .WithFlavorLine("All too well they could see for themselves the black sails.")
                .WithFlavorLine("-The Return of the King")
                .WithInfo(22, 3, Artist.Michael_Rasmussen);
            addLocation("Starlit Sea", EncounterSet.VoyageAcrossBelegaer, 3, 2)
                .WithTraits("Ocean.")
                .WithTextLine("While you are off-course (Cloudy, Rainy, or Stormy), Starlit Sea gains: \"Travel: Raise each player’s threat by 3.\"")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack (+2 Attack instead if you are off-course).")
                .WithInfo(23, 2, Artist.Mateusz_Ozminski);
            addLocation("Fog Bank", EncounterSet.VoyageAcrossBelegaer, 2, 5)
                .WithTraits("Ocean.")
                .WithTextLine("While Fog Bank is the active location, Ship enemies do not make engagement checks, cannot attack, and cannot be attacked.")
                .WithShadow("Shadow: If your heading is at the worst setting (Stormy), attacking enemy makes an additional attack after this one.")
                .WithInfo(24, 2, Artist.Alyn_Spiller);
            addQuest("Explore the Island", EncounterSet.TheFateOfNumenor, 1, 'A', 20)
                .WithTextLine("Setup: Set Shrine to Morgoth aside, out of play. Prepare the Uncharted deck. Add 2 copies of Lost Island from the top of the Uncharted deck to the staging area (3 copies instead if there are 3 or 4 players in the game). The first player takes control of Calphon. Shuffle the encounter deck.")
                .WithFlavorLine("You arrive on the island’s western beach, the edge of a dense jungle looming beyond. With no map to guide you and no idea of what to expect, you venture forward, deeper into the island...")
                .WithOppositeTextLine("Progress cannot be placed on Explore the Island except by quest effects.")
                .WithOppositeTextLine("Forced: After a location is explored, add progress to Explore the Island equal to that location’s printed quest points.")
                .WithOppositeTextLine("Forced: When an Uncharted location becomes the active location, add 1 copy of Lost Island from the top of the Uncharted deck to the staging area.")
                .WithIncludedEncounterSets(EncounterSet.DrownedDead, EncounterSet.RuinsOfNumenor)
                .WithInfo(25, 1, Artist.Jon_Bosco);
            addQuest("A Fateful Discovery", EncounterSet.TheFateOfNumenor, 2, 'A', Card.VALUE_NA)
                .WithTextLine("When Revealed: Add 2 copies of Lost Island from the top of the Uncharted deck to the staging area. Add Shrine to Morgoth to the staging area, Lost Island side faceup. Remove all progress from each Uncharted location in the staging area and shuffle them so that the players do not know which one is which.")
                .WithFlavorLine("Markings on Adûnaic suggest the existence of a grand shrine somewhere on the island. Perhaps there, you will find answers.")
                .WithOppositeTextLine("Forced: After a location is explored, if it would be shuffled into the Uncharted deck, add it to the victory display instead.")
                .WithOppositeTextLine("The players cannot defeat this stage unless Shrine to Morgoth is in the victory display. When Shrine to Morgoth is added to the victory display, the players win the game.")
                .WithOppositeFlavorLine("You search for the shrine, unsure of its exact location...")
                .WithIncludedEncounterSets(EncounterSet.DrownedDead, EncounterSet.RuinsOfNumenor)
                .WithInfo(26, 1, Artist.Jon_Bosco);
            addLocation("Shrine to Morgoth", EncounterSet.TheFateOfNumenor, 5, 8)
                .WithUnique()
                .WithOppositeTitle("Lost Island")
                .WithSlugSuffix("Lost Island")
                .WithTraits("Ruins.")
                .WithKeywords("Uncharted.")
                .WithTextLine("While Shrine to Morgoth is the active location, players cannot draw cards or search their decks.")
                .WithTextLine("Forced: After Shrine to Morgoth is flipped over while active, exhaust each ally in play with printed cost 2 or less. Then, each player must search the encounter deck and discard pile for an Undead enemy and put it into play engaged with him. Shuffle the encounter deck.")
                .WithOppositeTextLine("Uncharted.")
                .WithOppositeTextLine("Cannot have player card attachments.")
                .WithOppositeTextLine("Forced: After Lost Island becomes the active location, flip it over.")
                .WithOppositeTextLine("Action: Remove 4 progress from Lost Island to look at its facedown side.")
                .WithInfo(27, 1, Artist.Jokubas_Uoginitas);
            addObjectiveAlly("Calphon", EncounterSet.TheFateOfNumenor, 1, 0, 1, 3)
                .WithUnique()
                .WithTraits("Gondor.", "Noble.")
                .WithTextLine("The first player gains control of Calphon.")
                .WithTextLine("Action: Exhaust Calphon to look at the bottom card of your deck. Then, you may switch that card with a card in your hand.")
                .WithTextLine("If Calphon leaves play, the players lose the game.")
                .WithInfo(28, 1, Artist.Ilich_Henriquez);
            addEnemy("Servant of the Deceiver", EncounterSet.TheFateOfNumenor, 35, 3, 3, 4, 3)
                .WithTraits("Undead.")
                .WithTextLine("Forced: When Servant of the Deceiver engages you, look at the top card of your deck. If its printed cost is 2 or less, place it on the bottom of your deck and Servant of the Deceiver gets +2 Attack until the end of the round.")
                .WithEasyModeQuantity(2)
                .WithInfo(29, 3, Artist.Florian_Devos);
            addLocation("Lush Jungle", EncounterSet.TheFateOfNumenor, 4, 4)
                .WithOppositeTitle("Lost Island")
                .WithSlugSuffix("Lost Island")
                .WithTraits("Forest.")
                .WithKeywords("Uncharted.")
                .WithTextLine("While Lush Jungle is in the staging area, characters get –1 Attack and lose ranged.")
                .WithTextLine("Forced: After Lush Jungle is flipped over while active, return it to the staging area unless each player exhausts each ready hero he controls.")
                .WithOppositeTextLine("Uncharted.")
                .WithOppositeTextLine("Cannot have player card attachments.")
                .WithOppositeTextLine("Forced: After Lost Island becomes the active location, flip it over.")
                .WithOppositeTextLine("Action: Remove 4 progress from Lost Island to look at its facedown side.")
                .WithInfo(30, 2, Artist.Katy_Grierson);
            addLocation("Forbidden Coast", EncounterSet.TheFateOfNumenor, 1, 6)
                .WithOppositeTitle("Lost Island")
                .WithSlugSuffix("Lost Island")
                .WithTraits("Coastland.")
                .WithKeywords("Uncharted.")
                .WithTextLine("Forced: After Forbidden Coast is flipped over while active, each player may draw a card. Then, each player chooses a card from his hand and places it on the bottom of his deck.")
                .WithOppositeTextLine("Uncharted.")
                .WithOppositeTextLine("Cannot have player card attachments.")
                .WithOppositeTextLine("Forced: After Lost Island becomes the active location, flip it over.")
                .WithOppositeTextLine("Action: Remove 4 progress from Lost Island to look at its facedown side.")
                .WithInfo(31, 2, Artist.Lukasz_Jaskolski);
            addLocation("Steep Plateau", EncounterSet.TheFateOfNumenor, 1, 3)
                .WithTraits("Coastland.")
                .WithTextLine("Response: After Steep Plateau is explored, peek at the facedown side of an Uncharted location in the staging area.")
                .WithShadow("Shadow: Discard the bottom card of the defending player’s deck. If that card’s printed cost is 2 or less, attacking enemy gets +2 Attack.")
                .WithInfo(32, 3, Artist.Florian_Devos);
            addTreachery("Mysterious Fog", EncounterSet.TheFateOfNumenor)
                .WithTextLine("When Revealed: Either each player must exhaust a character he controls, or each Lost Island in the staging area gets +1 Threat until the end of the phase.")
                .WithShadow("Shadow: Discard the bottom card of your deck. If that card’s printed cost is 2 or less, exhaust a character you control.")
                .WithInfo(33, 2, Artist.Yoann_Boissonnet);
            addTreachery("Lingering Malevolence", EncounterSet.TheFateOfNumenor)
                .WithTextLine("When Revealed: The first player discards the bottom card of his deck. Then, he discards each card in his hand with a printed cost higher than that of the discarded card.")
                .WithShadow("Shadow: Discard the bottom card of the defending player’s deck. If that card’s printed cost is 2 or less, attacking enemy gets +2 Attack.")
                .WithEasyModeQuantity(1)
                .WithInfo(34, 2, Artist.Preston_Stone);
            addTreachery("Ruins of Ages Past", EncounterSet.TheFateOfNumenor)
                .WithKeywords("Doomed 2.")
                .WithTextLine("Doomed 2.")
                .WithTextLine("When Revealed: Add 1 copy of Lost Island from the top of the Uncharted deck to the staging area. Then, remove all progress from each Uncharted location in the staging area and shuffle them so that the players do not know which one is which.")
                .WithEasyModeQuantity(1)
                .WithInfo(35, 2, Artist.Alyn_Spiller);
            addQuest("The Corsairs' Assault", EncounterSet.RaidOnTheGreyHavens, 1, 'A', 18)
                .WithTextLine("Setup: Set Captain Sahír and Na'asiyah aside, out of play. Add The Havens Burn, The Dream-chaser, and 1 copy of Sahír’s Ravager to the staging area. Shuffle the encounter deck and discard cards from the top of the encounter deck until X locations with the Aflame keyword are discarded, where X is the number of players in the game. Add each discarded Aflame location to the staging area. Then, shuffle the encounter discard pile back into the encounter deck.")
                .WithOppositeTextLine("Forced: At the end of the combat phase, deal X damage to the Aflame location in play with the lowest Aflame value. X is the number of Corsair enemies in play.")
                .WithOppositeFlavorLine("Corsairs are attacking the Grey Havens and burning the Elven fleet. You must defend the Havens from these fierce raiders and save as many ships as you can!")
                .WithIncludedEncounterSets(EncounterSet.CorsairRaiders, EncounterSet.TheStormcallerElite)
                .WithInfo(36, 1, Artist.Simon_Dominic);
            addQuest("Sahír's Advance", EncounterSet.RaidOnTheGreyHavens, 2, 'A', Card.VALUE_NA)
                .WithTextLine("When Revealed: Add Na’asiyah and Captain Sahír to the staging area, enemy side faceup. Each player reveals the top card of the encounter deck. Place resources on Na’asiyah and Captain Sahír equal to the amount of damage on The Dream-chaser. Add 1 resource to each other Raider enemy in play.")
                .WithFlavorLine("A menacing ship leads the raiders, its charismatic captain bellowing orders to the Corsairs: \"Kill the defenders!\" he shouts. \"Destroy their ships!\"")
                .WithOppositeTextLine("Any time players would place progress on this quest, remove an equal amount of damage from locations in play instead. (Progress is placed on the active location before triggering this effect.)")
                .WithOppositeTextLine("Each Raider enemy revealed by the encounter deck enters play with 1 resource on it.")
                .WithOppositeTextLine("If Captain Sahír is in the victory display and each location in play has no damage, the players win the game.")
                .WithIncludedEncounterSets(EncounterSet.CorsairRaiders, EncounterSet.TheStormcallerElite)
                .WithInfo(37, 1, Artist.Sara_Winters);
            addObjective("The Havens Burn", EncounterSet.RaidOnTheGreyHavens)
                .WithTextLine("Forced: When a card is placed underneath The Havens Burn, reveal the top card of the encounter deck.")
                .WithTextLine("If there are X or more cards underneath The Havens Burn, the Corsairs have destroyed the Elven fleet and the players lose the game. X is 3 more than the number of players in the game.")
                .WithInfo(38, 1, Artist.Nate_Abell);
            addLocation("Dream-chaser", EncounterSet.RaidOnTheGreyHavens, 2, Card.VALUE_NA)
                .WithUnique()
                .WithSlugSuffix("Location")
                .WithTraits("Grey Havens.", "Ship.")
                .WithKeywords("Aflame 12.")
                .WithTextLine("Aflame 12. Immune to player card effects.")
                .WithTextLine("The players cannot travel to the Dream-chaser.")
                .WithTextLine("When the Dream-chaser is placed underneath The Havens Burn, the players lose the game.")
                .WithInfo(39, 1, Artist.Lukasz_Jaskolski);
            addEnemy("Corsair Arsonist", EncounterSet.RaidOnTheGreyHavens, 28, 2, 2, 1, 3)
                .WithTraits("Corsair.")
                .WithTextLine("When Revealed: Either deal 2 damage to an Aflame location in play, or search the encounter deck and discard pile for an Aflame location with the highest Aflame X value, and add it to the staging area.")
                .WithInfo(40, 3, Artist.Leanna_Teneycke);
            addEnemy("Sahír's Ravager", EncounterSet.RaidOnTheGreyHavens, 36, 3, 4, 3, 5)
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("Forced: After Sahír’s Ravager attacks, place 1 resource on it. Then, deal X damage to the Aflame location in play with the lowest Aflame value, where X is the number of resources on Sahír's Ravager.")
                .WithEasyModeQuantity(1)
                .WithInfo(41, 3, Artist.Sara_Winters);
            addLocation("Mithlond Harbor", EncounterSet.RaidOnTheGreyHavens, 1, 2)
                .WithTraits("Grey Havens.")
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("While Mithlond Harbor is in the staging area, progress cannot be placed on locations in the staging area.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack for each damage token on the active location.")
                .WithEasyModeQuantity(1)
                .WithInfo(42, 2, Artist.Matt_Stewart);
            addLocation("Burning Piers", EncounterSet.RaidOnTheGreyHavens, 1, 3)
                .WithTraits("Grey Havens.")
                .WithKeywords("Aflame 5.")
                .WithTextLine("Aflame 5.")
                .WithTextLine("Burning Piers gets +1 Threat for each damage on it.")
                .WithTextLine("Forced: When Burning Piers is placed underneath The Havens Burn, deal 3 damage to The Dream-chaser.")
                .WithShadow("Shadow: Add Burning Piers to the staging area.")
                .WithInfo(43, 2, Artist.Lukasz_Jaskolski);
            addLocation("Pillaged Ship", EncounterSet.RaidOnTheGreyHavens, 2, 4)
                .WithTraits("Grey Havens.", "Ship.")
                .WithKeywords("Aflame 5.")
                .WithTextLine("Aflame 5.")
                .WithTextLine("When Revealed: Either deal 3 damage to Pillaged Ship, or add the topmost enemy in the encounter discard pile to the staging area.")
                .WithShadow("Shadow: If attacking enemy is a Raider, move all resources from defending character to attacking enemy.")
                .WithInfo(44, 2, Artist.Simon_Dominic);
            addLocation("White Ship", EncounterSet.RaidOnTheGreyHavens, 4, 6)
                .WithTraits("Grey Havens.", "Ship.")
                .WithKeywords("Aflame 4.")
                .WithTextLine("Aflame 4.")
                .WithTextLine("Travel: Search the encounter deck and discard pile for a Corsair enemy and add it to the staging area. Shuffle the encounter deck.")
                .WithTextLine("Forced: When White Ship is placed underneath The Havens Burn, place 1 resource on each Raider enemy in play.")
                .WithEasyModeQuantity(1)
                .WithInfo(45, 2, Artist.Katy_Grierson);
            addLocation("Elven Wave-runner", EncounterSet.RaidOnTheGreyHavens, 3, 3)
                .WithTraits("Grey Havens.", "Ship.")
                .WithKeywords("Aflame 3.")
                .WithTextLine("Aflame 3.")
                .WithTextLine("Response: After Elven Wave-runner is added to the victory display, each player draws 1 card.")
                .WithShadow("Shadow: If attacking enemy is a Raider, discard a card at random from your hand and place 1 resource on attacking enemy.")
                .WithVictoryPoints(3)
                .WithInfo(46, 2, Artist.Katy_Grierson);
            addLocation("Elven Caravel", EncounterSet.RaidOnTheGreyHavens, 3, 5)
                .WithTraits("Grey Havens.", "Ship.")
                .WithKeywords("Aflame 4.")
                .WithTextLine("Aflame 4.")
                .WithTextLine("Travel: Each player must assign damage among characters he controls equal to the amount of damage on Elven Caravel.")
                .WithTextLine("Forced: When Elven Caravel is placed underneath The Havens Burn, deal 1 damage to each character in play.")
                .WithEasyModeQuantity(1)
                .WithInfo(47, 2, Artist.Nate_Abell);
            addTreachery("Put to the Torch", EncounterSet.RaidOnTheGreyHavens)
                .WithTextLine("When Revealed: Each player must either deal 3 damage to a character he controls, or to an Aflame location in play.")
                .WithShadow("Shadow: If the active location has the Aflame keyword, either deal it 3 damage or deal the defending character 1 damage.")
                .WithInfo(48, 2, Artist.Michael_Rasmussen);
            addTreachery("The Fires Spread", EncounterSet.RaidOnTheGreyHavens)
                .WithKeywords("Doomed 2.")
                .WithTextLine("Doomed 2.")
                .WithTextLine("When Revealed: Deal 1 damage to each Aflame location in play. If less than 3 total damage is dealt by this effect, The Fires Spread gains surge.")
                .WithShadow("Shadow: If this attack destroys a character, deal 1 damage to each Aflame location in play.")
                .WithInfo(49, 2, Artist.Michael_Rasmussen);
            addLocation("Calm Waters", EncounterSet.VastOceans, 1, 4)
                .WithTraits("Ocean.")
                .WithTextLine("While Calm Waters is the active location, look at 2 additional cards from the top of the encounter deck during each Sailing test.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack (+3 Attack instead if attacking enemy is a Ship Enemy).")
                .WithInfo(50, 2, Artist.Lukasz_Jaskolski);
            addLocation("Rolling Seas", EncounterSet.VastOceans, 4, 3)
                .WithTraits("Ocean.")
                .WithTextLine("Travel: Shift your heading off-course to travel here.")
                .WithTextLine("Shadow: If this attack deals damage to a Ship objective, shift your heading off-course.")
                .WithFlavorLine("The winds of wrath came driving him, and blindly in the foam he fled… —The Fellowship of the Ring")
                .WithEasyModeQuantity(1)
                .WithInfo(51, 3, Artist.Carlos_Palma_Cruchaga);
            addTreachery("Thrown Off Course", EncounterSet.VastOceans)
                .WithTextLine("When Revealed: Either remove all progress from the current quest and raise each player’s threat by 4, or shift your heading off-course.")
                .WithShadow("Shadow: If this attack destroys a character, shift your heading off-course.")
                .WithInfo(52, 2, Artist.Nicholas_Gregory);
            addLocation("Rough Waters", EncounterSet.StormyWeather, 2, 3)
                .WithTraits("Ocean.")
                .WithTextLine("While Rough Waters is in the staging area, cancel the first Sailing Success symbol found during each Sailing test.")
                .WithShadow("Shadow: If you are off-course (Cloudy, Rainy, or Stormy), attacking enemy gets +2 Attack.")
                .WithInfo(53, 2, Artist.Carlos_Palma_Cruchaga);
            addLocation("Waterspout", EncounterSet.StormyWeather, 2, 4)
                .WithTraits("Ocean.")
                .WithTextLine("While your heading is at the worst setting (Stormy), when faced with the option to travel, the players must travel to Waterspout, if able.")
                .WithTextLine("Forced: After traveling to Waterspout, deal 4 damage to each Ship objective.")
                .WithEasyModeQuantity(1)
                .WithInfo(54, 2, Artist.Jokubas_Uoginitas);
            addTreachery("Sudden Storms", EncounterSet.StormyWeather)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: Either shift your heading off-course or deal 1 damage to each exhausted character.")
                .WithShadow("Shadow: Excess damage from this attack is dealt to a Ship objective you control.")
                .WithEasyModeQuantity(2)
                .WithInfo(55, 3, Artist.Simon_Dominic);
            addTreachery("Winds of Wrath", EncounterSet.StormyWeather)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: If you are off-course, deal 1 damage to each character in play. If your heading is at the worst setting (Stormy), this effect cannot be canceled.")
                .WithShadow("Shadow: Either shift your heading off-course or treat this attack as undefended.")
                .WithEasyModeQuantity(1)
                .WithInfo(56, 2, Artist.Nate_Abell);
            addShipEnemy("Light Cruiser", EncounterSet.UmbarFleet, 37, 4, 6, 5, 7)
                .WithTraits("Corsair.", "Ship.")
                .WithKeywords("Boarding 2.")
                .WithTextLine("Boarding 2. Cannot have attachments.")
                .WithTextLine("Each Raider enemy revealed from the Corsair deck by Light Cruiser’s boarding keyword enters play with 1 resource on it.")
                .WithFlavorLine("And looking thither they cried in dismay; for black against the glittering stream they beheld a fleet borne up on the wind… —The Return of the King")
                .WithInfo(57, 2, Artist.Michael_Rasmussen);
            addShipEnemy("Corsair Warship", EncounterSet.UmbarFleet, 44, 3, 8, 4, 9)
                .WithTraits("Corsair.", "Ship.")
                .WithKeywords("Boarding 3.")
                .WithTextLine("Boarding 3. Cannot have attachments.")
                .WithTextLine("While Corsair Warship is in the staging area, it cannot be damaged and gains archery 4.")
                .WithFlavorLine("...ships of great draught with many oars, and with black sails bellying in the breeze. —The Return of the King")
                .WithEasyModeQuantity(0)
                .WithInfo(58, 2, Artist.Michael_Rasmussen);
            addTreachery("Boarding Party", EncounterSet.UmbarFleet)
                .WithTextLine("When Revealed: Each player reveals the top card of the Corsair deck and puts it into play, engaged with him.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack (+2 Attack instead if you control an exhausted Ship objective).")
                .WithEasyModeQuantity(1)
                .WithInfo(59, 2, Artist.Darek_Zabrocki);
            addEnemy("Southron Sailor", EncounterSet.CorsairPirates, 28, 0, 2, 1, 4)
                .WithTraits("Corsair.")
                .WithTextLine("While Southron Sailor is engaged with you, each Ship enemy engaged with you contributes its Threat to the total Threat in the staging area.")
                .WithFlavorLine("\"There is a great fleet drawing near to the mouths of Anduin, manned by the corsairs of Umbar in the South.\" —Beregond, The Return of the King")
                .WithInfo(60, 2, Artist.Leanna_Teneycke);
            addEnemy("Cunning Pirate", EncounterSet.CorsairPirates, 36, 1, 2, 2, 4)
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("Cunning Pirate gets +1 Attack and +1 Defense for each resource on it.")
                .WithTextLine("Forced: When Cunning Pirate engages you, discard an attachment you control and place resources on Cunning Pirate equal to that attachment's printed cost.")
                .WithInfo(61, 3, Artist.Adam_Lane);
            addEnemy("Vicious Marauder", EncounterSet.CorsairPirates, 12, 2, 3, 3, 3)
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("Forced: When Vicious Marauder engages you, discard a random card from your hand and place resources on it equal to that card’s printed cost.")
                .WithTextLine("Forced: When Vicious Marauder attacks you, distribute damage among characters you control equal to the number of resources on it.")
                .WithInfo(62, 2, Artist.Nate_Abell);
            addEnemy("Umbar Captain", EncounterSet.CorsairPirates, 40, 4, 5, 3, 5)
                .WithTraits("Corsair.")
                .WithTextLine("While you are engaged with Umbar Captain, characters you control cannot attack Ship enemies.")
                .WithFlavorLine("...the strength of the rebels in Umbar was a great peril to Gondor... —The Return of the King")
                .WithEasyModeQuantity(0)
                .WithInfo(63, 2, Artist.David_Kegg);
            addEnemy("Umbar Raider", EncounterSet.CorsairRaiders, 24, 2, 3, 2, 4)
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("Umbar Raider gets +1 Attack for each resource on it.")
                .WithTextLine("Forced: After Umbar Raider attacks you, move 1 resource from one of your heroes’ resource pools to Umbar Raider.")
                .WithFlavorLine("\"And there men of Lamedon contested the fords with fell folk of Umbar and Harad who had sailed up the river.\" —Legolas, The Return of the King")
                .WithInfo(64, 3, Artist.David_Kegg);
            addEnemy("Corsair Infiltrator", EncounterSet.CorsairRaiders, 16, 2, 3, 3, 2)
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("Forced: When Corsair Infiltrator attacks, deal it 1 additional shadow card for each resource on it.")
                .WithTextLine("Forced: After the engaged player collects resources at the beginning of the resource phase, that player moves 1 resource from one of his heroes' pools to Corsair Infiltrator.")
                .WithInfo(65, 2, Artist.Adam_Lane);
            addEnemy("Raid Leader", EncounterSet.CorsairRaiders, 40, 3, 5, 1, 5)
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("Raid Leader gets +1 Defense for each resource on it.")
                .WithTextLine("Forced: When Raid Leader engages you, move 1 resource from each of your heroes' resource pools to Raid Leader.")
                .WithFlavorLine("\"The Corsairs are upon us! It is the last stroke of doom!\" —Men of Gondor, The Return of the King")
                .WithEasyModeQuantity(0)
                .WithInfo(66, 2, Artist.Michael_Rasmussen);
            addTreachery("Battle-Hardened", EncounterSet.CorsairRaiders)
                .WithTextLine("When Revealed: Place 1 resource on each Raider enemy in play. Each engaged non-Ship enemy makes an immediate attack. If there are no engaged non-Ship enemies, Battle-Hardened gains surge.")
                .WithShadow("Shadow: If the attacking enemy is a Raider, place 2 resources on it.")
                .WithEasyModeQuantity(0)
                .WithInfo(67, 2, Artist.Emile_Denis);
            addEnemy("Drowned Dead", EncounterSet.DrownedDead, 32, 2, 4, 3, 3)
                .WithTraits("Undead.")
                .WithTextLine("Forced: When Drowned Dead attacks and destroys an ally by an attack, place that ally on the bottom of your deck.")
                .WithShadow("Shadow: If this attack destroys an ally, place that ally on the bottom of your deck.")
                .WithInfo(68, 3, Artist.Chris_Grun);
            addEnemy("Soulless Cadaver", EncounterSet.DrownedDead, 38, 3, 3, 2, 4)
                .WithTraits("Undead.")
                .WithTextLine("While you are engaged with Soulless Cadaver, your deck cannot be searched.")
                .WithTextLine("Forced: When Soulless Cadaver engages you, place each card in your hand with printed cost 2 or less on the bottom of your deck.")
                .WithEasyModeQuantity(1)
                .WithInfo(69, 2, Artist.Helge_C_Balzer);
            addEnemy("Throngs of Unfaithful", EncounterSet.DrownedDead, 26, 1, 2, 0, 4)
                .WithTraits("Undead.")
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Forced: When Throngs of Unfaithful is defeated, discard the bottom card of the engaged player's deck. If that card’s printed cost is 2 or less, return Throngs of the Unfaithful to the top of the encounter deck.")
                .WithEasyModeQuantity(1)
                .WithInfo(70, 2, Artist.Helge_C_Balzer);
            addTreachery("Curse of the Downfallen", EncounterSet.DrownedDead)
                .WithTextLine("When Revealed: Deal 1 damage to each ally with printed cost 2 or less. Place each ally that is destroyed by this effect on the bottom of its owner's deck.")
                .WithShadow("Shadow: Discard the bottom card of your deck. If that card's printed cost is 2 or less, attacking enemy makes an additional attack after this one.")
                .WithEasyModeQuantity(0)
                .WithInfo(71, 2, Artist.Piya_Wannachaiwong);
            addLocation("Flooded Ruins", EncounterSet.RuinsOfNumenor, 3, 5)
                .WithOppositeTitle("Lost Island")
                .WithSlugSuffix("Lost Island")
                .WithTraits("Ruins.")
                .WithKeywords("Uncharted.")
                .WithTextLine("While Flooded Ruins is the active location, it contributes its Threat to the staging area.")
                .WithFlavorLine("Númenor was thrown down and swallowed in the sea... –The Return of the King")
                .WithOppositeTextLine("Uncharted.")
                .WithOppositeTextLine("Cannot have player card attachments.")
                .WithOppositeTextLine("Forced: After Lost Island becomes the active location, flip it over.")
                .WithOppositeTextLine("Action: Remove 4 progress from Lost Island to look at its facedown side.")
                .WithInfo(72, 2, Artist.Juan_Carlos_Barquet);
            addLocation("Drowned Graves", EncounterSet.RuinsOfNumenor, 2, 2)
                .WithOppositeTitle("Lost Island")
                .WithSlugSuffix("Lost Island")
                .WithTraits("Ruins.")
                .WithKeywords("Uncharted.")
                .WithTextLine("Forced: After Drowned Graves is flipped to this side while active, discard the top X cards of the encounter deck. Each player adds an Undead enemy discarded from this effect to the staging area. X is 2 more than the number of players in the game.")
                .WithFlavorLine("...their years lessened as their fear of death grew, and their joy departed. –The Return of the King")
                .WithOppositeTextLine("Uncharted.")
                .WithOppositeTextLine("Cannot have player card attachments.")
                .WithOppositeTextLine("Forced: After Lost Island becomes the active location, flip it over.")
                .WithOppositeTextLine("Action: Remove 4 progress from Lost Island to look at its facedown side.")
                .WithInfo(73, 2, Artist.Juan_Carlos_Barquet);
            addLocation("Cursed Temple", EncounterSet.RuinsOfNumenor, 1, 3)
                .WithOppositeTitle("Lost Island")
                .WithSlugSuffix("Lost Island")
                .WithTraits("Ruins.")
                .WithKeywords("Uncharted.")
                .WithTextLine("While Cursed Temple is the active location, characters with less than 2 Willpower do not ready during the refresh phase.")
                .WithFlavorLine("It was not long before he had bewitched the King and was master of his counsel... –The Return of the King")
                .WithOppositeTextLine("Uncharted.")
                .WithOppositeTextLine("Cannot have player card attachments.")
                .WithOppositeTextLine("Forced: After Lost Island becomes the active location, flip it over.")
                .WithOppositeTextLine("Action: Remove 4 progress from Lost Island to look at its facedown side.")
                .WithInfo(74, 2, Artist.Davis_Engel);
            addTreachery("Aimless Wandering", EncounterSet.RuinsOfNumenor)
                .WithTextLine("When Revealed: The players, as a group, must remove characters with a total of at least X Willpower from the quest. X is the number of Uncharted locations in the staging area. The first player may give Aimless Wandering doomed 2 to look at the facedown side of an Uncharted location in the staging area.")
                .WithInfo(75, 3, Artist.David_Ogilvie);
            addEnemy("Captain Sahír", EncounterSet.TheStormcallerElite, 4, 6, 6, 2, 5)
                .WithUnique()
                .WithSlugSuffix("Enemy")
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("Captain Sahír engages the first player.")
                .WithTextLine("For each point of damage Captain Sahír would take, discard 1 resource from him and cancel that damage.")
                .WithTextLine("Forced: After Captain Sahír attacks, place 2 resource tokens on him (4 instead if his attack destroyed a character).")
                .WithVictoryPoints(6)
                .WithInfo(76, 1, Artist.Sara_Winters);
            addObjectiveAlly("Captain Sahír", EncounterSet.TheStormcallerElite, 0, 0, 2, 5)
                .WithUnique()
                .WithSlugSuffix("Objective-Ally")
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("The first player gains control of Captain Sahír.")
                .WithTextLine("Captain Sahír gets +1 Willpower and +1 Attack for each resource on him (max +6).")
                .WithTextLine("Action: Spend 1 resource from a hero you control to place 1 resource on Captain Sahír. (Limit once per round).")
                .WithTextLine("If Captain Sahír leaves play, the players lose.")
                .WithInfo(77, 1, Artist.Sara_Winters);
            addEnemy("Na'asiyah", EncounterSet.TheStormcallerElite, 8, 1, 2, 2, 4)
                .WithUnique()
                .WithSlugSuffix("Enemy")
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("Na’asiyah engages the last player.")
                .WithTextLine("Forced: When Na’asiyah engages you, discard each event in your hand. Add 1 resource to Na’asiyah for each event discarded in this way.")
                .WithTextLine("Forced: When Na’asiyah attacks or defends, she gets +1 Attack and +1 Defense for this attack for each resource on her. After this attack, discard 1 resource from her.")
                .WithInfo(78, 1, Artist.Ilich_Henriquez);
            addObjectiveAlly("Na'asiyah", EncounterSet.TheStormcallerElite, 1, 2, 2, 4)
                .WithUnique()
                .WithSlugSuffix("Objective-Ally")
                .WithTraits("Corsair.", "Raider.")
                .WithTextLine("The last player gains controls of Na'asiyah.")
                .WithTextLine("Action: While Na'asiyah is attacking or defending, spend 1 resource from her to give her +2 Attack or +2 Defense for this attack.")
                .WithTextLine("Action: Spend 1 resource from a hero you control to place 1 resource on Na'asiyah. (Limit once per round).")
                .WithTextLine("If Na'asiyah leaves play, the players lose.")
                .WithInfo(79, 1, Artist.Ilich_Henriquez);
            addShipObjective("Dream-chaser", EncounterSet.TheDreamChasersFleet, true, 5, 4, 4, 18)
                .WithSlugSuffix("Ship-Objective")
                .WithTraits("Grey Havens.", "Ship.")
                .WithKeywords("Sentinel.")
                .WithTextLine("Immune to player card effects. Sentinel.")
                .WithTextLine("The Dream-chaser can always be committed to sailing tests (even if you are not the first player), and counts as 2 characters when committed to a Sailing test.")
                .WithTextLine("If the Dream-chaser is destroyed, the players lose the game.")
                .WithInfo(80, 1, Artist.Nele_Klumpe);
            addShipObjective("Dawn Star", EncounterSet.TheDreamChasersFleet, true, 3, 3, 4, 16)
                .WithTraits("Gondor.", "Ship.")
                .WithKeywords("Sentinel.")
                .WithTextLine("Immune to player card effects. Sentinel.")
                .WithTextLine("Raise your starting threat by 3.")
                .WithTextLine("Draw 1 additional card during the resource phase.")
                .WithTextLine("If the Dawn Star is destroyed, its controller is eliminated from the game.")
                .WithInfo(81, 1, Artist.Titus_Lunter);
            addShipObjective("Nárelenya", EncounterSet.TheDreamChasersFleet, true, 3, 3, 5, 15)
                .WithTraits("Grey Havens.", "Ship.")
                .WithKeywords("Sentinel.")
                .WithTextLine("Immune to player card effects. Sentinel.")
                .WithTextLine("Reduce the cost of the first ally you play each round by 1.")
                .WithTextLine("If the Nárelenya is destroyed, its controller is eliminated from the game.")
                .WithInfo(82, 1, Artist.Nele_Klumpe);
            addShipObjective("Silver Wing", EncounterSet.TheDreamChasersFleet, true, 2, 4, 2, 14)
                .WithTraits("Gondor.", "Ship.")
                .WithKeywords("Sentinel.", "Ranged.")
                .WithTextLine("Immune to player card effects. Sentinel. Ranged.")
                .WithTextLine("Reduce your starting threat by 3.")
                .WithTextLine("Each hero you control gets +1 Attack.")
                .WithTextLine("If the Silver Wing is destroyed, its controller is eliminated from the game.")
                .WithInfo(83, 1, Artist.Nele_Klumpe);
            addObjective("Navigation", EncounterSet.TheDreamChasersFleet)
                .WithTextLine("Sunny, Cloudy, Rainy, Stormy")
                .WithInfo(84, 1, Artist.Unknown);
        }
    }
}
