/* Generated CardSet class: The Sands of Harad */

using System;

namespace HallOfBeorn.Models.LotR.Sets.TheSandsOfHarad
{
    public class TheSandsOfHaradSet : CardSet
    {
        protected override void Initialize()
        {
            Name = "The Sands of Harad";
            Abbreviation = "TSoH";
            Number = 42;
            SetType = Models.SetType.Deluxe_Expansion;

            addHero("Gimli", 11, Sphere.Leadership, 2, 2, 2, 5)
                .WithTraits("Dwarf.", "Noble.", "Warrior.")
                .WithKeywords("Sentinel.")
                .WithTextLine("Sentinel.")
                .WithTextLine("Response: After Gimli is declared as a defender, spend 1 resource from his pool to ready another hero. If that hero is Legolas, he gets +1 Attack until the end of the phase. (Limit once per phase.)")
                .WithFlavorLine("\"Faithless is he that says farewell when the road darkens...\"")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithTemplate("<p class='main-text'>{keyword:Sentinel.}</p><p class='main-text'><b>Response:</b> After {self} is declared as a defender, spend 1 resource from his pool to ready another hero. If that hero is {title:Legolas}, he gets +1 {Attack} until the end of the phase. (Limit once per phase.)</p><p class='flavor-text'>&ldquo;Faithless is he that says farewell when the road darkens...&rdquo;<br>&ndash;The Fellowship of the Ring</p>")
                .WithCommunityVersion("Autumn/Gimli-Leadership-Hero")
                .WithInfo(1, 1, Artist.Owen_William_Weber);
            addHero("Legolas", 9, Sphere.Spirit, 1, 3, 1, 4)
                .WithTraits("Silvan.", "Noble.", "Scout.")
                .WithKeywords("Ranged.")
                .WithTextLine("Ranged.")
                .WithTextLine("Response: After Legolas commits to a quest, discard a card from your hand to ready another hero. If that hero is Gimli, he gets +1 Willpower until the end of the phase. (Limit once per phase.)")
                .WithFlavorLine("\"I go to find the Sun!\"")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithTemplate("<p class='main-text'>{keyword:Ranged.}</p><p class='main-text'><b>Response:</b> After {self} commits to a quest, discard a card from your hand to ready another hero. If that hero is {title:Gimli}, he gets +1 {Willpower} until the end of the phase. (Limit once per phase.)</p><p class='flavor-text'>&ldquo;I go to find the Sun!&rdquo;<br>&ndash;The Fellowship of the Ring</p>")
                .WithCommunityVersion("Autumn/Legolas-Spirit-Hero")
                .WithInfo(2, 1, Artist.Aleksander_Karcz);
            addAlly("Greenwood Archer", 2, Sphere.Leadership, false, 0, 2, 0, 1)
                .WithTraits("Silvan.")
                .WithKeywords("Ranged.")
                .WithTextLine("Ranged.")
                .WithTextLine("Response: After Greenwood Archer enters play, ready a hero.")
                .WithFlavorLine("They dwelt most often by the edges of the woods, from which they could escape at times to hunt...")
                .WithFlavorLine("-The Hobbit")
                .WithTemplate("<p class='main-text'>{keyword:Ranged.}</p><p class='main-text'><b>Response:</b> After {self} enters play, ready a hero.</p><p class='flavor-text'>They dwelt most often by the edges of the woods, from which they could escape at times to hunt...<br>&ndash;The Hobbit</p>")
                .WithInfo(3, 3, Artist.Tawny_Fritzinger);
            addAlly("Erebor Guard", 4, Sphere.Spirit, false, 0, 1, 2, 3)
                .WithTraits("Dwarf.", "Warrior.")
                .WithKeywords("Sentinel.")
                .WithTextLine("Sentinel.")
                .WithTextLine("Response: When you play Erebor Guard from your hand, discard the top 2 cards of your deck to reduce its cost by 2.")
                .WithFlavorLine("...the fortress of the dwarves could not be taken by surprise.")
                .WithFlavorLine("-The Hobbit")
                .WithTemplate("<p class='main-text'>{keyword:Sentinel.}</p><p class='main-text'><b>Response:</b> When you play {self} from your hand, discard the top 2 cards of your deck to reduce its cost by 2.</p><p class='flavor-text'>...the fortress of the dwarves could not be taken by surprise. &ndash;The Hobbit</p>")
                .WithInfo(4, 3, Artist.Marius_Bota);
            addAlly("Halfling Bounder", 2, Sphere.Lore, false, 1, 1, 0, 2)
                .WithTraits("Hobbit.")
                .WithTextLine("While there is a side quest in the victory display, Halfling Bounder gains: \"Response: Discard Halfling Bounder to cancel the 'when revealed' effects of an encounter card that was just revealed from the encounter deck.\"")
                .WithFlavorLine("\"The Bounders have never been so busy before.\"")
                .WithFlavorLine("-Sam Gamgee, The Fellowship of the Ring")
                .WithInfo(5, 3, Artist.Aleksander_Karcz);
            addAlly("Vigilant Dúnadan", 4, Sphere.Tactics, false, 1, 3, 2, 3)
                .WithTraits("Dúnedain.", "Ranger.")
                .WithTextLine("While there is a side quest in the victory display, Vigilant Dúnadan does not exhaust to defend.")
                .WithFlavorLine("\"I don't think we've rightly understood till now what they did for us.\"")
                .WithFlavorLine("-Barliman Butterbur, The Return of the King")
                .WithInfo(6, 3, Artist.JB_Casacop);
            addEvent("Unlikely Friendship", 0, Sphere.Leadership)
                .WithTextLine("Play only if you control a unique character with the Silvan trait and another unique character with the Dwarf trait.")
                .WithTextLine("Action: Draw 1 card and add 1 resource to the resource pool of a hero you control.")
                .WithFlavorLine("...folk that saw them pass marvelled to see such companions...")
                .WithFlavorLine("-The Return of the King")
                .WithInfo(7, 3, Artist.Aleksander_Karcz);
            addEvent("Well Warned", 0, Sphere.Spirit)
                .WithTextLine("Play only if you control a unique character with the Noble trait and another unique character with the Scout trait.")
                .WithTextLine("Response: After a player engages an enemy, reduce his threat by X, where X is that enemy's printed Threat.")
                .WithFlavorLine("...the Captains of the West were well warned by their scouts...")
                .WithFlavorLine("-The Return of the King")
                .WithInfo(8, 3, Artist.Ashley_Lange);
            addEvent("Dour-handed", 1, Sphere.Tactics)
                .WithTextLine("Action: Deal X damage to an enemy engaged with you. X is the number of side quests in the victory display.")
                .WithFlavorLine("...the tides of fate had turned against them and their doom was at hand. -The Return of the King")
                .WithInfo(9, 3, Artist.JB_Casacop);
            addAttachment("Dwarven Shield", 2, Sphere.Leadership, false)
                .WithTraits("Item.", "Armor.")
                .WithKeywords("Restricted.")
                .WithTextLine("Attach to a Dwarf hero. Restricted.")
                .WithTextLine("Attached hero gets +1 Defense.")
                .WithTextLine("Response: After attached hero takes damage from an enemy attack, exhaust Dwarven Shield to add 1 resource to attached hero's pool.")
                .WithFlavorLine("...each of them had also a short broad sword at his side and a round shield slung at his back.")
                .WithFlavorLine("-The Hobbit")
                .WithTemplate("<p class='main-text'>Attach to a {trait:Dwarf.@Dwarf} hero. {keyword:Restricted.}</p><p class='main-text'>Attached hero gets +1 {Defense}.</p><p class='main-text'><b>Response:</b> After attached hero takes damage from an enemy attack, exhaust {self} to add 1 resource to attached hero's pool.</p><p class='flavor-text'>...each of them had also a short broad sword at his side and a round shield slung at his back.<br>&ndash;The Hobbit</p>")
                .WithInfo(10, 3, Artist.Mariusz_Gandzel);
            addAttachment("Mirkwood Long-knife", 2, Sphere.Spirit, false)
                .WithTraits("Item.", "Weapon.")
                .WithKeywords("Restricted.")
                .WithTextLine("Attach to a Silvan hero. Restricted.")
                .WithTextLine("Attached hero gets +1 Willpower and +1 Attack.")
                .WithFlavorLine("Legolas had a bow and a quiver, and at his belt a long white knife.")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithTemplate("<p class='main-text'>Attach to a {trait:Silvan.@Silvan} hero. {keyword:Restricted.}</p><p class='main-text'>Attached hero gets +1 {Willpower} and +1 {Attack}.</p><p class='flavor-text'>Legolas had a bow and a quiver, and at his belt a long white knife.<br>&ndash;The Fellowship of the Ring</p>")
                .WithInfo(11, 3, Artist.Alexandr_Elichev);
            addAttachment("The Road Goes Ever On", 0, Sphere.Lore, false)
                .WithTraits("Song.")
                .WithTextLine("Attach to a quest card in play.")
                .WithTextLine("Response: When attached quest is defeated, the first player chooses a player. That player searches his deck for a side quest, adds it to his hand, and shuffles his deck.")
                .WithFlavorLine("\"Now far ahead the Road has gone,")
                .WithFlavorLine("And I must follow, if I can...\"")
                .WithFlavorLine("-Frodo Baggins, The Fellowship of the Ring")
                .WithInfo(12, 3, Artist.Jason_Jenicke);
            addPlayerSideQuest("The Storm Comes", 0, Sphere.Neutral, 5)
                .WithTextLine("Limit 1 copy of The Storm Comes in the victory display.")
                .WithTextLine("While this quest is in the victory display, the first ally played by each player each round does not require a resource match.")
                .WithFlavorLine("\"For behold! The storm comes, and now all friends should gather together, lest each singly be destroyed.\"")
                .WithFlavorLine("-Gandalf, The Two Towers")
                .WithVictoryPoints(1)
                .WithInfo(13, 3, Artist.Tomasz_Jedruszek);
            addObjective("\"Seize Them!\"", EncounterSet.EscapeFromUmbar)
                .WithTextLine("Forced: After an enemy attacks and destroys a character, remove X progress from the main quest, X is the attacking enemy's Threat.")
                .WithTextLine("At the end of the round, if the main quest has been in play the entire round and there are no progress tokens on it, the players lose the game.")
                .WithInfo(14, 1, Artist.Victor_Manuel_Leza_Moreno);
            addEnemy("Umbar Sentry", EncounterSet.EscapeFromUmbar, 28, 1, 2, 1, 3)
                .WithTraits("Harad.")
                .WithKeywords("Surge.", "Archery 1.")
                .WithTextLine("Surge. Archery 1.")
                .WithTextLine("Forced: When ~Umbar Sentry attacks, either remove 1 progress token from the main quest, or it gets +2 Attack for this attack.")
                .WithFlavorLine("Umbar remained at war with Gondor for many lives of men...")
                .WithFlavorLine("-The Return of the King")
                .WithEasyModeQuantity(4)
                .WithInfo(15, 5, Artist.Victor_Manuel_Leza_Moreno);
            addLocation("Narrow Alleyway", EncounterSet.EscapeFromUmbar, 2, 2)
                .WithTraits("City.")
                .WithTextLine("Response: After the player travel here, choose a non-unique enemy engaged with a player and place it faceup under this location. While an enemy is under this location, that enemy is considered to be out of play.")
                .WithTextLine("Forced: After Narrow Alleyway leaves play, put each enemy under it into play, engaged with the first player.")
                .WithInfo(16, 2, Artist.Pavel_Kolomeyets);
            addLocation("Umbar Street", EncounterSet.EscapeFromUmbar, 3, 3)
                .WithTraits("City.")
                .WithTextLine("While Street of Umbar is the active location, each enemy gets -1 engagement cost for each progress token on the main quest.")
                .WithShadow("Shadow: Discard an attachment you control.")
                .WithEasyModeQuantity(1)
                .WithInfo(17, 2, Artist.Pavel_Kolomeyets);
            addLocation("Umbar Square", EncounterSet.EscapeFromUmbar, 2, 3)
                .WithTraits("City.")
                .WithTextLine("While Umbar Square is the active location, it gains: \"Response: After an enemy is defeated, place 1 progress on the main quest, bypassing the active location.\"")
                .WithTextLine("Travel: Reveal the top card of the encounter deck to travel here.")
                .WithFlavorLine("The loss of Umbar was grievous to Gondor...")
                .WithFlavorLine("-The Return of the King")
                .WithInfo(18, 3, Artist.Mariusz_Gandzel);
            addLocation("Port of Harad", EncounterSet.EscapeFromUmbar, Card.VALUE_X, 4)
                .WithTraits("City.")
                .WithTextLine("X is the number of engaged enemies.")
                .WithTextLine("Travel: Assign X damage among characters in play to travel here.")
                .WithFlavorLine("Often those on who suspicion fell had fled to Umbar and there joined the rebels...")
                .WithFlavorLine("-The Return of the King")
                .WithInfo(19, 2, Artist.Mariusz_Gandzel);
            addLocation("Haradrim Estate", EncounterSet.EscapeFromUmbar, 3, 1)
                .WithTraits("City.")
                .WithTextLine("While Haradrim Estate is in the staging area, progress cannot be placed here.")
                .WithTextLine("Travel: Search the encounter deck and discard pile for a Harad enemy and put it into play engaged with the first player. Then, place 1 progress on the main quest, bypassing the active location. Shuffle the encounter deck.")
                .WithInfo(20, 2, Artist.Pavel_Kolomeyets);
            addTreachery("Enemy Pursuit", EncounterSet.EscapeFromUmbar)
                .WithTextLine("When Revealed: Either remove all progress from the main quest, or assign X damage among characters in play. X is the number of progress tokens on the main quest.")
                .WithShadow("Shadow: Attacking enemy makes an additional attack against you after this one.")
                .WithEasyModeQuantity(1)
                .WithInfo(21, 2, Artist.Will_OBrien);
            addTreachery("Mirage", EncounterSet.DesertCrossing)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: Discard a the active location. Shuffle the encounter discard pile into the encounter deck and discard cards from the top until a location is discarded. Make that location the active location.")
                .WithInfo(22, 2, Artist.Kamila_Szutenberg);
            addEncounterSideQuest("Seek Shade", EncounterSet.DesertCrossing, 6)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Forced: At the end of the round, remove X progress from the main quest. X is the tens digit of the temperature.")
                .WithTextLine("Response: When Seek Shade is defeated, reduce the temperature by 10.")
                .WithFlavorLine("You must find a cool place to rest, out of the sun’s burning gaze...")
                .WithVictoryPoints(10)
                .WithInfo(23, 1, Artist.Victor_Garcia);
            addEnemy("Carrion Bird", EncounterSet.DesertCrossing, 40, 2, 2, 1, 3)
                .WithTraits("Creature.")
                .WithTextLine("Carrior Birds gets -1 engagement cost for each damaged character in play.")
                .WithTextLine("Forced: After Carrion Bird engages you, discard a damaged character you control.")
                .WithEasyModeQuantity(1)
                .WithInfo(24, 2, Artist.Dimitri_Bielak);
            addLocation("Burnt Sands", EncounterSet.DesertCrossing, 2, 3)
                .WithTraits("Desert.")
                .WithTextLine("While the temperature is 40 or higher, Burnt Sands gets +2 Threat.")
                .WithTextLine("Forced: After Burnt Sands becomes the active location, increase the temperature by 2.")
                .WithFlavorLine("...all seemed ruinous and dead, a desert burned and choked. -The Return of the King")
                .WithInfo(25, 4, Artist.Katy_Grierson);
            addLocation("Scorched Hamada", EncounterSet.DesertCrossing, Card.VALUE_X, 4)
                .WithTraits("Desert.")
                .WithTextLine("X is the tens digit of the temperature.")
                .WithTextLine("Forced: After Scorched Hamada becomes the active location, assign X damage among characters in play.")
                .WithShadow("Shadow: Raise your threat by X, where X is the tens digit of the temperature.")
                .WithEasyModeQuantity(1)
                .WithInfo(26, 2, Artist.Pavel_Kolomeyets);
            addLocation("Parched Wadi", EncounterSet.DesertCrossing, 3, 3)
                .WithTraits("Desert.")
                .WithTextLine("While Parched Wadi is in the staging area, each Creature enemy gets +1 Threat and +1 Attack.")
                .WithTextLine("Forced: After Parched Wadi becomes the active location, shuffle the encounter discard pile into the encounter deck and discard cards from the top until a Creature enemy is discarded. Add that enemy to the staging area.")
                .WithInfo(27, 2, Artist.Katy_Grierson);
            addEnemy("Were-worm", EncounterSet.DesertCrossing, 22, Card.VALUE_X, Card.VALUE_X, Card.VALUE_X, 5)
                .WithTraits("Creature.")
                .WithTextLine("X is the tens digit of the temperature.")
                .WithTextLine("Forced: After Were-worm engages you, it makes an immediate attack. (Do not deal it a shadow card.)")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack (+2 Attack instead if the temperature is 40 or higher).")
                .WithInfo(28, 4, Artist.Dmitry_Prosvirnin);
            addTreachery("Unbearable Heat", EncounterSet.DesertCrossing)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: Each player assigns X damage among characters he controls, where X is the tens digit of the temperature.")
                .WithShadow("Shadow: Attacking enemy gets +X Attack, where X is the tens digit of the temperature.")
                .WithEasyModeQuantity(1)
                .WithInfo(29, 2, Artist.Kim_Sokol);
            addTreachery("Scorching Sun", EncounterSet.DesertCrossing)
                .WithTraits("Weather.")
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("When Revealed: Increase the temperature by 4.")
                .WithShadow("Shadow: Either raise the temperature by 2, or return attacking enemy to the staging area after this attack.")
                .WithEasyModeQuantity(1)
                .WithInfo(30, 2, Artist.Dimitri_Bielak);
            addObjectiveHero("Kahliel", EncounterSet.TheLongArmOfMordor, 2, 2, 2, 3)
                .WithTraits("Harad.", "Noble.")
                .WithTextLine("Response: At the beginning of the planning phase, add 1 resource to a hero's pool.")
                .WithTextLine("If Kahliel leaves play, you are eliminated from the game.")
                .WithTemplate("<p class='main-text'><b>Response:</b> At the beginning of the planning phase, add 1 resource to a hero's pool.<br><br><b>If {self} leaves play, you are eliminated from the game.</b></p>")
                .WithInfo(31, 1, Artist.David_A_Nash);
            addObjectiveHero("Firyal", EncounterSet.TheLongArmOfMordor, 3, 1, 2, 3)
                .WithTraits("Harad.", "Scout.")
                .WithTextLine("Response: After Firyal commits to a quest, look at the top of the encounter deck. Then, you may discard that card.")
                .WithTextLine("If Firyal leaves play, you are eliminated from the game.")
                .WithInfo(32, 1, Artist.Tawny_Fritzinger);
            addObjectiveHero("Yazan", EncounterSet.TheLongArmOfMordor, 2, 3, 1, 3)
                .WithTraits("Harad.", "Ranger.")
                .WithKeywords("Ranged.")
                .WithTextLine("Ranged.")
                .WithTextLine("Response: After Yazan is declared as an attacker, deal 1 damage to a non-unique enemy in play. (Limit once per phase.)")
                .WithTextLine("If Yazan leaves play, you are eliminated from the game.")
                .WithInfo(33, 1, Artist.David_A_Nash);
            addObjectiveHero("Jubayr", EncounterSet.TheLongArmOfMordor, 1, 2, 3, 3)
                .WithTraits("Harad.", "Warrior.")
                .WithKeywords("Sentinel.")
                .WithTextLine("Sentinel.")
                .WithTextLine("Response: After Jubayr is declared as a defender, discard 1 facedown shadow card from a non-unique enemy. (Limit once per phase.)")
                .WithTextLine("If Jubayr leaves play, you are eliminated from the game.")
                .WithInfo(34, 1, Artist.Colin_Boyer);
            addEnemy("Sauron's Enforcers", EncounterSet.TheLongArmOfMordor, 30, Card.VALUE_X, Card.VALUE_X, Card.VALUE_X, 3)
                .WithTraits("Orc.", "Uruk.")
                .WithTextLine("X is the stage number on the main quest.")
                .WithTextLine("Forced: At the end of the round, assign X damage among characters in play.")
                .WithFlavorLine("Fierce and shrill rose the yells of the Orcs...")
                .WithFlavorLine("-The Fellowship of the Ring")
                .WithInfo(35, 4, Artist.Ken_McCuen);
            addLocation("Southron Boma", EncounterSet.TheLongArmOfMordor, Card.VALUE_X, 4)
                .WithTraits("Forest.", "Village.")
                .WithTextLine("X is the stage number of the main quest.")
                .WithTextLine("Travel: Each player spends 1 resource to travel here.")
                .WithShadow("Shadow: If the defending character is an objective-hero, ready it and cancel all damage from this attack.")
                .WithInfo(36, 2, Artist.Pavel_Kolomeyets);
            addLocation("Village Hut", EncounterSet.TheLongArmOfMordor, 2, 2)
                .WithTraits("Forest.", "Village.")
                .WithTextLine("Response: After the players travel to Village Hut, the first player discards the top card of his deck. If that card is an ally, he puts it into play under his control, exhausted.")
                .WithTextLine("Travel: Discard the top card of the encounter deck. If that card is an enemy, add it to the staging area.")
                .WithInfo(37, 2, Artist.Mariusz_Gandzel);
            addTreachery("Savage Attack", EncounterSet.TheLongArmOfMordor)
                .WithTextLine("When Revealed: Each player must choose: either discard the highest cost ally you control, or reveal an encounter card.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack. If this attack destroys a character, reveal the top card of the encounter deck.")
                .WithEasyModeQuantity(1)
                .WithInfo(38, 2, Artist.Dimitri_Bielak);
            addTreachery("Overrun by Orcs", EncounterSet.TheLongArmOfMordor)
                .WithTextLine("When Revealed: Until the end of the phase, increase the total Threat in the staging area by X, where X is twice the stage number of the main quest.")
                .WithShadow("Shadow: Assign X damage among characters you control, where X is the stage number of the main quest.")
                .WithInfo(39, 3, Artist.Mariusz_Gandzel);
            addEncounterSideQuest("Southron Champion", EncounterSet.HaradSoldiers, 4)
                .WithTextLine("When Revealed: Discard cards from the encounter deck until a Harad enemy is discarded. Add that enemy to the staging area and place a resource token on it. That enemy is \"the Champion.\" While this stage is in play, the Champion gets +2 Threat, +2 Attack, +2 Defense and gains: Immune to player card effects. The main quest stage cannot be defeated while the Champion is in play.\"")
                .WithTextLine("The champion cannot take damage unless there are at least 4 progress tokens here. This stage cannot be defeated while the champion is in play.")
                .WithVictoryPoints(10)
                .WithInfo(40, 1, Artist.Alexandr_Elichev);
            addEnemy("Southron Captain", EncounterSet.HaradSoldiers, 40, 2, 5, 3, 6)
                .WithUnique()
                .WithTraits("Harad.")
                .WithTextLine("While Southron Captain is in the staging area, each other Harad enemy gets +1 Threat.")
                .WithTextLine("While Southron Captain is engaged with you, each other Harad enemy engaged with you gets +1 Attack.")
                .WithInfo(41, 1, Artist.Ellyson_Ferrari_Lifante);
            addEnemy("Southron Soldier", EncounterSet.HaradSoldiers, 32, 3, 3, 2, 5)
                .WithTraits("Harad.")
                .WithTextLine("Forced: After Southron Soldier engages you, either remove 2 progress tokens from the main quest, or Southron Soldier makes an immediate attack.")
                .WithShadow("Shadow: Choose an enemy in the staging area. Engage it and deal it a shadow card.")
                .WithEasyModeQuantity(2)
                .WithInfo(42, 3, Artist.Alexandr_Elichev);
            addEnemy("Southron Archer", EncounterSet.HaradSoldiers, 36, 2, 4, 3, 4)
                .WithTraits("Harad.")
                .WithKeywords("Archery 2.")
                .WithTextLine("Archery 2.")
                .WithTextLine("Forced: After Southron Archer engages you, either remove 2 progress tokens from the main quest, or discard an ally you control.")
                .WithEasyModeQuantity(3)
                .WithInfo(43, 4, Artist.J_Lonnee);
            addTreachery("Nowhere to Hide", EncounterSet.HaradSoldiers)
                .WithTextLine("When Revealed: The first player discards cards from the top of the encounter deck until an enemy is discarded, and puts that enemy into play engaged with him.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack (+2 Attack instead if it was engaged this round).")
                .WithEasyModeQuantity(2)
                .WithInfo(44, 3, Artist.Kim_Sokol);
            addEncounterSideQuest("In Enemy Territory", EncounterSet.HaradTerritory, 8)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Each player cannot have more than 5 cards in his hand. (If you have more than 5, immediately choose and discard cards from hand until you have only 5.)")
                .WithTextLine("Response: When this stage is defeated, each player draws a card.")
                .WithFlavorLine("Alone in a hostile land, cut off from help, you struggle to find your bearings...")
                .WithVictoryPoints(10)
                .WithInfo(45, 1, Artist.Will_OBrien);
            addTreachery("Injured Companion", EncounterSet.HaradTerritory)
                .WithTextLine("When Revealed: Each player must choose: either raise your threat by 1 for each character you control, or discard a character you control.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack. If this attack destroys a character, raise each player's threat by 1.")
                .WithEasyModeQuantity(2)
                .WithInfo(46, 3, Artist.Ilich_Henriquez);
            addTreachery("Enfeebled", EncounterSet.HaradTerritory)
                .WithTextLine("When Revealed: Each player exhausts a character he controls. Until the end of the combat phase, exhausted characters cannot ready.")
                .WithShadow("Shadow: Until the end of the round, defending character cannot ready.")
                .WithEasyModeQuantity(1)
                .WithInfo(47, 2, Artist.Adam_Duff);
            addEncounterSideQuest("Find Water", EncounterSet.DesertSands, 6)
                .WithTextLine("Characters cannot be readied by player card effects.")
                .WithTextLine("Response: When this stage is defeated, each player readies 1 hero he controls.")
                .WithFlavorLine("Your companions grow weary from thirst. They need water to drink.")
                .WithVictoryPoints(10)
                .WithInfo(48, 1, Artist.Marius_Bota);
            addLocation("Towering Dunes", EncounterSet.DesertSands, 3, 4)
                .WithTraits("Desert.")
                .WithTextLine("While Towering Dunes is in the staging area, progress cannot be placed on locations in the staging area not named Towering Dunes.")
                .WithTextLine("Forced: After Towering Dunes becomes the active location, reveal the top card of the encounter deck.")
                .WithEasyModeQuantity(2)
                .WithInfo(49, 3, Artist.Katy_Grierson);
            addLocation("Desert Oasis", EncounterSet.DesertSands, 2, 2)
                .WithTraits("Desert.")
                .WithTextLine("While Desert Oasis is the active location, it gains: \"Response: When Desert Oasis is explored, heal 4 damage from among characters in play.\"")
                .WithTextLine("Forced: After Desert Oasis becomes the active location, each player exhausts a character he controls.")
                .WithInfo(50, 2, Artist.Katy_Grierson);
            addTreachery("Sandstorm", EncounterSet.DesertSands)
                .WithTraits("Weather.")
                .WithTextLine("When Revealed: Each player either discards his hand, or assigns X damage among characters he controls. X is the number of cards in his hand.")
                .WithShadow("Shadow: Either discard the highest cost attachment you control, or assign X damage among characters you control where X is the number of attachments you control.")
                .WithEasyModeQuantity(1)
                .WithInfo(51, 2, Artist.Mariusz_Gandzel);
            addTreachery("Heat Exhaustion", EncounterSet.DesertSands)
                .WithTextLine("When Revealed: Each player exhausts a character he controls and deals 1 damage to that character.")
                .WithShadow("Shadow: Exhaust a character you control.")
                .WithInfo(52, 2, Artist.Victor_Garcia);
            addEncounterSideQuest("Craft Remedy", EncounterSet.DesertCreatures, 6)
                .WithTextLine("Treat the printed text box of each damaged character as if it were blank (except for Traits).")
                .WithTextLine("Response: When this is defeated, heal 1 damage from each character in play.")
                .WithFlavorLine("Some of your companions have been poisoned! They need a remedy to counteract the venom.")
                .WithVictoryPoints(10)
                .WithInfo(53, 1, Artist.Ashley_Lange);
            addEnemy("Sand Viper", EncounterSet.DesertCreatures, 44, 4, 1, 1, 3)
                .WithTraits("Creature.")
                .WithTextLine("Players cannot declare defenders against Sand Viper.")
                .WithTextLine("Forced: After the players travel to a location, Sand Viper engages the first player.")
                .WithFlavorLine("To some suddenly it seemed that they saw a snake coiling itself to strike.")
                .WithFlavorLine("-The Two Towers")
                .WithEasyModeQuantity(1)
                .WithInfo(54, 2, Artist.Piya_Wannachaiwong);
            addEnemy("Giant Scorpion", EncounterSet.DesertCreatures, 33, 3, 3, 2, 4)
                .WithTraits("Creature.")
                .WithTextLine("Forced: After Giant Scorpion damages a character, that character cannot ready until the end of the round.")
                .WithShadow("Shadow: If this attack deals damage, the defending character cannot ready until the end of the round.")
                .WithInfo(55, 3, Artist.Dimitri_Bielak);
            addLocation("Jungle Trail", EncounterSet.JungleForest, 4, 4)
                .WithTraits("Forest.")
                .WithTextLine("While Jungle Trail is the active location, each location in the staging area gets -1 Threat.")
                .WithTextLine("Travel: Reveal the top card of the encounter deck to travel here.")
                .WithFlavorLine("The path itself was narrow and wound in and out among the trunks.")
                .WithFlavorLine("-The Hobbit")
                .WithEasyModeQuantity(1)
                .WithInfo(56, 2, Artist.Katy_Grierson);
            addLocation("Forest Clearing", EncounterSet.JungleForest, 3, 2)
                .WithTraits("Forest.")
                .WithTextLine("Forced: When Forest Clearing is explored, discard the top card of the encounter deck. If that card is an enemy, add that enemy to the staging area.")
                .WithShadow("Shadow: Discard an attachment you control.")
                .WithEasyModeQuantity(2)
                .WithInfo(57, 3, Artist.Mariusz_Gandzel);
            addLocation("Dense Jungle", EncounterSet.JungleForest, 2, 3)
                .WithTraits("Forest.")
                .WithTextLine("Forced: When Dense Jungle is explored, discard the top card of the encounter deck. If that card is a location, add that location to the staging area.")
                .WithShadow("Shadow: Discard a random card from your hand.")
                .WithInfo(58, 3, Artist.Mariusz_Gandzel);
            addTreachery("Overgrown", EncounterSet.JungleForest)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("When Revealed: Attach to the highest Threat location in the staging area without a copy of Overgrown attached. (Counts as a Condition attachment with the text: \"Attached location gets +1 Threat and gains 'Immune to player card effects.'\"")
                .WithEasyModeQuantity(1)
                .WithInfo(59, 2, Artist.Kamila_Szutenberg);
            addEncounterSideQuest("Uruks of the Eye", EncounterSet.MordorOrcs, 5)
                .WithKeywords("Surge.")
                .WithTextLine("Surge.")
                .WithTextLine("Each Orc enemy in the staging area gets -5 engagement cost.")
                .WithTextLine("Each Orc enemy engaged with a player gets +1 Threat.")
                .WithFlavorLine("The Uruks of Mordor attack with a savagery that is difficult to match.")
                .WithVictoryPoints(10)
                .WithInfo(60, 1, Artist.Victor_Garcia);
            addEnemy("Uruk Chieftain", EncounterSet.MordorOrcs, 50, 4, 5, 3, 6)
                .WithUnique()
                .WithTraits("Orc.", "Uruk.")
                .WithTextLine("Cannot have player card attachments or be optionally engaged.")
                .WithTextLine("While the engaged player is engaged with another Orc enemy, ~Uruk Chieftain cannot take damage.")
                .WithTextLine("Forced: At the end of the encounter phase, ~Uruk Chieftain engages the player engaged with the most non-unique Orc enemies.")
                .WithInfo(61, 1, Artist.Sam_Lamont);
            addEnemy("Uruk of Mordor", EncounterSet.MordorOrcs, 35, 2, 4, 2, 4)
                .WithTraits("Orc.", "Uruk.")
                .WithTextLine("Each ally with less Willpower than Uruk of Mordor's Threat cannot defend against Uruk of Mordor.")
                .WithShadow("Shadow: Attacking enemy gets +1 Attack (+2 Attack instead if its Threat is greater than the defending character's Willpower.")
                .WithInfo(62, 3, Artist.Diego_Gisbert_Llorens);
            addEnemy("Uruk Warg-rider", EncounterSet.MordorOrcs, 40, 3, 3, 1, 5)
                .WithTraits("Orc.", "Uruk.")
                .WithTextLine("Uruk Warg-Rider gets +X Attack while attacking a character with less Willpower than Uruk Warg-rider's Threat. X is the difference.")
                .WithShadow("Shadow: Return attacking enemy to the staging area after this attack.")
                .WithEasyModeQuantity(1)
                .WithInfo(63, 2, Artist.Piya_Wannachaiwong);
            addEnemy("Mordor Warg", EncounterSet.MordorOrcs, 20, 2, 2, 2, 2)
                .WithTraits("Creature.")
                .WithTextLine("When Revealed: Attach to an Orc enemy and return that enemy to the staging area. Limit 1 per enemy. (Counts as a Mount attachment with the text: \"Attached enemy gets +2 Threat, +2 Attack, +2 Defense and +2 hit points.")
                .WithTextLine("Forced: When attached enemy leaves play, add Mordor Warg to the staging area.\"")
                .WithEasyModeQuantity(1)
                .WithInfo(64, 2, Artist.Mariusz_Gandzel);
            addTreachery("Fear of Mordor", EncounterSet.MordorOrcs)
                .WithTextLine("When Revealed: Each ally in play gets -1 Willpower, -1 Attack, and -1 Defense until the end of the round.")
                .WithShadow("Shadow: If attacking enemy's Threat is greater than the defending character's Willpower, it makes an additional attack after this one.")
                .WithEasyModeQuantity(1)
                .WithInfo(65, 2, Artist.Mariusz_Gandzel);
            addQuest("Stranded in Umbar", EncounterSet.EscapeFromUmbar, 1, 'A', 15)
                .WithTextLine("Setup: Add “Seize them!” to the staging area. Each player adds 1 different location to the staging area and puts 1 copy of ~Umbar Sentry into play engaged with him. Shuffle the encounter deck.")
                .WithFlavorLine("At the end of a long sea-voyage, you have reached the port of Umbar but your ship was dashed upon the rocks. Though you completed the quest that brought you to Harad, it has left you stranded in enemy territory, far from help.")
                .WithOppositeTextLine("This stage cannot have more than 15 progress tokens on it.")
                .WithOppositeTextLine("While at least 1 player is engaged with an enemy, the players cannot defeat this stage.")
                .WithOppositeFlavorLine("Alarm bells ring from high watchtowers and the city guard shouts for you to lay down your arms and surrender. You must run or be captured!")
                .WithIncludedEncounterSets(EncounterSet.HaradTerritory, EncounterSet.HaradSoldiers)
                .WithInfo(66, 1, Artist.Nikolas_Hagialas);
            addQuest("Flee the City", EncounterSet.EscapeFromUmbar, 2, 'A', 15)
                .WithTextLine("When Revealed: End the current phase. Shuffle the encounter discard pile into the encounter deck. Starting with the first player, each player discards cards from the top of the encounter deck until he discards an enemy, and puts that enemy into play engaged with him.")
                .WithFlavorLine("The whole of Umbar is astir, and the Southrons chase you through the streets. If you cannot escape the city quickly, you are certain to be taken prisoner.")
                .WithOppositeTextLine("This stage cannot have more than 15 progress tokens on it.")
                .WithOppositeTextLine("Forced: At the beginning of the quest phase, if any player is not engaged with an enemy, discard cards from the top of the encounter deck until an enemy is discarded and add it to the staging area.")
                .WithOppositeTextLine("While at least 1 player is engaged with an enemy, the players cannot defeat this stage. If the players defeat this stage, they win the game.")
                .WithIncludedEncounterSets(EncounterSet.HaradTerritory, EncounterSet.HaradSoldiers)
                .WithInfo(67, 1, Artist.Joshua_Cairos);
            addQuest("The Desert of Harad", EncounterSet.DesertCrossing, 1, 'A', 8)
                .WithTextLine("Setup: Each player searches the encounter deck for a copy of Burnt Sands and adds it to the staging area. Shuffle the encounter deck. Place the heat tracker next to the quest deck and set the temperature to 10.")
                .WithFlavorLine("You have escaped from Umbar and thrown off your pursuers by fleeing into the desert, but many barren miles lie between you and the other side. To turn back is to walk into the arms of the Haradrim, so you set out on a dangerous desert crossing.")
                .WithOppositeTextLine("Forced: After an ally enters play, either exhaust it, or deal 1 damage to it.")
                .WithOppositeTextLine("Forced: At the end of the round, increase the temperature by 4.")
                .WithOppositeTextLine("If the temperature is 60 or higher, the players lose the game.")
                .WithOppositeFlavorLine("As the sun climbs into the sky, you can feel the rising heat begin to take its toll on you...")
                .WithIncludedEncounterSets(EncounterSet.DesertCreatures, EncounterSet.DesertSands)
                .WithInfo(68, 1, Artist.Kim_Sokol);
            addQuest("Under the Merciless Sun", EncounterSet.DesertCrossing, 2, 'A', 14)
                .WithTextLine("When Revealed: Increase the temperature by 2. Shuffle the encounter discard pile into the encounter deck and reveal 1 encounter card per player.")
                .WithFlavorLine("You trudge across the barren desert with the blazing sun overhead and deadly creatures underfoot, but nothing is more dangerous to you than your lack of water.")
                .WithOppositeTextLine("Forced: At the end of the round, increase the temperature by 4. Then, each player assigns X damage among characters he controls, where X is the tens digit of the temperature.")
                .WithOppositeTextLine("If the temperature is 60 or higher, the players lose the game.")
                .WithOppositeFlavorLine("If you cannot make it across the desert soon, you are certain to die of thrist...")
                .WithIncludedEncounterSets(EncounterSet.DesertCreatures, EncounterSet.DesertSands)
                .WithInfo(69, 1, Artist.Victor_Garcia);
            addQuest("Beasts of Legend", EncounterSet.DesertCrossing, 3, 'A', 16)
                .WithTextLine("When Revealed: Increase the temperature by 2. Each player searches the encounter deck, discard pile, and victory display for a Were-worm and adds it to the staging area, if able. Shuffle the encounter deck.")
                .WithFlavorLine("You have wandered through the trackless desert and discovered the legendary nesting grounds of the wild Were-worms. The beasts rear up and circle to attack. You must drive them off or meet your end upon the desert sands.")
                .WithOppositeTextLine("During the quest phase, add X Threat to the total Threat in the staging area, where X is the tens digit of the temperature.")
                .WithOppositeTextLine("Forced: At the end of the round, increase the temperature by 4.")
                .WithOppositeTextLine("While at least 1 Were-worm is in play, the players cannot defeat this stage. If the players defeat this stage, they win the game. If the temperature is 60 or higher, the players lose the game.")
                .WithIncludedEncounterSets(EncounterSet.DesertCreatures, EncounterSet.DesertSands)
                .WithInfo(70, 1, Artist.Dimitri_Bielak);
            addQuest("Surprise Attack", EncounterSet.TheLongArmOfMordor, 1, 'A', 0)
                .WithTextLine("Setup: Set Uruk Chieftain aside, out of play. Each player adds 1 copy of Sauron’s Enforcers to the staging area. Move each hero to the staging area. Each player takes control of an objective-hero and adds 2 resources to its resource pool. Remove each remaining objective-hero from the game. For the remainder of the game, heroes in the staging area are in play but under no player’s control, immune to player card effects, and their text boxes are considered to be blank.")
                .WithFlavorLine("A tribe of Haradrim has rescued you, but their village is attacked by Orcs!")
                .WithOppositeTextLine("Damage from undefended attacks must be dealt to a hero in the staging area, if able.")
                .WithOppositeTextLine("The first card each player plays each phase does not require a resource match.")
                .WithOppositeTextLine("Forced: After placing progress from questing successfully, each player chooses a hero he owns in the staging area and, takes control of that hero, and exhausts it. Advance to stage 2A.")
                .WithIncludedEncounterSets(EncounterSet.MordorOrcs, EncounterSet.JungleForest)
                .WithInfo(71, 1, Artist.Alexandr_Elichev);
            addQuest("Find the Others", EncounterSet.TheLongArmOfMordor, 2, 'A', 5)
                .WithFlavorLine("Still weary from the long journey across the desert, your companions are somewhere in the village. In your weakened state you are no match for the attacking Orcs. Your only chance to survive is to flee into the jungle, but you will not abandon your friends.")
                .WithOppositeTextLine("Damage from undefended attacks must be dealt to a hero in the staging area, if able.")
                .WithOppositeTextLine("The first card each player plays each phase does not require a resource match.")
                .WithOppositeTextLine("Forced: When this stage is defeated, each player chooses a hero he owns in the staging area, takes control of that hero, and exhausts it.")
                .WithIncludedEncounterSets(EncounterSet.MordorOrcs, EncounterSet.JungleForest)
                .WithInfo(72, 1, Artist.Joshua_Cairos);
            addQuest("Free the Captives", EncounterSet.TheLongArmOfMordor, 3, 'A', 10)
                .WithTextLine("When Revealed: Each player searches the encounter deck and discard pile for an Orc enemy and adds it to the staging area. Shuffle the encounter deck. Attach each hero in the staging area to a different Orc enemy in the staging area. Each hero attached to an enemy is guarded by that enemy. Guarded heroes are under no player’s control, immune to player card effects, and their text boxes are considered to be blank.")
                .WithFlavorLine("Orcs have seized your friends and are now dragging them away as captives.")
                .WithOppositeTextLine("While an enemy is guarding a hero it gets +1 Threat, +1 Attack, +1 Defense and is immune to player card effects.")
                .WithOppositeTextLine("Forced: When the enemy guarding a hero is defeated, that hero’s owner takes control of that hero and exhausts it.")
                .WithOppositeTextLine("This stage cannot be defeated while an enemy is guarding a hero.")
                .WithIncludedEncounterSets(EncounterSet.MordorOrcs, EncounterSet.JungleForest)
                .WithInfo(73, 1, Artist.Nikolas_Hagialas);
            addQuest("Escape into the Jungle", EncounterSet.TheLongArmOfMordor, 4, 'A', 15)
                .WithTextLine("When Revealed: Add Uruk Chieftain to the staging area. Shuffle the encounter discard pile into the encounter deck and reveal 1 encounter card per player.")
                .WithFlavorLine("The Orcs run rampant through the Haradrim boma. Amidst the chaos, you see an opportunity to escape but a large Uruk chieftain bars your way. You will have to defeat the chieftain in order to get past him.")
                .WithOppositeTextLine("Uruk Chieftain cannot take non-combat damage.")
                .WithOppositeTextLine("Each non-unique Orc enemy gets -10 engagement cost.")
                .WithOppositeTextLine("Forced: After Uruk Chieftain engages a player, it makes an immediate attack.")
                .WithOppositeTextLine("The players cannot defeat this stage while Uruk Chieftain is in play. If the players defeat this stage, they win the game.")
                .WithIncludedEncounterSets(EncounterSet.MordorOrcs, EncounterSet.JungleForest)
                .WithInfo(74, 1, Artist.David_A_Nash);
        }
    }
}
